### ISSUE TITLE
Redundant presence of 'Project Estimates' on Project outline panel for Website project 

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1007] opened 2017-07-24 19:08 UTC
### Expected behavior
Any field which doesn't have any significance or usage in that particular page, should be removed.For 'Other Design' project option, there are no option to reflect any value for 'Project Estimate'.Hence, 'Project Estimate' should be kept hidden for 'Website Project'.

### Actual behavior
Unnecessary presence of 'Project Estimate' details in Project Outline panel for 'Website Projects'.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com.
- Click 'Start a Project'.
- Chose 'Website Project'.
- Observe & try to identify any relevance of 'Project Estimate' in Project Outline.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/20595047/28540001-5f584f0a-70d1-11e7-9c2a-a2c635ad41ef.png)
![image](https://user-images.githubusercontent.com/20595047/28540011-664b89bc-70d1-11e7-9b1b-04f883d6e600.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not Logged In
- Account used: -NA-

**Comment by gondzo** [comment] 2017-07-27 18:07
duplicate of #1002

**Closed by gondzo** 2017-07-27 18:07 UTC
Labels: bug hunt, duplicate
