### ISSUE TITLE
Unify .svg resource loading and use

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1422] opened 2017-12-06 18:36 UTC
We should refactor the use of SVG images in all components to be consistent. SVG images are text-based vector data that shouldn't be included as CSS backgrounds or <IMG> elements. This will allow us dynamic modifications with CSS and JS - drawing/animation/color change, transformations, etc..

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-39

**Comment by gondzo** [comment] 2018-01-04 18:34
duplicate of #1442

**Closed by gondzo** 2018-01-04 18:34 UTC
Labels: Aha!:Ready to develop
