### ISSUE TITLE
"Latest First/Oldest First/Name A-Z" is not displaying in IE11

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#222] opened 2016-09-28 19:46 UTC
Description
-----------------------------------------------------------------
"Latest First/Oldest First/Name A-Z" is not displaying in IE11

Steps to Reproduce
-----------------------------------------------------------------

- Open the site
- Login as a valid user (christina_uw or pat_monahan)
- In the Dashboard
- Click on the 3rd Table column name

Expected Result(s)
-----------------------------------------------------------------
- Must display the drop down

Actual Result
-----------------------------------------------------------------
- "Latest First/Oldest First/Name A-Z" is not displaying in IE11

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2016-09-28 23:41
![2016-09-29_5-10-54](https://cloud.githubusercontent.com/assets/4592712/18936213/22f4adba-8603-11e6-985d-c759de251904.png)

**Comment by vic-appirio** [comment] 2016-10-04 21:31
Layout issue

**Comment by vic-appirio** [comment] 2016-10-04 22:21
Duplicate of #193

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate, functionality, P0, visual styling
