### ISSUE TITLE
[$300] Registration screens

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1070] opened 2017-07-28 16:57 UTC
This is a placeholder issue for a bug bash to track related issues.

Fixing all of the following bugs is in scope
- [x] #976
- [x] #977
- [x] #978
- [x] #980
- [x] #1014
- [x] #1015
- [x] #1017
- [x] #1024
- [x] #1049
- [x] #1053

**Comment by rushikesh90** [comment] 2017-07-29 18:53
@gondzo Can I get more time ? I am geting errors in deploying locally

**Comment by gondzo** [comment] 2017-07-29 19:39
yes, that's fine.

**Comment by gondzo** [comment] 2017-07-30 16:09
@rushikesh90 - any updates?
If you can't fix your install issues in the next few hours, just add open for pickup label to this issue (so someone else can pick it up). After you fix your environment you can pick up another task. Thanks!

**Comment by rushikesh90** [comment] 2017-07-30 16:32
I am able to install succesfully. Anyway if I cant solve the issues I will change the status.

**Comment by gondzo** [comment] 2017-07-30 17:15
@all this is now open for pickup

**Comment by chq-matteo** [comment] 2017-07-30 17:41
#976 is duplicate of #1013 or rather the other way around

**Comment by chq-matteo** [comment] 2017-07-30 19:23
@gondzo the issue with #1014 is quite tricky since topcoder is an international website

See
https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
https://softwareengineering.stackexchange.com/questions/330512/name-validation-best-practices

**Comment by chq-matteo** [comment] 2017-07-31 08:31
I'm quite confused which branch of https://github.com/appirio-tech/accounts-app is active at the moment?
I think it is either
https://github.com/appirio-tech/accounts-app/commits/feature/updated-connect-reg-flow/
or 
https://github.com/appirio-tech/accounts-app/commits/feature/copy-change-pin-verification
because most of the issues do not apply to dev branch
@gondzo @vikasrohit

**Comment by gondzo** [comment] 2017-07-31 08:58
feature/copy-change-pin-verification is the correct one

**Comment by chq-matteo** [comment] 2017-07-31 08:58
My guess is `feature/updated-connect-reg-flow` because the string pick a nickname is only in that branch
```
$ git show-ref --heads | xargs git grep "Pick a nickname"
74fdac359f34dce8975ded10aa0e0ba79a0f9835:app/views/connect/registration.jade:        label Pick a nickname
refs/heads/feature/updated-connect-reg-flow:app/views/connect/registration.jade:        label Pick a nickname
```

**Comment by chq-matteo** [comment] 2017-07-31 09:00
@gondzo if it is copy-change-pin-verification #1049 is already fixed

**Comment by gondzo** [comment] 2017-07-31 09:01
OK, I'll merge both later into updated-connect-reg-flow. Thanks.

**Comment by vikasrohit** [comment] 2017-07-31 09:07
@chq-matteo @gondzo feature/copy-change-pin-verification was created from feature/updated-connect-reg-flow. I was waiting for bug hunt to finish before merging it back to feature/updated-connect-reg-flow branch. feature/copy-change-pin-verification branch contains changes for https://github.com/appirio-tech/connect-app/issues/960. Ideally, feature/updated-connect-reg-flow should be the base of all bug fixes. However, even if someone is taking feature/copy-change-pin-verification as base, it would not be a problem. It would rather introduce less conflicts while merging back.

**Comment by chq-matteo** [comment] 2017-07-31 09:09
I'll rewrite my fixes with feature/updated-connect-reg-flow as base then
@vikasrohit @gondzo

**Comment by chq-matteo** [comment] 2017-07-31 10:06
https://github.com/appirio-tech/connect-app/issues/1024
only applies to old code

**Comment by vikasrohit** [comment] 2017-08-01 07:13
fyi only, branch feature/copy-changes-pin-verification has been merged and deleted. So, please use feature/updated-connect-reg-flow for any near future changes about connect reg flow.

**Comment by chq-matteo** [comment] 2017-08-02 06:46
@gondzo A couple of the issue that were assigned to me had their specs changes am I supposed to update my fixes?

**Comment by gondzo** [comment] 2017-08-02 18:00
no, your tasks are marked as accepted and you don't need to do anything further.

**Closed** 2017-08-02 18:31 UTC
Labels: ACCEPTED
