### ISSUE TITLE
Long Project Name spill over Project Outline space

### ISSUE THREAD

**Issue by m-prabhu** [appirio-tech/connect-app#1010] opened 2017-07-24 19:13 UTC
### Expected behavior
Long Project Name spill over the Project Outline space

### Actual behavior
Project name should not spill over the Project Outline space

### Steps to reproduce the problem
-goto https://connect.topcoder-dev.com
-click start a project
-select 'software development'
-provide a long project name like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and save the project
- As shown in screenshot project name will spill over the Project Outline space.

### Screenshot/screencast
![selection_039](https://user-images.githubusercontent.com/30400318/28540169-f7773990-70d1-11e7-86cf-55009592c190.png)
![selection_046](https://user-images.githubusercontent.com/30400318/28540446-0c90750c-70d3-11e7-841d-ffad2fd85c5a.png)

--

#### Environment
- OS: Windows 7 32 bit
- Browser (w/version): Firefox 54, Chrome 59
- User role (client, copilot or manager): Not Applicable
- Account used: Not Applicable

**Comment by gondzo** [comment] 2017-07-27 18:09
duplicate of #988

**Closed by gondzo** 2017-07-27 18:09 UTC
Labels: bug hunt
