### ISSUE TITLE
[Web-Chrome] Business Phone Drop Down Is Not Accepting Country Name From Key

### ISSUE THREAD

**Issue by devsreekrishna** [appirio-tech/connect-app#3676] opened 2020-01-30 17:54 UTC
### Expected behavior
Business Phone Should Take By After Clicking Country Drop Down Through Pressing Key

### Actual behavior
Business Phone Drop Down Is Not Accepting Country Name From Key

### Steps to reproduce the problem
1. Go To App

2. Login As topcoderconnect+Manager@gmail.com

3. Click On My Profile

4. Select Profile Information

5. Try To Fill Business Phone By Clicking Key From Keyboard Then See & Observe.

6. See Screencast

### Screenshot/screencast

[While Filling Profile Information.mp4.zip](https://github.com/appirio-tech/connect-app/files/4135476/While.Filling.Profile.Information.mp4.zip)

#### Environment
- OS: 

[Mac Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135477/Mac.Version.png.zip)

- Browser (w/version):

[Chrome Version.png.zip](https://github.com/appirio-tech/connect-app/files/4135482/Chrome.Version.png.zip)

- User role (client, copilot or manager): Manager

- Account used: topcoderconnect+Manager@gmail.com

**Comment by devsreekrishna** [comment] 2020-01-30 17:55
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment] 2020-01-31 10:27
@devsreekrishna , out of scope

**Comment by nithyaasworld** [comment] 2020-02-03 05:36
Not a bug.

(Bug video is Nice!)

**Closed by nithyaasworld** 2020-02-03 05:36 UTC
Labels: BH_OOS, BugHunt_JanRelease, Functional, P3
