### ISSUE TITLE
Prompt if page has updated/changed

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1537] opened 2017-12-23 03:25 UTC
### Expected behavior
While on the Dashboard, if there is a new post, I would love the page to notify me that new posts are available and I can force reload at my convenience. This is tied to the automatic polling of new notifications.

The blue button that prompts refresh appears when the user has scrolled down the page
![screen shot 4](https://user-images.githubusercontent.com/8484061/34316557-c1ddd0f8-e74d-11e7-9d2a-384020c2d95f.png)

If the user is at the top of the dashboard, reload the page automatically to display the post with the latest updates at the top.

**Comment by vikasrohit** [comment] 2017-12-24 08:36
Until we use web sockets (which has extra load on server when compared to pull way instead of push), we can add single timer in the application which can pull multiple updates for the application. May be we can create an api end point which can supply individual users their interested notifications using the new notifications system. I guess we already have timer which pulls notifications from connect notifications server. We can use the same timer and API server to serve the latest topics as well. May be we can use the same for notifying users about alteration of the project specs when some one else has updated the specs while first user is on the page.

fyi @mtwomey

**Comment by gondzo** [comment] 2018-01-04 18:46
duplicate of #1437

**Closed by gondzo** 2018-01-04 18:46 UTC
