### ISSUE TITLE
[$10] Minor UI Issues

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3440] opened 2019-12-17 06:12 UTC
### Expected behavior
- Long user names to be wrapped around correctly.
- Extra apostrophe to be removed from Phase addition message.

### Actual behavior
- Long user names overflow beyond left pane.
- Phase addition message has unnecessary apostrophe.

### Steps to reproduce the problem
- TBD.
- TBD.
- TBD.

### Screenshot/screencast
Attach or link a resource.

<img width="1652" alt="Screenshot 2019-12-17 at 11 29 16 AM" src="https://user-images.githubusercontent.com/51733042/70969509-d1de3880-20c1-11ea-8bdb-43455bd6bba2.png">
![Phaseadded](https://user-images.githubusercontent.com/51733042/70969611-3600fc80-20c2-11ea-9a32-6801a5308e24.jpg)
--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment] 2019-12-17 06:14
cc @maxceem @nithyaasworld

**Comment by vikasrohit** [comment] 2019-12-18 11:47
@lakshmiathreya I think wrong screen shot is attached, there is no phase in the attached screenshot.
Further, as the issue is very minor, I would propose to move it to 2.5.1.

**Comment by lakshmiathreya** [comment] 2019-12-19 10:19
Pls see the second attachment - link to the jpg @vikasrohit

**Comment by lakshmiathreya** [comment] 2019-12-19 10:22
attached screenshot for Phase added message ...
![Screenshot 2019-12-19 at 3 50 07 PM](https://user-images.githubusercontent.com/51733042/71165843-8c636c00-2277-11ea-8c02-d20a715c25a6.jpg)

**Comment by vikasrohit** [comment] 2019-12-19 11:11
Thanks @lakshmiathreya, I understood the part 2 of the issue i.e. extra apostrophe but not able to see the overflowing phase name issue.

**Comment by nithyaasworld** [comment] 2019-12-19 12:52
@vikasrohit Its the overflowing user name. Please find the below screenshot.

![image](https://user-images.githubusercontent.com/5114190/71174995-6f856380-228c-11ea-88f6-9be9df14b6c3.png)

**Comment by nithyaasworld** [comment] 2019-12-19 20:57
One more screenshot of the issue.

![image](https://user-images.githubusercontent.com/5114190/71208930-2ce57a80-22d0-11ea-88e6-f6211aff992a.png)

**Comment by lakshmiathreya** [comment] 2019-12-20 00:28
thanks @nithyaasworld your screenshot is better than mine - name overflows right into All Projects ...

**Comment by maxceem** [comment] 2020-01-20 06:06
Sum up:
- Long user name should not go out in the profile info. It should be cut.
  - **NOTE** @vikasrohit  for the multiline text we cannot use CSS for adding ellipsis `...`. So I suggest that we just cut it. Otherwise, we would have to use some JS lib for adding ellipsis.
- Remove the "'" from the success message when we are adding a phase. You can use project http://local.topcoder-dev.com:3000/projects/8702 for testing.

**Comment by lakshmiathreya** [comment] 2020-01-20 06:34
@SathyaJayabal @nithyaasworld

**Comment by vikasrohit** [comment] 2020-01-20 06:42
@maxceem we are [using](https://github.com/appirio-tech/connect-app/search?utf8=%E2%9C%93&q=react-text-truncate&type=) javascript library already for truncating text where css is not sufficient. In this particular case, I am okay with css fix only, though. But if it make sense to use the js, feel free to use the mentioned library.

**Comment by maxceem** [comment] 2020-01-20 06:58
@vikasrohit  I was considering that, but that library can only truncate text by lines:

![image](https://user-images.githubusercontent.com/146016/72704986-2da25280-3b95-11ea-8fe8-2dbc41e49809.png)

So we cannot use it here, and if we want to do so, we have to find another library and probably replace the existent one too, for consistency.

**Comment by vikasrohit** [comment] 2020-01-20 09:05
Makes sense. Lets use the css fix for this issue.

**Comment by iversonLv** [comment] 2020-01-21 11:55
@bug-bash-helper assign

**Comment by iversonLv** [comment] 2020-01-21 13:10
Can I break the name into multiple lines??
![image](https://user-images.githubusercontent.com/4952611/72807435-5bb98c80-3c92-11ea-8b7e-3c99c78e93a2.png)

**Comment by iversonLv** [comment] 2020-01-21 13:13
Or 
![image](https://user-images.githubusercontent.com/4952611/72807632-cc60a900-3c92-11ea-8eee-fffa54c57e13.png)

**Comment by maxceem** [comment] 2020-01-21 14:14
The second option would be better, don't break one "word" into several lines.

**Comment by iversonLv** [comment] 2020-01-21 14:18
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3500 is ready for review

**Comment by maxceem** [comment] 2020-01-23 03:34
CSS `ellipsis ` appears to work great for our case, as we have too long **word** not too long **text** where it doesn't work:

![image](https://user-images.githubusercontent.com/146016/72954692-35036f00-3dd4-11ea-9504-383654d5afd8.png)

**Comment by maxceem** [comment] 2020-01-23 03:35
New stage alert also looks good now without extra apostrophes:

![image](https://user-images.githubusercontent.com/146016/72954749-63814a00-3dd4-11ea-9ed3-dd4a668bbd73.png)

**Comment by nithyaasworld** [comment] 2020-01-28 14:30
Verified in Dev.
![image](https://user-images.githubusercontent.com/5114190/73272452-69c65a80-4208-11ea-949d-96c25eee874f.png)

![image](https://user-images.githubusercontent.com/5114190/73272678-c6297a00-4208-11ea-8ef2-1126088958c1.png)

**Comment by drasticdpk** [comment] 2020-02-28 11:26
Test Data 
First Name : First Name This is first Name First Name Thais is firs t Name
Last Name : Last Name Thais is last Name Last Name Thais is last Name


![image](https://user-images.githubusercontent.com/25297859/75544441-15530c80-5a4c-11ea-983d-111f12a39bca.png)


First Name : dfafdfajddlfkadlafadfkadflafdkfafjdfalfdkfa
Last Name : asfafdkfasdofafsdfdfdsfpdasfoisdjfdsf
![image](https://user-images.githubusercontent.com/25297859/75544992-3405d300-5a4d-11ea-810d-249337d75110.png)

**Comment by iversonLv** [comment] 2020-02-28 12:25
Because it's one word which we won't break it down.
If the name is multiple, break words down.

> The second option would be better, don't break one "word" into several lines.

**Comment by vikasrohit** [comment] 2020-03-02 07:34
@drasticdpk couple of notes:
- Original requirements are met for the issue and special case you found is not part of the requirements and is still debatable how to handle that. Please feel free to create a separate issue for that as enhancement.
- As the issue passed in dev env and the same use case was not reported during dev testing, we should close this one and handle any new concern found in separate issues.

Closing the issue for cleanup. Please feel free to create separate regression issues.

**Closed by vikasrohit** 2020-03-02 07:34 UTC
Labels: ACCEPTED, CF-20, P4, PAID, QA Fail in Prod
