### ISSUE TITLE
Links section have a 'Shared with' option

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3994] opened 2020-05-12 12:38 UTC
### Expected behavior
Since the link dialog box don't have 'Shared with' option to restrict the link for particular users; the column should remove from the table

### Actual behavior
Links section have a 'Shared with' option

### Steps to reproduce the problem

- Login as Manager
- Click on a project on project listing page - https://connect.topcoder-dev.com/projects/9074/assets
- Go to 'Assets Library' > Links
- Click Add New and insert a link
- Check the table; there is a 'Shared with' column

cc @vikasrohit 

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/81692145-8c7d2780-9423-11ea-8ce1-505c0fe18340.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Chrome 81.0.4044.138
**- User role (client, copilot or manager):**  Manager
**- Account used:**  `TCConManager`

**Comment by maxceem** [comment] 2020-05-12 12:55
@vikasrohit what do you think about this? Technically we can support it now, as links are now handled the same way as files using Attachment model.

**Comment by vikasrohit** [comment] 2020-05-13 09:24
We do have it logged https://github.com/appirio-tech/connect-app/issues/3747, but for some reason the feature is on hold by product manager. I have asked for the go ahead of this, lets wait for the confirmation.

**Comment by maxceem** [comment] 2020-05-15 12:24
Closing this issue as duplicate of https://github.com/appirio-tech/connect-app/issues/3747.

**Closed by maxceem** 2020-05-15 12:24 UTC
Labels: Dev Environment, P4, duplicate, enhancement
