### ISSUE TITLE
[Edit project] - the down border line is not displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#313] opened 2016-09-29 06:41 UTC
Expected behavior
------------------------------------------------------------

- The down border line must be displayed the same as others.

Actual behavior
------------------------------------------------------------

- The down border line of textarea is not displayed.

Steps to reproduce the problem

------------------------------------------------------------

- Login into application as manager.

- Edit any existing project.

- Set focus on Comment field.

- Observe the down border line as is not displayed.

Environment

------------------------------------------------------------

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
User role: manager
Account used: pat_monahan

![no-border](https://cloud.githubusercontent.com/assets/5114907/18943531/e52eb66c-8628-11e6-94af-22d5fa73c645.png)

**Comment by mahestro** [comment] 2016-10-04 12:30
Duplicate of #220

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate, visual styling
