### ISSUE TITLE
Count is 2, but only display one link

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#404] opened 2016-10-01 11:08 UTC
### Expected behavior
-----------------------------------------------------------------
Must display 2 links or the count must 1

### Actual behavior
-----------------------------------------------------------------
Count is 2, but only display one link

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (cp-superstar)
- In the Projects
- Click on a Project (https://connectv2.topcoder-dev.com/projects/363)
- Now Check the Links
- It is displayed the count as 2, but only displayed one

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_16-37-57](https://cloud.githubusercontent.com/assets/4592712/19013666/76e77602-87f5-11e6-9f0d-51fe6278b3ef.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment] 2016-10-04 18:40
Valid.

**Comment by fnisen** [comment] 2016-10-14 01:04
Still seeing this on the project cited above.

**Comment by fnisen** [comment] 2016-10-15 00:23
Not able to reproduce from scratch, so maybe this was resolved somehow already. Closing until it's reported on a new project.

**Closed by fnisen** 2016-10-15 00:23 UTC
Labels: P1
