### ISSUE TITLE
Define another screen and screens limit

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#637] opened 2017-03-01 21:25 UTC
### Expected behavior
If the "Define another screen" button is disabled due to the number of screens limit, it's confusing to let the user enter values into the fields of a screen which can't be saved.

### Actual behavior
Currently the new screen can be added but not saved. this is confusing.

### Steps to reproduce the problem
Open the project specification page, select 3 as number of screens and add 3 new screens (4 total). You can't save the 4th screen and it shouldn't be possible to add it at all

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/3051646/23481989/cae3b622-fecd-11e6-91e7-cc2e03fc9e5e.png)

--

#### Environment
- OS: all
- Browser (w/version):all
- User role (client, copilot or manager):all
- Account used: all

**Comment by fnisen** [comment] 2017-03-03 01:17
Yes, good call here. The button should be disabled one screen earlier. Also, the mouseover message is not styled correctly. @vikasrohit can you please provide the component for that?

**Comment by vikasrohit** [comment] 2017-03-03 10:00
@gondzo we have a tooltip component already available with two different themes in [react-components](https://github.com/appirio-tech/react-components/tree/feature/connectv2/components/Tooltip).

**Comment by ThomasKranitsas** [comment] 2017-03-03 12:31
The `Define another screen` button works as submit button thus when you enter the details of the last available screen you have to click it first so the screen is saved but when you click it a new form is being rendered but it cannot be saved as the button is now disabled.

A possible solution for this is to change the button from `Define another screen` to `Save & Add new screen` and when you click it on the last available screen it will hide that button and will render the error message (`You have reached the number of screens...`) instead of a new screen form.

Thoughts?

**Comment by ThomasKranitsas** [comment] 2017-03-03 12:39
It also makes more sense to change the button from `Define another screen` to `Save & Add new screen`

**Comment by ThomasKranitsas** [comment] 2017-03-03 13:06
With the changes I suggested the app will look/work like this: http://take.ms/5xZce

**Comment by ThomasKranitsas** [comment] 2017-03-03 14:11
@cwdcwd I submitted a PR for this one. Shall I remove the `in progress` label?

**Comment by fnisen** [comment] 2017-03-03 18:30
@ThomasKranitsas - hello and nice to meet you! I'm the Product Manager for this project (and for Connect). Thanks a lot in advance for your help and for all your hard work on the community side, as well. 

Regarding this issue: good ideas. I'd like to simplify things a little and go with the original design, which does not match the current implementation. Here is the design: 
![screen shot 2017-03-03 at 10 21 01 am](https://cloud.githubusercontent.com/assets/12552247/23563417/74c91e60-fffb-11e6-99a9-ed77b065243d.png)
The "Notes" section is not part of the design and if it's removed, the Save button lines up right below the "Define another screen" button. So, once the user hits the screen limit, the "Define another screen" button is grayed out (and can be moused over) and the Save button is active. (I understand that we're auto-saving every time "Define another screen" is hit, but other parts of the form don't work the same way--the user has to press "Save." I don't want to introduce two different ways to save, even if that's what's happening behind the scenes. The right experience is auto-saving everywhere, but that's a more complicated implementation that we're planning to do later). 

So, can you please:
- Remove the Notes section
- Disable the "Define" button once the limit is hit
- Enable the mouseover on the "Define" button when it's disabled, using the tool-tip component @vikasrohit referenced above
Thank you.

**Comment by ThomasKranitsas** [comment] 2017-03-03 18:44
Hi @fnisen! Nice to meet you too!

Currently each screen is being saved once you press the `Define another screen` button thus if we disable that button once we are at the last (allowed) screen we **can't** save the last screen. That was the reason I suggested to rename the button from `Define another screen` to `Save & Add new screen`.

I understand you point that it's a bit confusing to have 2 Save buttons.
I can change my implementation so the buttons says `Define another screen` and when it's clicked from the last (allowed) screen it will:
* Save the screen.
* Disable the `Define another screen` button and show the error on hover.
* Hide the form to add new screen. (As we've reached the limit)

Is that what you need?

About the *Notes* part: There is another ticket for that #648 so I guess I will fix it on the other ticket, correct?

**Comment by fnisen** [comment] 2017-03-03 19:01
@ThomasKranitsas summarizing what we agreed on Slack:
- "Define another screen" will be disabled after it's clicked on the second-to-last screen
- User will use "Save" to save the last screen
- "Notes" section will be removed from the "App Screens" section only (#648 is a separate issue) 
Thank you!

**Comment by vikasrohit** [comment] 2017-03-04 03:56
>User will use "Save" to save the last screen

@fnisen To me it seems confusing because if we are saving all screens (other than the last one) on clicking of "Define another screen" button, and saving last screen on clicking the "Save" button, user might miss saving the the last screen. IMO, as you said earlier, we should save all screens on click of save button.

**Comment by ThomasKranitsas** [comment] 2017-03-04 10:51
@vikasrohit I understand your confusion here... 

Actually the buttons on the view do not accurately describe what's happening behind the scenes.

The `Define another screen` button give to the user the idea that it's purpose is to create a new screen but it's real purpose is to `push` the screen which has the `isNew` property to the `screens` array so that screen will be saved once you click the `Save changes` button.

The `Save changes` button is a generic button which saves the whole object and it's not directly connected with each screen.

In conclusion: Currently even if you click the `Define another screen` you still have to click the `Save changes` button to actually save the screen.

Please check a demo here http://take.ms/SZl23 and notice the `DEBUG` line I've added on the footer which shows how many screens are actually pushed in the `screens` array.
As you can see in the demo the `isNew` screen is not saved until I click the `Define another screen` button.

There are two possible approaches for this to be resolved:

1) Leave it as it is in my demo where you have to click `Define another screen` to push the screen to the `screens` array and then click `Save changes` to save all changes to the screens and if you click the `Define another screen` button in the last screen it will push the last screen to the `screens` array and it will then be disabled with the error tooltip on hover over.

2) Change it so each `isNew` screen will be automatically pushed to the `screens` array, the role of the `Define another screen` will **ONLY** be to add another screen, and you will just have to click the `Save changes` button to save the screens.

@fnisen @vikasrohit Which approach makes more sense to you?

*PS: sorry for the long post :)*

**Comment by vikasrohit** [comment] 2017-03-06 06:52
Yes, 2 options is what I am looking for. Still, lets wait for @fnisen to weigh in.

**Comment by fnisen** [comment] 2017-03-06 16:51
@vikasrohit, @ThomasKranitsas let's go with option 2. 

Vikas, you can make the call regarding the best implementation, but either way I agree that the user experience is confusing. Right now we say "Project updated" when "Define another screen" is clicked. Regardless of whether we're saving behind the scenes, we should not be establishing the expectation that anything is being saved because we need the user to click the "Save" button at the end.

**Comment by vikasrohit** [comment] 2017-03-07 05:18
Yes, exactly @fnisen That was my intention. That Project updated message sets wrong expectation right now. So, yes, option 2 is one we should go for.

**Comment by ThomasKranitsas** [comment] 2017-03-07 09:47
Is validation out of scope? I mean the validation is not working correctly right now.. For example if I add 3 screens and then clear all fields of the first screen it shows the validation errors but if I click the `Save Changes` button and refresh the page the app saves the empty screen.. Is that the expected behaviour?

Will validation be handled in another ticket?

**Comment by gondzo** [comment] 2017-03-07 09:53
Let's handle it in this ticket. Saving the empty screen's shouldn't be possible.

**Comment by ThomasKranitsas** [comment] 2017-03-07 09:55
So should I just remove the empty screens before saving the project? Or disable the `Save Changes` button if there is any invalid screen?

**Comment by gondzo** [comment] 2017-03-07 10:10
Disable the Save Changes button

**Closed** 2017-03-09 18:54 UTC
Labels: in progress, known-issue, P1, products
