### ISSUE TITLE
[$50] Cannot read property 'add' of null

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2916] opened 2019-03-15 06:00 UTC
### Expected behavior
Should not throw error in console

### Actual behavior
For certain use case, it is throwing the mentioned error and it is reported by Sentry

### Screenshot/screencast

```
TypeError: Cannot read property 'add' of null
  at ? (/main.ccb45b5919e555701f4f.js:23:38673)
  at Array.map(<anonymous>)
  at t.createProduct(/main.ccb45b5919e555701f4f.js:23:38527)
  at Object.createProduct(/main.ccb45b5919e555701f4f.js:114:83874)
  at t.value(/main.ccb45b5919e555701f4f.js:287:152657)
  at onClick(/main.ccb45b5919e555701f4f.js:287:160395)
  at Object.i(/main.ccb45b5919e555701f4f.js:33:4576)
  at s(/main.ccb45b5919e555701f4f.js:33:2777)
  at Object.executeDispatchesInOrder(/main.ccb45b5919e555701f4f.js:33:3506)
  at d(/main.ccb45b5919e555701f4f.js:28:114025)
  at f(/main.ccb45b5919e555701f4f.js:28:114151)
  at Array.forEach(<anonymous>)
  at e.exports(/main.ccb45b5919e555701f4f.js:77:295485)
  at Object.processEventQueue(/main.ccb45b5919e555701f4f.js:28:115555)
  at ? (/main.ccb45b5919e555701f4f.js:114:27795)
  at Object.handleTopLevel [as _handleTopLevel](/main.ccb45b5919e555701f4f.js:114:27817)
  at f(/main.ccb45b5919e555701f4f.js:114:49978)
  at c.perform(/main.ccb45b5919e555701f4f.js:28:168729)
  at Object.batchedUpdates(/main.ccb45b5919e555701f4f.js:114:49458)
  at Object.batchedUpdates(/main.ccb45b5919e555701f4f.js:28:13803)
  at dispatchEvent(/main.ccb45b5919e555701f4f.js:114:50759)
  at HTMLDocument.d(raven.js:386:29)
```

More specific code block identified by Sentry:

```
snip} ne",null),r=(0,y.getPhaseActualData)(e,n);return r.endDate.add(1,"day")}),a=(0,p.default)().hours(0).minutes(0).seconds(0).milliseconds(0),s {snip}
```

--

#### Environment
- OS: Windows 10
- Browser (w/version): Chrome 68.0.3440
- User role (client, copilot or manager): Manager
- Account used: N/A

**Comment by maxceem** [comment] 2019-04-01 11:12
Sum up: 
- Looks like of the error is here https://github.com/appirio-tech/connect-app/blob/dev/src/projects/actions/project.js#L253
For this issue it would the best to do two things:
- find out the possible root of this issue
- instead of hiding the error at the line where this error has been logged, fix the issue as close to the root as possible

**Comment by sumitdaga** [comment] 2019-04-11 08:24
@maxceem   
can you assign it to me please?

**Comment by maxceem** [comment] 2019-04-11 08:30
done

**Comment by sumitdaga** [comment] 2019-04-11 11:07
@maxceem  
i think the issue is caused in this function https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/projectHelper.js#L223   
are milestones certain to have non-null `startDate` and `endDate`?  
most likely the issue i think comes from here  https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/projectHelper.js#L232  
what do you think ?

**Comment by sumitdaga** [comment] 2019-04-11 13:25
btw any idea why this just keeps loading https://connect.topcoder-dev.com/projects/7855/add-phase  
why is `/phases` endpoint throwing 404 for this project ?

**Comment by maxceem** [comment] 2019-04-11 13:48
Could be some issue during project creating. Do you have to know the reason for that issue? Or you need a project where it works? For example, it works for this project https://connect.topcoder-dev.com/projects/7968/plan

**Comment by sumitdaga** [comment] 2019-04-11 13:55
i thought i needed a project with no phases and then add a phase to it ...but its not needed   
can you answer the above https://github.com/appirio-tech/connect-app/issues/2916#issuecomment-482070554 ?

**Comment by maxceem** [comment] 2019-04-11 14:52
> i thought i needed a project with no phases and then add a phase to it
I think we don't have such projects where we don't have phases but can add some in production. Such a project can be in DEV if something went wrong during testing.

> are milestones certain to have non-null startDate and endDate?
I guess in that line it checks endData of the phase not a milestone.
Technically endDate can be null https://github.com/topcoder-platform/tc-project-service/blob/dev/src/models/projectPhase.js#L11. But during project creation here https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/projects/create.js#L101 looks like we always define it. We also can add a phase and it depends on data from Connect https://github.com/topcoder-platform/tc-project-service/blob/dev/src/routes/phases/create.js#L65
So we may also check how Connect adds a phase.

> and how to verify this issue ?
I don't have an answer for this. It would be great if we understand the root of the issue and find out how to verify the fix. The minimal task is to try to understand the issue as close to the root as we can and fix it. After we will see if this issue happens again.

**Comment by sumitdaga** [comment] 2019-04-12 04:57
And unassigned me from this one. Can't figure out the exact reason

**Comment by rashmi73** [comment] 2019-04-12 05:08
@maxceem please assign this to me thanks

**Comment by maxceem** [comment] 2019-04-12 07:18
Thanks for update @sumitdaga.

@rashmi73 it's on you.

**Comment by rashmi73** [comment] 2019-04-13 00:17
@maxceem need some more time because it is tricky and lengthy a bit thanks

**Comment by maxceem** [comment] 2019-04-13 01:30
Sure, take your time.

**Comment by rashmi73** [comment] 2019-04-13 23:33
@maxceem MR https://github.com/appirio-tech/connect-app/pull/2953

**Comment by sumitdaga** [comment] 2019-04-16 09:37
@maxceem   
i put a considerable amount of time on this. I didn't know just a simple patch would do!

**Comment by rashmi73** [comment] 2019-04-16 20:11
@maxceem MR updated

**Comment by maxceem** [comment] 2019-04-17 04:38
@sumitdaga sorry if I mislead you by the task specification. The task was to find the cause of the issue as close to the root as possible and I also didn't know how far we can go there to find it out.

**Comment by sumitdaga** [comment] 2019-04-17 05:08
@maxceem  no worries :)

**Comment by rashmi73** [comment] 2019-04-17 10:29
@maxceem can you please review it. PR updated

**Closed** 2019-04-22 10:32 UTC
Labels: ACCEPTED, CF-16, P3, PAID, Sentry
