### ISSUE TITLE
Two Upload sections displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#407] opened 2016-10-01 15:08 UTC
### Expected behavior

---

Must display only one Upload section
### Actual behavior

---

Two Upload sections displayed
### Steps to reproduce the problem

---
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Upload a File using the File uploader
- Click Save Changes
- Now refresh the page
- Once the page fully loaded
- Click EDIT of the uploaded file
- Click OK
- Check the upload section
### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section)

---

![2016-10-01_20-36-38](https://cloud.githubusercontent.com/assets/4592712/19014902/d900739a-8816-11e6-90a4-762514adf8dd.png)
### Environment

---
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment] 2016-10-04 18:53
Noted that. Valid.

**Comment by parthshah** [comment] 2016-10-18 17:47
I've seen this once when there are errors on the page. But I am not able to reproduce this consistently. 
@vikasrohit - can you look into this when you get a chance?
@fnisen - downgrading this for now.

**Comment by fnisen** [comment] 2016-12-06 20:19
Not able to reproduce. Closing.

**Closed by fnisen** 2016-12-06 20:19 UTC
Labels: P1
