### ISSUE TITLE
[$10] Join Project Email Typo

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3486] opened 2020-01-07 05:45 UTC
Recently, we've updated buttons texts to `Join Project` and `Decline` instead of one button `View Project On Connect`.

We also have to update the text above respectively.

![image](https://user-images.githubusercontent.com/146016/71871289-b19b1a00-3153-11ea-9554-819a563945e2.png)

Should we just update text to:
**Hi Maksym Mykhailenko, you are invited to join the project TaaS-New updated. Please click on the button ("Join Project") below to join.**

Or should we also include to the text an option to `Decline` invitation?

cc @vikasrohit

**Comment by vikasrohit** [comment] 2020-01-07 06:51
Good catch @maxceem. fyi @RishiRajSahu

**Comment by maxceem** [comment] 2020-01-20 04:10
Sum up:
- this issue has to be fixed in another repo https://github.com/topcoder-platform/tc-notifications
- see file https://github.com/topcoder-platform/tc-notifications/blob/dev/emails/src/partials/project-team.html notification type `connect.notification.project.member.invite.created`

**Comment by rashmi73** [comment] 2020-01-21 10:37
@bug-bash-helper assign

**Comment by rashmi73** [comment] 2020-01-21 10:44
@bug-bash-helper https://github.com/topcoder-platform/tc-notifications/pull/169 is ready for review

**Comment by nithyaasworld** [comment] 2020-01-28 12:15
@maxceem I am seeing a different text than we intended above. Can you confirm please if this is intended?

**Comment by maxceem** [comment] 2020-01-29 02:52
This wasn't in the original issue description, though I guess it should get fixed too.

In the original issue, there is a text for a user with no-SSO login - we fixed that.
In the screenshot you've shared above, it's message for SSO login, which is different. Though we should also adjust it to reflect the fact that we have button for direct actions now.

So this is fixed now for SSO login too via commit https://github.com/topcoder-platform/tc-notifications/commit/c3b96a59e582063eddf9672fc3363e47b54f902c. 

As soon as the email template would be updated at Sendgrid it would be ready for testing. I would update here.

**Comment by maxceem** [comment] 2020-01-29 05:49
@nithyaasworld this is now fixed for SSO login too. It can be tested now on DEV.

**Comment by nithyaasworld** [comment] 2020-01-31 05:31
@maxceem I am not sure if topcoderconnect+Copilot@gmail.com is a SSO user. **Can you confirm please?**

If yes, I will have to check with Lakshmi for a non-SSO user. CC: @lakshmiathreya

**Comment by maxceem** [comment] 2020-01-31 05:35
It depends on the project. Please use the same project for testing as you did before "Test Project New" it would use SSO login.

For non-SSO login you may use any project without REF code.

**Comment by nithyaasworld** [comment] 2020-02-03 04:28
Verified in Dev.

This is for a project with Reference code:
![image](https://user-images.githubusercontent.com/5114190/73625424-cb545200-466a-11ea-84b1-9353d109f5d1.png)

This is for a project with No Reference code:
![image](https://user-images.githubusercontent.com/5114190/73625623-a7ddd700-466b-11ea-8865-cbbf8ecada31.png)

**Comment by nithyaasworld** [comment] 2020-02-05 01:29
@maxceem 

Being a Copilot Manager user, I tried inviting a Copilot and also a Account Manager. But both of them did not get any emails.

Copilot Manager used: @TCConCopilotMgr
Project tested with: https://connect.topcoder-dev.com/projects/8853 ( it has refcode = 'topcoder' )
 
Could you check please? 

I also checked that the Notifications are enabled in the Notification-settings of Copilot and Account Manager users.

**Comment by maxceem** [comment] 2020-02-05 01:38
I would check it out @nithyaasworld.
As it's another issue, would it be better to track it as a separate from the current one?

**Comment by nithyaasworld** [comment] 2020-02-05 03:25
Sure @maxceem 

I again checked the Original issue of this ticket. Now, I am not getting notification email for that too, thought it worked 2 days ago.

Tested by logging in as: TCConCopilotMgr
Project tested with: https://connect.topcoder-dev.com/projects/8851
User invited: TCConnCopilot

Can you please check and confirm if we are missing anything? 

I double checked that the invited user (TCConnCopilot) has all the notifications enabled in the settings.

**Comment by maxceem** [comment] 2020-02-06 06:36
@nithyaasworld it was some issue with TC Notification Service on DEV not relevant to any of our changes so service was partially down. Could you please try to test this again.

**Comment by drasticdpk** [comment] 2020-02-28 10:42
Verified for project with No Reference code:
![image](https://user-images.githubusercontent.com/25297859/75542078-306f4d80-5a47-11ea-8fe4-8518b30c628e.png)

**Comment by vikasrohit** [comment] 2020-03-02 07:35
Closing the issue for cleanup. Please feel free to create separate regression issues.

**Closed by vikasrohit** 2020-03-02 07:35 UTC
Labels: ACCEPTED, CF-20, PAID, QA Pass in Dev
