### ISSUE TITLE
Project Features: complete image not visible on Payment feature 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#330] opened 2016-09-29 09:41 UTC
### Expected behavior
image should be displayed completly or page must be scroll-able 
### Actual behavior
not able to see image 

### Steps to reproduce the problem
- 1. Open the Application
2. Login with username sweta.singh
3. Create new project
4. Goto Specification
5. Goto Feature Section
6. click on Add/Edit feature
7. Redirect to Project feature
8. Go to PAyment

### Screenshot/screencast
ttach or link a resource.

--
![image](https://cloud.githubusercontent.com/assets/16131461/18948972/db5fccce-8656-11e6-81ee-da725ad0cecc.png)

#### Environment
- OS:Windows 7
- Browser (w/version): IE 11  1366* 768 resolution 
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment] 2016-10-04 12:45
Duplicate of #200

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
