### ISSUE TITLE
Must validate Projects without a name

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#308] opened 2016-09-29 01:40 UTC
### Expected behavior
-----------------------------------------------------------------
Must validate Projects without a name

### Actual behavior
-----------------------------------------------------------------
Can create a Project without a name

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Project'
- Select: What would you like to do? --> Prototype an app
- Select: Phone, Tablet --> Pick target device(s)
- Enter spaces for Project name and Description
- Click 'Create Project'

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_7-07-20](https://cloud.githubusercontent.com/assets/4592712/18938101/ba197b16-8613-11e6-9c2c-0b4a59e721e3.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment] 2016-09-29 01:54
![2016-09-29_7-24-24](https://cloud.githubusercontent.com/assets/4592712/18938366/cb47bff4-8615-11e6-8292-6daead3eb218.png)

**Comment by mahestro** [comment] 2016-10-04 12:09
Duplicate of #184.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
