### ISSUE TITLE
Project features: text Alignment issues in Social Login  in IE 11

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#329] opened 2016-09-29 09:35 UTC
### Expected behavior
enable/disable button should be disabled 

### Actual behavior
button not displayed even page is not scorllable .

### Steps to reproduce the problem
1. Open the Application
2. Login with username
3. Create new project
4. goto Specification
5. Go to Features section
6. Add/Edit Feature
7. Click on Social Login 

### Screenshot/screencast
![image](https://cloud.githubusercontent.com/assets/16131461/18948798/291c71c0-8656-11e6-839f-cc6a3503be97.png)

--

#### Environment
- OS:Windows 7
- Browser (w/version): IE 11
- User role (client, copilot or manager):
- Account used:

**Comment by swetaipec** [comment] 2016-09-29 09:36
Screen Resolution : 1366*768

**Comment by swetaipec** [comment] 2016-09-29 09:54
same issue with Activity feed & Profiles in Social Feature

**Comment by mahestro** [comment] 2016-10-04 12:43
Duplicate of #200.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate, visual styling
