### ISSUE TITLE
Can't create a new account "Unexpected end of JSON input" error displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#980] opened 2017-07-24 17:25 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' > Register for free

- Enter all the required data

- Click Register

Actual Result(s)
-----------------------------------------------------------------
- Can't create a new account "Unexpected end of JSON input" error displayed

Expected Result(s)
-----------------------------------------------------------------
- Must able to create new users

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/connect/registration

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![11](https://user-images.githubusercontent.com/4592712/28535790-389877ae-70c3-11e7-8b23-40e4234dca8d.jpg)

``

app.0c1c6c6….js:sourcemap:438 Error: transition prevented
    at L [as $get] (app.0c1c6c6….js:sourcemap:23)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at n (app.0c1c6c6….js:sourcemap:436)
    at r (app.0c1c6c6….js:sourcemap:436)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at c (app.0c1c6c6….js:sourcemap:436)
    at le (app.0c1c6c6….js:sourcemap:436)
    at a (app.0c1c6c6….js:sourcemap:436) "Possibly unhandled rejection: {}"
(anonymous) @ app.0c1c6c6….js:sourcemap:438
app.0c1c6c6….js:sourcemap:438 Error: transition aborted
    at L [as $get] (app.0c1c6c6….js:sourcemap:23)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at n (app.0c1c6c6….js:sourcemap:436)
    at r (app.0c1c6c6….js:sourcemap:436)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at c (app.0c1c6c6….js:sourcemap:436)
    at le (app.0c1c6c6….js:sourcemap:436)
    at a (app.0c1c6c6….js:sourcemap:436) "Possibly unhandled rejection: {}"
(anonymous) @ app.0c1c6c6….js:sourcemap:438
app.0c1c6c6….js:sourcemap:438 Error: transition failed
    at L [as $get] (app.0c1c6c6….js:sourcemap:23)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at n (app.0c1c6c6….js:sourcemap:436)
    at r (app.0c1c6c6….js:sourcemap:436)
    at Object.a [as invoke] (app.0c1c6c6….js:sourcemap:436)
    at app.0c1c6c6….js:sourcemap:436
    at c (app.0c1c6c6….js:sourcemap:436)
    at le (app.0c1c6c6….js:sourcemap:436)
    at a (app.0c1c6c6….js:sourcemap:436) "Possibly unhandled rejection: {}"
(anonymous) @ app.0c1c6c6….js:sourcemap:438
api.topcoder-dev.com/v3/users/validateHandle?handle= Failed to load resource: the server responded with a status of 400 ()
topcoder-dev.auth0.com/oauth/ro Failed to load resource: the server responded with a status of 400 ()
api.topcoder-dev.com/v3/users/validateHandle?handle= Failed to load resource: the server responded with a status of 400 ()
topcoder-dev.auth0.com/oauth/ro Failed to load resource: the server responded with a status of 400 ()
api.topcoder-dev.com/v3/users/validateHandle?handle= Failed to load resource: the server responded with a status of 400 ()
topcoder-dev.auth0.com/oauth/ro Failed to load resource: the server responded with a status of 400 ()
api.topcoder-dev.com/v3/users/resetToken?email=dilhani&resetPasswordUrlPrefix=https%3A%2F%2Faccounts.topcoder-dev.com%2Fconnect%2Freset-password Failed to load resource: the server responded with a status of 404 ()
api.topcoder-dev.com/v3/users/validateHandle?handle= Failed to load resource: the server responded with a status of 400 ()
topcoder-dev.auth0.com/oauth/ro Failed to load resource: the server responded with a status of 400 ()
app.0c1c6c6….js:sourcemap:438 Validating email: sdguntc@gmail.com
app.0c1c6c6….js:sourcemap:438 Validating username: sdguntc
app.0c1c6c6….js:sourcemap:438 Validating username: sd
app.0c1c6c6….js:sourcemap:438 Validating email: sdguntc@gmail.com
app.0c1c6c6….js:sourcemap:438 Validating username: Qa
app.0c1c6c6….js:sourcemap:438 Validating username: sdguntc
api.topcoder-dev.com/v3/users Failed to load resource: the server responded with a status of 504 ()
``

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Not logged in
- **Account used:** N/A

**Comment by sdgun** [comment] 2017-07-25 05:14
https://www.screencast.com/t/yUJo4e421
https://www.screencast.com/t/Bj59m2WPDz

**Comment by gondzo** [comment] 2017-07-27 17:29
That was backend API error. The error message could be more friendly though.

**Comment by rushikesh90** [comment] 2017-07-30 04:49
Cannot reproduce this.  Any specific way to reproduce?

**Comment by vikasrohit** [comment] 2017-07-30 05:17
I think you can reproduce it by having api endpoint which either does not exist or return specific error e.g. 504. My guess is that it is because of JSON.parse is trying to parse empty string.

**Comment by gondzo** [comment] 2017-07-30 08:13
Right, invalid endpoint will cause this issue. You should only update error handling to display a more friendly error message.

**Comment by fnisen** [comment] 2017-08-02 01:57
That's not much friendlier. 🤓  Can you please change it to: "We weren't able to register you because of a system error. Please try again or contact suppor@topcoder.com." Also, the error styling is incorrect.

**Comment by chq-matteo** [comment] 2017-08-02 04:46
@fnisen What is the correct styling

**Comment by vikasrohit** [comment] 2017-08-02 06:50
@chq-matteo Just update the css class of the element where we are rendering these generic errors i.e. instead of `p.error` just use `.error-block`.

**Comment by chq-matteo** [comment] 2017-08-02 06:50
ok

**Comment by chq-matteo** [comment] 2017-08-02 06:53
Pull request updated @vikasrohit @fnisen

**Comment by vikasrohit** [comment] 2017-08-02 07:18
@chq-matteo can you please update the PR once more? Actually, we need to render it as div instead of paragraph element to get proper styles. Just remove the `p`.

**Comment by chq-matteo** [comment] 2017-08-02 07:22
@vikasrohit done

**Comment by vikasrohit** [comment] 2017-08-02 07:24
Thanks. @gondzo please verify and merge the PR.

**Comment by fnisen** [comment] 2017-08-02 16:15
Thanks @chq-matteo and @vikasrohit.

**Comment by gondzo** [comment] 2017-08-02 18:49
Changes are merged and styling looks correct.

**Comment by fnisen** [comment] 2017-08-02 22:14
Seeing some kind of merge issue now: 

![screen shot 2017-08-02 at 3 11 54 pm](https://user-images.githubusercontent.com/12552247/28897375-4c90ebaa-7795-11e7-9cd2-634fe520fa8e.png)

https://accounts.topcoder-dev.com/!#/connect/registration

**Comment by fnisen** [comment] 2017-08-02 23:31
OK, styling looks good, thanks. 

@vikasrohit what are the error messages we show? I was able to get a weird one "Failed to fetch" by turning off my connection during the API call.

**Comment by vikasrohit** [comment] 2017-08-03 06:10
This seems to a message from the fetch library, I guess, we might need to show a generic error message instead, if possible.

**Comment by fnisen** [comment] 2017-08-03 19:06
OK, do you want to work on this later?

**Comment by vikasrohit** [comment] 2017-08-16 12:21
@fnisen I have handled the 'Failed to fetch' error as well to show the generic error message. In fact I have tried to to capture all errors which are not checked errors (i.e. errors that are not explicitly set by our backend APIs) to show that generic error. Let me know if you still see any specific runtime error.

**Comment by fnisen** [comment] 2017-08-22 19:01
@vikasrohit this is working well, thanks. However, the styling of the text looks a little off to me. It seems to be too compressed (the two lines are too close together). I can't find an example of Vic's design of a two-line error, but can you please check if this matches our normal paragraph spacing? 

![screen shot 2017-08-22 at 11 59 10 am](https://user-images.githubusercontent.com/12552247/29582379-55bf8762-8731-11e7-9658-71d8a29bd944.png)

![screen shot 2017-08-22 at 12 00 43 pm](https://user-images.githubusercontent.com/12552247/29582439-8cd3c1aa-8731-11e7-9b8e-34eacf81ea58.png)

**Comment by vikasrohit** [comment] 2017-08-23 06:48
@fnisen We are not explicitly setting or reducing the line spacing for error block. And when we are comparing it with the line spacing in spec question, they are different HTML elements and have different spacings. Spec question is rendered using h5 while error block is rendered using normal div. They are different in terms of typography as well. So, it makes sense to have different spacing in these two places. However, I think we can improve the spacing of error block a bit. So, I have just increased the line spacing a bit (15px from 13px) for error blocks. Please let me know if that suffice.

**Comment by fnisen** [comment] 2017-08-23 19:25
@vikasrohit that looks better, thank you.

**Closed by fnisen** 2017-08-23 19:25 UTC
Labels: bug hunt, P2
