### ISSUE TITLE
[$130] Update react-select version

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2846] opened 2019-02-19 02:50 UTC
We started using `react-select` library a pretty long time ago. And current version `0.9.1` has several issues while the latest version is `2.4.0`.

Issues:
- Warning in browser console: `Warning: Unknown prop 'minWidth' on <input> tag.`
- Warning in browser console: `Warning: AutosizeInput: isMounted is deprecated.`
- So far we have to call API method directly from the component because the current version expects a promise as `asyncOptions`. And if we try to rewrite it in a controlled way to utilize the Redux actions and reducers we have to define `onInputChange` to react on input change. But if we define it, then current version doesn't update the input value and we cannot control input value from the outside. So we cannot implement it in a controlled way.

At the moment we use `react-select` only in two places:
- File permissions dialog by utilizing `UserAutoComplete` component https://github.com/appirio-tech/connect-app/blob/feature/team-management-autocomplete/src/components/UserAutoComplete/UserAutoComplete.jsx#L14
- Topcoder/Prokect team dialogs by utilizing `AutocompleteInput` component https://github.com/appirio-tech/connect-app/blob/feature/team-management-autocomplete/src/components/TeamManagement/AutocompleteInput.jsx#L12

### TODO
- Update `react-select` to the latest `2.4.0` version.
- Refactor `AutocompleteInput` 
   - Split `AutocompleteInput` component into two: `AutocompleteInput` and `AutocompleteInputContainer`. Only container should be connected to the redux store.
   - It shouldn't call API method `loadMemberSuggestions` directly, but call a redux action `loadMemberSuggestions` instead from https://github.com/appirio-tech/connect-app/blob/feature/team-management-autocomplete/src/projects/actions/projectMember.js#L24
   - Update code of `LOAD_MEMBER_SUGGESTIONS` reducer. Now it keeps values for suggested member in the same place where we keep all the members: `members.members`. We don't want them mix them up. So we should keep suggested members in `members.suggestedMembers` instead https://github.com/appirio-tech/connect-app/blob/feature/team-management-autocomplete/src/reducers/members.js#L18. Also, now we keep suggested members as an object which doesn't guaranties an order. So we should keep the suggested members as an array instead.
   - After we updated reducer `AutocompleteInputContainer` can get list of suggested members from the Redux store `members.suggestedMembers` and pass it to `AutocompleteInput` to show them.
- `UserAutoComplete` should still work after `react-select` version update.

**Comment by maxceem** [comment] 2019-02-25 05:24
To see places, where these components are in use `pshah_manager` user, can be used. This project has both places: http://local.topcoder-dev.com:3000/projects/7855
- `UserAutoComplete`

    ![image](https://user-images.githubusercontent.com/146016/53315864-5deb5d80-3900-11e9-9143-f3fcacadc6d1.png)

- `AutocompleteInput`

   ![image](https://user-images.githubusercontent.com/146016/53315898-85422a80-3900-11e9-971e-ebe975f3de70.png)

**Comment by khushimehta03** [comment] 2019-02-26 05:11
@maxceem can i try this? thank you

**Comment by maxceem** [comment] 2019-02-26 05:12
@khushimehta03 sure

**Comment by gautam1168** [comment] 2019-02-27 01:01
@maxceem Is this becoming open for pickup again?

**Comment by maxceem** [comment] 2019-02-27 01:27
As there was no PR for 12 hours, this issue is now open for pick up.

@gautam1168 please, comment again if you want to take the issue **after** it's open for pick up. This is to keep it fair to everybody as per our [Bug Bash rules](https://www.topcoder.com/challenges/30084798)

Thank you.

**Comment by mhikeo** [comment] 2019-02-27 01:28
@maxceem Can I take this up? Thanks.

**Comment by maxceem** [comment] 2019-02-27 01:29
@mhikeo sure, it's on you.

**Comment by gautam1168** [comment] 2019-02-27 12:59
https://github.com/appirio-tech/connect-app/issues/2846

**Comment by maxceem** [comment] 2019-02-27 14:37
As no PR was raised during 12 hours and there is no comment for the extension, this issues is now open for pick up.

Note, the one who comments first after this issue is open for pick up can start working on it without waiting to be assigned, as per our [Bug Bash rules](https://www.topcoder.com/challenges/30084798)

**Comment by PrakashDurlabhji** [comment] 2019-02-27 14:42
@maxceem assign it to me

**Comment by gautam1168** [comment] 2019-02-27 14:44
dang! missed it again!

**Comment by maxceem** [comment] 2019-02-27 15:03
@PrakashDurlabhji done

**Comment by gautam1168** [comment] 2019-02-28 00:34
This time 🤞

**Comment by gautam1168** [comment] 2019-02-28 02:19
@maxceem is this open again?

**Comment by maxceem** [comment] 2019-02-28 02:50
As no PR was raised during 12 hours and there is no comment for the extension, this issues is now open for pick up.

Note, the one who comments first after this issue is open for pick up can start working on it without waiting to be assigned, as per our [Bug Bash rules](https://www.topcoder.com/challenges/30084798)

**Comment by gautam1168** [comment] 2019-02-28 02:50
assign to me

**Comment by maxceem** [comment] 2019-02-28 02:52
@gautam1168 done!

**Comment by maxceem** [comment] 2019-02-28 02:53
@gautam1168 please, use branch `cf15` for your work. As in last PR you used `dev`.

**Comment by gautam1168** [comment] 2019-02-28 03:13
@maxceem ok Ill use that branch

**Comment by gautam1168** [comment] 2019-02-28 05:22
@maxceem The issue asks to update the `LOAD_MEMBER_SUGGESTIONS` reducer. But I don't see any such reducer action being handled in the indicated members.js file or any other file in the project. So, this reducer action handling is to be added? As in 
```
case LOAD_MEMBER_SUGGESTIONS:
   //populate the array with payload
```

**Comment by maxceem** [comment] 2019-02-28 05:28
@gautam1168 The action is called `LOAD_MEMBER_SUGGESTIONS`, but in reducer it's used with suffixes like `LOAD_MEMBER_SUGGESTIONS_SUCCESS`, `LOAD_MEMBER_SUGGESTIONS_PENDING`, `LOAD_MEMBER_SUGGESTIONS_FAILURE`.

Here it is in the file `src/reducers/members.js`: https://github.com/appirio-tech/connect-app/blob/cf15/src/reducers/members.js#L18

Currently, `LOAD_MEMBER_SUGGESTIONS_SUCCESS` has the same reducer as `LOAD_MEMBERS_SUCCESS`. But it should be separated and put data in separate place in the redux store.

**Comment by gautam1168** [comment] 2019-02-28 08:57
@maxceem is something wrong with the servers? I cannot load the projects anymore

**Comment by maxceem** [comment] 2019-02-28 09:16
@gautam1168 I've just checked and it works good for me. Do you still have this issue? Do you have any errors in browser console?

**Comment by gautam1168** [comment] 2019-02-28 09:54
@maxceem I have been working with the other account since my comment. It must have been a problem with my wifi. 

I have another question. I have updated the version and split the reducer as asked and everything seems to be working fine but only for the `Manage Team` popup. It seems that the other select box is unaffected by my changes. Im making a PR in a few minutes. Please check and tell me if the PR covers everything you need. Ill make more changes if something is missing.

**Comment by maxceem** [comment] 2019-02-28 10:00
@gautam1168 sure, thank you!

**Comment by gautam1168** [comment] 2019-02-28 10:19
@maxceem please check PR: https://github.com/appirio-tech/connect-app/pull/2870

**Comment by gautam1168** [comment] 2019-02-28 10:47
@maxceem That was a false alarm. Running npm start again fixed the problem. Please check PR: https://github.com/appirio-tech/connect-app/pull/2870

**Comment by maxceem** [comment] 2019-02-28 11:41
> Please give me some more time if after checking you find that the PR needs more changes.

No worries, 12 hours limitation is for the PR only. I guess I'll review PR tomorrow. It's ok to provide an update for PR during 24 hours after review.

**Comment by gautam1168** [comment] 2019-03-01 07:25
@maxceem I just updated the PR. Please see if you need any more changes.

**Comment by vikasrohit** [comment] 2019-03-07 11:19
Closing as dropdown is working fine after production release. So, seems like upgrade is successful without any regression.

**Closed by vikasrohit** 2019-03-07 11:19 UTC
Labels: ACCEPTED, PAID
