### ISSUE TITLE
Private messages for only Topcoder users

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2963] opened 2019-04-18 11:55 UTC
Internal users (all TC roles) should have the capability to have a private discussion feature where a discussion post is only viewable to TC users. The post should have a distinct UI to make it apparent to TC users that the message is not customer-viewable.

**Comment by ajefts** [comment] 2019-04-18 11:55
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1671343

**Comment by RishiRajSahu** [comment] 2019-04-18 11:56
duplicate of https://github.com/appirio-tech/connect-app/issues/2180

**Closed by RishiRajSahu** 2019-04-18 11:56 UTC
