### ISSUE TITLE
Project Description spill over the Project Outline space

### ISSUE THREAD

**Issue by m-prabhu** [appirio-tech/connect-app#1011] opened 2017-07-24 19:15 UTC
### Expected behavior
Project Description spill over the Project Outline space

### Actual behavior
Project Description should not spill over the Project Outline space

### Steps to reproduce the problem
-goto https://connect.topcoder-dev.com
-click start a project
-select 'software development'
-provide a long project description like 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' and save the project
- As shown in screenshot project description will spill over the Project Outline space.

### Screenshot/screencast
![selection_039](https://user-images.githubusercontent.com/30400318/28540169-f7773990-70d1-11e7-86cf-55009592c190.png)
![selection_046](https://user-images.githubusercontent.com/30400318/28540468-23660468-70d3-11e7-8d76-9bf3b0901eda.png)

--

#### Environment
- OS: Windows 7 32 bit
- Browser (w/version): Firefox 54, Chrome 59
- User role (client, copilot or manager): Not Applicable
- Account used: Not Applicable

**Comment by gondzo** [comment] 2017-07-27 18:10
duplicate of #995

**Closed by gondzo** 2017-07-27 18:10 UTC
Labels: bug hunt, duplicate
