### ISSUE TITLE
[$175] In app notifications are sent though they are turned off

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3455] opened 2019-12-19 22:27 UTC
1. Login as Copilot (topcoderconnect+Copilot@gmail.com) and create a new project
2. In Notification settings, turn off in-app notifications of 'Project status' 
3. Login as Connect Manager ( topcoderconnect+manager@gmail.com)
4. Join the project (which the Copilot created in Step 1) as manager
5. Change the project status 
6. Then check the notification in Copilot's user's login

![image](https://user-images.githubusercontent.com/5114190/71214879-44c2fb80-22dc-11ea-9d5a-81d288d56297.png)

![image](https://user-images.githubusercontent.com/5114190/71215109-dc284e80-22dc-11ea-8c4a-e9f99efb1bb3.png)

**Comment by nithyaasworld** [comment] 2019-12-19 22:28
cc: @lakshmiathreya

**Comment by maxceem** [comment] 2019-12-23 06:01
Can reproduce the issue and it looks valid as this notification type 

![image](https://user-images.githubusercontent.com/146016/71338869-677b3b80-258c-11ea-8b35-e93622f0fade.png)

suppose to be turned off by that setting:

![image](https://user-images.githubusercontent.com/146016/71338888-76fa8480-258c-11ea-95d4-7cd6a92ad708.png)

Sum up:
- to fix this issue we would have to make the full setup of Project Service + Connect App + Notification Service. It can be done by following the next sections:
   1. https://github.com/topcoder-platform/tc-project-service#local-deployment-with-other-topcoder-services
   2. https://github.com/topcoder-platform/tc-project-service#steps-to-run-locally
   3. https://github.com/topcoder-platform/tc-project-service#run-connect-app-with-project-service-locally
   4. (Optionally) create a demo data https://github.com/topcoder-platform/tc-project-service#import-sample-metadata--projects

**Comment by yoution** [comment] 2020-01-21 10:43
@bug-bash-helper assign

**Comment by yoution** [comment] 2020-01-21 16:37
@maxceem 

for `create` type
* this is ui
![image](https://user-images.githubusercontent.com/3863914/72823296-74d03680-3cae-11ea-8ee3-7fdc2556cf3c.png)
* this is request param
![image](https://user-images.githubusercontent.com/3863914/72823426-a812c580-3cae-11ea-9efd-fa1ede0d3c6d.png)
* this is the db data
![image](https://user-images.githubusercontent.com/3863914/72823631-fa53e680-3cae-11ea-8d2c-8a21f5d2f8f6.png)

is the db data right? or could you give the right format, I will remap to it?

**Comment by maxceem** [comment] 2020-01-21 16:57
@yoution I'm not sure what you mean in your question.

We have issues with notification type `connect.notification.project.approved` https://github.com/appirio-tech/connect-app/blob/cf20/src/config/constants.js#L920 not `create`, just in case.

When we disable this option 
![image](https://user-images.githubusercontent.com/146016/72824497-51a68680-3cb0-11ea-927e-1f6c76c0c30f.png)

`connect.notification.project.approved` should be disabled for user together with other notification types about project status change notifications:

![image](https://user-images.githubusercontent.com/146016/72824544-6aaf3780-3cb0-11ea-958f-a3b5d930f21c.png)

So when we get the list of the notifications for the user using endpoint TC Notifications service https://api.topcoder-dev.com/v5/notifications/list?read=false&per_page=1000 it supposes to filter notifications with such type and don't return them https://github.com/topcoder-platform/tc-notifications/blob/v5-upgrade/src/services/NotificationService.js#L190-L198 but it returns it in some reason.

So what can be checked:
- we correctly save the value for `connect.notification.project.approved` in settings
- if we save correct setting for `connect.notification.project.approved`, check why notifications with such type are not filtered in TC Notifications Service

**Comment by yoution** [comment] 2020-01-22 00:04
@maxceem 

this is for  `approved ` type, I just used `create` type for example
* this is ui
![image](https://user-images.githubusercontent.com/3863914/72823296-74d03680-3cae-11ea-8ee3-7fdc2556cf3c.png)
* this is request param
![image](https://user-images.githubusercontent.com/3863914/72823426-a812c580-3cae-11ea-9efd-fa1ede0d3c6d.png)
![image](https://user-images.githubusercontent.com/3863914/72853595-d8795480-3cec-11ea-8ea9-07c3d33b64f4.png)

* this is the db data
![image](https://user-images.githubusercontent.com/3863914/72853556-b384e180-3cec-11ea-9c67-2b470340bbd5.png)
* the data in db
![image](https://user-images.githubusercontent.com/3863914/72853843-7ec55a00-3ced-11ea-8fb8-3e865c83a73b.png)

is the db data right? for 'approve' type, it will generate 6 line datas?

**Comment by maxceem** [comment] 2020-01-22 03:04
Got it @yoution.

The data looks correct. 
We have 3 kind of "services" which can deliver notification:
- `web` - show notification in Connect App is what we have the issue with at the moment
- `email` - send notification by email
- `emailBundling` - redundant service which has been replaced by setting `bundlePeriod`
- each of the 3 services have 2 settings: 
   - `enabled` - if it's enabled or no, 
   - `bundlePeriod` that says if several notifications should be combined to one during some period of time or no. But only `email` service uses this setting, `web` - doesn't.

So from the data in DB it looks like notifications of type `approved` are disabled for `web`, because it has the value `no`. But for some reason we still get it.

**Comment by yoution** [comment] 2020-01-22 03:47
@bug-bash-helper https://github.com/topcoder-platform/tc-notifications/pull/170 is ready for review

**Comment by nithyaasworld** [comment] 2020-01-28 21:51
Works Perfect!! Verified in dev.

**Comment by vikasrohit** [comment] 2020-03-02 11:44
Closing. Please feel free to create new issues for any regression.

**Closed by vikasrohit** 2020-03-02 11:44 UTC
Labels: ACCEPTED, CF-20, Dev Environment, P3, PAID, QA Pass in Dev
