### ISSUE TITLE
After Leaving the project; Still displayed in the table

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#417] opened 2016-10-01 16:15 UTC
### Expected behavior
-----------------------------------------------------------------
Must remove from the table after he/she leaves from the project

### Actual behavior
-----------------------------------------------------------------
After Leaving the project; Still displayed in the table

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- In the FILTER
- Project Type: Visual Prototype
- Status: In Review
- Set: ON - My Projects
- Now click on a Project
- Leave the user from the Project
- Check the table once it is loaded again

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_21-44-48](https://cloud.githubusercontent.com/assets/4592712/19015342/502fb1fc-8820-11e6-9854-a8f692b6767d.png)

http://screencast.com/t/dnntL60i5an

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 19:12
Duplicate of #243

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
