### ISSUE TITLE
swetaipec: after deleting project , should lands user to project listing page 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#189] opened 2016-09-28 18:59 UTC
Steps:
1.) Open the application
2.) Login with username sweta.singh
3.) create project
4.) delete project

expected Result: should lands user to listing page
Actual Result: still showing project delete page even after delete confirmation msg

![image](https://cloud.githubusercontent.com/assets/16131461/18927955/b1f3d95a-85db-11e6-8b6b-3506c29a4200.png)

**Comment by fnisen** [comment] 2016-10-26 22:38
Also not able to reproduce. Closing.

**Closed by fnisen** 2016-10-26 22:38 UTC
Labels: won't fix
