### ISSUE TITLE
User can't download the file attached

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3848] opened 2020-04-06 06:23 UTC
### Expected behavior
Should be able to download the file.

### Actual behavior
After changing the file name, the user can't download the file

### Steps to reproduce the problem
- Login as Customer
- Click on a project that has permission
- Click "Assets Library"
- Upload a file (Word.doc) and select 'Member X' from the 'OR ONLY SPECIFIC PEOPLE' section > Click 'Share with selected members
- Click on the file to download

File Used: 
[CSVFile_119kb (1).zip](https://github.com/appirio-tech/connect-app/files/4424034/CSVFile_119kb.1.zip)

### Screenshot/screencast

https://www.screencast.com/t/aunh9OGtiw

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Customer
- Account used:  CustomerUser

**Comment by maxceem** [comment] 2020-04-15 13:09
I think this issue is a duplicate of https://github.com/appirio-tech/connect-app/issues/3839 as I cannot reproduce it.

@codejamtc could you, please, check if you can reproduce it or we can close it as a duplicate.

**Comment by codejamtc** [comment] 2020-04-15 14:07
https://monosnap.com/file/NFVeD0bvkvpSnxuTA6cfEetjeIlhid

**Comment by maxceem** [comment] 2020-04-15 14:09
Closing it as a duplicate of https://github.com/appirio-tech/connect-app/issues/3839.

**Closed by maxceem** 2020-04-15 14:09 UTC
Labels: Dev Environment, Functional, P3, duplicate
