### ISSUE TITLE
Test Environment: v5 - Any user can change the project status if the project is visible to them

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3400] opened 2019-12-09 12:10 UTC
**Issue Description:** Any user can change the project status if the project is visible to them

1. Login as topcoderconnect+copilot@gmail.com / appirio123 in the test environment https://connect-test01.topcoder-dev.com
2. Observe that the user has an option to mark a project as cancelled or paused or anything, though this user is not even part of that project.
3. Notice that the same option is not available in the Project details page. It's available only in the Project listing page

![image](https://user-images.githubusercontent.com/5114190/70434651-d21b7a00-1aaa-11ea-805e-6e50b8b361e0.png)

![image](https://user-images.githubusercontent.com/5114190/70434699-ee1f1b80-1aaa-11ea-8ece-f906fdb93178.png)

**Comment by nithyaasworld** [comment] 2019-12-09 12:10
cc: @lakshmiathreya @maxceem

**Comment by RishiRajSahu** [comment] 2019-12-11 03:48
@maxceem this seems to be a legit issue to be able to change the status without joining the project.

another thing @vikasrohit do we always wanted copilot being able to change the status of project being part of it?

**Comment by maxceem** [comment] 2019-12-12 10:37
It's fixed by PR https://github.com/appirio-tech/connect-app/pull/3415

Ready to review in both DEV and TEST environments.

**Comment by vikasrohit** [comment] 2019-12-12 11:18
> another thing @vikasrohit do we always wanted copilot being able to change the status of project being part of it?

what is the behaviour now after this fix? From top of my head, I think we do not have any restrictions on copilots' changing the projects' statuses, however, from very long time there was some bug which was preventing copilots to update the status of the projects to some specific statuses like `Active`. We may need to discuss it with product managers.

**Comment by maxceem** [comment] 2019-12-12 11:22
Generally, the issue was that logic on the project detail page was different form logic in project list page. The logic on the project details page was more correct IMHO so we end using it to the project listing page.

The previous logic on the project listing page has several breaches.

- When copilot is invited as `customer` but not yet a member, he could edit status as the user itself is has Topcoder copilot role, but he has to be able to do so ONLY if he is the `copilot` in the particular project.

So we should be safe now, as now we have the logic as on project details page, which should be good, as nobody reported any issues with it.

**Comment by vikasrohit** [comment] 2019-12-12 11:30
> So we should be safe now, as now we have the logic as on project details page, which should be good, as nobody reported any issues with it.

I have received some occasional issues from copilots in past for status updates and I have done status updates on their behalf.

**Comment by maxceem** [comment] 2019-12-12 11:33
As long as copilot is a member with `copilot` role, the current logic should work. If there are any issues, we could solve it for both places: project listing and project details in the same way.

**Comment by vikasrohit** [comment] 2019-12-12 11:36
Agreed. So, we would take copilot privileges for status updates after the release. @maxceem could you please log an issue for that?

**Comment by maxceem** [comment] 2019-12-12 11:41
@vikasrohit I'm not sure what is the issue with copilot privileges? do you mean occasional issues you've got from the coilots? https://github.com/appirio-tech/connect-app/issues/3400#issuecomment-564969036

**Comment by vikasrohit** [comment] 2019-12-13 07:55
I mean, we don't have clear understanding of what copilots are allowed to in terms of status updates. Although we haven't restricted explicitly, copilots are not able to update the project status to certain specific ones.

**Comment by maxceem** [comment] 2019-12-13 09:15
Created a follow up issue https://github.com/appirio-tech/connect-app/issues/3426

**Comment by nithyaasworld** [comment] 2019-12-16 21:25
@maxceem Currently, I am not able to change the status of a project being a Copilot for that project. Please confirm if this is an intentional change.

**Comment by maxceem** [comment] 2019-12-17 04:40
@nithyaasworld copilots should be able to change the status of the projects. It works good for me. Please, check that your user is a member of **Topcoder Team** with the `copilot` role. If you can still reproduce the issue, please let me know the project id which you are testing with:

![image](https://user-images.githubusercontent.com/146016/70965365-6482d580-20ca-11ea-86bf-606242a67c48.png)

**Comment by nithyaasworld** [comment] 2019-12-18 06:46
Thanks @maxceem It seems I had checked for a project where this Copilot user was a Customer and not a copilot!

**Closed** 2019-12-19 03:56 UTC
Labels: 2.4.16, P1, QA Pass in Prod
