### ISSUE TITLE
[Upload Files] - Error: Request failed with status code 500

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#356] opened 2016-09-29 16:38 UTC
Expected behavior
------------------------------------------------------------

- The 500 code error message is displayed in console.

Actual behavior
------------------------------------------------------------

- Do not display this error message.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Edit an existing project eg. Project{Nicu1}.

- Select Specification tab application.

- Go to Project Files (0) section.

- Press Add File.

- Choose Files and select a file from local computer(ex. an png image).

- After the image is uploaded press again the Choose File button.

- Select images from local computer.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

**Comment by mahestro** [comment] 2016-10-04 13:26
By the moment of loading the page there are two known errors and several warnings. After replicating the steps, there are no more console errors.

Can't replicate - http://take.ms/Zja8a

**Comment by fnisen** [comment] 2016-10-25 19:48
Can't reproduce either. Closing.

**Closed by fnisen** 2016-10-25 19:48 UTC
