### ISSUE TITLE
Even no results sort columns available

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#368] opened 2016-09-29 17:34 UTC
Expected behavior
------------------------------------------------------------

- Do not display sort option for columns.

Actual behavior
------------------------------------------------------------

- The sort option available even no results.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as mamager user role.

- Expand filter options.

- Set Project Type=Visual Prototype, Status=Open.

- Set My Project=Yes.

- Press on the column Status.

- Observe sort asc / desc icon displayed.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager user role
Account used: pat_monahan

![sort-options](https://cloud.githubusercontent.com/assets/5114907/18965040/28ab1ed4-8684-11e6-9f17-8a3f57f714c4.png)

**Comment by mahestro** [comment] 2016-10-04 15:51
Duplicate of #323

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
