### ISSUE TITLE
[$25] Long Ref Code goes out of the left panel

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3884] opened 2020-04-10 22:53 UTC
### Expected behavior
Should trim the long ref codes as in other browsers

### Actual behavior
Long Ref Code goes out of the left panel

### Steps to reproduce the problem

- Login as Manager
- Select a project from the list { https://connect.topcoder-dev.com/projects/9074 }
- Check the 'Ref Code'

### Screenshot/screencast

![image](https://user-images.githubusercontent.com/42398485/79028016-1c456280-7b54-11ea-8579-d604e72a6efe.png)

#### Environment
**- OS:** HP 15-dw1xxx 15.6 inch; Window 10
**- Browser (w/version):** Firefox 75
**- User role (client, copilot or manager):** Manager
**- Account used:**  `TCConManager`

**Comment by vikasrohit** [comment] 2020-04-13 09:08
Moving to 2.10

**Comment by maxceem** [comment] 2020-04-16 09:11
Sum up:
- I also can reproduce this issue in Internet Explorer 11 on Windows 10:

   ![image](https://user-images.githubusercontent.com/146016/79437537-f9df9900-7fda-11ea-930c-e46f6f566580.png)

- This issue should be fixed for all browsers, in particular for Firefox and IE 11

- additionally to this, we have to fix the tooltip which is shown when hover the REF code:

   ![image](https://user-images.githubusercontent.com/146016/79437717-3f9c6180-7fdb-11ea-8de1-323d55b59a18.png)

   - the tooltip is need so we can see the long REF code, but at the moment tooltip also shows the cut REF code. We should make the text inside the tooltip multiline, so if the REF code is too long, it wraps to the next line. Done make the tooltip width bigger.

**Comment by maxceem** [comment] 2020-04-16 09:12
This issue is open for pickup.

**Comment by sumitdaga** [comment] 2020-04-16 09:14
@bug-bash-helper assign

**Comment by Vips19** [comment] 2020-04-16 09:14
@bug-bash-helper assign

**Comment by Vips19** [comment] 2020-04-16 09:14
@bug-bash-helper assign

**Comment by sumitdaga** [comment] 2020-04-16 09:32
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/3920 is ready for review

**Comment by sumitdaga** [comment] 2020-04-16 09:34
@maxceem  i could see another related issue (not browser specific)   
the tooltip is also not fully visible if its long ...its because a fixed with of 200px is given to the tooltip inner content ...probably it is fine since a ref code will not practically not be any longer than that  

![Selection_424](https://user-images.githubusercontent.com/7769148/79440236-6070b100-7ff3-11ea-8aa0-2d2b76cbb163.jpg)

**Comment by maxceem** [comment] 2020-04-16 09:37
@sumitdaga most likely no. But we want to fix it, so just incase the REF code inside tooltip is longer than that, it should be wrapped to the next line.

As fixing this is a part of this issue, I've changed the status of the issue to `Feedback` as I guess this part is not fixed.

**Comment by sumitdaga** [comment] 2020-04-16 09:44
@maxceem  sure, i have pushed a fix!

**Comment by maxceem** [comment] 2020-04-16 09:47
@sumitdaga just comment again 
```
@ bug-bash-helper #3920 is ready for review
```

**Comment by sumitdaga** [comment] 2020-04-16 09:50
@bug-bash-helper #3920 is ready for review

**Comment by maxceem** [comment] 2020-04-18 14:10
@sumitdaga review is ready https://github.com/appirio-tech/connect-app/pull/3920#pullrequestreview-395917046

**Comment by sumitdaga** [comment] 2020-04-18 17:04
@bug-bash-helper #3920 is ready for review

**Comment by sumitdaga** [comment] 2020-04-18 17:06
@maxceem   
if possible please add some $$s to this issue ...after a lot of trial, i have been able to find a solution that works in all browsers (hopefully) ...IE 11 is especially notorious!

**Comment by maxceem** [comment] 2020-04-19 09:53
@sumitdaga the new review is ready https://github.com/appirio-tech/connect-app/pull/3920#pullrequestreview-395997165

> if possible please add some $$s to this issue ...after a lot of trial, i have been able to find a solution that works in all browsers (hopefully) ...IE 11 is especially notorious!

Sorry, but for this issue, I think I cannot justify the prize increasing. I understand that fixing cross-browser issues might be tricky. Though it was explicitly mentioned in the issue that it has to be fixed in IE11. The intention here is that the one who is familiar with the cross-browser issues would pick up this ticket and the fix would take some reasonable time which is justified by the current prize.

**Comment by sumitdaga** [comment] 2020-04-19 11:11
@bug-bash-helper #3920 is ready for review

**Comment by codejamtc** [comment] 2020-04-20 13:11
IE11
![image](https://user-images.githubusercontent.com/42398485/79755285-8097bd00-82de-11ea-8814-7d178905ee9b.png)

FF
![image](https://user-images.githubusercontent.com/42398485/79755319-8d1c1580-82de-11ea-9c6e-7efc1ec1e54f.png)

**Comment by codejamtc** [comment] 2020-04-29 08:01
FF:

![image](https://user-images.githubusercontent.com/42398485/80573385-799b3980-89c5-11ea-851d-b278e85b4ee8.png)

IE11:

![image](https://user-images.githubusercontent.com/42398485/80573476-a5b6ba80-89c5-11ea-9deb-51e6c5894a9a.png)

**Closed** 2020-04-29 08:04 UTC
Labels: ACCEPTED, CF, Dev Environment, NeedToVerifyByManagerAcc, P4, PAID, QA Pass in Dev, QA Pass in Prod, UI
