### ISSUE TITLE
[Chrome]Cannot delete photo/image on settings profile page

### ISSUE THREAD

**Issue by degraphic** [appirio-tech/connect-app#3632] opened 2020-01-29 17:49 UTC
#### Expected behavior
When we try delete new photo after we uploaded, should have feature to delete new photo

#### Actual behavior
When we try delete new photo after we uploaded, we cant see any feature to delete new photo

#### Steps to reproduce the problem

1. Open the Browser then type https://connect.topcoder-dev.com/	and login with credential
2. Then click "My Profile" on the top
3. Then upload with new photo 
4. Then try to delete the new photo

#### Screenshot/screencast
![Screen Shot 2020-01-30 at 00 42 07](https://user-images.githubusercontent.com/4364214/73382561-5398c700-42fa-11ea-9b2a-0ac29cdcef66.png)

#### Environment

    OS: MacOs Mojave 10.14.6
    Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
    User role (client, copilot or manager): copilot
    Account used: topcoderconnect+Copilot@gmail.com

**Comment by degraphic** [comment] 2020-01-29 17:50
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment] 2020-01-31 06:37
@degraphic , out of scope

**Comment by nithyaasworld** [comment] 2020-02-03 05:32
Not a bug.

**Closed by nithyaasworld** 2020-02-03 05:32 UTC
Labels: BH_OOS, BugHunt_JanRelease, Functional, P2
