### ISSUE TITLE
Arrow is not displayed with the drop down container

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#314] opened 2016-09-29 06:49 UTC
### Expected behavior
-----------------------------------------------------------------
Arrow must displayed with the drop down container

### Actual behavior
-----------------------------------------------------------------
Arrow is not displayed with the drop down container

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click 'Latest first' drop down
- Check the arrow head

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_12-18-39](https://cloud.githubusercontent.com/assets/4592712/18943699/e4bf6ae4-863e-11e6-9e60-01b74da03589.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 12:02
Duplicate of #303.

**Comment by vikasrohit** [comment] 2016-10-05 07:03
@vic-appirio we should remove the extra caret icon, right?

**Comment by vic-appirio** [comment] 2016-10-12 20:55
fixed

**Closed by vic-appirio** 2016-10-12 20:55 UTC
Labels: P1, visual styling
