### ISSUE TITLE
[$35] Update "CoderBot" Message

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2852] opened 2019-02-22 07:18 UTC
The Coderbot message and page that is displayed when the user has registered in Connect but has not created a project is confusing.

<p></p>

Update requests:

1. Remove CoderBot image and designed orange line/message box.

2. Update the message content to read: "Welcome to Topcoder. To get started, click the 'Start a Project' button below."

3. Display a blank project card with a + button that says 'Start Project'

4. Add subtext under the button that reads, "If you have already created a project with us and are not seeing it listed, contact [support@topcoder.com](mailto:support@topcoder.com)"

**Comment by ajefts** [comment] 2019-02-22 07:18
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1792909

**Comment by maxceem** [comment] 2019-02-25 02:04
@ajefts Could you please have a look, if I got the requirements right?

<img width="1385" alt="new-customer-welcome-message" src="https://user-images.githubusercontent.com/146016/53309714-5918b080-38e4-11e9-94cf-6411a54300dc.png">

Note, the whole blank project card is a link as per our current usage, so I put a subtext below the project card. But can change that if necessary.

**Comment by vikasrohit** [comment] 2019-02-25 07:13
Looks nice to me @maxceem. Let me get it confirmed by product as well.

**Comment by vikasrohit** [comment] 2019-02-25 14:34
Got confirmation from product team. You can go ahead with the suggested design for now @maxceem

**Comment by maxceem** [comment] 2019-02-26 02:35
Sum up:
- For testing can use user `maxceem2` - which doesn't have projects.
- Go to page https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc to see the message  which has to be updated:

    ![image](https://user-images.githubusercontent.com/146016/53309341-48673b00-38e2-11e9-87aa-e6e2f0bb6930.png)
- To see a blank project card, user user `pshah_manager`, navigate to the same page http://local.topcoder-dev.com:3000/projects?sort=updatedAt%20desc&status=active and switch to `Card View`

    ![image](https://user-images.githubusercontent.com/146016/53309395-81071480-38e2-11e9-940e-7e4413b453ee.png)
- After that at the end of the list you will see a blank project card:
  
     ![image](https://user-images.githubusercontent.com/146016/53309426-a431c400-38e2-11e9-815c-58727a9b1697.png)

- Header style: `font-size: 28px; line-height: 36px; font-family: Roboto-Medium`
- Subtext style: `font-size: 14px; font-family: Roboto-Regular`
- For colors and font-sizes use variables from https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/_variables.scss
- For font use mixins: https://github.com/appirio-tech/tc-ui/blob/feature/connectv2/src/styles/mixins/_typography.scss
- On mobile devices everything should be kept fuild.

**Comment by sumitdaga** [comment] 2019-02-26 04:13
@maxceem   
Please assign this to me

**Comment by maxceem** [comment] 2019-02-26 04:44
@sumitdaga done

**Comment by sumitdaga** [comment] 2019-02-26 05:47
@maxceem   
https://github.com/appirio-tech/connect-app/tree/dev/src/projects/list/components/Walkthrough  
this is the component that is displayed when there are no projects, should i update this component or create a new component ?

**Comment by maxceem** [comment] 2019-02-26 05:52
@sumitdaga if this component is not being used in other places then, please, update it. Otherwise, create a new one.

**Comment by sumitdaga** [comment] 2019-02-26 06:45
@maxceem   PR at #2860   
can you make its prize $35 ?

**Comment by sumitdaga** [comment] 2019-02-26 06:56
@maxceem   
i found what seems like an issue (although unlikely to happen)  
when you are logged in as one user and start creating a project and then log in as another user it prompts you to `continue where i left off`  
i guess this information is not stored in storage `per user`  
like i said its unlikely that two users will login from the same system ...but still i thought i should point this out to you!

**Comment by maxceem** [comment] 2019-02-26 07:01
> can you make its prize $35 ?

I'll check it out during the review.

@sumitdaga thank you for reporting it. I guess this shouldn't happen in real life. But just in case @RishiRajSahu you may check the report about possible issue in the comment above.

**Comment by RishiRajSahu** [comment] 2019-02-26 07:35
@maxceem yeah I think we are good with that for now as customers won't be logging with different accounts consecutively on the same machine.

**Comment by maxceem** [comment] 2019-02-27 02:00
@sumitdaga I've checked the PR works great. As you had to clean quite many of existent code and had to take care of a proper link for creating a new project we would adjust the prize to $35.

Thank you.

**Comment by RishiRajSahu** [comment] 2019-03-05 09:38
@maxceem the changes looks good but I am still seeing the login button in top right corner, also not able to select project type getting redirected to landing page.

**Comment by maxceem** [comment] 2019-03-05 09:59
> @maxceem the changes looks good but I am still seeing the login button in top right corner even after logging in, also not able to select project type getting redirected to landing page.

@RishiRajSahu everything works good for me.

We didn't change the login button in this issue, and I also can successfully click create a new project link and proceed to the form. Could you please, remove `node_modules` and reinstall dependencies,  just in case. To make sure all the dependencies are correct.

**Comment by RishiRajSahu** [comment] 2019-03-05 10:05
<img width="1405" alt="screen shot 2019-03-05 at 3 07 07 pm" src="https://user-images.githubusercontent.com/11248478/53797466-3ded1700-3f5c-11e9-9a76-effc6505d2ed.png">

@maxceem I am seeing this on dev.

**Comment by maxceem** [comment] 2019-03-05 10:10
@RishiRajSahu do you see it here? http://connect.topcoder-dev.com

Which user do you use?

**Comment by RishiRajSahu** [comment] 2019-03-06 07:01
It seemed to some issue with user for whom there is no role assigned(maybe due to some error during account creation), worked fine after assigning role to the user.  Thanks @maxceem !

**Closed by RishiRajSahu** 2019-03-06 07:01 UTC
Labels: ACCEPTED
