### ISSUE TITLE
Add RUX final design acceptance milestone

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2312] opened 2018-08-07 18:23 UTC
For RUX final design selection we have to allow selection of 8 final designs, so I'll add the design based on the regular 3 winner selection.

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-300

**Comment by vikasrohit** [comment] 2018-08-08 11:08
@vic-topcoder IMO, we should consider this for next release as we might some changes in code to support the dynamic count for final design selection if we do properly, or we have to make redundant component of final designs to support 8 winner selection.

**Comment by vikasrohit** [comment] 2018-08-08 11:09
I have moved it to the 2.4.5 milestone, please feel free to move it back if it is really urgent to get done in this release.

**Comment by vikasrohit** [comment] 2018-08-17 10:29
@vic-topcoder Do we have the designs ready?

**Comment by maxceem** [comment] 2018-08-21 14:25
@vikasrohit will be there some specific designs? Some description of how it suppose to work also ould help if we already have elements for milestone implemented.

**Comment by vikasrohit** [comment] 2018-08-22 05:56
Essentially, we need to update our `final-designs` milestone to support a configurable number of final design selection which is right now hard code to `5`. I think we need to update the milestone templates to support metadata to support this type of configuration because we don't have any field right now to store this configuration per milestone template.

**Comment by maxceem** [comment] 2018-08-22 06:00
Do you think adding some property for such configuration in `details` would work?

So far we have:
```
details: {
   content: {},
   prevMilestoneContent: {},
   prevMilestoneType: '',
}
```

So we can add something like `details.meta` or `details.config`.

**Comment by vikasrohit** [comment] 2018-08-22 06:05
I don't think that would work because for each product we have a list of milestone templates where we have to put that information so that when actual milestones are instantiated from those milestone templates, they have the correct behaviour in place.

**Comment by maxceem** [comment] 2018-08-22 06:11
Yeah, I've missed that `milestoneTemplates` don't have `details` property. So if I get it right, first some new property has to be added to both `milestoneTemplates` and `milestones`.

**Comment by vikasrohit** [comment] 2018-08-23 05:52
@maxceem Can you please start on this now? I know we need the backend support for `metadata` field in milestone templates, however, can you assume that to be there for now in the response and write code accordingly. If there is no metadata or no config in that for number of final designs, assume it to be the default `5`.

**Comment by maxceem** [comment] 2018-08-23 05:58
Ok I'll expect that we have `metadata` property in milestone `details`:
```js
details: {
   content: {},
   prevMilestoneContent: {},
   prevMilestoneType: '',
   metadata: {
      winnerQuantity: 5
   }
}
```

**Comment by vikasrohit** [comment] 2018-08-23 06:33
Makes sense, with minor change `winnerQuantity` => `requiredWinnersCount` or something similary

**Comment by maxceem** [comment] 2018-08-24 00:59
@vikasrohit 
1. Can a customer buy additional designs for $100 in RUX same like in design competitions?
    ![image](https://user-images.githubusercontent.com/146016/44559305-bdaf5300-a77b-11e8-822f-fb03fc2c79e8.png)

2. Should we show all 8 places if there is less than 8 submissions? Or if there only 5 submissions we show only 5 places?
    ![image](https://user-images.githubusercontent.com/146016/44559324-e5062000-a77b-11e8-83df-16e69f94175b.png)

**Comment by vikasrohit** [comment] 2018-08-24 05:46
1. Yes, I am thinking of keeping the purchase cost to be configurable just like we are configuring number of winners so that we can have different cost per design for RUX.

2. I think we should show only those much places as we have the number of submissions.

**Comment by maxceem** [comment] 2018-08-24 05:54
Ok, so I'm adding `additionalDesignCost` to `metadata`.

**Comment by vikasrohit** [comment] 2018-08-24 06:01
👍

**Comment by maxceem** [comment] 2018-08-24 08:33
Done. 

Editing demo: https://monosnap.com/file/MEEYlajCMXqMhXEStuIKamkzGOglgL
View demo: https://monosnap.com/file/682ExMgSSrickK19e70lzjwNhDVaCk

**Comment by vikasrohit** [comment] 2018-08-24 08:50
Great @maxceem . One minor suggestion, can we try left or center aligning the rank placeholders (in mobile view when they are wrapped in the next row)? I think left align would look better for devices having non standard resolutions.

fyi @vic-topcoder @acshields please check the demo videos shared by @maxceem and let us know your feedback.

**Comment by maxceem** [comment] 2018-08-24 09:58
Aligned left

![image](https://user-images.githubusercontent.com/146016/44578850-3982bd00-a7c7-11e8-8165-24ff1238fa6b.png)

**Comment by vikasrohit** [comment] 2018-08-29 10:53
Moved to 2.4.6 as backend changes are not yet merged into dev because of other changes are also going with the change.

**Comment by maxceem** [comment] 2018-09-11 07:52
I've just tested this. The issue is now fully resolved as project service was already updated to provided metadata, necessary for RUX designs. I've also fixed a small decoration issue and committed directly to dev.

Fyi @RishiRajSahu

**Comment by RishiRajSahu** [comment] 2018-09-11 08:28
Thanks for the update @maxceem

**Closed by RishiRajSahu** 2018-09-11 08:28 UTC
Labels: Aha!:In development, Ready for Review
