### ISSUE TITLE
[$50] Type Error 'Cannot read property 'version' of null'

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2791] opened 2019-01-28 12:36 UTC
Observing following error in console for few projects:

`TypeError: Cannot read property 'version' of null
  at ? (/main.cff9bc43004fa36c3860.js:134:91314)
  at s(/main.cff9bc43004fa36c3860.js:21:54731)
  at r.render(/main.cff9bc43004fa36c3860.js:67:36796)
  at d._renderValidatedComponentWithoutOwnerOrContext(/main.cff9bc43004fa36c3860.js:67:43229)
  at d._renderValidatedComponent(/main.cff9bc43004fa36c3860.js:67:43441)
  at d._updateRenderedComponent(/main.cff9bc43004fa36c3860.js:67:42660)
  at d._performComponentUpdate(/main.cff9bc43004fa36c3860.js:67:42461)
  at d.updateComponent(/main.cff9bc43004fa36c3860.js:67:41739)
  at d.receiveComponent(/main.cff9bc43004fa36c3860.js:67:40856)
  at Object.receiveComponent(/main.cff9bc43004fa36c3860.js:21:137806)
  at d._updateRenderedComponent(/main.cff9bc43004fa36c3860.js:67:42704)
  at d._performComponentUpdate(/main.cff9bc43004fa36c3860.js:67:42461)
  at d.updateComponent(/main.cff9bc43004fa36c3860.js:67:41739)
  at d.receiveComponent(/main.cff9bc43004fa36c3860.js:67:40856)
  at Object.receiveComponent(/main.cff9bc43004fa36c3860.js:21:137806)
  at d._updateRenderedComponent(/main.cff9bc43004fa36c3860.js:67:42704)
  at d._performComponentUpdate(/main.cff9bc43004fa36c3860.js:67:42461)
  at d.updateComponent(/main.cff9bc43004fa36c3860.js:67:41739)
  at d.performUpdateIfNecessary(/main.cff9bc43004fa36c3860.js:67:41072)
  at Object.performUpdateIfNecessary(/main.cff9bc43004fa36c3860.js:21:137988)
  at s(/main.cff9bc43004fa36c3860.js:21:24049)
  at r.perform(/main.cff9bc43004fa36c3860.js:21:199894)
  at o.perform(/main.cff9bc43004fa36c3860.js:21:199894)
  at o.perform(/main.cff9bc43004fa36c3860.js:21:25208)
  at Object.P [as flushBatchedUpdates](/main.cff9bc43004fa36c3860.js:21:25377)
  at r.closeAll(/main.cff9bc43004fa36c3860.js:21:200482)
  at r.perform(/main.cff9bc43004fa36c3860.js:21:199977)
  at Object.batchedUpdates(/main.cff9bc43004fa36c3860.js:67:49583)
  at Object.l [as enqueueUpdate](/main.cff9bc43004fa36c3860.js:21:24262)
  at r(/main.cff9bc43004fa36c3860.js:40:4763)
  at Object.enqueueSetState(/main.cff9bc43004fa36c3860.js:40:5895)
  at s.r.setState(/main.cff9bc43004fa36c3860.js:40:136947)
  at s.handleChange(/main.cff9bc43004fa36c3860.js:67:78833)
  at u(/main.cff9bc43004fa36c3860.js:40:167171)
  at u(/main.cff9bc43004fa36c3860.js:21:215253)
  at ? (/main.cff9bc43004fa36c3860.js:21:214092)
  at ? (/main.cff9bc43004fa36c3860.js:72:54531)
  at ? (/main.cff9bc43004fa36c3860.js:67:119675)
  at ? (/main.cff9bc43004fa36c3860.js:72:49213)
  at dispatch(/main.cff9bc43004fa36c3860.js:67:84933)
  at ? (/main.cff9bc43004fa36c3860.js:21:177046)
  at ? (/main.cff9bc43004fa36c3860.js:67:119666)
  at ? (/main.cff9bc43004fa36c3860.js:72:49213)
  at Object.getNotifications(/main.cff9bc43004fa36c3860.js:67:84251)
  at ? (/main.cff9bc43004fa36c3860.js:46:362848)
  at d(/3.17.0/raven.min.js:2:6417)`

Exact line where error is raised
`
{snip} &&e.error.type===k.LOAD_PROJECT_FAILURE||("v3"!==e.project.version||e.projectTemplate)&&e.productTemplates.length>0)}),U=function(e){var t=e {snip}`

https://sentry.io/topcoder/connect-app/issues/860833969/

**Comment by maxceem** [comment] 2019-02-25 04:38
@vikasrohit This issue looks like have the same root as https://github.com/appirio-tech/connect-app/issues/2828 because I think the error happens at the same place.

As we don't have certain steps to reproduce the error in this issue, I guess we can fix another one and check if this issue still happens in some other conditions.

**Comment by vikasrohit** [comment] 2019-03-12 09:43
@maxceem it seems the error is at this [line](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/ProjectDetail.jsx#L57)  and it is raised when `project` is null in props which can be there when there was an error in loading the project via api.

**Comment by maxceem** [comment] 2019-03-15 01:59
@vikasrohit we can try to play with it and simulate an error in project loading trying to reproduce it. By [code](https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/ProjectDetail.jsx#L55), if an error happens during project loading, that line should not be called.

**Comment by maxceem** [comment] 2019-03-29 11:22
@vikasrohit This issue might have been fixed by this PR https://github.com/appirio-tech/connect-app/pull/2871. Are there any new instances of this error after the previous release `2.4.10`?

**Comment by vikasrohit** [comment] 2019-04-01 07:38
@maxceem Yes, we have seen the issue in sentry after `2.4.10` release. However, it has been 14 days now since last occurrence of this issue. If it does not seems to workable for now, please exclude it from the CF, we can take it back in later.

**Comment by maxceem** [comment] 2019-04-01 07:55
Ok, I'm excluding this for now. As by logic this error should never happen. And if it still happens it would be good to understand the root of the issue and fix it rather than gracefully handle the error.

**Comment by vikasrohit** [comment] 2019-04-02 06:29
@maxceem It just appeared again. 

```
{snip} &&e.error.type===P.LOAD_PROJECT_FAILURE||("v3"!==e.project.version||e.projectTemplate)&&e.productTemplates.length>0)})(L(function(e){var t=e {snip}
```

**Comment by maxceem** [comment] 2019-04-02 06:30
@vikasrohit ok, thanks! Will add it to the CF.

**Comment by maxceem** [comment] 2019-04-02 06:38
Sum up: 
- Looks like line of the error is here https://github.com/appirio-tech/connect-app/blob/cf16/src/projects/detail/ProjectDetail.jsx#L57
For this issue it would the best to do two things:
- find out the possible root of this issue and add it as a comment to the issue for future references
- instead of hiding the error at the line where this error has been logged, fix the issue as close to the root as possible

**Comment by simranb86** [comment] 2019-04-11 08:43
hey @maxceem can you assign this to me?

**Comment by maxceem** [comment] 2019-04-11 08:48
done

**Comment by maxceem** [comment] 2019-04-12 07:24
As no PR has been risen for 12 hours and no update provided, this issue is now open for pick up.

**Comment by trushita23** [comment] 2019-04-12 07:32
Hi, can I work on this

**Comment by maxceem** [comment] 2019-04-12 07:34
@trushita23 it's on you since you commented as per our Bug Bash rules. To keep it clear I can assign you to this issue in the UI. For this, please accept the invitation to this repository which you should get to your email.

**Comment by trushita23** [comment] 2019-04-12 21:03
Could you please unassign me. Couldn’t find the root cause.

**Comment by Gauravseta** [comment] 2019-04-12 21:47
@maxceem please assign this to me

**Comment by maxceem** [comment] 2019-04-13 01:28
done

**Comment by Gauravseta** [comment] 2019-04-14 00:00
@maxceem MR raised https://github.com/appirio-tech/connect-app/pull/2954

**Closed** 2019-04-22 10:22 UTC
Labels: ACCEPTED, CF-16, P3, PAID, Sentry
