### ISSUE TITLE
Enable Tagging of Files and Links

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3462] opened 2019-12-24 05:42 UTC
**Objective:** When a user is sharing a file or link, provide them with the option to create a tab for the file or link. For projects with many files and links shared, this will aide in quick retrieval of the necessary document. Additionally, this could be a method for users to track versions of the same document.

<p></p>

**Requirement:**

- When a user is sharing a file or link, they should see an optional free text field labeled Tag

  - For Files, this optional tagging question should appear after the file has been uploaded but before the user indicates who they want to share the file with. The screen should state: 'Create a Tag (Optional)' with a free text field underneath for tag creation. This field should be responsive and return any tags that match 

- Tag should be included as a column in the Assets Library display of shared files. This column should be filterable by text input to filter to the required tag.

- Once a file or link has been shared, user should be able to create or designate a tag in the column in the Assets Library for the file.

<p></p>

<p></p>

**Comment by ajefts** [comment] 2019-12-24 05:42
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2753491

**Comment by maxceem** [comment] 2019-12-24 07:55
It feels for me that users would not always add tags. So if we add an additional window for enterim them, file uploading workflow would become longer, and all the users have to pass through the optional step of adding tags, whether they want to add them or no.

Maybe we can add a filed for adding tags to the same window where add permissions? Just slightly reformat this window and title it something like `Attachment properties` or `Attachment options`.

![image](https://user-images.githubusercontent.com/146016/71401692-90bbca80-2665-11ea-810f-af59cbbfc16f.png)

**Comment by vikasrohit** [comment] 2019-12-30 12:05
Good idea @maxceem. I will confirm it with product managers. However, just for reference, we have a upcoming feature where product manager want to merge the two dialogs for files and links into one dialog i.e. we would show a common dialog always, which would ask if user want to create a file or link. So, if that goes through, though I am still debating against it, we might have a new intermediate screen any way where we can show the tags editor field.

**Comment by vikasrohit** [comment] 2020-02-26 09:31
@maxceem moving to next release as we want to release #3512 along with this feature. Let me know how we should handle the branching in this case. If we have to merge or already merged the PR for this changes, we can disable the tagging feature from UI.

**Comment by codejamtc** [comment] 2020-03-30 14:11
https://www.screencast.com/t/SH0rLUqjcTHq

**Comment by maxceem** [comment] 2020-03-30 15:17
> {Tag is integrated with the existing popup as mentioned here #3462 (comment). But I can see the text label is not stating it as optional like 'Create a Tag (Optional)'}

This is now fixed. `(optional)` is added during file or link creation and edition.

> {Can't see a separate column for tags}

I cannot find a place where it was confirmed by Vikas, but this was changed to reuse the **Name** column because we don't have enough space to add a new column.

> Once a file or link has been shared, user should be able to create or designate a tag in the column in the Assets Library for the file.

We can add tags using `edit` functionality for files and links.

cc @codejamtc

**Comment by codejamtc** [comment] 2020-03-30 15:43
![image](https://user-images.githubusercontent.com/42398485/77932577-591b7a80-7273-11ea-9a7e-0dc831d87294.png)

**Comment by coderhacker** [comment] 2020-04-01 14:09
Verified on dev working as expected.

**Comment by coderhacker** [comment] 2020-04-02 09:50
https://connect.topcoder.com/projects/14177/assets
CustomerUser/appirio123
Verified on prod, working as expected.

[3462-prod.zip](https://github.com/appirio-tech/connect-app/files/4420186/3462-prod.zip)

**Closed** 2020-04-03 10:07 UTC
Labels: Attachment Improvements, P2, QA Pass in Dev, QA Pass in Prod
