### ISSUE TITLE
Cancel button will delete the 'Custom Features' entry

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#341] opened 2016-09-29 11:25 UTC
### Expected behavior
-----------------------------------------------------------------
Cancel button must not delete the 'Custom Features' entry; because it have a seperate DELETE button to do this
- Also if the user accidentally goes into the EDIT mode he/she needs to cancel the operation by clicking the cancel button

### Actual behavior
-----------------------------------------------------------------
Cancel button will delete the 'Custom Features' entry

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Scroll down and click on the Add/Edit Features
- Scroll the Left side panel options down
- Click 'Add a custom features' button
- Enter any Name to 'Feature Name'
- Click Save Feature
- Add 2-3 Custom Features
- Select a Custom Feature
- Now OFF the slider; It will go to EDIT mode 
- Click CANCEL
- Check the list

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_16-54-03](https://cloud.githubusercontent.com/assets/4592712/18951947/5dff3936-8665-11e6-95e1-5d6e76606b14.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 12:52
Valid.

**Comment by fnisen** [comment] 2016-10-05 00:54
@vikasrohit I think you're fixing this as part of https://github.com/appirio-tech/connect-app/issues/125

**Comment by fnisen** [comment] 2016-10-05 00:55
@mahestro this is similar to https://github.com/appirio-tech/connect-app/issues/343

**Comment by vikasrohit** [comment] 2016-10-06 09:59
Last step in steps to reproduce is not needed because custom feature is not deleted because of cancel button. It got deleted as soon as feature is disabled. It is fixed with #265

**Closed by vikasrohit** 2016-10-06 09:59 UTC
Labels: duplicate
