### ISSUE TITLE
[$40] Hide Change password/email functionality for Social Logged in user

### ISSUE THREAD

**Issue by sachin-maheshwari** [appirio-tech/connect-app#4249] opened 2021-01-07 06:12 UTC
Please find detail here - https://github.com/topcoder-platform/tc-auth-lib/issues/29

**Comment by maxceem** [comment] 2021-03-01 11:21
Sum up:
- we can handle it the same way as it's done in Community App on the page https://www.topcoder-dev.com/settings/account

   ![image](https://user-images.githubusercontent.com/146016/109490024-52ebda80-7a90-11eb-9af4-01b4ced24cf5.png)
   
- if a user is logged-in using SSO Service, then 
   - disable email field so we cannot change it
   - show red warning message similar to Community App
   - hide section for changing the password

   ![image](https://user-images.githubusercontent.com/146016/109490188-8fb7d180-7a90-11eb-9e3f-12509d39abbb.png)
   
- on how to detect SSO login see community app source code https://github.com/topcoder-platform/community-app
- you can create a new DEV account for testing using this link https://accounts-auth0.topcoder-dev.com/?retUrl=https://www.topcoder-dev.com/start&mode=signUp (NOTE: you have to sign up using Google or GitHub)

**Comment by maxceem** [comment] 2021-03-01 13:15
Challenge https://www.topcoder.com/challenges/27d1ab70-77c7-4ff5-bfdd-6cbcc7007f5c has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by yoution** [comment] 2021-03-01 13:30
@bug-bash-helper assign me

**Comment by maxceem** [comment] 2021-03-01 13:30
Challenge https://www.topcoder.com/challenges/27d1ab70-77c7-4ff5-bfdd-6cbcc7007f5c has been assigned to yoution.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by yoution** [comment] 2021-03-01 15:38
@bug-bash-helper    https://github.com/appirio-tech/connect-app/pull/4322 is ready for review

**Comment by drasticdpk** [comment] 2021-03-05 03:26
**Verified with Github login**
![image](https://user-images.githubusercontent.com/25297859/110063173-baf13800-7d92-11eb-87ff-afff7f569a60.png)

**Comment by maxceem** [comment] 2021-03-09 11:38
@drasticdpk thanks for the report. I cannot reproduce it myself. Could you please check one server request?

In the dev tools there should one request which ends `?fields=credentials` and in response there should be value `hasPasssowrd`, what value do you have there?

![image](https://user-images.githubusercontent.com/146016/110465039-98d21f80-80dc-11eb-8c71-fbc1ad7763ba.png)

**Comment by drasticdpk** [comment] 2021-03-10 08:50
@maxceem , 
here is the requested data. 
![image](https://user-images.githubusercontent.com/25297859/110601751-63e1cd80-81ad-11eb-99d4-295767565425.png)

**Scenario**,
Let's say I have registered new account my gmail  - email1@gmail.com. (without social login) 
After that re-register with email1@gmail.com with social login. 
Let me know if you want this scenario with video.

**Comment by maxceem** [comment] 2021-03-10 08:52
> Let me know if you want this scenario with video.

@drasticdpk if you could make a video that would help a lot. As I'm not 100% sure how this happened.

**Comment by maxceem** [comment] 2021-03-10 09:02
Anyway, this looks like the issue with Topcoder API, not with Connect App. Because Connect App check if `hasPassword === true` it means user login with password, not with a social login. The same way it's done in Community App here https://www.topcoder-dev.com/settings/account.

@drasticdpk I would suggest logging a separate issue for this somewhere. While testing this ticket with a regular user created with social login initially, not with a password.

On the second thought, I wonder if this is an issue at all? If the user initially created an account with a password their account has a password so the user can change it.

@vikasrohit do you know someone who could clarify for us this moment?

**Comment by drasticdpk** [comment] 2021-03-10 11:44
Ok based on above discussion we can make this issue passed and we can create new issue for above scenario. 
please suggest. cc @maxceem @vikasrohit @coderhacker

**Comment by maxceem** [comment] 2021-03-10 12:01
I agree @drasticdpk. The above scenario looks like an edge case in the general Topcoder API logic, or maybe even it's not an issue if we should allow changing a password in such case.
So I opt for moving this discussion to a separate issue. If you could provide detailed steps or video that would also help, as I'm not entirely sure how to reproduce it.

**Comment by maxceem** [comment] 2021-03-10 12:32
Payment failed: [400]: Failed to activate challenge. Detail: Cannot Activate this project, it has no active billing accounts.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by drasticdpk** [comment] 2021-03-11 06:57
Prod verified.
![image](https://user-images.githubusercontent.com/25297859/110747996-3fe2c280-8267-11eb-8bdc-a4244ae5eb3e.png)

**Closed by drasticdpk** 2021-03-11 06:57 UTC
Labels: ACCEPTED, CF, Have A Question, QA Fail in Dev, Release Due Date: 3/12, tcx_Assigned, tcx_FixAccepted
