### ISSUE TITLE
[$40] Attachments uploaded in phase specification tab are not immediately reflected in the left panel

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#2213] opened 2018-07-19 12:14 UTC
### Expected behavior
The left panel's Files section should render the link to the newly uploaded file immediately.

### Actual behavior
It does not reflect the link of the file immediately, rather it requires a full page refresh to see the changes.

### Steps to reproduce the problem
- Upload file in phase's specification tab.
- Observe the Files section in the left panel, it does not gets the link of the uploaded file.
- Now refresh the page and the link of the file would be visible in the left panel.

--

#### Environment
- OS: Any
- Browser (w/version): Any
- User role (client, copilot or manager): Any
- Account used:  N/A

**Comment by vikasrohit** [comment] 2018-07-19 12:14
fyi @rmjmccormick @RishiRajSahu

**Comment by vikasrohit** [comment] 2018-07-19 12:21
@gondzo could this be included in CF 10?

**Comment by enodi** [comment] 2018-07-19 12:32
I am working on this.

**Comment by enodi** [comment] 2018-07-20 12:10
@gondzo and @vikasrohit I am unable to reproduce this error, the link is displayed without reloading this page. Please check again.

**Comment by gondzo** [comment] 2018-07-23 16:43
this is now open for pickup

**Comment by PrakashDurlabhji** [comment] 2018-07-26 18:59
@gondzo it is working now.checked many times.it is working as expected. Checked in project plan tab in phase's specification.i shud have taken some other issue as no open for pickup left and it is already working hence lost prize.

**Comment by gondzo** [comment] 2018-07-27 10:17
ok, looks like it is indeed working.
I'll split the prize for @PrakashDurlabhji and @enodi that hekped debugging this one.

**Closed** 2018-07-27 12:11 UTC
Labels: Aha!:In development

**Comment by PrakashDurlabhji** [comment] 2018-07-27 12:15
@gondzo thanks
