### ISSUE TITLE
User is able to apply filter at  File Edit Mode

### ISSUE THREAD

**Issue by drasticdpk** [appirio-tech/connect-app#3730] opened 2020-02-27 14:26 UTC
### Expected behavior
1. Cursor should Focus on Search box so user can type text. -> https://github.com/appirio-tech/connect-app/issues/3749
2. User should not  able to apply filter in File Edit Mode -> https://github.com/appirio-tech/connect-app/issues/3750
3. User should not able to input from date which is greater that To date .  
4.  The filter box should not hide the filtered value.
5. Created by filed should be have handle instead of Name.

### Actual behavior
1. Search Box : Cursor Focus Missing on Search box. 
2. Filter in Edit Mode : User is able to apply filter even in File Edit Mode
3. Date Picker : End Date less than Start date  - In such case the date should be disable. 
4. Filter box UI : The filter box is hiding the filtered value
5. Created By  : Should be handle instead of Name

### Steps to reproduce the problem
-- Log in to application  https://connect.topcoder-dev.com/ with manager Role
--  Select the project "ABC"
-- Select Assets Library and Go to All File tabs.
-- Select Grid header( Name and Share with column) to type filter text
-- Click edit icon (---) to  edit the file item and try to to filter grid.
-- Try to filter with date and observe the result.

### Screenshot/screencast
Attach or link a resource.
1. 
![image](https://user-images.githubusercontent.com/25297859/75452068-afa64800-5999-11ea-87d6-725a02e9abcc.png)
2. 
![image](https://user-images.githubusercontent.com/25297859/75452372-4a068b80-599a-11ea-9ada-a219c250411c.png)
3.
 ![image](https://user-images.githubusercontent.com/25297859/75452729-e03ab180-599a-11ea-871d-2bcc4d51d4e5.png)
4. 
![image](https://user-images.githubusercontent.com/25297859/75453495-16c4fc00-599c-11ea-90a0-c374980c8536.png)

#### Environment
- OS: macOS
- Browser (w/version): Google Chrome/80
- User role (client, copilot or manager):manager
- Account used: topcoderconnect+manager@gmail.com

**Comment by vikasrohit** [comment] 2020-03-03 10:02
@maxceem CF candidate

**Comment by maxceem** [comment] 2020-03-09 04:18
For issues 1 and 2 I've created separate tickets:
- Cursor should Focus on Search box so user can type text. -> https://github.com/appirio-tech/connect-app/issues/3749
- User should not able to apply filter in File Edit Mode -> https://github.com/appirio-tech/connect-app/issues/3750

@vikasrohit regarding the rest of the issue I have some questions.

> 3. User should not able to input from date which is greater that To date .

So far we are using the standard browser date field. If we want to implement such a feature, we have to introduce a custom date field. In such case it would make sense to replace date field with a custom field in all the places across the Connect App for consistency.

> 4. The filter box should not hide the filtered value.

Not sure how to fix this one as by design out filters cover the first row when opened. And we are going to add the second line to the "title" filter for filtering tags, so it would cover even more space below.

> 5. Created by filed should be have handle instead of Name.

In most places we are showing user full name:
![image](https://user-images.githubusercontent.com/146016/76182498-09abd680-6200-11ea-9138-7ca931d0fee8.png)

I guess it would be better to follow some consistent format, either show full name or handle everywhere across the Connect App.

**Comment by vikasrohit** [comment] 2020-03-09 06:37
3. What do you think in terms of efforts for the common date component? I think even after custom component, we would still be using the HTML date picker, only difference would be that we would be applying some validations on the top of it, right?

4. I don't think we can have a good solution for this and at the same time the issue does not seem to be troubling the use cases as user can hide the filter to see what is underneath and then show it again, if he/she want to continue filtering. Lets leave it.

5. Yes, I don't think that this is a bug or deviation from the requirements. Requirements of the original issue (#3464) requires handle in `Shared With` column where we have updated requirements to show the Avatar instead. So, we should not be doing anything for this as well.

**Comment by maxceem** [comment] 2020-03-09 07:07
> 3. What do you think in terms of efforts for the common date component? I think even after custom component, we would still be using the HTML date picker, only difference would be that we would be applying some validations on the top of it, right?

Looks like we have a "date" input only in 2 places:
- Phase edit form

   ![image](https://user-images.githubusercontent.com/146016/76190062-1a1b7b80-6217-11ea-86fd-9a0bb57f31e2.png)

- Assets filtering

   ![image](https://user-images.githubusercontent.com/146016/76190090-28699780-6217-11ea-92b0-5bd0c44d654f.png)

So the task shouldn't be hard: basically we have to find some custom date picker which would support a feature to "disable" dates before or after some date.
Or, we may use a plugin which would support selecting date ranges for the assets filtering, so it would enforce that "from" date is always before "to" date. For example, the one we use in community app:

![image](https://user-images.githubusercontent.com/146016/76190241-826a5d00-6217-11ea-9594-b2fb6eb0744a.png)

**Comment by vikasrohit** [comment] 2020-03-09 08:08
I am good with the plugin community app is using. However, I am also okay if we don't use any plugin and just rely on basic HTML min/max attributes with small script for dynamically setting these attributes in our wrapper date component.
Crux is that, we don't need to be too fancy for this and all we need is some basic validation on dates. Community app option is looking good to me.

**Comment by maxceem** [comment] 2020-03-10 04:41
For the first 3 issues, separate tickets have been created:
- Cursor should Focus on Search box so user can type text. -> https://github.com/appirio-tech/connect-app/issues/3749
- User should not able to apply filter in File Edit Mode -> https://github.com/appirio-tech/connect-app/issues/3750
- User should not able to input from date which is greater that To date . -> https://github.com/appirio-tech/connect-app/issues/3752

Issues 4 and 5 shouldn't be fixed as per https://github.com/appirio-tech/connect-app/issues/3730#issuecomment-596354358

I'm closing this issue as everything would be handled by separate issues.

**Closed by maxceem** 2020-03-10 04:41 UTC
