### ISSUE TITLE
P2: Assets Library Column Filtering

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3464] opened 2019-12-24 06:00 UTC
**Objective:** In an effort to make it easier for users to quickly locate a file or link that was shared in the Assets Library, the following columns should be filterable to quickly return results.

<p></p>

**Requirements:**

- Name column should be filterable by keyword entry

- 'Date' column should be filterable by date

- 'Shared By' column should be filterable by user handle (this is covered in the 'Shared By' feature

- ~~Tag column should be filterable by tag (this is covered in the 'Tag' feature)~~

- When a user uses one of these filters, the results returned should also include files or links embedded inside folders.

**UPDATE:** We are deferring the tag feature for next release.

**Comment by ajefts** [comment] 2019-12-24 06:00
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2753835

**Comment by maxceem** [comment] 2019-12-24 07:42
As we always have all the files and links loaded at Assets Library, I guess it would be best to implement such filtering client-side. Also, client-side filtering would work very fast. What do you think?

**Comment by vikasrohit** [comment] 2019-12-30 12:01
I guess in future, we might have paging implemented in assets as well when the number of files and links increases to a project. So, it would be better to have it server side. But lets keep client side open as well until we finalize the new attachment service because without the new common attachment service, it is not possible to have server side filtering which in turn means we have to implement client side filtering if we don't go with common attachment service.

**Comment by maxceem** [comment] 2020-01-15 08:52
1. We don't have a design for the filters, though I guess we can use the same UI as we have for project filtering:

    ![image](https://user-images.githubusercontent.com/146016/72418271-7b921180-37b5-11ea-9ea5-ae2f63c1677a.png)

2. For the date filter, we can use the same widget which is used in Community App:

    ![image](https://user-images.githubusercontent.com/146016/72418415-c1e77080-37b5-11ea-9ed4-eeb3cf3c382c.png)

     - the only thing we should show two fields one by one vertically, instead of horizontally, as we don't have much space
    - we should show some `clear` button for the date filter, as we don't have any way to clear this filter otherwise

3. I guess we should add some button to clear all the filters at once:
 
     ![image](https://user-images.githubusercontent.com/146016/72419184-41c20a80-37b7-11ea-8537-db7d4613c3d1.png)

**Comment by vikasrohit** [comment] 2020-01-16 06:49
1. Agreed.
2. Can we use our date picker which we are already using in phase edit form?
    - I am okay with vertical alignment of the start and end date selectors
    - If it is easy to include a `clear` button specific date filter, go with that, otherwise I think we can live with the global clear filter as you suggested in next point.
3. I guess, we can just replace the `All Link` header with something which says that current view is filtered and user needs to clear the filters to view all links.
<img width="758" alt="Screen Shot 2020-01-16 at 12 12 01 PM" src="https://user-images.githubusercontent.com/2417632/72500391-5c00f480-385a-11ea-9d48-af9ae6fc0f0d.png">
We can make the `clear` text as hyperlink to clear the filters.

**Comment by maxceem** [comment] 2020-01-16 10:33
> 2. Can we use our date picker which we are already using in phase edit form?

Yes, we can. Though I've just noticed that we are using a native browser feidl `input[type="date"]` which is generally good. Though in IE 11 there is no UI for entering a date https://monosnap.com/file/n6D9TRO14Q9qMODc8tGsMPT58yTT5C which all modern browsers have. We can still continue using the native date field and think about solving the issue in IE 11 separately.

>  3. I guess, we can just replace the All Link header with something which says that current view is filtered and user needs to clear the filters to view all links.

Great idea, what about showing all the current filters and `Clear` button with `cross` icon at the end:

![image](https://user-images.githubusercontent.com/146016/72517253-03e3e580-388e-11ea-80e4-d31dc7e5766f.png)

Or if it looks too dirty, we can do as you've suggested, something like this, where "Clear filter" is some link/button to clear filter.

![image](https://user-images.githubusercontent.com/146016/72517537-8a002c00-388e-11ea-9a1b-7f423c9f69dd.png)

**Comment by maxceem** [comment] 2020-01-16 10:35
4. In the spec there is the next requirement:

    > When a user uses one of these filters, the results returned should also include files or links embedded inside folders.

    When we filter, should we show all the files/links in a flat list without folders? Or should we keep folders which has files/links that match request and users should enter to the folders to see the files/links that match filter inside that folder?

**Comment by maxceem** [comment] 2020-01-16 11:35
@vikasrohit I don't see a good existent style for "link" style for clear button. Should we use button like this?

<img width="811" alt="clear-file-filters" src="https://user-images.githubusercontent.com/146016/72521836-3514e380-3897-11ea-9bf3-fdfd64dfc0df.png">

- this button would be only shown when there are some filters

**Comment by vikasrohit** [comment] 2020-01-16 11:56
I am good with browser's native date field. We don't need to worry about IE11 for now. I just want to reuse whatever we are using in phase edit form.

> When we filter, should we show all the files/links in a flat list without folders? Or should we keep folders which has files/links that match request and users should enter to the folders to see the files/links that match filter inside that folder?

which one is easier for us in terms of technical complexity? I guess having the folders would be less complex and straightforward, right?

> this button would be only shown when there are some filters

I liked the button style. However, I would like to change the text of the header too from `All Files` to `Files` or `Filtered Files`.

**Comment by vikasrohit** [comment] 2020-01-16 12:20
yes, leave it to participants. We can get the feedback from users after release.

**Comment by nithyaasworld** [comment] 2020-01-27 06:25
@maxceem @vikasrohit Shared with column filters are not fetching the right results if the result entity has 'All Project members'. Should we have to handle this? 

![image](https://user-images.githubusercontent.com/5114190/73154006-dc95df80-40fb-11ea-8c77-e634cd48b365.png)

**Comment by maxceem** [comment] 2020-01-27 06:46
@nithyaasworld good catch.

So far we only search be the members who are directly listed, like for the first row with "zip" archive. And for the "All Project Members" we are searching by the text "All Project Members" but not by actual members names who are represented by this "All Project Members" text. So entering into search field text "All" would show the records with "All Project Members" text.

@vikasrohit as I understand we should implement searching by user names in such cases also, as it looks like it is what expected. Should we?

**Comment by vikasrohit** [comment] 2020-01-27 09:52
@maxceem yep, from my understanding it seems a valid behaviour. How difficult is to implement that? If it is not much tricky, we can go for this in this release, otherwise, I guess we can live with it till next release.

**Comment by vikasrohit** [comment] 2020-01-27 09:52
And I can ask product managers as well about this.

**Comment by vikasrohit** [comment] 2020-01-27 09:56
One more thing, came to my mind, if we go with implementing the expected behaviour, we need to make sure that we don't return all the attachments shared with all project members, even if user enters any arbitrary handle/text i.e. they should be returned only if the handle is member of the project.

**Comment by maxceem** [comment] 2020-01-27 09:59
> @maxceem yep, from my understanding it seems a valid behaviour. How difficult is to implement that?

I guess it shouldn't be tricky. I may ask to make it as a private task. If it's ready fast, we can include it to the release, otherwise, keep for the next one.

Would you like to still keep ability of searching by text like `All Project Members` and `Only Topcoder Members`? Or only by actual user names and handles?

![image](https://user-images.githubusercontent.com/146016/73165345-99a12f80-412e-11ea-9135-08d4f6ff44a1.png)

**Comment by vikasrohit** [comment] 2020-01-27 10:01
Makes sense. Lets keep the searching behaviour for `All Project Members` and `Only Topcoder  Members` as is, if it is not difficult to keep it.

**Comment by nithyaasworld** [comment] 2020-01-28 21:15
@maxceem Removed the 'Ready for QA' label. Please add it back once the 'Shared with' filter is enhanced. Or if we are going to release this after 2.5.1, please let me know, I will create a new issue just to address the 'Shared with' filter enhancement.

**Comment by maxceem** [comment] 2020-01-29 04:04
@nithyaasworld let's keep this enhancement for the next release, as I see there some other issues which also require assistance and look more urgent for this release. Also, don't want to implement this enhancement in a hurry, as the release is already tomorrow.

**Comment by vikasrohit** [comment] 2020-01-29 05:45
Agreed with @maxceem and I have also got confirmation from product managers as well. We are good with current behaviour i.e. no logical filtering of shared with column and it would be doing literal filtering.

@nithyaasworld it would be great if you can create a separate issue for that enhancement.

**Comment by lakshmiathreya** [comment] 2020-02-28 01:46
@drasticdpk pls update Prod status on this.

**Comment by vikasrohit** [comment] 2020-02-28 10:14
@drasticdpk I think from your concerns raised in #3731, all original requirements are fulfilled but we do have some common bugs and enhancements. So, I think we can close this issue and address the bugs/enhancements separately in upcoming releases as per priority.

**Comment by drasticdpk** [comment] 2020-02-28 15:12
I verified this issue is exist on prod env too where some issue are enhancements type. As suggested by @vikasrohit  we can do it in upcoming release.

**Closed by drasticdpk** 2020-02-28 15:12 UTC
Labels: 2.5.1, P2, QA Pass in Dev
