### ISSUE TITLE
List of steps during project creation looks visually broken

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2622] opened 2018-10-12 01:43 UTC
When we open project creation wizard https://connect.topcoder-dev.com/new-project, the list of step on the left sidebar looks visually broken.

![image](https://user-images.githubusercontent.com/146016/46842938-135ebe00-ce03-11e8-8337-a4ff0873df11.png)

@RishiRajSahu I guess we can include it to CF-13.

**Comment by vikasrohit** [comment] 2018-10-12 06:02
Yes, we should. It seems it is a regression.

**Comment by maxceem** [comment] 2018-10-12 06:10
@vikasrohit I guess it's caused by the [font fix](https://github.com/appirio-tech/connect-app/issues/2588). When Robot font is applied to the text for the second option it doesn't fit one line, and markup supports only one-line text.

I guess it would be enough just slightly increase width for the text items, so the second option fits one line.

Let me know if you think we have to support miltiline text here instead.

**Comment by vikasrohit** [comment] 2018-10-12 06:19
> I guess it would be enough just slightly increase width for the text items, so the second option fits one line.

Yes, that should be good enough provided it works well in both accounts-app registration form and connect app project forms.

**Comment by maxceem** [comment] 2018-10-13 02:55
It's fixed via PR https://github.com/appirio-tech/react-components/pull/302 to `react-components`.


I've noticed one more thing, the difference between new project page and registration page is that Roboto font is rendered differently:
- Connect App
   ![image](https://user-images.githubusercontent.com/146016/46900326-cc3ffe00-ced2-11e8-9ec8-6b10cb3c4fb8.png)

- Accounts App
   ![image](https://user-images.githubusercontent.com/146016/46900331-d82bc000-ced2-11e8-9fed-82c6fcfb3466.png)

The difference is because in Connect App we use `webkit-font-smoothing: antialiased;` while for accounts-app we don't.
Here is the difference in rendering for the whole page:
- `webkit-font-smoothing: antialiased` - enabled:
   ![image](https://user-images.githubusercontent.com/146016/46900447-cba86700-ced4-11e8-9527-c3ddb3a5dc5e.png)
- `webkit-font-smoothing: antialiased` - disabled:
    ![image](https://user-images.githubusercontent.com/146016/46900462-132ef300-ced5-11e8-8798-981ac2c83cdd.png)

I guess we have to have to either enable it everywhere or disabled it everywhere.
Probably @vic-topcoder could give some input.

**Comment by vikasrohit** [comment] 2018-10-15 07:09
@vic-topcoder your input needed for `webkit-font-smoothing: antialiased;` ☝️

**Comment by vic-topcoder** [comment] 2018-10-16 03:44
I usually like "geometric-precision" or "antialiased" on. Either one is fine for me :) Let's use it as it makes font readability/rendering much better. Thanks!

**Comment by maxceem** [comment] 2018-10-16 04:55
@vikasrohit do you think we should enable `antialiased` in accounts-app or react-components (connect branch)?

**Comment by vikasrohit** [comment] 2018-10-16 05:16
@maxceem I think we need to do this for both apps right? For `accounts-app`, we should change the style for only connect pages, not for member side pages to be minimalistic.

**Comment by vikasrohit** [comment] 2018-10-16 05:35
I don't see any harm in doing it in `react-components` as well because as you said it is used only for connect-app and accounts-app(only connect pages). It would make it consistent.

**Comment by maxceem** [comment] 2018-10-17 04:38
I've created a separate issue for the font `anitialised` https://github.com/appirio-tech/connect-app/issues/2636

Note, the current issue can be closed as soon as [PR](https://github.com/appirio-tech/react-components/pull/302) to `react-components` is reviewed and merged.

**Comment by maxceem** [comment] 2018-10-17 05:37
@vikasrohit I also wanted to use it, but I think we cannot. From `tc-ui` we only include this file `@import '~tc-ui/src/styles/tc-includes';` example https://github.com/appirio-tech/react-components/blob/feature/connectv2/components/RegistrationScreen/style.scss

But `tc-includes` should NOT containt any styles only variables and mixins, otherwise these styles will be included multiple times (each time we call @import) and lead to growth of CSS styles, and could lead to performance issues like this https://github.com/appirio-tech/connect-app/issues/2587

**Comment by RishiRajSahu** [comment] 2018-11-14 05:37
@maxceem this task related to issue seems to be done and working fine on both prod and dev. Closing the issue.

**Closed by RishiRajSahu** 2018-11-14 05:37 UTC
Labels: Ready for Review
