### ISSUE TITLE
Screen visible area not updated properly 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#762] opened 2017-03-09 12:42 UTC
### Expected behavior
should visible the dropdwon values 

### Actual behavior
dropdwon values  shown on bottom of the page 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Application Visual Design - Concepts 
- Goto Project Specfication 
- IN App Definition :  Enter valid data 
- In App Screens Click Define another Screen 
- click Screen importance dropdown 

- see 

### Screenshot/screencast

https://www.screencast.com/t/340OzCy9Rdp

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by gondzo** [comment] 2017-03-09 23:46
duplicate of #679

**Closed by gondzo** 2017-03-09 23:46 UTC
Labels: bug hunt
