### ISSUE TITLE
Delay in Coder message on Dashboard after creating new project/new user

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#963] opened 2017-07-10 19:08 UTC
Vikas, I've tested the flow end-to-end and am now seeing this issue: right after I verify the PIN, I'm logged in and the project loads on the Dashboard, which is good. However, the Dashboard is blank at that point, and I have to reload the page in order to get the first Coder message. Can you please have the message appear right away? Otherwise, the user may be confused whether anything has happened.

**Comment by vikasrohit** [comment] 2017-07-11 04:13
@fnisen It must be timing issue as the posting of coder bot messages is async process. I guess we have the same issue with normal project creation flow as well.
Still, I will check if there is any possibility to handle it.

**Comment by fnisen** [comment] 2017-07-31 18:08
@vikasrohit any update on this one?

**Comment by vikasrohit** [comment] 2017-08-01 05:38
I didn't see the issue for my few tries, so I think it is timing issue of async process of posting messages. May be we need @mtwomey's help here.

**Comment by fnisen** [comment] 2017-08-01 16:36
Yeah, now I'm not able to reproduce either. OK, let's assume it's fine for now. Will see if it comes back.

**Comment by fnisen** [comment] 2017-08-03 16:54
Seeing this again. Will ask Matt.

**Comment by vikasrohit** [comment] 2017-08-08 11:01
@fnisen @mtwomey One possible workaround is to wait until we get at least one topic for a newly created project and if we are not able to do so in a certain time (may be 5 seconds), we can show some message to user which can ask them to refresh the page in some time to check the latest happening on their project.

**Comment by fnisen** [comment] 2017-08-08 15:58
Discussed briefly with Matt today. He's been thinking about it and will take a look when he has a chance.

**Comment by gondzo** [comment] 2017-11-23 09:30
If/When we implement notifications via web sockets, this would be a non issue as we can update the message feed as soon as new message is posted.

**Comment by vic-topcoder** [comment] 2017-12-13 02:24
That'll be amazing! :) 🥇  @gondzo - do we plan to do web socket notifications?

**Comment by vikasrohit** [comment] 2017-12-13 05:32
@vic-topcoder @gondzo Web Sockets are heavy on server. So we have to plan it accordingly.

**Comment by vikasrohit** [comment] 2017-12-14 08:53
I don't have that data @gondzo, however, I don't think it is more than few tens of concurrent users.

**Comment by vic-topcoder** [comment] 2018-01-05 04:10
can we close this one?

**Comment by vikasrohit** [comment] 2018-01-05 04:56
I guess so @vic-topcoder because now we are eliminating most of the coder bot messages and the issue is intermittent.

**Comment by vic-topcoder** [comment] 2018-01-05 20:40
ok, closing

**Closed by vic-topcoder** 2018-01-05 20:40 UTC
Labels: P1
