### ISSUE TITLE
Register page won't load when user tries to create a project without login

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1055] opened 2017-07-26 07:20 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Start a Project'

- Click on 'Create Project' button from 'Wireframes' in the Dashboard ("Select your project type")

- Fill all the required data

- Click 'Continue'

Actual Result(s)
-----------------------------------------------------------------
- Register page won't load when user tries to create a project without login instead it will load a blank empty page with 'Privacy Policy' text on it
- Issue Happens: EDT 3:22 AM Wednesday 2017/07/26

Expected Result(s)
-----------------------------------------------------------------
- User must able to create new projects without any issue and prompt  the registration page to the user to register to create the new project

URL where the Bug Appears
-----------------------------------------------------------------
https://accounts.topcoder-dev.com/#!/connect/registration?retUrl=https://connect.topcoder-dev.com/new-project-callback

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![32](https://user-images.githubusercontent.com/4592712/28609194-41f24f8e-7201-11e7-91b7-cd217fb5fb82.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by sdgun** [comment] 2017-07-26 07:34
https://www.screencast.com/t/aQxnvGFA

**Comment by gondzo** [comment] 2017-07-27 18:46
duplicate of #1052

**Closed** 2017-07-27 18:46 UTC
Labels: bug hunt, duplicate
