### ISSUE TITLE
[$100] Window-Mozilla –All the entered specification details are lost, in customer page, if project manager move the project from In-Review to Draft 

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1791] opened 2018-03-01 23:02 UTC
_From @youdare on February 20, 2018 13:56_

1. Summary:
Window-Mozilla –All the entered specification details are lost, in customer page, if project manager move the project from In-Review to Draft 
### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3. Create App project 
4.Go to specification and fill the required information and Click “Submit For Review”
5.Log out the app
6.Log in with  pshah_manager/topcoder123
7.Move the project from in-review to draft
8. Log out the app
9.Again log in to Log in with pshah_customer/topcoder123
10. Click project 
11 GO to specification page 
12 View the mandatory fields 

## Expected Result ###
Window-Mozilla – Notification should displayed to customer as “Your project is moved to draft” if project manager move the project from In-Review to Draft 
.
### Actual  Result ###
Window-Mozilla – Notification is not displayed to customer if project manager move the project from In-Review to Draft 

### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrom 

_Copied from original issue: topcoderinc/connect-test-cycle-1#418_

**Comment by vic-topcoder** [comment] 2018-03-01 23:02
_From @youdare on February 20, 2018 13:58_

![image](https://user-images.githubusercontent.com/31862600/36427495-5f0bfe32-1673-11e8-8565-08188dc70697.png)
![image](https://user-images.githubusercontent.com/31862600/36427504-67d14478-1673-11e8-9128-e50b17f6b76c.png)

![image](https://user-images.githubusercontent.com/31862600/36427370-0efc5090-1673-11e8-90f2-7e2b501dc689.png)

![image](https://user-images.githubusercontent.com/31862600/36427809-2addae20-1674-11e8-8b59-a0f840bd34fc.png)

**Comment by vic-topcoder** [comment] 2018-03-01 23:02
_From @sdgun on February 23, 2018 1:48_

@vic-topcoder

**Comment by vic-topcoder** [comment] 2018-03-01 23:02
Yeah, that shouldn't happen. Thanks for reporting!

**Comment by Colinh84** [comment] 2018-03-09 09:28
@vic-topcoder I have followed the reproduction steps and tested with both methods of changing project status (from grid view and project dashboard) as manager, and both times all information in the specifications page was retained. This bug does not seem to be valid.

**Comment by Colinh84** [comment] 2018-03-09 16:41
@vic-topcoder @gondzo OK, so I figured out what was really going on here. It wasn't the changing of the project status that caused the loss of information as stated in the issue description, rather it was a failure of the user to press the "Save Changes" button on the form BEFORE clicking the "Submit for Review" button on the sidebar. The real bug here was that the "Submit for Review" button is enabled once the required fields are filled, but before they are saved. The "Submit for Review" button is not capable of saving the form information since it is part of another component, it only progresses the status to ready for review. So, obviously if it is not checking if the form is saved yet before becoming active, the form will lose the required information when it is clicked.

I submitted a fix for this which also fixes #1795 which is a related problem. Now the "Submit for Review" button remains disabled until the changes on the form are saved and all the required fields are filled.

**Comment by vic-topcoder** [comment] 2018-03-09 19:29
Ah, that sounds great! Thanks @Colinh84 !

**Comment by vikasrohit** [comment] 2018-03-10 14:07
Nice catch @Colinh84 
However, just for information, @vic-topcoder we intentionally, for better user experience, made the "Submit for Review" button active as soon as required details are filled. However, I think the bug is more confusing for the user, so disabling the button until the form is saved, as fixed by @Colinh84, might be good.

**Comment by vic-topcoder** [comment] 2018-03-13 02:50
Agree!

**Closed** 2018-03-18 22:22 UTC
Labels: ACCEPTED, Functional
