### ISSUE TITLE
If user select 1-3 in "How many screens do you need designed?" user should be able to add three screen 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#749] opened 2017-03-09 07:16 UTC
### Expected behavior
should be able to max number of screen , in case of 1-3 screen user should be able to add 3 screen 

### Actual behavior
user able to add only 1 screen 

### Steps to reproduce the problem
1. Open Application
2. login with manager pat_monahan / topcoder123!
3. Create Design project
4. Go to Specification 
5. Select How many screens do you need designed? as 1 to 3 screen
6. go to add App screen 
7. user should be able to add 3 screen 

### Screenshot/screencast
Attach or link a resource.
![image](https://cloud.githubusercontent.com/assets/16131461/23739716/4b347dd6-04c6-11e7-91e4-67aa0402df04.png)

![image](https://cloud.githubusercontent.com/assets/16131461/23739730/673a88f4-04c6-11e7-87f8-9f1a52818407.png)

--

#### Environment
- OS: windows 7
- Browser (w/version): IE 11
- User role (client, copilot or manager):pat_monahan / topcoder123!
- Account used:  manager

**Comment by gondzo** [comment] 2017-03-09 23:26
duplicate of #700

**Closed** 2017-03-09 23:52 UTC
Labels: bug hunt, invalid
