### ISSUE TITLE
Add Design Link: URL input text field automatically fetching old URL link

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2662] opened 2018-11-01 18:37 UTC
**Expected behavior :**
Describe : Add design Link: URL input text box should be empty, when user click on Add link

**Actual behavior
Describe.**
Add design Link: URL input text box automatically fetching old URL link, when user click on Add link.

**Project Name:**
Phase and Dashboard Validation

**Screen Shot:**

![url of the add design link having same link](https://user-images.githubusercontent.com/30447858/47871910-41985200-de33-11e8-8e8a-615e83d83006.PNG)

**Comment by deepakanbarasan1** [comment] 2018-11-01 18:38
@RishiRajSahu  Please fix it.

**Comment by deepakanbarasan1** [comment] 2018-11-01 18:41
Please find the reference screen shot.
![add design link_url input text field automatically fetching old url link](https://user-images.githubusercontent.com/30447858/47872129-d7cc7800-de33-11e8-82a1-f4bb33db2a12.PNG)

**Comment by maxceem** [comment] 2018-11-02 01:18
@RishiRajSahu Fixed in PR https://github.com/appirio-tech/connect-app/pull/2664

**Comment by RishiRajSahu** [comment] 2018-11-02 05:06
Duplicate of https://github.com/appirio-tech/connect-app/issues/2430 . Closing.

**Closed by RishiRajSahu** 2018-11-02 05:06 UTC
Labels: Functional, Ready for Review, UI
