### ISSUE TITLE
Must trigger the search when user click on the search button

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#299] opened 2016-09-28 22:51 UTC
### Expected behavior
-----------------------------------------------------------------
Must trigger the search when user click on the search button

### Actual behavior
-----------------------------------------------------------------
Nothing happens when user click on the search icon

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Enter 'test' in the search
- Click BLUE Search button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_4-21-25](https://cloud.githubusercontent.com/assets/4592712/18935209/36dd6b7a-85fc-11e6-9487-59d565a26b82.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 11:38
Duplicate of #188. You registered the previous one.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
