### ISSUE TITLE
[$20] Post mention should not be link

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2476] opened 2018-09-07 07:32 UTC
@mention should not lead to the profile page; let's remove the profile link - we don't want customers to go to the community profile page at this time.

continued from https://github.com/appirio-tech/connect-app/issues/2301

**Comment by maxceem** [comment] 2018-09-12 01:28
@RishiRajSahu in another issue there is a task to make mentions bold https://github.com/appirio-tech/connect-app/issues/2201.

After we make mentions not links in this task, should they stay bold? Other words if they are not links anymore, should they be highlighted by styles in some way or look just like a regular text?

**Comment by RishiRajSahu** [comment] 2018-09-12 05:04
@maxceem so what we need is - 
1.In #2201 it say mentions needs to be bold, which should not be changed
2.As part of this issue we want bold mentions not to contain a href of user profile.

**Comment by maxceem** [comment] 2018-09-12 10:19
This is one is open for pick up now.

**Comment by PrakashDurlabhji** [comment] 2018-09-12 10:20
@maxceem please assign it to me

**Comment by gondzo** [comment] 2018-09-12 11:34
@maxceem @RishiRajSahu post mention being a link is expected in notifications so we should be careful not to break that feature https://github.com/topcoder-platform/tc-notifications/blob/d2e0c71f56a3744cd11516044bd9f9beec7b92a7/connect/connectNotificationServer.js#L72

**Comment by maxceem** [comment] 2018-09-12 11:57
Thank you @gondzo for your comment.

@PrakashDurlabhji just to be clear on this we only have to remove links from @menitions inside posts:

![image](https://user-images.githubusercontent.com/146016/45423390-c84b7100-b6c5-11e8-9cba-db44b65b918a.png)

There is `@Parth Customer` is a links now, but shouldn't. You may find this example in the project with id `7298` on the dashboard tab.

@RishiRajSahu fyi

**Comment by vikasrohit** [comment] 2018-09-12 12:10
Good catch @gondzo. Thanks for saving us from a regression. 👍

**Comment by PrakashDurlabhji** [comment] 2018-09-12 12:48
sure will implement same.

**Comment by nahidshahin** [comment] 2018-09-12 17:10
@maxceem Want to work on it

**Comment by PrakashDurlabhji** [comment] 2018-09-13 11:15
@maxceem releasing it, docs are not proper of markdown ,trying to understand since long. wont be able to do it. open for pickup now.

**Comment by suppermancool** [comment] 2018-09-13 11:47
@maxceem pls assign to me

**Comment by RishiRajSahu** [comment] 2018-09-13 11:49
@suppermancool assigned to you !

**Comment by suppermancool** [comment] 2018-09-13 12:59
@RishiRajSahu @maxceem  ready for review in 
https://github.com/appirio-tech/connect-app/pull/2510/files

**Comment by suppermancool** [comment] 2018-09-14 05:18
@maxceem done in the latest commit, pls check, thanks

**Closed** 2018-09-19 05:30 UTC
Labels: ACCEPTED, CF-12
