### ISSUE TITLE
Project Name input placeholder is not centered in FF

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1034] opened 2017-07-25 19:46 UTC
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com using Firefox
Click Start a project  
Select any project type  
Notice the placeholder text of the Project Name field
Repeat the steps above using Chrome, IE, or Edge and compare the Project Name placeholder

### Expected behavior  
Project Name input placeholder should be centered

### Actual behavior  
Project Name input placeholder is not centered in FF

### Screenshot/screencast
FF
![placeholder ff](https://user-images.githubusercontent.com/1199534/28590482-d8744cc0-71b4-11e7-8f59-1d0246a29827.png)

Chrome, IE, Edge
![placeholder other](https://user-images.githubusercontent.com/1199534/28590487-db4c7620-71b4-11e7-9bf9-5eaa0fd7d2aa.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment] 2017-07-27 18:29
duplicate of #994

**Closed** 2017-07-27 19:05 UTC
Labels: bug hunt, duplicate
