### ISSUE TITLE
Logged as copilot the create custom button is not available

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#397] opened 2016-09-30 18:13 UTC
Expected behavior
------------------------------------------------------------

- The button must be available to be used.

Actual behavior
------------------------------------------------------------

- The button is not available to be used.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as copilot user role.

- Press New Project button.

- Select App Design & Dev, Prototype an app, Tablet.

- Set a project name and description to enable Create Project button.

- Create Project.

- Select Specification.

- From Feature requirements press Add / Edit Features button.

- Move the vertical scroll bar to the bottom of page.

- Observe as the button is not available to be used.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635 
Display resolution: 1366x768
Browser(s): Chrome 49.0.2623.112 m
User role: connect user role
Account used: christina_uw 

![a](https://cloud.githubusercontent.com/assets/5114907/19002021/b9b2bef4-8752-11e6-8614-ac226548236f.png)

**Comment by mahestro** [comment] 2016-10-04 18:07
Duplicate of #366.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
