### ISSUE TITLE
Missing login form when clicked on log in button in the homepage

### ISSUE THREAD

**Issue by meontechno** [appirio-tech/connect-app#1054] opened 2017-07-26 07:06 UTC
### Steps to reproduce the problem

- Open URL https://connect.topcoder-dev.com

- Click on **Log in**

- Observe the page

### Expected behavior
Login form should appear when clicked on the **log in** button in the top right corner of the homepage.

### Actual behavior
when clicked on the login button, a page with content "privacy policy" is displayed instead of showing a login form

### Screenshot/screencast
![welocme](https://user-images.githubusercontent.com/24816337/28608619-da6330ec-7195-11e7-8717-af083745aca7.PNG)

## After clicking on log in button
![nocontent](https://user-images.githubusercontent.com/24816337/28608662-0d9a765a-7196-11e7-869c-2c7757ab7e37.PNG)

#### Environment
- OS: Windows 10 Home
- Browser (w/version): Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- User role (client, copilot or manager): NA
- Account used: NA

**Comment by gondzo** [comment] 2017-07-27 18:45
duplicate of #1052

**Closed** 2017-07-27 18:45 UTC
Labels: bug hunt, duplicate
