### ISSUE TITLE
Log out not working on feature/productsv1 branch

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#676] opened 2017-03-06 23:28 UTC
### Expected behavior
When clicking on Log Out from the user drop-down menu, the user should be able to log out

### Actual behavior
Nothing happens on click.

**Comment by vikasrohit** [comment] 2017-03-07 11:20
We haven't change the way of login/logout in productsv1 branch. So, it should not be issue with the changes made in this branch. It is working for me. However, sometimes, it logs back me in after logout and that seems to be the case even on production for me. I am assuming that is happening because of multiple environment testing on our local machines. If that issue is consistently reproducible, we can look into it.

**Comment by fnisen** [comment] 2017-03-09 23:44
Seems to be working on Dev, so will close this.

**Closed by fnisen** 2017-03-09 23:44 UTC
Labels: known-issue, P1, products
