### ISSUE TITLE
Project estimate is not displayed for below QA services

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3689] opened 2020-01-31 02:41 UTC
![image](https://user-images.githubusercontent.com/42398485/73508139-b349ad80-43a0-11ea-88c0-5ae10003fda0.png)

1. Open the Application and Login as valid user (Manager)(portrait)
2. Click + New Project > Solutions > QA Services (23-08-2019)
3. Fill all the mandatory fields > Next
4. Select Any service from the below list;

Regression Testing
End-User Acceptance Testing/Beta Testing
Compatibility Testing
Exploratory Testing
Accessibility Testing
Localization/Language Testing
Functional/Feature Testing
User Sentiment Analysis
Regression Automation

5. Complete all the steps and check the 'Project estimate'

**Actual:** Project estimate is not displayed for below QA services

**Expected:** Should display the Project estimate

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment] 2020-01-31 02:41
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P4

**Comment by SathyaJayabal** [comment] 2020-01-31 13:45
related #3688

**Comment by nithyaasworld** [comment] 2020-02-26 08:49
@maxceem @vikasrohit 

I am able to reproduce with the updated UI as well. Please confirm if this is an issue.

![image](https://user-images.githubusercontent.com/5114190/75327741-ebaab180-58a2-11ea-8512-d6e367158a7d.png)

**Comment by vikasrohit** [comment] 2020-02-26 12:16
Project estimates should be hidden on production. I think we enabled it for testing in dev, @maxceem do you remember if we have configuration to hide it from the template itself? or do we need to change code to hide it?

**Comment by vikasrohit** [comment] 2020-02-26 12:21
@maxceem I just recalled how to hide the estimate component. @nithyaasworld please ignore the timeline and cost estimate in deve env because on production they are not enabled. We kept them enabled on dev because we are testing the estimator occasionally in dev and at the same time, we kept the config of estimator(which we removed on production) in dev as backup.

**Comment by vikasrohit** [comment] 2020-02-26 12:22
@nithyaasworld `QA Services (23-08-2019)` no longer exist on dev and after the release it won't be there on prod as well. So, I think we can safely close this issue.

**Closed** 2020-02-26 22:33 UTC
Labels: BugHunt_JanRelease, Functional, P2
