### ISSUE TITLE
Can create projects without description/goal of your application/users 

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1069] opened 2017-07-27 12:47 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click Login and login as a client

- Click + New Project

- Select 'Web site' or 'Front-end Prototype' project

- Fill 'Project Name'

- Fill all the required data with spaces

- Click 'Continue' and observe

Actual Result(s)
-----------------------------------------------------------------
- Can create 'Website' project without a description by simply putting spaces as the description. But in normal condition when user tries to create a project without description the 'Continue' button is not enabled. but when user enters spaces for the required fields 'Continue' button is enabled and can create a project

- This applies to the 'What is the goal of your application? How will people use it?' and 'Who are the users of your application?' fields also

Expected Result(s)
-----------------------------------------------------------------
- Must validate the spaces as input for the description field in 'Website' project

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/projects/?page=1&sort=createdAt+desc

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
![39](https://user-images.githubusercontent.com/4592712/28670773-cdc40128-72f7-11e7-9bd5-6522cc072126.jpg)

https://www.screencast.com/t/NmmeKj8v

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** Client
- **Account used:** dil333/123456Qa

**Comment by gondzo** [comment] 2017-07-27 18:58
duplicate of #981

**Closed** 2017-07-27 18:59 UTC
Labels: bug hunt, duplicate
