### ISSUE TITLE
Redundant presence of 'Project Estimates' on Project outline panel for Software Development project 

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1012] opened 2017-07-24 19:16 UTC
### Expected behavior
Any field which doesn't have any significance or usage in that particular page, should be removed.For 'Other Design' project option, there are no option to reflect any value for 'Project Estimate'.Hence, 'Project Estimate' should be kept hidden for 'software Development Project'.

### Actual behavior
Unnecessary presence of 'Project Estimate' details in Project Outline panel for 'Software Development Projects'.

### Steps to reproduce the problem
-Go to url https://connect.topcoder-dev.com.
- Click 'Start a Project'.
- Chose 'Software Development Project'.
- Observe & try to identify any relevance of 'Project Estimate' in Project Outline.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28540314-8e98a840-70d2-11e7-912e-3cc01c683745.png)
![image](https://user-images.githubusercontent.com/20595047/28540325-9de618e6-70d2-11e7-913f-bf8a91f877fb.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not Logged In
- Account used: -NA-

**Comment by gondzo** [comment] 2017-07-27 18:08
duplicate of #1002

**Closed by gondzo** 2017-07-27 18:08 UTC
Labels: bug hunt, duplicate

**Comment by Kvm87** [comment] 2017-07-28 07:30
I am surprised that issue#1007, 1008 and 1012 have been counted as duplicate of issue#1002. Even though the nature of issues is same, a testing effort goes for each of 8 types of project to see where is it applicable and where not.I request you to kindly correct me if I am wrong.Thanks!
