### ISSUE TITLE
message: showing the wrong timing on message post 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#223] opened 2016-09-28 19:46 UTC
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to message
5. Post a status message

Expected Result: should displayed the correct time
Actual Result: showing timing in negative

Enviroment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18929472/34fd0ec4-85e2-11e6-91b5-6c7188106dc8.png)

**Comment by vikasrohit** [comment] 2016-10-05 07:54
Working fine for me. Is it reproducible with new project only?

**Comment by vikasrohit** [comment] 2016-10-10 10:37
@mahestro  @fnisen Can you please let me know if this is still applicable?

**Comment by mahestro** [comment] 2016-10-10 10:50
I could reproduce it the last week but not today. I could notice was this: http://take.ms/lASDY - A strange error when you reply to an existing message thread. Something throws an error.

I think the -time issue could have been fixed by Parth, maybe?

**Comment by vikasrohit** [comment] 2016-10-10 11:09
That error is because API throws 429 error occasionally. Which I guess is limitation from discourse.

**Comment by fnisen** [comment] 2016-10-10 16:53
Can't reproduce the original error. I think it was fixed by Parth. Filing a bug for the one mentioned to Luis (was able to reproduce, as well): https://github.com/appirio-tech/connect-app/issues/453.

**Closed by fnisen** 2016-10-10 16:53 UTC
Labels: P1
