### ISSUE TITLE
[$10] Update & Unhide "Manage billing account in Salesforce"

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4315] opened 2021-02-23 21:32 UTC
Update 1
Update hyperlink (Sumit will provide)

Update 2
Unhide hyperlink

**Comment by maxceem** [comment] 2021-03-01 12:18
@acshields we can include this task into the release as soon as we have a new hyperlink format.

**Comment by vikasrohit** [comment] 2021-03-02 10:02
@maxceem here is the link format `https://topcoder.my.salesforce.com/apex/baredirect?id={tcBillingAccountId}`.

**Comment by maxceem** [comment] 2021-03-02 10:50
@yoution you may pick up this issue.

Sum up:
- show this link again https://github.com/appirio-tech/connect-app/blob/hotfix/taas-job-editor-improvements/src/projects/detail/components/BillingAccountField/index.js#L93-L103
- it would be visible on page like https://connect.topcoder-dev.com/projects/16952/settings
- create a new env variable `SALESFORCE_BILLING_ACCOUNT_LINK` similar to how we config `SALESFORCE_PROJECT_LEAD_LINK` with the values provided in the https://github.com/appirio-tech/connect-app/issues/4315#issuecomment-788784637 above

**Comment by yoution** [comment] 2021-03-02 10:51
@bug-bash-helper assign me

**Comment by maxceem** [comment] 2021-03-02 10:53
Challenge https://www.topcoder.com/challenges/255f5ff2-fd50-454c-b012-aa1da45a9b7b has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2021-03-02 10:53
Challenge https://www.topcoder.com/challenges/255f5ff2-fd50-454c-b012-aa1da45a9b7b has been assigned to yoution.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2021-03-02 10:53
@yoution assigned manually.

**Comment by yoution** [comment] 2021-03-02 13:13
@maxceem  
show this link again https://github.com/appirio-tech/connect-app/blob/hotfix/taas-job-editor-improvements/src/projects/detail/components/BillingAccountField/index.js#L93-L103

change the https://github.com/appirio-tech/connect-app/blob/hotfix/taas-job-editor-improvements/src/projects/detail/components/BillingAccountField/index.js#L97 to **SALESFORCE_BILLING_ACCOUNT_LINK**?

**Comment by maxceem** [comment] 2021-03-02 15:30
> show this link again https://github.com/appirio-tech/connect-app/blob/hotfix/taas-job-editor-improvements/src/projects/detail/components/BillingAccountField/index.js#L93-L103

yes

> change the https://github.com/appirio-tech/connect-app/blob/hotfix/taas-job-editor-improvements/src/projects/detail/components/BillingAccountField/index.js#L97 to SALESFORCE_BILLING_ACCOUNT_LINK?

yes, before we use the wrong link here, so we hide it. Now in the https://github.com/appirio-tech/connect-app/issues/4315#issuecomment-788784637 above, we've got the new URL for this link. But this URL is different from what we use before. So we have to update this URL to new one. And we have to introduce a new variable for this link `SALESFORCE_BILLING_ACCOUNT_LINK`.

**Comment by yoution** [comment] 2021-03-02 15:35
@maxceem    
but how about the url queryid，the old url used the projectid，but the new url use tcBillingAccountid？
 https://c.cs18.visual.force.com/apex/baredirect?id={tcBillingAccountId}

**Comment by maxceem** [comment] 2021-03-02 15:45
Yes, new URL has to use `billingAccountId` form the project:

![image](https://user-images.githubusercontent.com/146016/109673747-fe735880-7b7e-11eb-915a-364b4b1871b8.png)

**Comment by maxceem** [comment] 2021-03-02 15:47
@vikasrohit I've noticed one thing. The URL to manage billing account depends on the actual billing account assigned. 
- So if the billing account is not assigned, we have to hide this link, because we don't which BA to manage
- If we change value in select we have to dynamically update this link even without form saving. because if we choose another value in the form user might expect that this link also leads to another billing account management.

Is it correct?

@acshields maybe you could also have a look at such cases and confirm.

**Comment by acshields** [comment] 2021-03-02 16:29
@maxceem - I am not understanding the scenario :(

**Comment by vikasrohit** [comment] 2021-03-03 05:53
Yes, I can confirm both points @maxceem. @acshields I can explain you in our next call.

**Comment by coderhacker** [comment] 2021-03-05 03:39
@drasticdpk  @lakshmiathreya  this is passed on dev

https://user-images.githubusercontent.com/62358241/110064118-81203180-7d92-11eb-800a-7c902f99884a.mp4

**Comment by maxceem** [comment] 2021-03-10 12:32
Payment failed: [400]: Failed to activate challenge. Detail: Cannot Activate this project, it has no active billing accounts.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by drasticdpk** [comment] 2021-03-11 07:45
Verified on Prod 
![image](https://user-images.githubusercontent.com/25297859/110752856-eaf67a80-826d-11eb-8f47-1f68e5a29893.png)


![image](https://user-images.githubusercontent.com/25297859/110752929-ff3a7780-826d-11eb-97ec-35ef3e57e5f9.png)

**Closed by drasticdpk** 2021-03-11 07:45 UTC
Labels: ACCEPTED, CF, Feature: Billing Accounts, Feature: Project Defaults, P3, QA Pass in Dev, Release Due Date: 3/12, tcx_Assigned, tcx_FixAccepted
