### ISSUE TITLE
New Project button is displayed as disable the back to section

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#409] opened 2016-10-01 15:17 UTC
Expected behavior

- Display the button as enable.

Actual behavior

- The New Project button is displayed as disable.

Steps to reproduce the problem

- Login into application as connect user role.

- New Project.

- Close the window using "x" close button from the top right.

- Observe the New Project button.

Environment
- OS: Windows 7
- Browser (w/version): IE 11.0
- User role (client, copilot or manager): copilot
- Account used: christina_uw

![new-project-button](https://cloud.githubusercontent.com/assets/5114907/19014980/4434f212-8803-11e6-974c-4200715132f1.png)

**Comment by mahestro** [comment] 2016-10-04 18:58
Duplicate of #240

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
