### ISSUE TITLE
[IE11 / App Definition] - features are not correct displayed in page

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#423] opened 2016-10-01 16:57 UTC
Expected behavior

- The feature pages must be correct displayed.

Actual behavior

- The feature pages are not correct displayed.

Steps to reproduce the problem

- Login into application as copilot role.

- Edit an existing project as nnn.

- Select Specification.

- From Feature requirements press Add / Edit Features.

- Select Social Login / Invitation / Introduction.

- Observe as the page is not correct displayed using IE 11.0.

Environment
- OS: Windows 7
- Browser (w/version): IE 11.0
- User role (client, copilot or manager): copilot
- Account used: cp-superstar

![invitations](https://cloud.githubusercontent.com/assets/5114907/19015671/4039ff5a-8811-11e6-973f-d22ac359f0fc.png)

![social-login](https://cloud.githubusercontent.com/assets/5114907/19015672/48287516-8811-11e6-8b9c-fdaf2dd4d898.png)

**Comment by mahestro** [comment] 2016-10-04 19:19
Duplicate of #200

**Closed** 2016-10-12 18:43 UTC
Labels: P0, visual styling
