### ISSUE TITLE
[$15] Update Cancellation reason codes

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2833] opened 2019-02-14 05:31 UTC
Update the project cancellation reason codes to include:

<p></p>

0. Spam

1. Demo/Test

2. Duplicate project

3. Want to join Topcoder as member - We can change the lead to SFDC but this wouldn't trigger the email to be sent. The person doing the lead review in SFDC would need to click a button in SFDC to send the invitation. SFDC team would need update SFDC integration to 'listen' to this event and create a trigger (code) in SFDC so that the email can be triggered. 

(If we can send an automated email to this person with “Join Topcoder” link for the Community, that would be good) 

4. Project budget doesn't fit

5. Insufficient input from Customer

6. Poor community fit

7. Customer not responsive

8. Unrealistic timeline

<p></p>

**Comment by ajefts** [comment] 2019-02-14 05:31
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1761882

**Comment by maxceem** [comment] 2019-02-25 02:32
@vikasrohit 
So far we have the next list of labels and values of cancelation reasons. Values - are the texts we send to the server during cancelation, probably it's important to keep some particular values for them.
```
      { value: 'spam', title: 'Spam'},
      { value: 'demo', title: 'Demo/Test'},
      { value: 'competitor', title: 'Customer selected competitor'},
      { value: 'price', title: 'Price too high'},
      { value: 'customer-inhouse', title: 'Being done in-house'},
      { value: 'customer-inactivity', title: 'Customer not responsive'},
      { value: 'non-community', title: 'Poor community fit'},
      { value: 'by-choice', title: 'Declined by us'}
```

Here are the new values and the values I propose to use. Do you think they are ok?
- Duplicate project: `duplicate`
- Want to join Topcoder as member: `join-as-member`
- Project budget doesn't fit: should we keep `price`? or create a new one `budget`?
- Insufficient input from Customer: `insufficient-input `
- 5\. Unrealistic timeline: `timeline`

**Comment by maxceem** [comment] 2019-02-26 01:47
@RishiRajSahu in case, you can advise here, we can also run this in CF.

**Comment by RishiRajSahu** [comment] 2019-02-26 07:21
@maxceem yep looks good, regarding `price` or `budget` let me confirm with other team like if they are using the existing data and has some filter to analyse data based on value `price`, if yes we will keep it same otherwise we will rename it to `budget`, will get back to you soon.

**Comment by RishiRajSahu** [comment] 2019-02-26 07:30
@maxceem okay I confirmed, we are not going to change the values which are send to server we will just update the title if needed, so we are good to get it included in CF.

**Comment by maxceem** [comment] 2019-02-26 07:39
@RishiRajSahu do I understand it correctly, that 
- 4\. Project budget doesn't fit: should we keep `price`? Other words it's the same option.

And these values are new - as I don't see any match in the current list for them.
- 2\. Duplicate project: `duplicate`
- 3\. Want to join Topcoder as member: `join-as-member`
- 5\. Insufficient input from Customer: `insufficient-input `
- 8\. Unrealistic timeline: `timeline`

**Comment by RishiRajSahu** [comment] 2019-02-26 09:42
@maxceem 
4. `{ value: 'price', title: 'Price too high'}` will become `{ value: 'price', title: 'Project budget doesn't fit'}`

yeah I am good with new ones.

**Comment by maxceem** [comment] 2019-02-26 10:10
Sum up:
- When on any project dashboard, for example http://local.topcoder-dev.com:3000/projects/7885 we change project state to the `Cancelled` 
   
     ![image](https://user-images.githubusercontent.com/146016/53404888-8e5ef480-39f1-11e9-9f1b-13e00c42fd64.png)

     we have to choose the reason to cancel:

     ![image](https://user-images.githubusercontent.com/146016/53404902-97e85c80-39f1-11e9-9867-29a082757f3b.png)

- We should update it to the list, described in [first comment](https://github.com/appirio-tech/connect-app/issues/2833#issue-410134975)

**Comment by maxceem** [comment] 2019-02-26 10:12
This issue is now open for pick up.

**Comment by r0hit-gupta** [comment] 2019-02-26 10:18
I would like to work on this.

**Comment by maxceem** [comment] 2019-02-26 10:21
@r0hit-gupta you can start working on it since your comment. To make it clear I've sent you an invitation to the repo, as soon as you accept it I could mark you as assigned.

**Comment by r0hit-gupta** [comment] 2019-02-26 10:24
I have accepted it.

**Comment by r0hit-gupta** [comment] 2019-02-26 13:06
```
{ value: "spam", title: "Spam"},
{ value: "demo", title: "Demo/Test"},
{ value: "duplicate", title: "Duplicate project"},
{ value: "join-as-member", title: "Want to join Topcoder as member"},
{ value: "price", title: "Project budget doesn't fit"},
{ value: "insufficient-input", title: "Insufficient input from Customer"},
{ value: "non-community", title: "Poor community fit"},
{ value: "customer-inactivity", title: "Customer not responsive"},
{ value: "unrealistic-timeline", title: "Unrealistic timeline"}
```

@maxceem Can you please review if these options and values are fine ?

**Comment by maxceem** [comment] 2019-02-26 13:12
@r0hit-gupta, yes looks good to me.

**Comment by r0hit-gupta** [comment] 2019-02-26 13:28
I have created a PR. Please review.

**Comment by maxceem** [comment] 2019-02-27 09:37
@r0hit-gupta reviewed, please have look https://github.com/appirio-tech/connect-app/pull/2864

**Comment by r0hit-gupta** [comment] 2019-02-27 11:39
@maxceem changes done as requested. Please review.

**Comment by RishiRajSahu** [comment] 2019-03-05 09:43
Closing. Working fine.

**Closed by RishiRajSahu** 2019-03-05 09:43 UTC
Labels: ACCEPTED
