### ISSUE TITLE
In some cases Time zone added when registering is not displayed in the User's profile

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3437] opened 2019-12-16 15:09 UTC
1. Go to connect-test01.topcoder-dev.com
2. Register a new user
3. Then check the newly created user's profile info

Actual:
The Time Zone added when registering, is not displayed in the user's profile

![image](https://user-images.githubusercontent.com/5114190/70917898-28a52d00-2044-11ea-8ee1-1308b26f1289.png)

**Comment by nithyaasworld** [comment] 2019-12-16 15:10
cc: @lakshmiathreya

**Comment by RishiRajSahu** [comment] 2019-12-16 15:12
@nithyaasworld was there any error during user creation ? could you provide the credentials of this user ?

**Comment by maxceem** [comment] 2019-12-17 03:25
@RishiRajSahu on DEV the registration form still doesn't have Working hours shown. I guess cache hasn't been reset for the `dev` branch during deploying.

From the screenshot in this issue looks like many required fields become empty, as "title", "phone", "company", "country" and "timezone" are required fields, but they are empty on the screenshot in this issue:

![image](https://user-images.githubusercontent.com/146016/70962350-d1dd3900-20bf-11ea-8b4e-f4b66de12b2b.png)

**Comment by vikasrohit** [comment] 2019-12-17 05:08
It seems member api issue, because we tested it today and it worked fine in the evening but we would definitely look into it before release. And as a backup up plan, we would fix it on production as patch release because leaving this feature out is more difficult then fixing it as patch.

**Comment by RishiRajSahu** [comment] 2019-12-17 05:12
@maxceem Cache has been reset for Accounts App you can see new fields on registration page now.
CC @nithyaasworld @lakshmiathreya

**Comment by lakshmiathreya** [comment] 2019-12-17 14:21
Verified in Prod - Timezone being set for new user and visible in Project Team view.

**Comment by nithyaasworld** [comment] 2019-12-18 09:15
@RishiRajSahu @lakshmiathreya I am able to reproduce this issue still.

Please find the video here: 
[entered info, not getting carried forward.zip](https://github.com/appirio-tech/connect-app/files/3977518/entered.info.not.getting.carried.forward.zip)

**Comment by maxceem** [comment] 2019-12-18 09:46
Looks like a Member Service issue. I'll check it out with the user which you've created in the demo video.

**Comment by nithyaasworld** [comment] 2019-12-19 05:22
@maxceem I just checked again and confirming that this issue is still reproducible

**Comment by RishiRajSahu** [comment] 2019-12-19 05:43
@nithyaasworld I created a new user in PROD and all the fields getting persisted successfully. could you confirm again or send me the credentials of the user you tested in prod ?

**Comment by nithyaasworld** [comment] 2019-12-19 05:53
yeah Sure!

This is the screenshot of another user which I just created. 

![image](https://user-images.githubusercontent.com/5114190/71148548-f36e2a00-2251-11ea-8e4c-68cc06f27234.png)

![image](https://user-images.githubusercontent.com/5114190/71148574-02ed7300-2252-11ea-94a1-6705522e88d8.png)

**Comment by RishiRajSahu** [comment] 2019-12-19 08:31
@nithyaasworld that's strange, could you please put the valid value for phone number and try. Another thing you can help debug, as I am not able to reproduce, could you grab the network logs when doing the registration ?

**Comment by RishiRajSahu** [comment] 2019-12-19 08:34
@nithyaasworld I checked DB, there are no traits created for this user. Possibly because of invalid phone number value, let me know once you verify above steps I mentioned.

**Comment by lakshmiathreya** [comment] 2019-12-19 09:12
Edited the Title - its happening in some cases - if it'd be happening in all cases, it would need immediate resolution! I verified with new user and it worked fine. @nithyaasworld pls retry with correct phone number and update the Issue.

**Comment by nithyaasworld** [comment] 2019-12-19 10:40
That's interesting!! Its always happening for me. I also tried by entering valid phone number. It never worked **even once for me.**

Network and Console Logs:
[logs.zip](https://github.com/appirio-tech/connect-app/files/3983057/logs.zip)

Here is the Video:
[profile info missing.zip](https://github.com/appirio-tech/connect-app/files/3983114/profile.info.missing.zip)

**Comment by RishiRajSahu** [comment] 2019-12-19 13:05
@nithyaasworld If you check the video at 0:42 you will see 503 error, service unavailable. which is not happening for other. Are you on VPN ? Is it possible that you could try on different network. Also you can see the detailed error by clicking on the failed request of trait and grab the error message from there for us.

**Comment by nithyaasworld** [comment] 2019-12-19 14:01
@RishiRajSahu Ok, here are the steps to reproduce this issue:

1. Open an Incognito window and go to connect
2. Choose to register a new user
3. Fill up valid values for all the fields but for the phone number, enter the country code manually. Example, **enter 91 in the phone number and observe that it gets the 'IND' automatically**, then enter the phone number
4. Click continue and check the error
5. It seems to call v3 api and not sure if this is okay and the call fails saying 'phone number is not of the right format'

Please check this video where you can see the call and response: 
[traits giving 400.zip](https://github.com/appirio-tech/connect-app/files/3983891/traits.giving.400.zip)

**Comment by RishiRajSahu** [comment] 2019-12-19 14:10
@nithyaasworld yes the phone number format is incorrect. User is not suppose to enter the country code `91` user just have to select the country from the dropdown. And even if you are adding manually user `+91` . This should resolve this issue. Please verify and close if working fine.

**Comment by RishiRajSahu** [comment] 2019-12-23 02:11
@nithyaasworld @lakshmiathreya I think we can close this.

**Comment by RishiRajSahu** [comment] 2020-01-06 02:48
Closing the issue.

**Closed by RishiRajSahu** 2020-01-06 02:48 UTC
Labels: P1, Prod Environment, QA Fail in Prod

**Comment by nithyaasworld** [comment] 2020-01-08 09:15
Thanks @RishiRajSahu 

Verified that its working fine if entered with +91
