### ISSUE TITLE
When user switch the Status error displayed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#334] opened 2016-09-29 10:26 UTC
### Expected behavior
-----------------------------------------------------------------
When user switch the Status; Must not display an error message

### Actual behavior
-----------------------------------------------------------------
When user switch the Status error displayed

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project
- Click on Dashboard
- Change the status to "Completed"
- Change the status to "In Review"

- **If user accidentally select "Completed"; User can't change it by selecting another value before the "Completed" stage**

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_15-52-14](https://cloud.githubusercontent.com/assets/4592712/18950410/4d9b5938-865d-11e6-817e-d80a5fdd7039.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 12:47
Duplicate of #244

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
