### ISSUE TITLE
A different error displayed when the user tries to invite to `a`

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3829] opened 2020-04-02 02:37 UTC
### Expected behavior
Should display like "a: User with such handle does not exist"

### Actual behavior
A different error displayed when the user tries to invite to `a`

### Steps to reproduce the problem
- Login as Manager
- Click on a project from the project listing page
- Click "Dashboard"
- On "Customer team" > Click 'Manage Invitations'
- Enter 'b' and click on the suggestion 
- Click 'Send Invite'
- There is an error "b: User with such handle does not exist" 
- Enter 'a' and click on the suggestion 
- Click 'Send Invite'
- There is an error "YOU ARE UNABLE TO INVITE MEMBERS SUCCESSFULLY." 

```
main.ccc5441047e8d3abacc5.js:130 POST https://api.topcoder-dev.com/v5/projects/9057/invites/?fields=id%2CprojectId%2CuserId%2Cemail%2Crole%2Cstatus%2CcreatedAt%2CupdatedAt%2CcreatedBy%2CupdatedBy%2Chandle 500
(anonymous) @ main.ccc5441047e8d3abacc5.js:130
e.exports @ main.ccc5441047e8d3abacc5.js:130
Promise.then (async)
e.exports @ main.ccc5441047e8d3abacc5.js:223
Promise.then (async)
c.request @ main.ccc5441047e8d3abacc5.js:223
(anonymous) @ main.ccc5441047e8d3abacc5.js:130
t.createProjectMemberInvite @ main.ccc5441047e8d3abacc5.js:162
(anonymous) @ main.ccc5441047e8d3abacc5.js:28
t @ main.ccc5441047e8d3abacc5.js:17
c @ main.ccc5441047e8d3abacc5.js:28
(anonymous) @ main.ccc5441047e8d3abacc5.js:28
(anonymous) @ main.ccc5441047e8d3abacc5.js:192
(anonymous) @ main.ccc5441047e8d3abacc5.js:223
(anonymous) @ main.ccc5441047e8d3abacc5.js:192
value @ main.ccc5441047e8d3abacc5.js:293
i @ main.ccc5441047e8d3abacc5.js:33
s @ main.ccc5441047e8d3abacc5.js:33
executeDispatchesInOrder @ main.ccc5441047e8d3abacc5.js:33
d @ main.ccc5441047e8d3abacc5.js:28
f @ main.ccc5441047e8d3abacc5.js:28
e.exports @ main.ccc5441047e8d3abacc5.js:130
processEventQueue @ main.ccc5441047e8d3abacc5.js:28
(anonymous) @ main.ccc5441047e8d3abacc5.js:192
handleTopLevel @ main.ccc5441047e8d3abacc5.js:192
f @ main.ccc5441047e8d3abacc5.js:192
perform @ main.ccc5441047e8d3abacc5.js:28
batchedUpdates @ main.ccc5441047e8d3abacc5.js:192
batchedUpdates @ main.ccc5441047e8d3abacc5.js:28
dispatchEvent @ main.ccc5441047e8d3abacc5.js:192
21:36:19.793 main.ccc5441047e8d3abacc5.js:130 Uncaught (in promise) Error: Request failed with status code 500
    at e.exports (main.ccc5441047e8d3abacc5.js:130)
    at e.exports (main.ccc5441047e8d3abacc5.js:223)
    at XMLHttpRequest.f.<computed> (main.ccc5441047e8d3abacc5.js:130)
```

### Screenshot/screencast

https://monosnap.com/file/sakVcL9SBI6F6VTNLc8fbcAOT6F0pZ

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  TopConnCustomer

**Comment by maxceem** [comment] 2020-04-16 07:42
This is an interesting catch. It looks like an issue in Project Service.
When we invite user with handle `b`, Project Service found user with handle `B` (uppercase) and created invite for it, but also returned the error that cannot invite user with handle `b`(lowercase).

@vikasrohit are user handles at Topocder case-sensitive or case-insensitive? In other words, should we invite a user with handle `B` when we type `b` or return an error?

**Comment by vikasrohit** [comment] 2020-04-16 08:51
@maxceem handles are case insensitive. `vikasrohit` or `VIKASrohit` should be same. It might not allow login using a variation of the casing in handle, but we should treat the handle case insenstive.

**Comment by maxceem** [comment] 2020-04-16 09:03
@codejamtc I can reproduce the issue when inviting user `b`. But I cannot reproduce the issue when inviting user `a`. I can successfully invite user `a`. See demo video https://monosnap.com/file/holPWoZqRlG9i9pPTVVOTTtJXmj9Rz.

Do you have any idea what steps should I make to reproduce it?

**Comment by codejamtc** [comment] 2020-04-16 12:04
@maxceem I can't reproduce it either but I will investigate more If I find something I will post here

**Comment by maxceem** [comment] 2020-05-15 13:37
I think this is a duplicate of https://github.com/appirio-tech/connect-app/issues/3828 which cannot be reproduced anymore. So I'm closing this issue also.

Feel free to reopen it if there is anything to be done.

cc @codejamtc

**Closed by maxceem** 2020-05-15 13:37 UTC
Labels: Cannot reproduce, Functional, P4
