### ISSUE TITLE
Add word breaking to dashboard & discussion posts

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#855] opened 2017-03-15 20:23 UTC
Let's add `word-break: break-all` to posts on the project dashboard and discussion threads.

Current:
![screen shot](https://cloud.githubusercontent.com/assets/8484061/23969117/7ce54db8-0982-11e7-99a2-1c14aa4f7466.png)

Expected:
![screen shot 1](https://cloud.githubusercontent.com/assets/8484061/23969124/8494919a-0982-11e7-8cad-810991c63b01.png)

**Comment by sirakovaDimitrina** [comment] 2017-03-16 07:51
@vic-topcoder  I can't reproduce this issue.

**Comment by gondzo** [comment] 2017-06-13 15:32
This one can be reproduced only in first post body, not in the post comments
![image](https://user-images.githubusercontent.com/3051646/27090737-513a05b4-505e-11e7-8704-496349c8d003.png)

**Comment by fnisen** [comment] 2017-07-07 17:53
@sirakovaDimitrina @gondzo is this in Dev? I'm still seeing the problem: 
<img width="775" alt="screen shot 2017-07-07 at 10 52 25 am" src="https://user-images.githubusercontent.com/12552247/27970128-7f2bdf54-6302-11e7-9139-20d77fcfc2c2.png">

**Comment by sirakovaDimitrina** [comment] 2017-07-10 19:12
@fnisen This issue is fixed in the deep-links branch

**Comment by fnisen** [comment] 2017-07-10 19:30
Thanks @sirakovaDimitrina. This one is actually part of messaging update, not the deep-links work. @gondzo can you please move it to test01?

**Comment by gondzo** [comment] 2017-07-10 19:38
Done, should be deployed soon.
@fnisen

**Closed** 2017-07-12 20:10 UTC
Labels: visual styling
