### ISSUE TITLE
P2: Include 'Shared With' Column

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3465] opened 2019-12-24 06:02 UTC
**Objective:** Enable users to quickly identify who the file/link has been shared with, which will aide in identifying the correct document/modifying viewing permissions if necessary.

<p></p>

**Requirements:**

- A 'Shared With' column should be displayed in the assets library.

- Logic Rules:

  - If the file was only shared with specific users, display each user's handle.

  - If the file was shared with all project members, display this text: "All Project Members"

**Comment by ajefts** [comment] 2019-12-24 06:02
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/3182105

**Comment by maxceem** [comment] 2020-01-15 08:33
Everywhere in the Connect App we usually show the full name of users, and only show the use `handle` in the tooltip:

![image](https://user-images.githubusercontent.com/146016/72417815-9dd75f80-37b4-11ea-8dde-fe8f8a734f95.png)

- In the column `Shared With` should show user `handle`s or full names of users?

**Comment by maxceem** [comment] 2020-01-16 04:05
2. I have one concern regarding adding one more column. Currently, we already have not so much space:

    ![image](https://user-images.githubusercontent.com/146016/72492365-e85de800-3857-11ea-9a64-1bda6accd430.png)

   - I guess we cannot make this widget wider, as we use the same width for content on all the pages, it's same for phases, posts, spec and so on 
   - if we add one more column with a list of users, it looks like there would be almost no space for the file name
   - also, we are going to add another column for `tags`
   - to save the space, we can show user `handle` instead of full name in `Created By` column and `Shared With` column, as I think `handle` is usually shorter, than the full name. Though, I'm not sure if it would be enough.

**Comment by vikasrohit** [comment] 2020-01-16 06:34
> In the column Shared With should show user handles or full names of users?

Comms separated handles should be fine for now.

I liked the idea about showing the handle for the `Created By` column, though it is something to be decided by product managers. However, I would like to go with showing handle in `Created By` column for now as we don't have time to get designs for this now and any way we are showing more details on tooltip of the `Created By` column.
For tags, we can avoid adding columns, and instead show the tags just below the file name in the same column. We used this design for project listing page. We can use this kind of grouping for including more information, if required, e.g. we can include created by and created date(if required) in the same column or do grouping of modified by and modified at columns.

On a separate note, there is some misalignment of the column header and the data beneath, can we get that fixed as well?

**Comment by maxceem** [comment] 2020-01-16 11:41
> For tags, we can avoid adding columns, and instead show the tags just below the file name in the same column. We used this design for project listing page. We can use this kind of grouping for including more information, if required, e.g. we can include created by and created date(if required) in the same column or do grouping of modified by and modified at columns.

Regarding such combining of different data in one column, I'm not sure where to put filters in such case, as we have one filter per one column, and if we show `date` and `created by` in one column, how to show the filter in the header then?

If we combine data in columns, then, I guess, we would have to create a separate panel with filters outside of the table like 

![image](https://user-images.githubusercontent.com/146016/72522216-1f53ee00-3898-11ea-8ac7-d6e60a8ed5bc.png)


> On a separate note, there is some misalignment of the column header and the data beneath, can we get that fixed as well?

Sure. Do you mean align everything to the left?

![image](https://user-images.githubusercontent.com/146016/72522075-c1bfa180-3897-11ea-8663-b93b3baee8f8.png)

**Comment by vikasrohit** [comment] 2020-01-16 12:10
<img width="238" alt="Screen Shot 2020-01-16 at 5 38 30 PM" src="https://user-images.githubusercontent.com/2417632/72524043-0c84ed80-3887-11ea-8510-f9070d711b0e.png">
Something like this can be used to combine the filters as well, if needed. I guess, after showing handles instead of full names, we would save some space for shared with columm and we can combined filters like this for name + tags column.

> Sure. Do you mean align everything to the left?

Yes, basically anything (we can try by central align as well) that make the data and its header aligned.

**Comment by nithyaasworld** [comment] 2020-02-26 19:27
@maxceem Few minor issues:

1. When searching with 'All Project', its not listing files shared with 'All Project Members'. But if I search with 'all project' with all letters in small case, it is showing the matching results. Expecting the result to show up regardless of the upper/lower cases.

2. We need to reduce the Tool tip size to fit its content. Its large now.
![image](https://user-images.githubusercontent.com/5114190/75378906-8b475e80-58fa-11ea-9a3f-311f5867262c.png)

3. If the file is shared with more than 3 people, we just show +N where N is the count of the remaining number of people. With this design, there is no way for us to know who is the 4th person the file is shared with. Is this okay for us? CC: @vikasrohit 
![image](https://user-images.githubusercontent.com/5114190/75379662-c6965d00-58fb-11ea-95a5-b59ce05f0b33.png)

**Comment by maxceem** [comment] 2020-02-27 03:56
@nithyaasworld 

1. fixed and pushed to DEV, ready for testing

2. Sometimes the full name can be quite big:

     ![image](https://user-images.githubusercontent.com/146016/75410695-af855880-5957-11ea-8932-2205879d21e6.png)

    also, admin users may see emails:

     ![image](https://user-images.githubusercontent.com/146016/75410744-d2b00800-5957-11ea-81cd-7cac787c9689.png)

     I'm not sure how we should adjust the size. Should it be dynamic per content?

**Comment by vikasrohit** [comment] 2020-03-02 09:25
Closing. Please feel free to create new issues for any regression.

**Closed by vikasrohit** 2020-03-02 09:25 UTC
Labels: 2.5.1, Feedback, P2
