### ISSUE TITLE
Projects are not loading at times

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3703] opened 2020-02-06 21:26 UTC
In Dev env, projects are not loading at times. 

This happened about 3 times since last 1 week. And it started working when I accessed it the next day.

Issue Video:  
[Projects are not loading at times.zip](https://github.com/appirio-tech/connect-app/files/4167794/Projects.are.not.loading.at.times.zip)

Seeing the below error in the console:
![image](https://user-images.githubusercontent.com/5114190/73979738-b7ec0400-4954-11ea-8f85-0675f10ccb8c.png)

**Comment by nithyaasworld** [comment] 2020-02-06 21:30
After about 20 mins, it started working now.

Requesting to look at it as it happens often and affects our testing. Thanks.

**Comment by nithyaasworld** [comment] 2020-02-07 03:49
@vikasrohit is this issue same as this one: https://github.com/appirio-tech/connect-app/issues/2715 ? Thanks.

cc: @maxceem

**Comment by nithyaasworld** [comment] 2020-02-07 03:51
I am seeing this issue very often in Dev Environment today, especially **when using the Admin user.** Highly affecting our testing on Dev Env. 

CC: @lakshmiathreya @SathyaJayabal

**Comment by maxceem** [comment] 2020-02-07 04:20
@nithyaasworld when you next time have this issue, could you please, check on the **Network** tab which of the requests fails.

**Comment by maxceem** [comment] 2020-02-07 04:49
@nithyaasworld I guess from your video that failing request for getting `metadata`.

When the next time it fails, could you please select `GET` request for `metadata` and after click **Timing** on the right and make a screenshot like this:

![image](https://user-images.githubusercontent.com/146016/74001888-2b6b3100-49a8-11ea-88a8-477b789e03a9.png)

**Comment by nithyaasworld** [comment] 2020-02-07 13:00
Thanks @maxceem for checking. I am trying on FF in Private window. 
I am not seeing 'metadata' call. Below are the calls that are made:

![image](https://user-images.githubusercontent.com/5114190/74031422-77819a00-49d7-11ea-9b4a-2f45c0a7dfc2.png)

**Comment by maxceem** [comment] 2020-02-07 13:10
Thanks for the screenshot @nithyaasworld.

The error with `orgConfig` is harmful, it's normal and it shouldn't break anything.

It looks like not all requests are shown on the **Network** which must be there. Could you please try opening **Network** tab first, then clean it if there are any requests, and then hit the **reload** button to reload the page. It should capture all the requests this way and there should be `metadata` request:

![image](https://user-images.githubusercontent.com/146016/74032098-1f09c700-49ee-11ea-9534-1bf210c36f19.png)

**Comment by nithyaasworld** [comment] 2020-02-07 13:58
Thanks @maxceem  Here we go:

![image](https://user-images.githubusercontent.com/5114190/74035301-0a263700-49e0-11ea-91b7-522b1c7a06f4.png)



**Other thing is, its working for me only on Edge browser. With windows FF, Mac Chrome and Mac Safari, its Not working. Tried with the same Admin user in all the browsers!!**

**Comment by maxceem** [comment] 2020-02-07 14:38
Thanks, @nithyaasworld this is what needed.

Hmm, so far it's hard to say what is going on. Could you please make another video as you did initially with the next scenario:
- open **Console** tab
- reload page
- wait until you see in console `Error: timeout 20000ms exceeded`
- wait a little bit more to make sure that nothing is happening anymore
- switch to the **Network** tab
- select request `GET` `metadata` and switch **Timing** tab to make it visible in the video
- also, if you can see any requests that have empty data in `size` column, then please, select them and open the **Timing** tab for them too:

   ![image](https://user-images.githubusercontent.com/146016/74037966-541c1680-49fa-11ea-8f0c-850d16637b88.png)

Btw, I've tried to test in FF with the same `@TCConAdmin` user, and all works well for me. I've tried to reload multiple times but couldn't reproduce the issue so far.

**Comment by nithyaasworld** [comment] 2020-02-07 15:45
Here we go @maxceem 

I also see 'Failed to load notification, timeout error' in the console

Video is quite big, Please fast forward whenever necessary: 
[projects not loading big video.zip](https://github.com/appirio-tech/connect-app/files/4171615/projects.not.loading.big.video.zip)

**Comment by maxceem** [comment] 2020-02-10 02:49
@nithyaasworld the last archive with the video doesn't work for me, I cannot open it and its size is 22 bytes which too small for video.

![image](https://user-images.githubusercontent.com/146016/74117513-dff89300-4bf2-11ea-8f28-f4723313f34d.png)

![image](https://user-images.githubusercontent.com/146016/74117520-e6870a80-4bf2-11ea-96b1-f9efdf5ea6ed.png)

**Comment by nithyaasworld** [comment] 2020-02-10 03:55
Sorry @maxceem Here is the video recorded 2 days back: 
[projects not loading big video.zip](https://github.com/appirio-tech/connect-app/files/4178853/projects.not.loading.big.video.zip)


Thing is, I am not able to reproduce the issue today. **It loads effortlessly!!!!** Also I see no notification error in my console today


Tried by Logged in with the same Admin user in FF Private window.
My console today:
![image](https://user-images.githubusercontent.com/5114190/74119852-2f38c680-4be7-11ea-901f-f0740b44890e.png)

**Comment by nithyaasworld** [comment] 2020-02-10 03:57
**UPDATE:** Notification error is also seen after couple of minutes

![image](https://user-images.githubusercontent.com/5114190/74119935-86d73200-4be7-11ea-844c-91defd8b20df.png)

**Comment by maxceem** [comment] 2020-02-10 04:35
Looks like the issue was with `GET /metadata` request:

![image](https://user-images.githubusercontent.com/146016/74121027-b9d9ef80-4c00-11ea-9ecd-65e96f27a3cc.png)

- only 18kb of 280kb loaded
- it took time close to 20 seconds (which is maximum time we allow for one request)
- on the response tab JSON data cannot be displayed, which most likely caused by the fact that not whole data has been transferred so JSON is broken

But why it happens is hard to say. The strange thing is that waiting time is 11 seconds. Project Service makes a very simple request to ES (read one document by id) which is a very fast operation. Also, at the same time So I doubt this could be caused by Project Service itself.

The two options left in my mind:
- Topcoder Gateway
- Somehow internet route from `nithyaasworld` to AWS server was slow while in general the internet connection stayed fast.

@vikasrohit do we have any way to check if the Topcoder Gateway returned the response fast?

**Comment by nithyaasworld** [comment] 2020-02-10 05:10
@maxceem If it happens again, **is there a way to check the internet-connection speed between my system and the AWS server?** 
One time, @SathyaJayabal also faced this issue at the same time I had this issue. But 2 days back, it was only for me. It worked for @SathyaJayabal.

**Comment by nithyaasworld** [comment] 2020-02-10 05:27
**Update:** It stopped working again. I saw the below in the console. I changed my internet connection to another network and refreshed the page and **it loaded!!!!**

![image](https://user-images.githubusercontent.com/5114190/74123255-226e9f80-4bf4-11ea-9074-09bdcbb485c1.png)

**Comment by maxceem** [comment] 2020-02-10 05:36
> If it happens again, is there a way to check the internet-connection speed between my system and the AWS server?

I don't know such a way, because AWS has many servers and it could be that speed to one server is good, but to another server is bad.

I also sometimes had this issue. And I guess Vikas also. Though usually, it doesn't happen for several people at once. So it feels that issues with the route from a person to AWS which sometimes become too slow in some reason.

**Comment by nithyaasworld** [comment] 2020-02-10 05:46
Thanks @maxceem for checking! 

I changed my internet-connection back to my first-ISP. Now, It is working with that network too. 
So if it happens again to me, I will just disconnect and reconnect my internet.

I am closing this ticket and lets re-open if something needs to be fixed from our side.

**Comment by vikasrohit** [comment] 2020-02-11 09:38
Yes, it happens for me as well and every time it works after I change my network connection to my personal WiFi instead of office network.

**Comment by maxceem** [comment] 2020-02-20 10:05
I come across this issue too now.

Logging some finding in case it could help:

![image](https://user-images.githubusercontent.com/146016/74922052-a18c8080-5409-11ea-9074-b6b7612e4c03.png)

On this image are shown:

- Two requests have very big `TTFB` ~ `16s`:

    ![image](https://user-images.githubusercontent.com/146016/74922092-b23cf680-5409-11ea-9a7f-c1eb2d0886f9.png)

- The same time quite a big image takes around `12s` to be downloaded due to issue https://github.com/appirio-tech/connect-app/issues/3252:

   ![image](https://user-images.githubusercontent.com/146016/74922274-edd7c080-5409-11ea-9580-e245de269eb4.png)

I've fixed the issue https://github.com/appirio-tech/connect-app/issues/3252, so the image became small.

`TTFB` for these requests dropped to `~2-7s`. But when I canceled the fix for the image `TTFB` stays the same, or sometimes goes up to `10s` again. So looks like there is no connection with the image.

Actually, it is expected results and `TTFB` suppose to not depend on other requests at least much.

**Comment by nithyaasworld** [comment] 2020-02-25 08:06
Re-opening again as its happening on production for the end users.

![image](https://user-images.githubusercontent.com/5114190/75227224-cb5ff180-57d3-11ea-80d0-43732b67fa94.png)

**Comment by lakshmiathreya** [comment] 2020-02-28 01:38
@drasticdpk pls verify in Prod and then we can close this.

**Comment by nithyaasworld** [comment] 2020-03-02 04:59
@lakshmiathreya I think no fix has been done to handle this. Should we can change the milestone to 2.8?

CC: @maxceem

**Comment by vikasrohit** [comment] 2020-03-02 11:47
There is no potential fix as of now for us to handle this. This is mostly because of network.

**Comment by drasticdpk** [comment] 2020-03-04 13:03
With reference to @vikasrohit 's comment above I am closing this issue. Let us know for anything. cc @lakshmiathreya

**Closed by drasticdpk** 2020-03-04 13:03 UTC
Labels: Dev Environment, P1, Prod Environment

**Comment by maxceem** [comment] 2020-04-15 08:08
This issue is solved now by removing timeout when making requests from Connect App by https://github.com/appirio-tech/connect-app/pull/3897
