### ISSUE TITLE
TaaS: "Continue where I left off" throws up missing name error 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3254] opened 2019-08-09 11:24 UTC
### Expected behavior
Should save Project details successfully via the 'Continue where I left off' option.

### Actual behavior
Throws up missing name error.

### Steps to reproduce the problem
---> Go to https://connect.topcoder-dev.com/new-project/
-- Select TaaS Project
-- Fill in Project details 
-- Now go back to Connect home - click on 'New Project'
-- Click on 'Continue where I left off"
-- The previously filled out form is presented
-- Click on Save 
-- Throws up a 500 error with an error message that Name is missing. Not that Name is mandatory - so Name is present in Project details previously filled.

---> Also, in the final screen, Name is missing - Name field needs to be present there.

### Screenshot/screencast
Attach or link a resource.

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by RishiRajSahu** [comment] 2019-08-20 12:27
@lakshmiathreya unable to reproduce it since then, could you please check it again ? also 
>Also, in the final screen, Name is missing - Name field needs to be present there.

Name field is present on the top of the form in final screen.

**Comment by maxceem** [comment] 2019-09-10 09:08
I've also tried to follow the proposed steps but cannot reproduce it.

**Comment by RishiRajSahu** [comment] 2019-09-10 10:21
Closing the ticket as not reproducible.

**Closed by RishiRajSahu** 2019-09-10 10:21 UTC
Labels: Cannot reproduce
