### ISSUE TITLE
Application is blocked when try to sort column

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#385] opened 2016-09-30 07:26 UTC
Expected behavior
------------------------------------------------------------

- Display data records.

Actual behavior
------------------------------------------------------------

- The app is blocked when try to sort.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager.

- Search "other work" text.

- Press on Price column name to sort.

Environment
------------------------------------------------------------
Operating System(s): Windows 7 Professional / 64 bit
Browser(s):  IE 11.0
User role: connect user role
Account used: christina_uw

![blocked](https://cloud.githubusercontent.com/assets/5114907/18983927/58bc5b00-86f8-11e6-8dd5-8103c46ecf43.png)

**Comment by mahestro** [comment] 2016-10-04 16:56
Duplicate of #182

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
