### ISSUE TITLE
Can create duplicate 'Custom Features' with the same name

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#425] opened 2016-10-01 17:07 UTC
### Expected behavior
-----------------------------------------------------------------
Must validate the same 'Custom Feature Names'

### Actual behavior
-----------------------------------------------------------------
Can create duplicate 'Custom Features' with the same name

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Enter name
- eg: Lorem ipsum
- Click Save Feature
- Click 'Add a custom feature'
- Enter name
- eg: Lorem ipsum
- Click Save Feature
- Check the List

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_22-37-00](https://cloud.githubusercontent.com/assets/4592712/19015733/9763aa18-8827-11e6-9096-ac1cbe56fc3a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 19:25
Duplicate of #261

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
