### ISSUE TITLE
[Dashboard] - infinite loading when set a filter

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#315] opened 2016-09-29 06:59 UTC
Expected behavior
------------------------------------------------------------

-  Do not display infinite loading.

Actual behavior
------------------------------------------------------------

- Infinite loading in displayed.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as manager.

- From Dashboard complete search field with "Test".

- Press enter to search.

- Expand Filters and select Status=Paused.

- Observe no data loaded.

- Press on "ID" column name.

Environment

------------------------------------------------------------

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2 
            IE 11.0
User role: manager
Account used: pat_monahan

![1](https://cloud.githubusercontent.com/assets/5114907/18943942/532e81a4-862b-11e6-9322-7851ea3d92ec.png)

![2](https://cloud.githubusercontent.com/assets/5114907/18943945/58ef508c-862b-11e6-9d21-264ad119f426.png)

**Comment by mahestro** [comment] 2016-10-04 12:31
Duplicate of #182

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
