### ISSUE TITLE
P1: Update Internal Catalog Display

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3513] opened 2020-01-24 11:19 UTC
**Objective:** Improve the presentation of the internal Connect catalog for work options.

<p></p>

**Requirements:**

Designs - https://marvelapp.com/cc9e4j1/screen/62801529

- All 3 screens of the Connect catalog will require updates to UI and content, including:

  - Screen 1: Solutions vs. On Demand options

  - Screen 2: Full List of Solution Options

  - Screen 3: Full List of On Demand options (TaaS/Capacity)

- Screens 2 & 3 will include substantial UI design updates, with new content displayed for:

  - Solution Description

  - Solution Deliverables

  - A link to a case study on the website

  - A 'select' button

**Comment by ajefts** [comment] 2020-01-24 11:19
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2851875

**Comment by maxceem** [comment] 2020-01-29 02:24
Here we have to do the next final fixes:
1. Increase icons size to take the same space as on new design https://marvelapp.com/cc9e4j1/screen/65344038/handoff and https://marvelapp.com/cc9e4j1/screen/65344039. So icons should have size up to 79px x 79px. We want to achieve the same sizing of the cards as in design.
2. Add font mixins https://fonts.google.com/specimen/Roboto+Condensed to the https://github.com/appirio-tech/connect-app/blob/414027e3fcee24061943ef5e5062d03828426929/src/styles/_fonts.scss with all 6 variations (light, regular, bold + italic) and select these languages, while adding font files to "src/fonts/roboto-condensed". To create fonts in all required formats eot/svg/ttf/woff you may use service https://www.fontsquirrel.com/tools/webfont-generator.
3. After font mixings are there update styles of all the headers that use Roboto-Condensed to match the design:
    - https://monosnap.com/file/LZxAP1rEJksnFZNX9y58jSGkJtrdP2
    - https://monosnap.com/file/y0vkVnldB82LavGFhVIUf1jhTGxzO0
    - as we don't have Roboto-Condensed Medium font-weight, use Regular or Bold depend on which one looks closer to design.

**Comment by maxceem** [comment] 2020-01-29 02:27
@vikasrohit after increasing icon size to 79px as per design it looks like this:

![image](https://user-images.githubusercontent.com/146016/73323236-bb5efb80-4281-11ea-8a74-06e26d69abd2.png)

![image](https://user-images.githubusercontent.com/146016/73323248-c74abd80-4281-11ea-8143-9f15901cd1e2.png)

I guess we should not increase the icon size and just make space around icons similar to the design but without color. What do you think?

**Comment by maxceem** [comment] 2020-01-29 03:09
For now, all [final fixes](https://github.com/appirio-tech/connect-app/issues/3513#issuecomment-579563326) are done and pushed to DEV as per current requirements.

**Comment by vikasrohit** [comment] 2020-01-29 07:14
Thanks @maxceem. I liked the increased icons on the first step but yes, on the second step they are looking bit odd. I even tried to create that weird oval shape around the icons, using the css shared by the designers, but not able to create that exactly. What kind of space around icons, you are thinking we can create?

**Comment by maxceem** [comment] 2020-01-29 09:17
> What kind of space around icons, you are thinking we can create?

I mean to keep the icon size as it was before. But just add white space around. Actually to make it the same as in design, but without a stylish background, so instead of the background, there would be just a white space.

**Comment by vikasrohit** [comment] 2020-01-29 09:54
Ohk, that is what we had before increasing the size of the icons, right?

I found an svg, which has similar shape, from marketing website. I have modified the colors to match something from our current palette. Let me know if we can use this.
```
<svg width="79px" height="70px" viewBox="0 0 79 70" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
                <defs>
                  <linearGradient x1="50%" y1="4.84564022%" x2="70.3177409%" y2="89.2565294%" id="linearGradient-2">
                    <stop stop-color="#0B71E6" offset="0%"></stop>
                    <stop stop-color="#26ADE9" offset="100%"></stop>
                  </linearGradient>
                </defs>
                <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                  <g transform="translate(-681.000000, -1700.000000)" fill="url(#linearGradient-2)">
                    <path d="M718.54015,1770 C745.222539,1770 756.340201,1748 759.675499,1729 C763.010798,1710 740.030553,1700 718.54015,1700 C697.049748,1700 674.069503,1710 682.963632,1735 C691.857762,1760 691.857762,1770 718.54015,1770 Z" id="Oval-Copy-5"></path>
                  </g>
                </g>
              </svg>
```

**Comment by maxceem** [comment] 2020-01-30 04:04
@vikasrohit it's done using this BG and pushed to dev, looks good to me!

![image](https://user-images.githubusercontent.com/146016/73418970-6f32ba80-4358-11ea-9222-4051aa72ac35.png)

![image](https://user-images.githubusercontent.com/146016/73418984-7b1e7c80-4358-11ea-8fc7-897f75fc0c13.png)

**Comment by vikasrohit** [comment] 2020-01-30 05:40
Awesome, looking good to me.

**Comment by vikasrohit** [comment] 2020-01-30 05:41
We are delaying the release by one week, so we can update the icons themselves now as well.

**Comment by maxceem** [comment] 2020-01-30 05:52
Sure, we can get their SVG from marvel. Looks like we have only 3 kinds of icons in the new design:

2 different for categories:

![image](https://user-images.githubusercontent.com/146016/73423624-a2c91100-4367-11ea-986a-8484bfc2571a.png)

And the same icon for all kind of projects:

![image](https://user-images.githubusercontent.com/146016/73423642-b07e9680-4367-11ea-822d-28d7a9ece4d4.png)

Should we do this? All projects have the same icon?

**Comment by vikasrohit** [comment] 2020-01-30 06:31
I guess that is better for us for now. Even many of templates right now are using default icons instead of specific ones. Having common icon for all project templates, would make our life easier. Go with that.

**Comment by maxceem** [comment] 2020-01-31 02:11
@vikasrohit would you prefer that we add a new icon and update all the ProjectTemplates to use it? Or should we just hardcode it for ProjectTemplate cards for now?

For ProjectTypes, we for sure would add new icon types and update data to use them.

**Comment by maxceem** [comment] 2020-01-31 02:32
@vikasrohit is it possible to obtain the wave from the design in SVG format

![image](https://user-images.githubusercontent.com/146016/73507761-eded2d80-4414-11ea-8761-e9ef472cdef2.png)

So far we are using a temporary PNG file, which has a few drawbacks.

**Comment by vikasrohit** [comment] 2020-02-03 07:20
I think, it would be better to replace the icons to all project templates as well to be sure that we have applied everything from the designs except the green theme. we can update the individual icons later if they are required to to be different.
Were you not able to find the wave svg from the handoff?

**Comment by maxceem** [comment] 2020-02-03 09:12
> I think, it would be better to replace the icons to all project templates as well to be sure that we have applied everything from the designs except the green theme. we can update the individual icons later if they are required to to be different.

Should we remove old icons from the repo? If we can remove them, then we don't have to update all the ProjectTemplates in DB. We can just remove old icons from the repo, and update the default icon, so all the Project Template would fallback to the default icon with whatever data they have.

> Were you not able to find the wave svg from the handoff?

No, I could not find the wave in the handoff. It just shows the background color, if I select the wave in handoff 

![image](https://user-images.githubusercontent.com/146016/73639941-50aa2780-46a8-11ea-8501-8e7ef5413507.png)

**Comment by vikasrohit** [comment] 2020-02-03 09:24
> Should we remove old icons from the repo? If we can remove them, then we don't have to update all the ProjectTemplates in DB. We can just remove old icons from the repo, and update the default icon, so all the Project Template would fallback to the default icon with whatever data they have.

Yes, I liked that. That way we can add the new icons as and when we need separate icons per project template. However, I would like to move the existing icons to a separate folder for now instead of deleting them.

For the wave image, I have asked the designer, lets see what we can get from him. I tried to generate/copy one from marketing site, but they are also using the png.

**Comment by maxceem** [comment] 2020-02-05 02:24
Sum up:
1. Replace the wave with SVG file [svg-curve.zip](https://github.com/appirio-tech/connect-app/files/4157076/svg-curve.zip) and remove current PNG file

2. In the new design of catalog we have new icons for project type cards https://marvelapp.com/cc9e4j1/screen/65344038/handoff and one new common default icon for projects https://marvelapp.com/cc9e4j1/screen/65344039/handoff. So we have to use them in a new catalog.

    These icons are shown using [ProjectTypeIcon](https://github.com/appirio-tech/connect-app/blob/dev/src/components/ProjectTypeIcon.jsx#L43) component. As we don't want to support old icon anymore we should:
     - remove all currently supported icons from `ProjectTypeIcon` component, but don't remove icon files
     -  add 2 new icon types to `ProjectTypeIcon` component:
        - `project-type-solutions`
        - `project-type-talent-as-a-service`
        - add for them corresponding icons from https://marvelapp.com/cc9e4j1/screen/65344038/handoff
        - put icon files to the forlder `src/assets/icons/v.2.5`.
     - as a [default](https://github.com/appirio-tech/connect-app/blob/dev/src/components/ProjectTypeIcon.jsx#L117) icon use a new icon from https://marvelapp.com/cc9e4j1/screen/65344039/handoff.
    - as a result for such changes our catalog icons should look the same as in designs on https://marvelapp.com/cc9e4j1/screen/65344038/handoff and https://marvelapp.com/cc9e4j1/screen/65344040/handoff

3. Move existent icon `connect-app/src/assets/icons/oval.svg` to folder `src/assets/icons/v.2.5`

**Comment by yoution** [comment] 2020-02-05 07:30
@maxceem  please review https://github.com/appirio-tech/connect-app/pull/3696

**Comment by maxceem** [comment] 2020-02-06 05:55
@vikasrohit we've replaced the icons during project creation:

![image](https://user-images.githubusercontent.com/146016/73909632-1cbd4500-48e8-11ea-9a7a-fc73c74409f4.png)

Though there is one side effect. By logic we should show the same icons for projects when we list on the Project Listing Page:

![image](https://user-images.githubusercontent.com/146016/73909660-32326f00-48e8-11ea-8e09-9753c634c35d.png)

Though as Icons are white we cannot see them now. I guess adding the same stylish background on the project listing page would take too big space for icons. Do you have any suggestions on how to deal with it?

**Comment by maxceem** [comment] 2020-02-06 05:58
Also, I would like to note, that for products (phases) we keep the old icons:

![image](https://user-images.githubusercontent.com/146016/73909887-bbe23c80-48e8-11ea-977c-b1efe53567a7.png)

![image](https://user-images.githubusercontent.com/146016/73909905-c4d30e00-48e8-11ea-9fdf-211c96e256aa.png)

**Comment by vikasrohit** [comment] 2020-02-06 06:14
For phases, I am okay with current icons as they are more specific to the deliverables.

For project listing page, I think sooner or later, we have to use separate icons for each different project template, so for now we can apply the same strategy here by defaulting to the new icon because the actual icon does not exist and later we can keep on adding specific icons of the project templates, and it would automatically update the icons.

**Comment by maxceem** [comment] 2020-02-06 06:18
Yep, we already show the defaul icons on the project listing page. But the color of the icons is white so it's hard to see them:

![image](https://user-images.githubusercontent.com/146016/73910799-55125280-48eb-11ea-8f3d-6e979583e2cc.png)

So the question is how to show new icons on the project listing page?

1. Add the stylish background as on new project catalog page? But the background is quite big, so such icons would take too big space here.

2. Change the color of them? To which?

**Comment by vikasrohit** [comment] 2020-02-06 06:36
I guess the second option is good for now:

<img width="360" alt="Screen Shot 2020-02-06 at 12 05 43 PM" src="https://user-images.githubusercontent.com/2417632/73911847-078cea00-48d9-11ea-9033-e7c647e59394.png">

**Comment by maxceem** [comment] 2020-02-06 10:26
Done

![image](https://user-images.githubusercontent.com/146016/73928452-13df6a00-490e-11ea-8318-73206e845e7d.png)

@vikasrohit so far from my side everything is done for this task.

**Comment by vikasrohit** [comment] 2020-02-06 12:13
Agreed. Thanks.

**Comment by maxceem** [comment] 2020-02-22 04:03
@vikasrohit fyi, marked this as ready for QA.

**Comment by nithyaasworld** [comment] 2020-02-26 06:43
@maxceem Can you please check these issues too as part of this ticket: https://github.com/appirio-tech/connect-app/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3ABugHunt_JanRelease+label%3Ap2

**Comment by maxceem** [comment] 2020-02-27 03:12
@nithyaasworld I've checked out these issues. Some of them are valid, but they are not caused by the redesign we did here. In this redesign, we only updated the view of selecting categories and selecting projects, while the form stays as it is without changes.

I would suggest treating these new found issues separately from this task.

**Comment by lakshmiathreya** [comment] 2020-02-28 01:35
@drasticdpk - this is the major feature of yesterday's release. We can close it after we wait for a day or so for Copilots feedback from Prod. You can do an overall Prod test too.

**Comment by vikasrohit** [comment] 2020-03-02 07:28
Closing the issue for cleanup. Please feel free to create separate regression issues.

**Closed by vikasrohit** 2020-03-02 07:28 UTC
Labels: P1, QA Pass in Dev, enhancement
