### ISSUE TITLE
[$40] Editing existing file title changes another file title

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2938] opened 2019-04-08 07:13 UTC
### Expected behavior
When we edit the title of the second file we should change the title of that file.

### Actual behavior
When we edit the title of the second file we change the title of the first file instead.

### Steps to reproduce the problem
- Use `pshah_manger` user create a new `App` project https://connect.topcoder-dev.com/new-project/app
- Upload file 1
- Upload file 2
- Change the title of file 1
- you would see that instead of changing the file 1 it would change the title of file 2.

### Screenshot/screencast
https://monosnap.com/file/tPHWX6OkvCipCGABeKXOiKwheQJJVK

This issues may have the same root as this one https://github.com/appirio-tech/connect-app/issues/2878

**Comment by mfikria** [comment] 2019-04-11 05:29
@maxceem is this ticket open for public?

**Comment by maxceem** [comment] 2019-04-11 05:30
Yes, it's open for everyone to pick up as a part of this Bug Bash challenge https://www.topcoder.com/challenges/30088391

Please, check the rules if you'd like to part.

**Comment by mfikria** [comment] 2019-04-11 05:32
@maxceem okay i take this one

**Comment by maxceem** [comment] 2019-04-11 05:34
@mfikria it's on you since you commented as per our Bug Bash rules. To keep it clear I can assign you to this issue in the UI. For this, please accept the invitation to this repository which you should get to your email.

**Comment by mfikria** [comment] 2019-04-11 08:43
@maxceem resolved in https://github.com/appirio-tech/connect-app/pull/2942. The problem is when editing the attachment it refers to the index instead to the attachment id

**Comment by mfikria** [comment] 2019-04-11 08:54
Note that i try this with local api-backend because i've got error when use https://api.topcoder-dev.com/v4/projects/ https://monosnap.com/file/vmcmjMnSXeDG7FRJ8UtnbQrchap0CO seems something's wrong with dev elasticsearch

**Comment by maxceem** [comment] 2019-04-11 08:57
@mfikria great! thank you for using local deployment. We are aware of the issue with Project Service and trying to get it back as soon as possible.

**Comment by RishiRajSahu** [comment] 2019-04-22 07:15
Working fine in dev. Closing.

**Closed by RishiRajSahu** 2019-04-22 07:15 UTC
Labels: ACCEPTED, CF-16, PAID
