### ISSUE TITLE
Phase posting functionality for Development Integration product

### ISSUE THREAD

**Issue by rmjmccormick** [appirio-tech/connect-app#2194] opened 2018-07-13 12:51 UTC
Posting functionality in a development integration phase seems to have been disabled?

![image](https://user-images.githubusercontent.com/39598852/42692488-2d619f00-86ac-11e8-8a70-fbc72f39d91b.png)

**Comment by rmjmccormick** [comment] 2018-07-16 14:51
@RishiRajSahu OK - understood. It's not a great UX for those customers this might affect though - how long would it take to correct in the backend? Thanks.

**Comment by vikasrohit** [comment] 2018-07-17 09:07
@rmjmccormick I know it is not a good UX for customers, but I don't think it should be occurring every other time a phase is added to the project. To me it seems like it is happening occasionally and all I am saying is that we can handle this just like we are handling issues in creating direct projects where we are asking users to log a ticket in the support.
We are still trying to find out the root cause of the issue. I would be able to devote more time to it once we have the release out and things are settled around it.

**Comment by rmjmccormick** [comment] 2018-07-17 10:01
@RishiRajSahu Thanks for clarifying! That's fine.

**Comment by RishiRajSahu** [comment] 2018-08-28 07:31
This issue seems to be fixed in the recent release and is no more occurring.

**Closed by RishiRajSahu** 2018-08-28 07:31 UTC
