### ISSUE TITLE
on adding blank link , validation message should displayed 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#310] opened 2016-09-29 05:46 UTC
### Expected behavior
on adding blank link validation message should displayed or Add link button should be displayed 

### Actual behavior\
clicking on Add link button nothing happen 

### Steps to reproduce the problem
1. Open the application
2. LOgin with user name sweta.singh
3. create new project
4. go to dashboard page
5. go to add link
6. add blank link 

### Screenshot/screencast
![image](https://cloud.githubusercontent.com/assets/16131461/18942324/d4941d8a-8635-11e6-8e92-5a7a7026da67.png)

--

#### Environment
- OS: Windows 7
- Browser (w/version): Chrome latest 
- User role (client, copilot or manager):
- Account used:

**Comment by mahestro** [comment] 2016-10-04 12:12
Validation issue duplicate of #219.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
