### ISSUE TITLE
[$50] Hide dismissed notifications without waiting for server response 

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2649] opened 2018-10-23 06:42 UTC
Follow up from https://github.com/appirio-tech/connect-app/issues/2607#issuecomment-429810521

To make it looks smoother we have to additionally implement `hide notification without waiting for the end of server request (if it fails we can show red alert popup and show notification back)`
For consistency, we have to implement it for cases when we show animation and we don't show animation:
1. Notifications dropdown: mark one notification as read
2. Notifications dropdown: mark all notifications as read
3. [Notifications page](http://local.topcoder-dev.com:3000/notifications): mark one notification as read
4. [Notifications page](http://local.topcoder-dev.com:3000/notifications): mark all notifications of one project as read

Implementation thoughts:
- we will need to save data to the Redux store about notifications which are preliminarily marked as read, and based on that data hide notifications in Dropdown and Notifications page
   1. maybe we can add some additional property to notifications objects in Redux store to keep track of preliminary read notifications, this will require updating existent componets so they will hide such notifications with this property
   2. or we can directly change `read` property of notifications in the redux store as they are really already `read` and in `FAILURE` action we can revert value for `read` property. This is possible as inside action unction we know the whole list of notification to mark, so we can pass this whole list to the `PEDNING`, `SUCCESS` and `FAILURE` actions as we dispatch them all inside one function https://github.com/appirio-tech/connect-app/blob/dev/src/routes/notifications/actions/index.js#L50. In this case we don't have to update other code I think. But theoretically it could affect other code which could detect such cases as `new unread notiifcations arrive`.

**Comment by maxceem** [comment] 2018-10-23 06:43
@RishiRajSahu here is the answer to your question:

> @maxceem first to understand it, so your point is if we toggle read state of notification again in case of failure from backend it will have effect on other components as treating them as new notifications, right ? and using approach 1 we can avoid it, right ?

yes, that's right, though for now I think we don't have such cases, but theoretically it's possbile to add code like this:
```
componentWillReceiveProps(nextProps) {
   if (_.filter(this.props.notifications, 'read').length === 0 && _.filter(nextProps.notifications, 'read').length > 0) {
      // do something in case there are new unread notifications appears
   }
}
```

> what are the other components sharing the notifications with notification drop-down ?
- Notification page
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/PostsRefreshPrompt/PostsRefreshPrompt.jsx
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/components/ProjectStage.jsx
- https://github.com/appirio-tech/connect-app/blob/dev/src/projects/detail/containers/DashboardContainer.jsx

**Comment by maxceem** [comment] 2018-10-25 03:03
@RishiRajSahu on the second thoughts I think we can try here with the second way `ii.`. As we currently **don't have** any place which will be broken in such case. And it feels kind of natural, and all existent code will work with such an approach without the necessity of any additional changes.

Let me know what you think. If we agree on this, I'll try to accomplish it fast so we can merge it with dependant issue https://github.com/appirio-tech/connect-app/pull/2653

**Comment by RishiRajSahu** [comment] 2018-10-29 12:29
@maxceem yeah as per me we can go with approach II, as approach I don't see any major difference between I and II, also I requires more refactoring and redundant kind of code.
Also, below should be the behaviour -
1.Marking notification read should have same impact on all the components
2.Failure from server should have same impact on all the components

I don't what was the thought process behind approach I, were you trying to avoid re-rendering of dependent components via approach I ? anyway, I am biased to approach II.

**Comment by maxceem** [comment] 2019-01-17 03:51
> don't know what was the thought process behind approach I, were you trying to avoid re-rendering of dependent components via approach I ?

I wanted to have more control in case for some functionality it's important to know if notifications are marked as `read` for real or just temporary during the server request. But I think there is no code which needs to know it so far. 

So we can go with the way `II`.

We have several actions which mark notifications as `read` and all of them should support applying making notifications read without waiting for server response. 
And revert back if response failed together with showing error message (I think error message is already there).

- https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/routes/notifications/actions/index.js#L55
- https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/routes/notifications/actions/index.js#L79
- https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/routes/notifications/actions/index.js#L94
- https://github.com/appirio-tech/connect-app/blob/feature/account-settings-improvements/src/routes/notifications/actions/index.js#L153

**Comment by khushimehta03** [comment] 2019-01-22 02:39
@maxceem i would like to work on this.

**Comment by maxceem** [comment] 2019-01-22 02:40
Sure, it's on you.

**Comment by maxceem** [comment] 2019-01-22 16:00
As no PR was provided for 12 hours, this issue is now open for pick up.
The one who first comments can start working immediately without waiting to be assigned.

**Comment by kiranmaroju** [comment] 2019-01-22 18:21
Please assign to me. I starting it now.

**Comment by maxceem** [comment] 2019-01-23 08:01
Thank you for update @amitpatra. So this issue is open for pick up.

**Comment by KevinLeigh** [comment] 2019-01-23 09:43
Hey @maxceem, please could you assign this ticket to me?

**Comment by maxceem** [comment] 2019-01-23 09:59
@KevinLeigh sure, done.

**Comment by KevinLeigh** [comment] 2019-01-23 10:04
@maxceem Thank you, much appreciated

**Comment by KevinLeigh** [comment] 2019-01-23 16:42
Hey @maxceem, 

I am currently catching up with what has been mentioned in comments and PR description now and as far as I can gather, the goal of this ticket is one to one with what the title says.

Basically we should hide notification _immediately_ when User clicks notification read button and if the server request for some reason, then we should show the notification again in the notifications drawer list?

**Comment by KevinLeigh** [comment] 2019-01-23 17:12
@maxceem 

Any idea what the cause of issue is below:
```
/connect-app/config/webpack/development.js:45
combinedConfig.entry.main = combinedConfig.entry.main.filter((entry) => (
                                                      ^

TypeError: Cannot read property 'filter' of undefined
    at Object.<anonymous> (/home/kavin/Desktop/Projects/connect-app/config/webpack/development.js:45:55)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:585:17)
    at require (internal/module.js:11:18)
    at buildConfig (/home/kavin/Desktop/Projects/connect-app/webpack.config.js:10:25)
    at handleFunction (/home/kavin/Desktop/Projects/connect-app/node_modules/webpack/lib/prepareOptions.js:26:13)
    at prepareOptions (/home/kavin/Desktop/Projects/connect-app/node_modules/webpack/lib/prepareOptions.js:11:13)
    at requireConfig (/home/kavin/Desktop/Projects/connect-app/node_modules/webpack/bin/convert-argv.js:98:14)
    at /home/kavin/Desktop/Projects/connect-app/node_modules/webpack/bin/convert-argv.js:104:17
    at Array.forEach (<anonymous>)
    at module.exports (/home/kavin/Desktop/Projects/connect-app/node_modules/webpack/bin/convert-argv.js:102:15)
    at yargs.parse (/home/kavin/Desktop/Projects/connect-app/node_modules/webpack/bin/webpack.js:171:41)
```

**Comment by KevinLeigh** [comment] 2019-01-23 18:08
@maxceem Please see below GIF below on UX behaviour currently without code changes.

When I click some notifications the notifications dropdown closes and if I click to see notifications it does not work and shows a small white diamond shape instead. I am busy making changes however this issue is effecting my workflow to test if changes I make work properly. Please advise

![weird_notifications_ux](https://user-images.githubusercontent.com/32452072/51627275-4e1bda80-1f4a-11e9-8627-2dda1a9b86c4.gif)

**Comment by KevinLeigh** [comment] 2019-01-23 19:15
Hey @maxceem, I have made the neccessary changes apart from bug I found in above comment, it looks like screen recording attached on comment https://github.com/appirio-tech/connect-app/issues/2607#issuecomment-429810521, is out-dated, and changes between now and Oct 2018 last year has effected how Dashboard notification drawer opens/closes when User clicks notification read/tick button.

**Comment by maxceem** [comment] 2019-01-24 12:11
@KevinLeigh I've reviewed your PR, please have a look https://github.com/appirio-tech/connect-app/pull/2779#pullrequestreview-195995394. Let me know if you have any questions.

**Comment by KevinLeigh** [comment] 2019-01-24 15:42
Hey @maxceem, will have a look at the review now, and update accordingly, thank you for the input. Will let you know if I have any questions.

**Comment by KevinLeigh** [comment] 2019-01-24 16:43
Hey @maxceem, I have updated PR, please let me know if all is in order or if I am missing anything and will be happy to update accordingly.

**Comment by maxceem** [comment] 2019-01-30 02:32
Hi @KevinLeigh, I still need your Topcoder handle to proceed the payment ;-)

**Closed** 2019-02-13 06:49 UTC
Labels: ACCEPTED, CF-14, PAID
