### ISSUE TITLE
[$20] Align design links correctly for design related milestones

### ISSUE THREAD

**Issue by RishiRajSahu** [appirio-tech/connect-app#2482] opened 2018-09-07 09:55 UTC
Design links URL should be aligned to the right and 30px from the widest text element design link name. Right now the checkpoint and final design links URL are not uniform (they should).

![screen shot 2018-09-07 at 3 23 44 pm](https://user-images.githubusercontent.com/11248478/45212245-09044e00-b2b2-11e8-8a2b-8150545d4e5f.png)

Continued from - https://github.com/appirio-tech/connect-app/issues/2301

**Comment by Gauravseta** [comment] 2018-09-08 06:39
@maxceem any tentative date/time when challenge will start? also how can simran assign it to itself while it is not open for pickup? can you please see into it @gondzo

**Comment by maxceem** [comment] 2018-09-08 06:43
@Gauravseta it has to start in several hours, but there is one blocker to be resolved first.

@simranb86 please, don't pick up issues yet, as it's not marked as `OPEN FOR PICK UP` yet.

But I've learned the lesson. Will remove prices until the challenge is started.

**Comment by Gauravseta** [comment] 2018-09-08 06:48
@maxceem there are very few people like simran . else it is never an issue to mark the prices it title. can you please unassign simran if possible? as someoneelse or myself should get equal chance of grabbing this issue. thanks

**Comment by maxceem** [comment] 2018-09-08 06:52
@Gauravseta sure

@simranb86 I have to unassign you from the issue so far to keep it fair for all the participants. Please, grab only the issues marked as `OPEN FOR PICK UP`. I'll let you know as soon challenge started and issues are ready for pick up. I'm still happy that you are interested to participate :-)

**Comment by maxceem** [comment] 2018-09-08 14:18
@Gauravseta, @simranb86  just want to let you know that challenge is planned to be started on Monday. The Bug Bash process will be slightly changed.

**Comment by simranb86** [comment] 2018-09-08 22:10
@maxceem Thanks for the update. I picked up because i was enrolled in bug bash already and saw the new tickets come up with pricing on them. Next time i will look for `OPEN FOR PICKUP` tag too. 

Will register for new one when it opens. Thanks

**Comment by maxceem** [comment] 2018-09-10 02:07
@Gauravseta, @simranb86 The challenge is on. 
**Important!** There is a change in the Bug Bash process, please read the new rules in the challenge spec carefully, before starting work on issue https://www.topcoder.com/challenges/30070926/?type=develop&noncache=true 
Thank you!

**Comment by iversonLv** [comment] 2018-09-10 02:10
Please assign this to me

**Comment by iversonLv** [comment] 2018-09-10 02:31
Could I know what password/username to login?

Thanks.

**Comment by maxceem** [comment] 2018-09-10 02:34
`pshah_manager`/`topcoder123`

**Comment by iversonLv** [comment] 2018-09-10 03:45
It’s done and ready for review

**Comment by RishiRajSahu** [comment] 2018-09-12 04:59
@maxceem Yes as per the requirement both milestones should have consistent alignment of links. Didn't got why it will need javascript for that ?

**Comment by maxceem** [comment] 2018-09-12 05:16
@RishiRajSahu What I mean if these milestones have to be aligned between each other, see screenshot

![align](https://user-images.githubusercontent.com/146016/45403570-c2d23480-b68d-11e8-95b4-8cb315bbea9b.png)

While we can align links inside one milestone using CSS only, I think we cannot do that without JS to align links between two different milestones.

**Comment by RishiRajSahu** [comment] 2018-09-12 06:12
@maxceem so there are few things which i have noted 
- They are two different components used at each places
- Possible way to solve this is by either making two components as similar as possible using styling
- Even after making them similar by using styling there will be an issue when title length is more
- We can use ellipses for long title name if length exceeds beyond the space

**Comment by maxceem** [comment] 2018-09-12 10:44
@iversonLv There is a couple of edge cases left, please have a look https://github.com/appirio-tech/connect-app/pull/2486#pullrequestreview-154586156.

**Comment by maxceem** [comment] 2018-09-13 05:52
@RishiRajSahu the issue is fixed as per requirements and PR is merged. The output looks like this fyi:

![image](https://user-images.githubusercontent.com/146016/45469460-36427780-b75c-11e8-8a3c-f438644f3ff6.png)

**Comment by RishiRajSahu** [comment] 2018-09-13 06:03
@maxceem yeah looks good !

**Closed** 2018-09-19 05:30 UTC
Labels: ACCEPTED, CF-12
