### ISSUE TITLE
Add A New Phase: Header Breaking in Firefox

### ISSUE THREAD

**Issue by coderhacker** [appirio-tech/connect-app#3915] opened 2020-04-16 04:31 UTC
### Expected behavior
The header should be properly visible in all browsers.
### Actual behavior
The header is breaking for Add a New Phase.

### Steps to reproduce the problem
Step 1- go to URL https://connect.topcoder-dev.com.
Step 2- Login with user : topcoderconnect+CopilotManager/appirio123.
Step 2- And go to https://connect.topcoder-dev.com/projects/9095/ and click **Add New Phase** button.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/62358241/79414646-cc89ef80-7fc8-11ea-8794-7c4a0917485d.png)

--

#### Environment
- OS: Windows 10
- Browser (w/version): Firefox (Latest Version)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+CopilotManager

**Comment by maxceem** [comment] 2020-04-16 06:39
@coderhacker this looks like a duplicate of https://github.com/appirio-tech/connect-app/issues/3915

**Comment by coderhacker** [comment] 2020-04-16 07:01
@maxceem could you please share another id for verifying. I am unable to find out. after verify I will close this issue.

**Comment by maxceem** [comment] 2020-04-16 07:04
Ah, sorry @coderhacker. I've fixed the comment above, here is the issue https://github.com/appirio-tech/connect-app/issues/3576

**Comment by coderhacker** [comment] 2020-04-16 07:10
@maxceem I have seen #3576, but observed that this is raised for only Chrome, could you please tag this issue #3915 for cross-browser fixing. Once #3576 will fix, I will verify and will close #3915. 
Please suggest.

**Comment by maxceem** [comment] 2020-04-16 07:19
> could you please tag this issue #3915 for cross-browser fixing

sure, how to do it? I'm not sure what you mean.

**Comment by coderhacker** [comment] 2020-04-16 07:26
@maxceem: I would suggest leave this issue #3915 in open status. Once #3576 will fix. I will verify all browsers for #3576 and will close #3915 accordingly. I hope this fine for you.

**Comment by maxceem** [comment] 2020-04-16 07:28
Yep, sounds good!

**Comment by lakshmiathreya** [comment] 2020-05-28 09:39
<img width="1617" alt="Screenshot 2020-05-28 at 3 08 16 PM" src="https://user-images.githubusercontent.com/51733042/83125458-2ec02f00-a0f5-11ea-81b4-5bd58b1a49af.png">

**Closed** 2020-05-31 04:36 UTC
Labels: Cross-Browser {Firefox}, Dev Environment, P2, QA Pass in Dev, QA Pass in Prod, UI
