### ISSUE TITLE
[$10] Billing Accounts: Displayed Data Enhancements

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4300] opened 2021-02-17 20:58 UTC
For all returned billing account options in a project, display the following details:
- Billing Account ID
- Billing Account Name
- Billing Account Expiration Date

**Comment by maxceem** [comment] 2021-03-01 11:52
Sum up:
- update format of options for billing account:

  ![image](https://user-images.githubusercontent.com/146016/109493383-166ead80-7a95-11eb-9cee-14509cfe682b.png)
  
  - additionally, show the `endDate` from the server response in format `23 Feb 2021`. So in total options should looks like:
     `Billing Account Name (2342545345) - 23 Feb 2021`

**Comment by maxceem** [comment] 2021-03-01 13:15
Challenge https://www.topcoder.com/challenges/c3f58fe3-1608-441c-a44d-3fe3bb106ffb has been created for this ticket.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by Gauravseta** [comment] 2021-03-01 14:50
@bug-bash-helper assign me

**Comment by maxceem** [comment] 2021-03-01 14:50
Challenge https://www.topcoder.com/challenges/c3f58fe3-1608-441c-a44d-3fe3bb106ffb has been assigned to gauravseta.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2021-03-02 08:04
@Gauravseta 12 hours have passed, but a Pull Request was not provided, so I have to unassign you from this task.

**Comment by maxceem** [comment] 2021-03-02 08:05
Challenge https://www.topcoder.com/challenges/c3f58fe3-1608-441c-a44d-3fe3bb106ffb gauravseta has been unassigned.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by maxceem** [comment] 2021-03-02 08:05
@yoution this is open for pickup now.

**Comment by yoution** [comment] 2021-03-02 08:12
@bug-bash-helper assign me

**Comment by maxceem** [comment] 2021-03-02 08:12
Challenge https://www.topcoder.com/challenges/c3f58fe3-1608-441c-a44d-3fe3bb106ffb has been assigned to yoution.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by yoution** [comment] 2021-03-02 08:33
![image](https://user-images.githubusercontent.com/3863914/109620510-ee567b80-7b74-11eb-8eaa-e4e4eb3278ce.png)

@maxceem I can not reproduce the issue, can you give me one account and projectid?

**Comment by maxceem** [comment] 2021-03-02 08:49
@yoution looks like my demo account doesn't have them anymore, I reach out for obtaining some demo account.

**Comment by yoution** [comment] 2021-03-02 09:02
I found the test data @maxceem

**Comment by yoution** [comment] 2021-03-02 09:02
https://github.com/topcoder-platform/tc-project-service/blob/854f8c3576f1cbf14fda56f416ca8c12287ef8a3/src/routes/billingAccounts/list.spec.js

**Comment by yoution** [comment] 2021-03-02 09:09
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/4326 for review

**Comment by yoution** [comment] 2021-03-02 09:09
@bug-bash-help is ready for review is ready for review

**Comment by yoution** [comment] 2021-03-02 09:10
@bug-bash-help https://github.com/appirio-tech/connect-app/pull/4326 is ready for review

**Comment by yoution** [comment] 2021-03-02 10:26
@bug-bash-helper https://github.com/appirio-tech/connect-app/pull/4326 is ready for review

**Comment by maxceem** [comment] 2021-03-04 08:24
QA guidelines:

![image](https://user-images.githubusercontent.com/146016/109933225-d8ab9800-7cd3-11eb-9d2e-377a6eea8fa9.png)

**Comment by drasticdpk** [comment] 2021-03-05 03:47
**Verified on dev env**
![image](https://user-images.githubusercontent.com/25297859/110064604-8337bf80-7d95-11eb-94c1-f05132fe37c4.png)

@maxceem , I could not get the exact scenario as mentioned above.

**Comment by maxceem** [comment] 2021-03-10 12:32
Payment failed: [400]: Failed to activate challenge. Detail: Cannot Activate this project, it has no active billing accounts.<br/><br/>```This is an automated message for maxceem via Topcoder X```

**Comment by drasticdpk** [comment] 2021-03-11 06:47
Verified on Prod env. 
![image](https://user-images.githubusercontent.com/25297859/110747071-e29a4180-8265-11eb-9b70-7266ec04aa46.png)

**Closed by drasticdpk** 2021-03-11 06:47 UTC
Labels: ACCEPTED, CF, Feature: Billing Accounts, QA Pass in Dev, Release Due Date: 3/12, tcx_Assigned, tcx_FixAccepted
