### ISSUE TITLE
Regarding users with no traits

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3451] opened 2019-12-18 08:33 UTC
This is regarding users with no traits.

This issue is originally found when testing: https://github.com/appirio-tech/connect-app/issues/3397

Issue is described here: https://github.com/appirio-tech/connect-app/issues/3397#issuecomment-566879634

**Comment by nithyaasworld** [comment] 2019-12-18 08:35
cc: @maxceem @lakshmiathreya @RishiRajSahu

**Comment by RishiRajSahu** [comment] 2019-12-19 05:23
@nithyaasworld this seems to be a transient error due to indexing issue of trait for user, as I checke the traits are present of the user in DB
<img width="1054" alt="Screen Shot 2019-12-19 at 10 52 04 AM" src="https://user-images.githubusercontent.com/11248478/71147108-b9028e00-224d-11ea-8dd8-cca47b33a999.png">

could you please try creating a new user and reproduce the issue ?

**Comment by lakshmiathreya** [comment] 2019-12-19 10:16
Profile details being saved and retrieved fine for this user in Prod. @nithyaasworld we could close this right?

**Closed** 2019-12-19 10:29 UTC
Labels: 2.5.0.1, P3, QA Pass in Prod
