### ISSUE TITLE
Must not display the Customer Name and other details overlap with each other

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#302] opened 2016-09-29 01:09 UTC
### Expected behavior
-----------------------------------------------------------------
Must not display the Customer Name and other details overlap with each other

### Actual behavior
-----------------------------------------------------------------
Customer Name and other details overlap with each other

### Steps to reproduce the problem
-----------------------------------------------------------------

- In Landscape/Portrait Mode
- Open the site
- Login as a valid user (pat_monahan)
- In the 'Projects'
- Check the table carefully
- Check the Customer Name column

### Screenshot/screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

### Environment
-----------------------------------------------------------------
- **Device(s):** iPad 3
- **Browser(s):** Safari
- **Operating System:** iOS 9.3.5
- **Resolution:** 1536 x 2048 pixels (~264 ppi pixel density)
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 11:49
Duplicate of #181.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
