### ISSUE TITLE
Two clear buttons appears in the search in IE11; and it overlaps with the search button

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#186] opened 2016-09-28 18:56 UTC
Description
-----------------------------------------------------------------
Two clear buttons appears in the search in IE11; and it overlaps with the search button

Steps to Reproduce
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (christina_uw or pat_monahan)
- In the Projects
- Click on 'Search' field
- Enter any text

Expected Result(s)
-----------------------------------------------------------------
- Must display only one clearing icon

Actual Result
-----------------------------------------------------------------
- Two clear buttons appears in the search in IE11 

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2016-09-28 23:15
![2016-09-29_4-45-12](https://cloud.githubusercontent.com/assets/4592712/18935726/88d267de-85ff-11e6-87e5-75e49b9c3171.png)

**Comment by mahestro** [comment] 2016-10-04 12:13
This is the first report. Granted as valid.

**Comment by vic-appirio** [comment] 2016-10-12 16:32
Can't reproduce on 2 separate environments; closing

**Closed by vic-appirio** 2016-10-12 16:32 UTC
Labels: functionality, P0, visual styling
