### ISSUE TITLE
[Project Dashboard]Status icon issue

### ISSUE THREAD

**Issue by arifnyet** [appirio-tech/connect-app#377] opened 2016-09-29 18:24 UTC
### Expected behavior
icon should be properly displayed

### Actual behavior
blank box icon

### Steps to reproduce the problem
go to project dashboard using firefox
click  on status drop down

### Screenshot/screencast
![screenshot 37](https://cloud.githubusercontent.com/assets/8684209/18966763/08dcdb8e-86b5-11e6-883e-4d9c5c248ce5.png)
![screenshot 38](https://cloud.githubusercontent.com/assets/8684209/18966779/1f286890-86b5-11e6-87a4-edf9e9ba9d4c.png)
![screenshot 39](https://cloud.githubusercontent.com/assets/8684209/18966831/5a0199be-86b5-11e6-8639-8bc484647f85.png)

#### Environment
- OS: Windows 10
- Browser (w/version):Mozilla firefox version 49
- User role :Co-pilot
- Account used: cp-superstar

**Comment by mahestro** [comment] 2016-10-04 16:39
Duplicate of #272

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
