### ISSUE TITLE
When user EDIT a 'Custom Features'; Other feature is removed

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#431] opened 2016-10-01 17:46 UTC
### Expected behavior
-----------------------------------------------------------------
Must not remove the other feature from the list

### Actual behavior
-----------------------------------------------------------------
When user EDIT a 'Custom Features'; Other feature is removed

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Enter name
- eg: Lorem ipsum
- Click Save Feature
- Click 'Add a custom feature'
- Enter name
- eg: Lorem ipsum (enter the previous item name)
- Click Save Feature
- Check the List and select an item - eg: Lorem ipsum
- Now OFF the slider to EDIT
- Check the list

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-15-49](https://cloud.githubusercontent.com/assets/4592712/19016003/046ba1ec-882d-11e6-9b2d-e20df35f9036.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 19:31
Duplicate of #265

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
