### ISSUE TITLE
Project listing: return user to previous spot in listing after back from project

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#552] opened 2016-11-22 19:36 UTC
### Expected behavior
User is browsing listing and clicks on project. User clicks back or "Projects" in nav and is taken to the same spot where they were originally in the listing

### Actual behavior
User is taken to the top of the listing. Example: http://www.screencast.com/t/7plejM46P

**Comment by vikasrohit** [comment] 2016-11-23 03:58
@fnisen I can understand that for back button it should go back to the same spot where user clicked the project, however, I guess it should not be the case with Projects in nav link because we are clearing out all filters explicitly when user clicks on Projects from the nav link.

**Comment by vikasrohit** [comment] 2016-11-23 12:41
@fnisen Investigated the possible solution. Found [react-router-scroll](https://github.com/taion/react-router-scroll) which implement browser's scroll behaviour, but it didn't work".
@parthshah do you have idea about it? How to maintain the scroll position after route change?

**Comment by fnisen** [comment] 2016-11-23 17:32
@vikasrohit that's actually not the expected UX. Clicking on Projects should not be clearing filters--they are meant to be sticky. Clicking on the Connect logo is the action that clears filters.

**Comment by vikasrohit** [comment] 2016-11-24 03:16
My bad @fnisen I mixed the Project nav link behaviour with Connect logo. Its not reseting the filters on clicking on Projects nav link.

**Comment by vikasrohit** [comment] 2016-11-28 10:41
@fnisen Got it fixed via community. However, there is a use case which I am not sure how we want to handle. When user moves between different pages of the project list, should we maintain the scroll position? Right now it maintains the scroll position in this case as well. IMO, mostly this behaviour is not required with one exception case where a user remembers that the project, he/she is looking for, is located in bottom of the list but he/she can't remember the exact page number. So in this case, if we maintain the scroll position, it would help user to find the project as he/she can just click through pages after scrolling to the bottom of the page.
Please let me know what should be the expected behaviour in this case.

**Comment by fnisen** [comment] 2016-11-29 01:26
@vikasrohit OK, have checked it out. Yes, maintaining is working well. I agree with you about the scroll position between listing pages--I would remove maintaining the position and reset it to go to the top of the page (this is behavior now if you click "Next"). I think it's more likely that a user going between pages would want to see the projects in order and so would want to be taken to the top of the page. That's the behavior I've seen on Google and other sites with pagination.

**Comment by vikasrohit** [comment] 2016-11-29 06:28
@fnisen I am not seeing the behaviour, you mentioned, for the "Next" button. For me it is still maintaining the scroll position. Nevertheless, I am committing changes which would resolve this for clicking on the page number as well.

**Comment by vikasrohit** [comment] 2016-11-29 07:32
Changes are in dev now.

**Closed by vikasrohit** 2016-11-29 07:32 UTC
Labels: P2, s_listing

**Comment by fnisen** [comment] 2016-11-29 17:31
Working well! 👍
