### ISSUE TITLE
The previous name and description are set in fields

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#430] opened 2016-10-01 17:46 UTC
Expected behavior

   - Do not display the name and description in fields.

Actual behavior

   - The name and description fields are completed.

Steps to reproduce the problem

    Login into application as manager role.

    Edit any existing project.

    Add / Edit Feature.

    Press Create Custom Feature button.

    Complete name and description.

    Set On.

    Press again Create Custom Feature button.

     Observe as the name and description fields are pre completed!

Environment

    OS: Windows 7
    Browser (w/version): Chrome
    User role (client, copilot or manager): manager
    Account used: pat_monahan

![precompleted-fields](https://cloud.githubusercontent.com/assets/5114907/19016004/105b078c-8818-11e6-9019-ce4ce1da6d77.png)

**Comment by mahestro** [comment] 2016-10-04 19:29
Duplicate of #205

**Closed** 2016-10-15 00:17 UTC
Labels: duplicate
