### ISSUE TITLE
[$70] Unnecessary calls to get latest comments for messages

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1394] opened 2017-12-01 07:35 UTC
Ideally we should not make call to `v4/topics/{id}/posts` when the number of comments for a message is less than 20 because by default the API returns first 20 comments of each message in `/v4/topics` call.

<img width="1201" alt="screen shot 2017-12-01 at 1 02 45 pm" src="https://user-images.githubusercontent.com/2417632/33472417-30a91acc-d698-11e7-98e5-961684f71b33.png">

fyi @mtwomey @vic-topcoder

**Comment by Lativado** [comment] 2017-12-05 00:24
Having technical difficulties, removing my assignment and re-adding pickup label.

**Comment by zjuasmn** [comment] 2017-12-05 13:58
Cannot reproduce the issue, there is no request for `posts/postId=:id` in app when viewing project.

**Comment by vikasrohit** [comment] 2017-12-05 15:33
Try adding a message which does not have more than 20 comments. If still issue is not reproducible, try creating more random data set for messages i.e. few messages with 5 comments, few with 10 comments etc. But ideally it should not do extra `/posts` request for total comments being less than 20.

**Comment by gondzo** [comment] 2017-12-05 17:47
@vikasrohit Looks like this is already implemented here https://github.com/appirio-tech/connect-app/blob/9e67bc62570db375340399e4fc8bb01491be353d/src/projects/actions/projectTopics.js#L60

@zjuasmn please hold off on making any changes.

**Comment by vikasrohit** [comment] 2017-12-06 05:31
Agree @gondzo but even after that code in place, it seems we are making some unnecessary calls as you can see from screenshot in issue description. So, it seems like a bug to me.

**Comment by zjuasmn** [comment] 2017-12-06 15:07
@vikasrohit could you show more detail of the network panel? Is the first request a OPTIONS request?

**Comment by vikasrohit** [comment] 2017-12-06 15:17
@zjuasmn Yes, the first call is OPTIONS and the second one is GET. Ideally it should not have been called because total comments for the message are 6 only (refer to screenshot in issue description).

**Comment by zjuasmn** [comment] 2017-12-07 00:24
@gondzo @vikasrohit I think I might have found the way to reproduce this bug and it seems to be an api bug.

Visit <https://connect.topcoder-dev.com/projects/2071> as `amy_admin`, the feed has 20 comments, but the api returns `postIds` array with 21 postIds and `posts` array with 20 posts. And the `retrievedPosts` field and `totalPosts ` field is also not correct. So the frontend would need to fetch more posts after that. This issue might be related to edit/remove comments api code. 

![image](https://user-images.githubusercontent.com/4462778/33692205-04107d78-db27-11e7-88f4-6f74e82e8194.png)

**Comment by gondzo** [comment] 2017-12-07 00:43
Good find @zjuasmn
I believe this is related to adding users to project - it creates an invite user post that we're filtering out in the api but the total count can't be correct unless we fetch all posts each time. I don't see a way around this. Any ideas @vikasrohit ?

**Comment by vikasrohit** [comment] 2017-12-07 07:01
> Visit https://connect.topcoder-dev.com/projects/2071 as amy_admin, the feed has 20 comments, but the api returns postIds array with 21 postIds and posts array with 20 posts

**Comment by vikasrohit** [comment] 2017-12-07 10:14
@gondzo @zjuasmn spent more time this. `retrievedPosts` count is always <=20 because it shows the number of posts returned in the `/topics` call and it counts only the real posts (posts which are posted by team members or coder bot), it minuses 1 from 20 for each post that is system generated. Example of system generated posts are the ones @gondzo you were concerned above i.e. `user invitation` messages. However, it is not counting the message which system posts for a user being removed from the topic which actually does not make much sense because even if it would have, front end has to still make request to get the latest posts (which in fact are of no use because they are just system messages). So, it seems it is not possible to avoid these calls until we fix discourse to return latest 20 posts for each topic.

Still there is one good take from this analysis:

We are not taking `user removal` messages into account [here](https://github.com/topcoder-platform/tc-message-service/blob/dev/app/services/adapter.js#L112) which causes two things:
1. Wrong retrievedPosts count (it should always say the non system posts c ount)
2. It updates the topics's `lastActivityAt` field to be that of the last user removal's timestamp which is one of the reasons of #1414 and that means even the fixes coming from #1281 would not fix that issue properly without fixing this. @gondzo can you please create new issue to fix this and apply the fix along with fix of #1281 

@vic-topcoder @mtwomey

**Comment by gondzo** [comment] 2017-12-18 12:54
@vikasrohit user removal is handled in syncUsers in tc-message service which retains topic timestamps properly.  I think we can close this one ?

**Comment by vikasrohit** [comment] 2017-12-19 12:34
@gondzo By `user removal` I meant, the system messages added by discourse when a user is removed from a topic. We are not taking those into account when reducing the `retrievedPosts` count [here](https://github.com/topcoder-platform/tc-message-service/blob/dev/app/services/adapter.js#L112).

**Comment by gondzo** [comment] 2017-12-19 12:51
ah, ok that clears it up. We need to fix it in the message service.

**Closed** 2017-12-20 16:55 UTC
Labels: ACCEPTED, Ready for Review
