### ISSUE TITLE
Spurious Avatars being rendered in ProjectCard

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1359] opened 2017-11-27 03:32 UTC
Found this in dev:

<img width="366" alt="screen shot 2017-11-27 at 9 01 01 am" src="https://user-images.githubusercontent.com/2417632/33249617-abb76c40-d351-11e7-84bb-bdfe0c5a3a59.png">

**Comment by vikasrohit** [comment] 2017-11-27 03:33
@sachin-maheshwari this project has only 4 unique members but it showing too many Avatars in card footer. You can login with pshah_customer to check this project.

**Comment by sachin-maheshwari** [comment] 2017-11-27 10:55
@vikasrohit, as investigated its a back-end API issue...checking further in corresponding back-end api to find out the root cause. 
https://api.topcoder-dev.com/v4/projects/?limit=1&offset=0&fields=id,name,description,members,status,type,actualPrice,estimatedPrice,createdAt,updatedAt,details&filter=status%3Din(draft,in_review,reviewed,active,completed,paused)&sort=updatedAt+desc

{
  "id": "34f1f8a1-b235-4e17-b206-cacf5eb4ce98",
  "version": "v4",
  "result": {
    "success": true,
    "status": 200,
    "content": [
      {
        "createdAt": "2017-11-25T15:32:54.000Z",
        "attachments": [
          
        ],
        "actualPrice": null,
        "estimatedPrice": null,
        "members": [
          {
            "createdAt": "2017-11-25T15:32:54.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": true,
            "id": 3171,
            "userId": 40153596,
            "projectId": 2072,
            "updatedAt": "2017-11-25T15:32:54.000Z"
          },
          {
            "createdAt": "2017-11-26T03:58:18.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3177,
            "userId": 23100286,
            "projectId": 2072,
            "updatedAt": "2017-11-26T03:58:18.000Z"
          },
          {
            "createdAt": "2017-11-26T04:15:51.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3178,
            "userId": 23100286,
            "projectId": 2072,
            "updatedAt": "2017-11-26T04:15:51.000Z"
          },
          {
            "createdAt": "2017-11-26T04:20:56.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3179,
            "userId": 23100286,
            "projectId": 2072,
            "updatedAt": "2017-11-26T04:20:56.000Z"
          },
          {
            "createdAt": "2017-11-26T04:20:56.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3179,
            "userId": 23100286,
            "projectId": 2072,
            "updatedAt": "2017-11-26T04:20:56.000Z"
          },
          {
            "createdAt": "2017-11-26T16:36:48.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3186,
            "userId": 23100286,
            "projectId": 2072,
            "updatedAt": "2017-11-26T16:36:48.000Z"
          },
          {
            "createdAt": "2017-11-26T17:46:08.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3189,
            "userId": 40152856,
            "projectId": 2072,
            "updatedAt": "2017-11-26T17:46:08.000Z"
          },
          {
            "createdAt": "2017-11-26T17:48:53.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3190,
            "userId": 40152855,
            "projectId": 2072,
            "updatedAt": "2017-11-26T17:48:53.000Z"
          },
          {
            "createdAt": "2017-11-26T17:48:53.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3190,
            "userId": 40152855,
            "projectId": 2072,
            "updatedAt": "2017-11-26T17:48:53.000Z"
          },
          {
            "createdAt": "2017-11-26T18:42:48.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3191,
            "userId": 40152922,
            "projectId": 2072,
            "updatedAt": "2017-11-26T18:42:48.000Z"
          },
          {
            "createdAt": "2017-11-27T03:20:40.000Z",
            "role": "customer",
            "updatedBy": 40153596,
            "createdBy": 40153596,
            "isPrimary": false,
            "id": 3192,
            "userId": 40152922,
            "projectId": 2072,
            "updatedAt": "2017-11-27T03:20:40.000Z"
          }
        ],
        "name": "test development project",
        "description": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. ",
        "details": {
          "appDefinition": {
            "goal": {
              "value": "Find a bug"
            },
            "primaryTarget": "phone",
            "users": {
              "value": "Project managers"
            }
          },
          "hideDiscussions": true,
          "products": [
            "frontend_dev"
          ],
          "utm": {
            
          }
        },
        "id": 2072,
        "type": "app_dev",
        "status": "draft",
        "updatedAt": "2017-11-26T16:39:02.000Z"
      }
    ],
    "metadata": {
      "totalCount": 122
    }
  }
}

**Comment by sachin-maheshwari** [comment] 2017-11-30 05:07
@vikasrohit , as checked in DB there are corresponding 11 rows in 'project_members' table. So data coming from listing API is correct. As discussed earlier we'll handle this type of data issues at front-end.

**Comment by vikasrohit** [comment] 2017-11-30 05:44
Then there must be some issue with code.

**Comment by sachin-maheshwari** [comment] 2017-11-30 12:13
@vikasrohit which code ? in 'detail' backend API code or front-end code?

**Comment by vic-topcoder** [comment] 2017-11-30 19:05
When there are too many people on a project, we should hide the overflow to keep avatars in 1 row, and add the number of hidden avatars in the format "+3". Ideally we can reuse the avatar rendering and display the number of additional avatars.

**Comment by vikasrohit** [comment] 2017-12-01 05:45
Yes, @vic-topcoder I was planning to do that change when work on list view updates where are restricting the number of avatars to be visible per row. However, this issue is different. It is a bug with API I guess which is not removing old team members from the list and to get it quickly fixed, we are thinking of handling it in AvatarGroup component.

**Comment by sachin-maheshwari** [comment] 2017-12-01 13:25
PR - https://github.com/appirio-tech/connect-app/pull/1395

**Closed** 2017-12-04 08:53 UTC
