### ISSUE TITLE
Remove "skip question" option for Design Guidelines section

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#842] opened 2017-03-14 20:26 UTC
1. Remove option to skip questions (all question are optional)
2. Remove duplicate description below skip question option 

Example project: http://connect.topcoder-dev.com/projects/1077/specification

![screen shot 2017-03-14 at 1 23 16 pm](https://cloud.githubusercontent.com/assets/12552247/23920839/7c44b20a-08b9-11e7-93ce-16f2eb28f272.png)

**Comment by vic-topcoder** [comment] 2017-03-14 20:27
assigning to @gondzo as this is in the functional part of the document.

Also - remove duplicate description on skippable questions.

**Comment by gondzo** [comment] 2017-03-15 00:30
@fnisen this is fixed and merged to dev

**Comment by fnisen** [comment] 2017-03-15 00:59
@gondzo @ThomasKranitsas fix is working, but another issue introduced. This is the placeholder text now shown:

![screen shot 2017-03-14 at 5 57 06 pm](https://cloud.githubusercontent.com/assets/12552247/23928884/b103c492-08df-11e7-8b7c-af7b712ca2de.png)

**Comment by ThomasKranitsas** [comment] 2017-03-15 01:23
@fnisen I can't reproduce it... I'm creating new projects of type(s) `wireframes` & `visual_design_prod` and works fine. Even after adding/removing some values and saving works fine

**Comment by fnisen** [comment] 2017-03-15 01:55
@ThomasKranitsas you're right. Looks like it went away on its own. 👍

**Closed** 2017-03-15 01:56 UTC
Labels: P1, products
