### ISSUE TITLE
Can't close the 'Define a new feature' popup from CANCEL button

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#432] opened 2016-10-01 17:52 UTC
### Expected behavior
-----------------------------------------------------------------
Must able to close the 'Define a new feature' popup

### Actual behavior
-----------------------------------------------------------------
Can't close the 'Define a new feature' popup from CANCEL button

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project and go to Specification
- Click 'Add a custom feature'
- Don't Enter name
- Click ON --> Click on CANCEL button
- Now  Click OFF --> Click on CANCEL button

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_23-23-03](https://cloud.githubusercontent.com/assets/4592712/19016067/07cdebb4-882e-11e6-9ed7-f2dadf08439a.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 19:48
Valid (click checkbox - can't cancel).

**Comment by fnisen** [comment] 2016-10-05 00:51
@mahestro this is a duplicate of https://github.com/appirio-tech/connect-app/issues/432.

**Comment by vikasrohit** [comment] 2016-10-06 10:12
Should be fixed with #125

**Closed by vikasrohit** 2016-10-06 10:12 UTC
Labels: duplicate
