### ISSUE TITLE
Same project has 2 different status (In review and reviewed)

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3520] opened 2020-01-27 05:03 UTC
1. In Dev Env, search with the keyword 'sathya'
2. Check that there is a project 'Sathya Jan 14 Copilot 1' in 'In review' status
3. Click on 'Reviewed' filter and check that the same project is now shown with 'Reviewed' status

![image](https://user-images.githubusercontent.com/5114190/73151272-7b1c4380-40f0-11ea-8536-fd94face2723.png)
![image](https://user-images.githubusercontent.com/5114190/73151277-80798e00-40f0-11ea-91ae-8987f8520913.png)

**Comment by nithyaasworld** [comment] 2020-01-27 05:04
Assigning this with 'p4' as the issue is seen only with the data present in Dev Environment.

If its a data issue, please clear the wrong-data, so we can close this issue.

**Comment by nithyaasworld** [comment] 2020-01-27 05:07
Another thing to note:

In Dev, If I simply navigate to 'Reviewed' tab, this project is not seen. Only **when I search with 'sathya' being in the 'Reviewed' tab**, this issue is seen.

**Comment by vikasrohit** [comment] 2020-01-27 06:33
@maxceem do you have idea about this? I doubt on inconsistency between ES and DB but I guess, now we are returning all data from ES and the two places where the data is different, are using the same API endpoint, so it should not be the inconsistency between ES and DB.

**Comment by maxceem** [comment] 2020-01-27 06:35
### Overview

This is caused by the data inconsistency between ES and DB.
Normally data comes from ES, where the project has 'In review'  status.

When searching by `Reviewed` and `sathya` there are no such results found in ES, so the backend tries to find it in DB, and in DB it finds one project where status is `Reviewed`. So the same project has different statuses in ES and DB.

### Root issue

While the issue itself is not a bug. We have to check why this project is not being reindexed in ES. I've just updated it for testing:

![image](https://user-images.githubusercontent.com/146016/73154291-dc084380-4111-11ea-96a8-674c472da4a3.png)

But after page reloading the data disappears, which means indexing failed:

![image](https://user-images.githubusercontent.com/146016/73154322-f510f480-4111-11ea-9d59-bd43b6309177.png)

**NOTE** This issue happens due to some particular data in this project, it doesn't happen for every project.

@RishiRajSahu when you have time, could you please help me to get the logs of the error during this project indexing.

**Comment by maxceem** [comment] 2020-01-27 06:38
> @maxceem do you have idea about this? I doubt on inconsistency between ES and DB but I guess, now we are returning all data from ES and the two places where the data is different, are using the same API endpoint, so it should not be the inconsistency between ES and DB.

It is an inconsistency between DB and ES. The observed effect of different output is due to aflling back to DB when no results found in ES. There is an issue logged exactly for such cases https://github.com/topcoder-platform/tc-project-service/issues/450.

**Comment by maxceem** [comment] 2020-01-28 04:09
The root reason for the issue mentioned in https://github.com/appirio-tech/connect-app/issues/3520#issuecomment-578610957 looks like got fixed by https://github.com/appirio-tech/connect-app/issues/3521 via https://github.com/topcoder-platform/project-processor-es/pull/21.

Also, data in ES has been fixed to match the DB.

So this issue should disappear now. This ticket may be tested and closed.

**Closed** 2020-01-28 08:25 UTC
Labels: P4, QA Pass in Dev
