### ISSUE TITLE
Blank page shown after clicking continue in the project setup page

### ISSUE THREAD

**Issue by meontechno** [appirio-tech/connect-app#1056] opened 2017-07-26 07:22 UTC
### Steps to reproduce the problem
-Open URL https://connect.topcoder-dev.com
-Click on Start a project
-Choose website option and click on Create project
-Fill in all the project details and click on Continue

### Expected behavior
Registration page should appear after clicking on **continue** button in the project setup page.

### Actual behavior
A page with content "Privacy Policy" is shown.
check out the screenshots below.

### Screenshot/screencast
![lets1](https://user-images.githubusercontent.com/24816337/28609096-0f8dc1cc-7198-11e7-92e1-badfd4f7a296.PNG)
![lets2](https://user-images.githubusercontent.com/24816337/28609118-2885d2aa-7198-11e7-81f4-8e291bf363e0.PNG)
![enabled](https://user-images.githubusercontent.com/24816337/28609132-35f7404a-7198-11e7-863a-f2d0647275cf.PNG)

## After clicking on continue
![nc222](https://user-images.githubusercontent.com/24816337/28609163-5a3e99c6-7198-11e7-9a7c-5b25912bfbec.png)

#### Environment
- OS: Windows 10 Home (64 bit)
- Browser (w/version): Google Chrome Version 59.0.3071.115 (Official Build) (64-bit)
- User role (client, copilot or manager): NA
- Account used: NA

**Comment by gondzo** [comment] 2017-07-27 18:46
duplicate of #1052

**Closed by gondzo** 2017-07-27 18:47 UTC
Labels: bug hunt, duplicate
