### ISSUE TITLE
[$100] Screen flicker in dropdown

### ISSUE THREAD

**Issue by gondzo** [appirio-tech/connect-app#1519] opened 2017-12-22 10:11 UTC
Found a weird issue with notifications dropdown.
When hover with mouse to the dropdown list global browser scrollbar disappears which causes flickering http://take.ms/g53EJ
@vikasrohit Is there anything in changes to the Dropdown component that could cause this (the one that was moved to react-components repository)?

Reported by @maxceem

**Comment by vikasrohit** [comment] 2017-12-22 10:45
It can be @gondzo However, I would like to know if this does not happen without those changes.

**Comment by gondzo** [comment] 2017-12-22 10:50
It doesn't > http://connect-test02.topcoder-dev.com
@maxceem is looking into possible (quick) fixes to get this before the release

**Comment by maxceem** [comment] 2017-12-22 10:52
I've checked it in the notification branch where the dropdown component was in the `connect-app`. Before moving to `react-components`.
This issue with the flickering was not there.
Also, this issue was fixed https://github.com/appirio-tech/connect-app/issues/1508 in that version.

This issue https://github.com/appirio-tech/connect-app/issues/1497 presents in the version before moving.

**Comment by vikasrohit** [comment] 2017-12-22 11:14
I have observed that when you move out from the header of the notifications dropdown, it does not flicker. So, IMO, it is something related with internal scroll bar and its corresponding div.

**Comment by vikasrohit** [comment] 2017-12-22 11:18
Its a class `noScroll` that is being added as soon as mouse enters the `notifications-dropdown-body` section.

**Comment by maxceem** [comment] 2017-12-22 11:48
Oh yes, so this issue is not related to the replaced dropdown component.
The new code was added to `NotificationsDropdownContainer` to prevent scrolling browser window when scrolling inside the notifications drop-down reaches the end http://take.ms/QBp1Z

Though now this flickering is introduced.

I propose to remove the code which adds `noScroll` class for the current release.

After release, this could be implemented different ways. In my opinion, the best way is to `preventDefault`/`stopPropagation` when we reach the end scrolling area inside the notifications drop-down.
Also, there is a decision to make. If there is no scroll in notification dropdown, should we block global scrolling or no?

**Comment by vikasrohit** [comment] 2017-12-22 11:52
Agree with @maxceem for getting rid of `noScroll`.

However, @maxceem I think we can always do `stopPropagation` in notification container to prevent scroll event from moving up.

**Comment by maxceem** [comment] 2017-12-22 12:09
@vikasrohit amazing idea with `stopPropagation`, though I've checked it and it doesn't work :-(.
In a good case, it's just because how react handles `onWhell` event. So we still have a chance to add a native listener with `addEventListener` and control `useCapture`.
In the worst case it's the a feature of browser how they propagate this particular event. Then we would have to check if we reach the end of scrolling.

As I don't have time for today (before release) to take care of this ticket properly. I can just remove `noScroll` for now or leave it for somebody else.

**Comment by gondzo** [comment] 2017-12-22 12:13
We can go with removing no-scroll for now and revisit this after the
release, in CF6

**Comment by vikasrohit** [comment] 2017-12-22 12:53
👍

**Comment by vic-topcoder** [comment] 2017-12-22 20:00
Ok, so - to have such a behavior, it means that something is making the whole body of the page scrollable, and adding/removing the "noScroll class is causing the window to fall back between bounds. I would actually think a slight modification of the CSS to disable only vertical scroll would remedy the issue. What environment are you guys testing this on? Can't reproduce it on my local machine (Mac, Chrome/Safari/Firefox - all latest). There are some other problems with CSS sizing of elements in top bar. I would like to dive deeper as the main reason for the "noScoll" is the breaking UX behavior - overscrolling the page under while reading notifications is very disruptive/hard to use.

If the issue is from the noscroll class, and we can't figure out what is causing vertical scroll, we can remove it as a last chance. For the moment I'd like to investigate further.

**Comment by vic-topcoder** [comment] 2017-12-22 22:16
Ok, after some thinking and research, probably JS scroll event trapping would be best, instead of modifying the CSS.

Example reactJS code here: https://codepen.io/somethingkindawierd/post/react-mixin-scroll-lock

Can you please evaluate and if acceptable - replace the "noScroll" CSS with the reactjs event handler mixin?

**Comment by gondzo** [comment] 2017-12-26 19:58
moving this one to cf6

**Comment by maxceem** [comment] 2018-01-07 00:28
I'll use this npm package  https://www.npmjs.com/package/react-scroll-lock-component. 
It has quite a lot of downloads. And it takes care of wheel events, touchmove events, and key press events that affect page location (e.g. directional arrows, pageup/pagedown/spacebar).

**Comment by vic-topcoder** [comment] 2018-01-08 20:28
👍

**Comment by gondzo** [comment] 2018-01-11 18:35
merged to dev

**Closed** 2018-01-16 20:39 UTC
Labels: ACCEPTED, PAID
