### ISSUE TITLE
[$150] Messages are not chronologically sorted

### ISSUE THREAD

**Issue by vikasrohit** [appirio-tech/connect-app#1281] opened 2017-10-24 16:34 UTC
When a new member joins the team for the project, it seems it disturbs the order of messages.

Steps to reproduce:

- Login and open any project
- Add 3-4 messages on the dashboard
- now update few messages (including code bot ones) by posting comments against them, but please make sure you don't update them in there creation order i.e. add comments to messages out of their creation time order.
- now add a team member to the project
- refresh the page and notice that message which was updated last is not at the top.

Example projects: https://connect.topcoder-dev.com/projects/2045/

**Comment by vic-topcoder** [comment] 2017-10-30 15:25
Can we get an estimate how much work a fix for this would be? If it is a quick fix - we might do this, but if it is too expensive/customizing Discourse too much, we might drop it. @mtwomey FYI

**Comment by callmekatootie** [comment] 2017-11-23 04:50
Just a co-pilot dropping in.

This is one of those issues that could be minor but are extremely annoying. It's very difficult to continue with existing discussions as the chronological sorting gets affected and locating discussions becomes a pain.

If there's anything that I could do to help resolve this, let me know but I would certainly like to see this resolved soon.

**Comment by gondzo** [comment] 2017-11-23 09:54
The error seems to be related to adding new users - when a new user is added, he is invited to all topics and Discourse will mark the thread as updated at that time. I don't think we can do anything about this, but we can use topic created date for sorting instead of updated date. Sounds good @vic-topcoder @vikasrohit @mtwomey

**Comment by vikasrohit** [comment] 2017-11-23 11:55
@gondzo if we sort them by creation date, it would still be annoying for the users because users might be updating a thread which resides 4-5 thread below, if sorted on created date. This would be usual because we post CoderBot messages on different project events and they would lying on top  even if users are discussing on a thread which is placed below them.

**Comment by gondzo** [comment] 2017-11-23 11:58
Right, that is the downside. We can then sort by the last comment - we are fetching latest comments for all the topics anyway ?

**Comment by vikasrohit** [comment] 2017-11-23 12:27
> we are fetching latest comments for all the topics anyway

Nopes, I think we are fetching only first 20 comments of the topic for first load.

> We can then sort by the last comment

That would be client side and that would never sort all topics in correct order.


I have another idea though if we can't configure discourse in correct way.

We can remove and add users for each topic in their updation date order. I mean right now we first [removing users](https://github.com/topcoder-platform/tc-message-service/blob/dev/app/routes/topics/syncUsers.js#L106) who left the project and [adding users](https://github.com/topcoder-platform/tc-message-service/blob/dev/app/routes/topics/syncUsers.js#L122) who joined the project. Instead we can first create a sorted (by their updation date) array of topics and then either add or remove the user from discourse based on the context. And we should do all these calls to discourse serially to avoid out of sync updates to discourse.

**Comment by vikasrohit** [comment] 2017-11-23 12:31
Or we can use http://docs.discourse.org/#tag/Topics%2Fpaths%2F~1t~1%7Bid%7D~1change-timestamp%2Fput endpoint to update a topics timestamp (which we can store in array before doing add/remove of users) immediately after adding/removing the users.

**Comment by gondzo** [comment] 2017-11-23 12:33
Aren't we loading latest comments first and displaying "view older comments" if there are more than a few ?

**Comment by vikasrohit** [comment] 2017-11-23 12:43
What I can remember @gondzo, we are fetching latest few comments (i think it is 6) from the server if total number of comments for a message(topic) are greater than 20 because discourse is returning us first 20 posts of a topic.

**Comment by gondzo** [comment] 2017-11-23 13:28
you're right @vikasrohit - we need to grant access to topics sequentially by last_posted_date ascending
For anyone picking up this ticket, the changes need to be made at https://github.com/topcoder-platform/tc-message-service/blob/dev/app/routes/topics/syncUsers.js - get all the topics list first, sort by last_posted_date and sync the users sequentially.

**Comment by mtwomey** [comment] 2017-11-23 17:05
@gondzo @vikasrohit 
> when a new user is added, he is invited to all topics and Discourse

Oh yeah! I didn't realize this problem when we did that.

I agree with the Vikas's idea of creating the array beforehand and adding in that order - great idea.

**Comment by gondzo** [comment] 2017-11-26 11:47
@kevinkid any progress ?
This one will be available for pickup if there are no updates in 2 hours.

**Comment by kevinkid** [comment] 2017-11-26 16:09
Still working on it, give more 2 more.

**Comment by kevinkid** [comment] 2017-11-26 16:10
I might be debugging a different problem. Any steps to reproduce the error?

**Comment by vikasrohit** [comment] 2017-11-27 03:18
@kevinkid are you able to reproduce it?

**Comment by kevinkid** [comment] 2017-11-27 03:25
@gondzo No, please give some steps .

**Comment by vikasrohit** [comment] 2017-11-27 03:53
@kevinkid Updates the steps in the original issue description and added an example project as well. added you to that project as well.

**Comment by kevinkid** [comment] 2017-11-27 07:17
Thanks @gondzo , it's the same issue i was debugging.

**Comment by vic-topcoder** [comment] 2017-11-27 18:07
Ok, if the issue is based on the new member joining all topics, can we join the member to all topics in the order they are in the project, so we can keep the latest updated relevant to all? If you have topics 1, 2, 3, and than update them to be 3,1,2, can we join members to 2, 1, 3, so after sorting for updated it'll preserve the order 3,1,2?

**Comment by kevinkid** [comment] 2017-11-28 06:39
Thats right @vic-topcoder, its the best way to go about it. Almost done

**Comment by vikasrohit** [comment] 2017-11-28 06:47
>  than update them to be 3,1,2, can we join members to 2, 1, 3,

As I suggested [here](https://github.com/appirio-tech/connect-app/issues/1281#issuecomment-346605621) I think we should add/remove members in their already sorted order so that even after adding/removing users it maintains the old sort order.

**Comment by gondzo** [comment] 2017-11-29 09:03
@kevinkid any updates ?

**Comment by kevinkid** [comment] 2017-11-30 03:59
Not yet @gondzo

**Comment by gondzo** [comment] 2017-12-04 13:31
This is now fixed in the dev branch at https://github.com/topcoder-platform/tc-message-service/

**Comment by vic-topcoder** [comment] 2018-01-03 20:13
@gondzo - what is the status of this one? Can we close it?

**Comment by vikasrohit** [comment] 2018-01-04 06:27
I think yes, however, the relevant issue is #1565 which seems to be happening because of existing incorrectly ordered topics. Fix from the current issue is intended to prevent it happening in future, however, it does fix the problem with existing ones. So, we have to add some adhoc process/method to fix existing incorrect ones.

**Comment by gondzo** [comment] 2018-01-04 18:54
ok, closing this one as we're tracking it through other issues

**Closed by gondzo** 2018-01-04 18:54 UTC
Labels: PAID, Ready for Review
