### ISSUE TITLE
Redundant presence of 'Project Estimates' on Project outline panel for Front-End Prototype.

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#1004] opened 2017-07-24 19:00 UTC
### Expected behavior
Any field which doesn't have any significance or usage in that particular page, should be removed.For 'Other Design' project option, there are no option to reflect any value for 'Project Estimate'.Hence, 'Project Estimate' should be kept hidden for 'Front-End Prototype Project'.

### Actual behavior
Unnecessary presence of 'Project Estimate' details in Project Outline panel for 'Front End Prototype Projects'.

### Steps to reproduce the problem
- Go to url https://connect.topcoder-dev.com..
- Click 'Start a Project'.
- Chose 'Front End Prototype Project'.
- Observe & try to identify any relevance of 'Project Estimate' in Project Outline.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28539741-63308a3a-70d0-11e7-89fb-52843d97712d.png)
![image](https://user-images.githubusercontent.com/20595047/28539744-68ced776-70d0-11e7-80b1-2b2e7ce0466f.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Firefox 54.0.1, Chrome Version 59.0.3071.115
- User role (client, copilot or manager):Not Logged In
- Account used: -NA-

**Comment by gondzo** [comment] 2017-07-27 18:07
duplicate of #1002

**Closed by gondzo** 2017-07-27 18:07 UTC
Labels: bug hunt, duplicate
