### ISSUE TITLE
All Projects Dashboard Bug - Not Scrolling

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#3812] opened 2020-03-26 15:16 UTC
### Expected behavior
A user should be able to scroll down in the all projects dashboard to see older projects. 

### Actual behavior
User cannot scroll and see projects load. 

### Steps to reproduce the problem
Scroll down on the all projects dashboard.
Projects will not load.

### Screenshot/screencast
![image (17)](https://user-images.githubusercontent.com/41118149/77663174-c4e7a580-6f4a-11ea-9292-993fc75b8393.png)

--

#### Environment
- OS: Mac
- Browser (w/version): Chrome
- User role (client, copilot or manager): Admin
- Account used: tjefts@topcoder.com

**Comment by vikasrohit** [comment] 2020-03-26 16:51
I think I saw this as well yesterday, I thought it was because of network bandwidth. But if you are also seeing it consistently, it might be an issue. @maxceem let me know if you are also seeing the same.

**Comment by maxceem** [comment] 2020-03-26 16:59
@vikasrohit I don't have enough projects for scrolling on PROD. On DEV I don't have such an issue.

**Comment by vikasrohit** [comment] 2020-03-27 08:00
It is still happening for me on production @maxceem and you are right, it is not happening on dev for me.

**Comment by vikasrohit** [comment] 2020-03-27 08:17
I observed that it is not making request to fetch the projects for the third page i.e. after hitting Load more project it loads the projects but then it is not triggering the further load on page scroll. One more difference I am observing is that on production it is failing (403) to load member's details after second page load which might be causing the missed request for the third page. On dev, member detail api call is returning successful.

**Comment by maxceem** [comment] 2020-03-30 15:48
@vikasrohit thanks for the details, they helped a lot. I think I've managed to reproduce it locally, by forcing member service to fail.

Created hotfixes:
- PROD https://github.com/appirio-tech/connect-app/pull/3817
- DEV https://github.com/appirio-tech/connect-app/pull/3818

**Comment by vikasrohit** [comment] 2020-03-31 08:59
Great!!. I have merged the dev version, but a bit confused if we should make a hotfix or a regular release because a regular release is already planned most probably for Thursday.

**Comment by maxceem** [comment] 2020-03-31 09:06
I guess we can make a hotfix to validate that the fix is correct, as the only way to do it for 100% is on PROD. Locally I artificially trigger the error which could be slightly different from PROD situation.

**Comment by vikasrohit** [comment] 2020-03-31 09:11
Deploying as hotfix.

**Comment by vikasrohit** [comment] 2020-03-31 10:01
Seems to work fine on production now. Thanks @maxceem

**Comment by vikasrohit** [comment] 2020-03-31 10:09
@acshields it is fixed and deployed to production.

**Closed** 2020-03-31 10:09 UTC
Labels: P1, after_release#2.4.3_issues, bug
