### ISSUE TITLE
[$50] Not able to join a project being an admin user

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3423] opened 2019-12-13 01:12 UTC
1. Login as Admin user to Test Environment
2. Try to Join a project and check

Actual:
I tried to join a project with all the listed user roles. But it did not let me join stating some validation errors.

![image](https://user-images.githubusercontent.com/5114190/70761574-a848a880-1d73-11ea-8b6e-6a992500c407.png)

**Comment by nithyaasworld** [comment] 2019-12-13 01:12
cc: @lakshmiathreya @maxceem

**Comment by vikasrohit** [comment] 2019-12-13 07:24
@nithyaasworld @lakshmiathreya if the logged in user does not have the same user role i.e. to join as Account Manager, does not have Account Manager user role, he/she has to join the project as regular Manager role. Could you please try joining as `Manager` when logged in as admin or any `Connect Manager`?
As context, this as per our future plan of simplifying role access where we would allow users to join in the same role only i.e. there would be no option for a user to join a project in different role than what they have i.e. an Account Manager would join Account Manager only. Generic roles like Manager and Observer would go away.

**Comment by nithyaasworld** [comment] 2019-12-28 01:28
@vikasrohit As an Admin user, I am not able to join the project as 'Manager'. Please advise what roles an admin user can take up when joining a project. Currently Admin users are not able to join any project with any of the user roles available.

![image](https://user-images.githubusercontent.com/5114190/71537258-686eed00-293f-11ea-9b7f-5fa4ed712842.png)

**Comment by vikasrohit** [comment] 2019-12-30 04:55
Admin users (`Connect Admin` and `administrator`) should be able to join the project with `Manager` role. They won't be able to join the project with specific roles like `Project Manager`/`Solution Architect`/`Program Manager`. As `administrator` I am able to join the projects as Manager, so I think the issue is with `Connect Admin` users.
@maxceem It seems to be a valid bug for `Connect Admin` only, please include it in our next bug bash.

**Comment by maxceem** [comment] 2019-12-31 04:02
> As administrator I am able to join the projects as Manager

I guess you could have both roles `administrator` and `Manager` so able to join. I will include it to the bug bash.

Sum up:
- This issue has to be fixed in Project Service.
- Users with Topcoder roles `Connect Admin` or `administrator` should be able to join projects with Project Role `manager` no matter if they have `Connect Manager` Topcoder role or no.
- Though, such admin users shouldn't be able to join projects with other specific Manger and Copilot roles https://github.com/topcoder-platform/tc-project-service/blob/develop/src/constants.js#L27-L32

**Comment by gets0ul** [comment] 2020-01-21 13:12
@bug-bash-helper assign

**Comment by gets0ul** [comment] 2020-01-21 16:29
@maxceem Any Admin user account I can use for this? Thanks.

**Comment by maxceem** [comment] 2020-01-21 16:35
@gets0ul Unfortunately, there are not admin users that could be shared for DEV env. Though, if Project Service deployed locally, you may use Postman file to send requests with an admin token that works locally `jwt-token` (in Postman file). Or we also have the admin token for locally deployed Project Service here https://github.com/topcoder-platform/tc-project-service/blob/develop/src/tests/util.js#L27

**Comment by gets0ul** [comment] 2020-01-22 09:39
@bug-bash-helper https://github.com/topcoder-platform/tc-project-service/pull/447 is ready for review

**Comment by maxceem** [comment] 2020-01-23 06:11
@gets0ul the fix itself works great. There is a couple of comments regarding unit tests, please have a look at the pull request review for details https://github.com/topcoder-platform/tc-project-service/pull/447#pullrequestreview-347075560.

**Comment by gets0ul** [comment] 2020-01-23 08:26
@maxceem PR is updated.

**Comment by lakshmiathreya** [comment] 2020-01-28 14:19
@maxceem pls clarify - I continue to get the error msg "Only manager is able to join as manager" - when I try to join project as manager via Admin user.

**Comment by nithyaasworld** [comment] 2020-01-28 14:43
Me too.. Seeing the same error as @lakshmiathreya when trying to join a project as admin user.

![image](https://user-images.githubusercontent.com/5114190/73273785-86fc2880-420a-11ea-85f3-2bf50fab53d9.png)

**Comment by maxceem** [comment] 2020-01-29 01:37
Currently, another branch `feature/looker_reporting` is deployed for Project Service instead of `develop` so there is no fix for this issue at this moment. I would update when it's there.

**Comment by maxceem** [comment] 2020-01-29 06:41
@nithyaasworld The Project Service on DEV has been updated. This issue can be tested now.

**Comment by lakshmiathreya** [comment] 2020-01-30 02:53
Working fine for Topcoder Admin - I tested with my user. @nithyaasworld pls set this to QA Pass on Dev once you verify with Connect Admin as well.

**Comment by nithyaasworld** [comment] 2020-01-31 03:56
Thanks @lakshmiathreya Verified with Connect Admin user as well.

**Comment by vikasrohit** [comment] 2020-03-02 09:14
Closing. Please feel free to create new issues for any regression.

**Closed by vikasrohit** 2020-03-02 09:14 UTC
Labels: ACCEPTED, CF-20, PAID, QA Pass in Dev, bug
