### ISSUE TITLE
Project show empty without refresh

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2354] opened 2018-08-13 14:15 UTC
### Expected behavior
Click on the project and it shows the discussion but it shows empty.

### Actual behavior
It shows empty

### Steps to reproduce the problem
  1.  You must filter by my projects (unfiltered will not exhibit this issue)
  1. Display connect project in list view
  2.  click on one project

### Screenshot/screencast
Attach or link a resource.

List view

![image](https://user-images.githubusercontent.com/1180747/44036900-8d80c372-9ed8-11e8-9e12-8da6c3bab769.png)

detailed view before refresh

![image](https://user-images.githubusercontent.com/1180747/44037106-1974c680-9ed9-11e8-9c67-77eabd935b16.png)

detailed after refresh

![image](https://user-images.githubusercontent.com/1180747/44037153-36d2c6d2-9ed9-11e8-831c-7773eeb4a60f.png)

--

#### Environment
- OS: mac
- Browser (w/version):  chrome
- User role (client, copilot or manager): manager
- Account used:   kbowerma

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-330

**Comment by kbowerma** [comment] 2018-08-13 14:35
I cant figure out how to replicate this but, sometimes I am getting the body (disucssion) from another project until I refresh then it goes to the correct challenge.    I will try to figure out how to replicate it.  @acshields

**Comment by kbowerma** [comment] 2018-08-13 15:03
Here is an example of two projects and one is caching the values from another project.

![image](https://user-images.githubusercontent.com/1180747/44040021-0fd3a8ce-9ee0-11e8-8f3f-dc29d4d9f4f5.png)

**Comment by kbowerma** [comment] 2018-08-13 15:04
Now I refresh both windows and they are the same;

![image](https://user-images.githubusercontent.com/1180747/44040169-4705075c-9ee0-11e8-86f6-53f47fcc92ac.png)

**Comment by acshields** [comment] 2018-08-13 16:43
Hi @kbowerma - We will take a look at this ASAP.

**Comment by vikasrohit** [comment] 2018-08-14 07:04
I have looked into it and it seems to be a intermittent issue when somehow api is responding slow and it shows the messages of the project, user last visited. We can definitely fix the even that temporary issue by removing the messages from state as soon as user has navigated to the project listing page. But that might take some time to fix and verify.
So, I would suggest, due to the fact that it corrects it self in few seconds, to go with our schedule release for the day after tomorrow and there after apply this as hotfix, otherwise, we have to resolve conflicts between dev and master because of major refactoring in the way we are showing messages.
If we still think, it is something need hotfix, we would allocate time (from the release deploy time) to do that today.

**Comment by vikasrohit** [comment] 2018-08-14 07:10
Also, @kbowerma it would be really helpful if you can share the console logs when you see the empty messages on dashboard because for me it is kind of alway loading messages (yes, it sometimes temporarily showing cached messages from other projects), even if I am going to project details from `My Projects` filter.

**Comment by kbowerma** [comment] 2018-08-14 12:57
here @vikasrohit 
```
main.94afa754558b608a598d.js:134 Uncaught (in promise) TypeError: e.props.toggleNotificationRead is not a function
    at main.94afa754558b608a598d.js:134
    at n (main.94afa754558b608a598d.js:21)
    at r (main.94afa754558b608a598d.js:6)
    at t.value (main.94afa754558b608a598d.js:134)
    at e.notifyAll (main.94afa754558b608a598d.js:40)
    at r.close (main.94afa754558b608a598d.js:67)
    at r.closeAll (main.94afa754558b608a598d.js:21)
    at r.perform (main.94afa754558b608a598d.js:21)
    at o.perform (main.94afa754558b608a598d.js:21)
    at o.perform (main.94afa754558b608a598d.js:21)
```

**Comment by vikasrohit** [comment] 2018-08-15 08:59
Thanks @kbowerma for the log details. I think we got it fixed in this release via https://github.com/appirio-tech/connect-app/issues/2123. We are still trying to cross validate the fix.

**Comment by mtwomey** [comment] 2018-08-23 17:46
@vikasrohit `We are still trying to cross validate the fix.` Were we able to validate this?

**Comment by vikasrohit** [comment] 2018-08-24 05:49
@mtwomey @kbowerma No we are not able to reproduce it again, but we are positive that the fix we have released in 2.4.4 should have fixed the error. However, we are still working on #2355.

**Comment by maxceem** [comment] 2018-08-29 03:36
I couldn't reproduce it, but I believe the fix for https://github.com/appirio-tech/connect-app/issues/2355 has to also fix this one. As there was some place in logic which could bring such a casual issue.

**Comment by vikasrohit** [comment] 2018-08-30 13:55
@kbowerma Could you please verify this one also at your end?

**Comment by vikasrohit** [comment] 2018-09-03 05:36
Closing to close the milestone. @kbowerma Please feel free to reopen it if you still see the issue.

**Closed by vikasrohit** 2018-09-03 05:36 UTC
Labels: Hot Fix, Priority
