### ISSUE TITLE
Talent Picker Component

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3950] opened 2020-04-22 06:28 UTC
Implement a new component for project creation form to choose talents:

![image](https://user-images.githubusercontent.com/146016/79947553-d012f000-847a-11ea-8d6e-ed9cfef963b5.png)

### Functionality

- The user needs to enter # People, Duration, and Skills for a minimum of one row for the question to be considered “answered.”
- The user does not need to complete all rows for the question to be considered “answered.”
- Clicking the + button at the end of a row should generate another row for the same role. 
Example: Clicking + at the end of the Designer row should create a second Designer row where the user can enter different numbers of people required/duration required/skills required.
- Clicking the X button at the end of a row deletes a row created by the user. They cannot delete the default rows, but they can leave these default rows as blank (as long as one row is completed, to fulfill the required answer functionality).

### Design

https://marvelapp.com/89h2ch3/screen/68335433/handoff with the following adjustments:

- don't show "months" inside, just a number. Add "months" to column header: "Duration (months)"
- If we enter too many skills, let the height of the input of the skills become multiline and grow down
- Reuse the existent style of inputs for **peoples**, **duration** and **skills**, don't implement a new design for inputs
- Don't make the component wide as on design, it should be the same width as other components in the project creation form
- As there is not enough space for "skills" component on one line, put it to the second line, and make the duration and people inputs take the whole space

### Read-optimized mode

- When we answer questions and click Next button, we render them in `read-optimized` mode inside an Accordion, see https://monosnap.com/file/5tHApYK9YEXh5IWXXXRdu2PTohEhJQ. We can open accordion and edit the values using normal UI https://monosnap.com/file/bkSCib1FWEovlfOGf60NutP7x0ZYPp.
- For this component it should display the quantity of people per role: e.g. "Designer: 9, Developer: 5".
- When we open the accordion, it should show the normal UI to edit question as we implemented above. Similar to other question types.

### QA guidelines

This new component should support some general form feature, and we should verify that they work:
- When we select some skills and click **Back** and after **Next** - the selected values should persist.
- When we select some skills and click **Next** and after **Back** - the selected values should persist.
- If we started filling the form, select some specialists, closed the browser tab and after follow project creation link again https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists we restore the form on the last place where the user left it. Selected specialists should be properly restored.
- After we create a project we can edit project scope on the **Scope** tab like this. We should make sure that after we created a project with selected specialists they are displayed properly on the **Scope** tab and we can edit them and **Save changes**.

### Known Issues

- ~value is not updated in read-optimized mode https://github.com/appirio-tech/connect-app/issues/3951~ fixed

**Comment by lakshmiathreya** [comment] 2020-04-22 06:36
cc @drasticdpk

**Comment by maxceem** [comment] 2020-04-22 07:12
This feature is ready of QA:
- Project Creation form with this component https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists
- Please, note existent issue https://github.com/appirio-tech/connect-app/issues/3951

**Comment by coderhacker** [comment] 2020-04-22 16:02
QA Comments: Please see below issue against this screen  https://connect.topcoder-dev.com/new-project/talent-as-a-service-specialists
as per provided below screens 
https://marvelapp.com/89h2ch3/screen/68335433
https://marvelapp.com/89h2ch3/screen/68335434
https://marvelapp.com/89h2ch3/screen/68335435
https://marvelapp.com/89h2ch3/screen/68335436
https://marvelapp.com/89h2ch3/screen/68335437
https://marvelapp.com/89h2ch3/screen/68335438
https://marvelapp.com/89h2ch3/screen/68335439
https://marvelapp.com/89h2ch3/screen/68335440


![image](https://user-images.githubusercontent.com/62358241/80001220-c077c380-84db-11ea-8a7a-70cc6d10855b.png)
1. Header text and alignment not matching 
2. Logo Icon mismatch
3. Text is not center align
4. Para text is not center align
5. In the Duration column have month text, which should be not there, it should be matched with the provided screen.
6. counter icon missing
7. Cross icon is missing
8. Skills column is misaligned not match the provided screen.

![image](https://user-images.githubusercontent.com/62358241/80002151-ec477900-84dc-11ea-80c1-f707df758ae9.png)
9. Icon mismatch with Full Stack Developer and Back End Developer
10. Icon color is not matching with provided design
11. Button design not matching with provided screen 
12.  Back and SET UP MY TEAM 
13. month and counter icon missing from input field

![image](https://user-images.githubusercontent.com/62358241/80002821-c7073a80-84dd-11ea-8a1d-0cbc73a5e5de.png)

14. People input box size not matching with provided screen
15. The duration default value is empty after the focus out.
16. Extra Pipe is coming in skills input field. this is not in the provided screen

![image](https://user-images.githubusercontent.com/62358241/80003401-9c69b180-84de-11ea-8503-73ab7704b267.png)

17. After removing value and go to next then click back button, the value is not restored with 0 month.
18. When increasing counter value this not shows 'months' i.e 3 months

![image](https://user-images.githubusercontent.com/62358241/80003673-fe2a1b80-84de-11ea-8db9-a322277d32d4.png)
19. Skill input box color mismatch

![image](https://user-images.githubusercontent.com/62358241/80003756-1732cc80-84df-11ea-85f5-edb0b14d04a5.png)

20. Breaking skill input filed after adding multiple skills
![image](https://user-images.githubusercontent.com/62358241/80003837-36315e80-84df-11ea-9b8e-dbbbe59498d4.png)

21. after focusing out form the skills,  this is not reset in one line as per design. It's not user friendly and looking very odd.

**Comment by coderhacker** [comment] 2020-04-22 16:03
@maxceem please see the above comments.

CC: @lakshmiathreya @drasticdpk

**Comment by maxceem** [comment] 2020-04-23 05:14
Thanks @coderhacker screenshot with numbers help a lot to understand the issues.

> 1. Header text and alignment not matching
> 2. Logo Icon mismatch
> 3. Text is not center align
> 4. Para text is not center align
> 12. Back and SET UP MY TEAM

Sorry for confusion you with the task description. We should only implement the component for inputting talents and use it in our existent form. Please, ignore everything what is outside in the design.

![image](https://user-images.githubusercontent.com/146016/80060212-a919f400-8536-11ea-8c9c-792ee50ada99.png)

> 5. In the Duration column have month text, which should be not there, it should be matched with the provided screen.

In the task description we've mentioned this change to the design: **"don't show "months" inside, just a number. Add "months" to column header: "Duration (months)""**

> 6. counter icon missing

It's shown when put cursor as per standard browser behaviour:

![image](https://user-images.githubusercontent.com/146016/80060489-60af0600-8537-11ea-9bed-d856f4db1ce4.png)

> 7. Cross icon is missing

As per task description **"They cannot delete the default rows, but they can leave these default rows as blank (as long as one row is completed, to fulfill the required answer functionality)."** We hide it so users cannot remove default row.

> 8. Skills column is misaligned not match the provided screen.

This is as per task description: **"As there is not enough space for "skills" component on one line, put it to the second line, and make the duration and people inputs take the whole space"**

> 9. Icon mismatch with Full Stack Developer and Back End Developer

✅Nice catch. Fixed:

![image](https://user-images.githubusercontent.com/146016/80060854-475a8980-8538-11ea-82eb-3589ce166242.png)

> 10. Icon color is not matching with provided design

Yeah, we use our current color palette, instead of implementing a new one. In general all "green" colors in design we replace with our current "blue" colors.

> 11. Button design not matching with provided screen

Same like above, we reuse our existent round blue button to match our current design instead of new green round buttons.

> 13. month and counter icon missing from input field

In the task description we've mentioned this change to the design: **"don't show "months" inside, just a number. Add "months" to column header: "Duration (months)""**

> 14. People input box size not matching with provided screen

As per description: **"As there is not enough space for "skills" component on one line, put it to the second line, and make the duration and people inputs take the whole space"**

> 15. The duration default value is empty after the focus out.

❌- valid issue, will consider fixing.

> 16. Extra Pipe is coming in skills input field. this is not in the provided screen

As per description: **"Reuse the existent style of inputs for peoples, duration and skills, don't implement a new design for inputs"**

> 17. After removing value and go to next then click back button, the value is not restored with 0 month.

❌- probably valid issue, will consider fixing together with 15.

> 18. When increasing counter value this not shows 'months' i.e 3 months

In the task description we've mentioned this change to the design: **"don't show "months" inside, just a number. Add "months" to column header: "Duration (months)""**

> 19. Skill input box color mismatch

As per description: **"Reuse the existent style of inputs for peoples, duration and skills, don't implement a new design for inputs"**

> 20. Breaking skill input filed after adding multiple skills

The design doesn't show how to deal with the situation, when we have many skills, so we use our existent feature to increase the height of the skills field.

> 21. after focusing out form the skills, this is not reset in one line as per design. It's not user friendly and looking very odd.

We reuse our existent field for skills which looks slightly different in this moment.

**Comment by maxceem** [comment] 2020-04-23 05:22
@vikasrohit could you please have a look on issues 15 and 17 in https://github.com/appirio-tech/connect-app/issues/3950#issuecomment-617870873.
Should we fix it?

**Comment by maxceem** [comment] 2020-04-23 05:36
NOTE. As per discussion with @vikasrohit on Slack we've updated the design of this component and now we are using the next view:

- no table header
- 3 lines:
  1. Role name + buttons
  2. People and duration fields
  3. Skills field

The reason for this is "skills" component which needs a lot of space. We've try out multiple approaches and come up that this design is the best we can have for now taking into account that skills component can show many skills and grow in height.

![image](https://user-images.githubusercontent.com/146016/80062691-fb5e1380-853c-11ea-8f30-9ea4e15ccf2d.png)

**Comment by maxceem** [comment] 2020-04-23 07:45
The existent issue has been fixed and ready for testing https://github.com/appirio-tech/connect-app/issues/3951

**Comment by vikasrohit** [comment] 2020-04-23 11:07
@maxceem I actually didn't understand the issues 15,17 properly and where my help is required.

**Comment by maxceem** [comment] 2020-04-23 11:28
@vikasrohit it's very minor issue, but just in case. By default when we load page all the values are prefilled with `0`:

![image](https://user-images.githubusercontent.com/146016/80093889-fbc2d280-856d-11ea-8ced-ea2b1b353fad.png)

The same is shown in design:

![image](https://user-images.githubusercontent.com/146016/80093947-1137fc80-856e-11ea-9b7f-276c0b0f4b0e.png)

- Issue 15. Now if we remove the value from the field, and remove cursor (unfocus) the field stays without value:

   ![image](https://user-images.githubusercontent.com/146016/80094018-33317f00-856e-11ea-8f36-cb05cefff3c2.png)

   - while as per QA the expected behaviour should be: when we leave the field without value the `0` should be put

- Issue 17 is same as 15 for me, but now I'm not sure. @coderhacker could you please, provide more details, about issue 17? I'm not sure how exactly to reproduce it.

**Comment by coderhacker** [comment] 2020-04-23 12:33
@maxceem  @vikasrohit  Please see below how to reproduce issue 17. Here if focus out from the input field this is not auto-set with 0 value when clicking the next button and come back the same page. value still shows empty. Ideally, this should be an auto-set value with 0.

![issue17](https://user-images.githubusercontent.com/62358241/80099729-929e8780-858c-11ea-9ee6-b23c6d1f6f97.gif)

**Comment by vikasrohit** [comment] 2020-04-23 13:02
Thanks @maxceem and @coderhacker for the details. I think we should not auto fill it with 0 when user has just focused out of the field because the user is still on the form and can come back to fill correct values and if start auto filling in such manner it can lead weird errors of loops of updating values. However, I do think we can fill them with default value when user has left the form step and came back, assuming that this field is option to provide.
Now, having said that, I think we should make these fields required which would prevent user from leaving them empty because I think we need all the information to scope the project.

**Comment by vikasrohit** [comment] 2020-04-27 10:27
> Just from the code point of view I guess it could be more straightforward to fill it with 0 on unfocus if possible, because we have a general logic for Next/Back buttons which is - keep all the values as they are. So if there is empty values, we keep it empty, if 0 we keep it 0.

Okay, go with that. And we can use placeholder value instead as well as suggested by @coderhacker 

> We already require only at least one role to have these values > 0, but not all.

Ok. I think we should make validations bit strict i.e. if user has altered any of the field (people, duration or skills) for any row, it should raise the validation error for other missing fields. However, if that seems bit difficult to achieve in this release, we can take it later as hotfix or regular release.

**Comment by maxceem** [comment] 2020-04-27 11:24
> Okay, go with that. And we can use placeholder value instead as well as suggested by

@vikasrohit unfortunately `input type="number"` which we user there, doesn't support `placeholder` (https://stackoverflow.com/questions/4887993/html5-input-type-number-and-the-placeholder-attribute).

So we would have implement logic to set `0` on **unfocus**. Can we move this requirement to the next release along with:
> Ok. I think we should make validations bit strict i.e. if user has altered any of the field (people, duration or skills) for any row, it should raise the validation error for other missing fields.

I just don't want to do such updates in the last days before release unless they are critical.

**Comment by vikasrohit** [comment] 2020-04-27 11:53
Okay. Lets log them separately and take care in next release (it might be a hotfix though).

**Comment by maxceem** [comment] 2020-04-27 12:15
@vikasrohit I've created 2 separate issues https://github.com/appirio-tech/connect-app/issues/3964 and https://github.com/appirio-tech/connect-app/issues/3965.

We would try to finish them before release or shortly after the release as a hotfix.

@coderhacker if all the clarifications are good https://github.com/appirio-tech/connect-app/issues/3950#issuecomment-618182322. 
Can we treat this issue as passed review as we would fix 2 left issues as a separate issues?

**Comment by coderhacker** [comment] 2020-04-27 13:17
@maxceem **Testing is in progress.** 

Known Issues: #3964 and #3965

**Comment by coderhacker** [comment] 2020-04-28 00:51
@maxceem This is QA Fail. Please find below details:

1. As per design Talent picker component should be available only one place but this appears two times, 

![image](https://user-images.githubusercontent.com/62358241/80434629-e821be00-8917-11ea-83c5-5897d66be0da.png)

For reproducing this issue please see attached video
[3950_QAFAIL.zip](https://github.com/appirio-tech/connect-app/files/4542785/3950_QAFAIL.zip)

**Comment by maxceem** [comment] 2020-04-28 05:59
@coderhacker this is for testing purpose. First component is required and the second component is not required to fill. This is just to demonstrate these 2 cases.

**Comment by coderhacker** [comment] 2020-04-28 06:42
@maxceem Update:  if people and duration are empty just filled only skills, the next button is active. 
![image](https://user-images.githubusercontent.com/62358241/80455492-782c2b80-8949-11ea-8c6c-c4b33bf8fc62.png)

As discussed This issue would be fixed with #3965

**Comment by coderhacker** [comment] 2020-04-28 07:15
@maxceem QA pass with known issues. #3964 and #3965

Please see the attached video refer for QA pass.

[3950_QA_pass.zip](https://github.com/appirio-tech/connect-app/files/4543925/3950_QA_pass.zip)

[3950_QA_pass_2.zip](https://github.com/appirio-tech/connect-app/files/4543939/3950_QA_pass_2.zip)

**Comment by coderhacker** [comment] 2020-04-29 07:34
Production verification failed, Please see attached video reference.

![image](https://user-images.githubusercontent.com/62358241/80571248-e8a27d80-8a19-11ea-9314-eda8e17d7fc1.png)

[3959_production_fail.zip](https://github.com/appirio-tech/connect-app/files/4550279/3959_production_fail.zip)

**Comment by coderhacker** [comment] 2020-04-29 12:54
Verified with this URL on production https://connect.topcoder.com/new-project/talent-as-a-service-v1.2
for all users customer, Admin, Account, Manager, Copilot Manager, and Copilot. This is working as expected.

![image](https://user-images.githubusercontent.com/62358241/80596746-7abf7b80-8a44-11ea-96c5-0ea92c0f20b4.png)

![image](https://user-images.githubusercontent.com/62358241/80596770-8743d400-8a44-11ea-9bab-3ce1e816e843.png)

![image](https://user-images.githubusercontent.com/62358241/80596806-932f9600-8a44-11ea-8cf0-6faf439ef086.png)

![image](https://user-images.githubusercontent.com/62358241/80596820-9a56a400-8a44-11ea-9aa4-f48a59134b54.png)

![image](https://user-images.githubusercontent.com/62358241/80596845-a3477580-8a44-11ea-9a43-004eee3e6ff0.png)

**Comment by coderhacker** [comment] 2020-04-29 12:55
@vikasrohit @maxceem Please note: This component has 2 known issues and the new component is not live on production, once this will fix, I will close this ticket

cc @lakshmiathreya @drasticdpk

**Comment by drasticdpk** [comment] 2020-04-29 13:24
@coderhacker either you can create that know issue as separate and close this, please suggest @vikasrohit @maxceem

**Comment by maxceem** [comment] 2020-04-29 13:26
@drasticdpk we already have two separate tickets for knows issues #3964 and #3965. So I guess we might close this one.

**Comment by lakshmiathreya** [comment] 2020-04-29 13:47
@maxceem @vikasrohit @drasticdpk might be better to close once Component is fully live in Prod?

**Comment by vikasrohit** [comment] 2020-04-29 14:01
@lakshmiathreya Did't get the meaning of `fully live`.

**Comment by coderhacker** [comment] 2020-04-29 14:13
@vikasrohit when new project creating with this URL https://connect.topcoder.com/new-project/talent-as-a-service. the new component is not displayed in production.

The new component is display form this URL https://connect.topcoder.com/new-project/talent-as-a-service-v1.2

I hope you are getting my point.

**Comment by vikasrohit** [comment] 2020-04-29 14:17
Ohk, that would be done once we have product manager approval.

**Comment by drasticdpk** [comment] 2020-04-30 04:21
> @drasticdpk we already have two separate tickets for knows issues #3964 and #3965. So I guess we might close this one.
With reference to above comment I am closing this issue.

**Closed by drasticdpk** 2020-04-30 04:21 UTC
Labels: Aha!: Issue Logged, NeedToVerifyByManagerAcc, QA Pass in Dev, QA Pass in Prod
