### ISSUE TITLE
Can't proceed to the next screen "Where do you need your app deployed?*" question won't have a answer box

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3603] opened 2020-01-29 12:31 UTC
https://www.screencast.com/t/oHAhURMqhTLg
![image](https://user-images.githubusercontent.com/42398485/73356868-eab14080-4260-11ea-8f76-bb6f10d2713f.png)

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions > (User) Design, Development & Deployment
3. Fill all the mandatory fields > Next 
4. Set Work needed > Design, Development, Deployment
5. Set Design goal > Production-ready designs
6. Set Need Add'l Screens > Yes
7. Set Screens Count > 15-30
8. Set Devices > Mobile
9. Set Mobile platforms > Don't select anything
10. Set Brand Guidelines > Yes
11. Set Specific Fonts > Yes
12. Set Specific Colors > Yes
13. Set Languages Pref > Yes

**Actual:** Can't proceed to the next screen "Where do you need your app deployed?*" the question won't have an answer box

**Expected:** Should have an answer box to "Where do you need your app deployed?*"

**Environment:** HP Pavilion x360 14 inch; Windows 10
**Browser:** Microsoft Edge_44.18362.449.0 | Google Chrome 79.0.3945.130 | FF 72.0.2

**Comment by codejamtc** [comment] 2020-01-29 12:31
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P2

**Comment by SathyaJayabal** [comment] 2020-01-31 03:45
@codejamtc , accepted.

Related #3581

**Comment by nithyaasworld** [comment] 2020-02-26 08:53
@maxceem I am still able to reproduce this.

As this is affecting the user from creating a new project, changing the priority to p0.

**Comment by maxceem** [comment] 2020-02-26 10:32
This happens because no **Mobile Platforms** are selected:

![image](https://user-images.githubusercontent.com/146016/75335011-c5493e00-58c3-11ea-95e0-8d887b4c187a.png)

If we select some **Mobile Platforms**, then this question has some field to select:

![image](https://user-images.githubusercontent.com/146016/75335109-e3af3980-58c3-11ea-8317-3b57b6391e24.png)

@RishiRajSahu as a fix for this issue I've updated condition 
```
"condition": "HAS_DEPLOY_DELIVERABLE"
``` 
to 
```
"condition": "HAS_DEPLOY_DELIVERABLE && ( ONE_DELIVERABLE || !(details.appDefinition.mobilePlatforms hasLength 0) || (details.appDefinition.targetDevices contains 'web-browser') )"
```
here:

![image](https://user-images.githubusercontent.com/146016/75336276-cda27880-58c5-11ea-8ca7-f4edaa6fe61f.png)

I'm not sure if it what is expected or no.

@nithyaasworld this is fixed now by changing the data of this Project Template. I'm not 100% sure, that this change is what is expected here, so it could make sense to get confirmation from @RishiRajSahu.

Also, this fix has to be applied to PROD separately by changing the relative Project Template too.

**Comment by vikasrohit** [comment] 2020-02-26 12:00
@maxceem what is project template id, which you fixed?

> As this is affecting the user from creating a new project, changing the priority to p0.

@nithyaasworld just fyi, if you are not able to proceed with one project type, please try with other available project types to remain unblocked, unless you are testing an issue related to the specific template only.

**Comment by vikasrohit** [comment] 2020-02-26 12:29
@maxceem @nithyaasworld I have the fixed the template to not let the user proceed without giving a value for the `Mobile Platforms` question. That should prevent the issue to reappear.

@maxceem I think we can remove that additional condition because we don't need that now as the question is required and now and it would always have some value. Can you please remove that or let me know the project template. I can't see that condition in the template(221) I edited.

**Comment by maxceem** [comment] 2020-02-26 14:03
@vikasrohit that's right, I've fixed template id 221 before.

Hmm, my condition is not there anymore. Probably you've edited template without reloading the page, so there were no updated condition in your template version.

**Comment by nithyaasworld** [comment] 2020-02-26 18:37
Verified.

Thanks @maxceem and @vikasrohit

**Comment by lakshmiathreya** [comment] 2020-02-28 01:31
@drasticdpk pls verify in Prod ...

**Comment by nithyaasworld** [comment] 2020-02-28 08:42
Verified in production.
![image](https://user-images.githubusercontent.com/5114190/75524668-5e976200-5a34-11ea-900e-f9e5fdedc893.png)

**Closed by nithyaasworld** 2020-02-28 08:42 UTC
Labels: Functional, P0, QA Pass in Dev
