### ISSUE TITLE
[$50] Window-Member – Project is submitted for review if user click cancel on message prompt “

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1739] opened 2018-03-01 22:01 UTC
_From @youdare on February 18, 2018 2:43_

Summary:
Window-Member – Project is submitted for review if user click cancel on message prompt “

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create a Web project with larger description and Project name
4.Go to specification and Enter the required information
5.With out saving enter some fields like Deice IOS, Fill Notes
6.Click “Submit For Review” button
7.Application will prompt “You have unsaved changes” with “OK” and Cancel” button
8.Click “Cancel” button 

### Expected Result ###
Window-Member – Project should not be submitted for review if user click cancel on message prompt “
### Actual  Result ###
Window-Member – Project is submitted for review if user click cancel on message prompt “

 ### Screenshots ###

See comments

### Issue Information ###

Frequency: Repeated

Device: Window

OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#142_

**Comment by vic-topcoder** [comment] 2018-03-01 22:01
_From @youdare on February 18, 2018 2:44_

https://youtu.be/PC5qQAm91eA

**Comment by Colinh84** [comment] 2018-03-09 21:25
@vic-topcoder This issue is a duplicate of #1795 which I have already solved..

**Closed** 2018-03-13 23:06 UTC
Labels: Functional, duplicate
