### ISSUE TITLE
Draft Icon is showing a different behaviour of expanding and collapsing. 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3589] opened 2020-01-29 09:31 UTC
### Expected behavior.
The Draft button should not do the collapse/expand function.

### Actual behavior
While clicking on Draft Icon it is letting the text to expand and collapse.

### Steps to reproduce the problem
- Login and Manager.
- GO to the OnDemand detail page.
- Add the required field to create a project.
- GO to Project Dashboard.
- Click on Add New Phase under Dev Iteration.
- Click on the Draft Icon
-Observe the activities after clicking the Draft icon. 

### Screenshot/screencast
Attach or link a resource.
<img width="1131" alt="draft" src="https://user-images.githubusercontent.com/57211549/73344022-b2822000-42a9-11ea-894f-592f5776a6d0.png">
<img width="813" alt="draftunclick" src="https://user-images.githubusercontent.com/57211549/73344031-b7df6a80-42a9-11ea-850a-7596b5560fa0.png">

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment] 2020-01-29 09:32
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1.

**Comment by SathyaJayabal** [comment] 2020-01-30 17:32
@CreeyaSean , out of scope

**Comment by nithyaasworld** [comment] 2020-02-03 05:04
Not a bug. The whole title area is clickable for easy-navigation.

**Closed by nithyaasworld** 2020-02-03 05:04 UTC
Labels: BH_OOS, BugHunt_JanRelease, Functional
