### ISSUE TITLE
Clicking on the 'Save Changes' button in totally different section will Save details of other section too

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#756] opened 2017-03-09 11:33 UTC
Description
-----------------------------------------------------------------
Clicking on the 'Save Changes' button in totally different section will Save details of other section too

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project (https://connect.topcoder-dev.com/projects/960/specification)
- Click on 'Specification' tab
- Select 9-15 from 'How many screens do you need designed?'
- Scroll down and click Save Changes button in the below section

Expected Result(s)
-----------------------------------------------------------------
- Must save the relevant section data only
- Because each section has the 'Save Changes' button but save only the section data

Actual Result
-----------------------------------------------------------------
- Clicking on the 'Save Changes' button in totally different section will Save details of other section too

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by gondzo** [comment] 2017-03-09 23:38
duplicate of #734

**Closed by gondzo** 2017-03-09 23:38 UTC
Labels: bug hunt
