### ISSUE TITLE
swetaipec:   on picking device as Tablet showing the validation msg "Please select at least 1 device"

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#175] opened 2016-09-28 18:45 UTC
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to pick device
5. Select Tablet

Expected Result: should not displayed validation msg
Actual Result: showing Validation msg

Enviroment: windows 7, chrome latest 

![image](https://cloud.githubusercontent.com/assets/16131461/18927481/ce5caf88-85d9-11e6-8935-793b411ffc01.png)

**Comment by parthshah** [comment] 2016-10-10 17:45
@vikasrohit please work on this one too. It might be an IE only issue. I am not able to reproduce it on chrome

**Comment by vikasrohit** [comment] 2016-10-12 08:09
@parthshah I have tried in the environment (Windows/Chrome) specified in issue description, but not able to reproduce. I also tried to check it for IE, however, after chrome test, I am not able to login in browserstack's browsers.

**Comment by fnisen** [comment] 2016-10-13 21:25
Not able to reproduce either in both browsers. Might have been fixed along with something else. Closing.

**Closed by fnisen** 2016-10-13 21:25 UTC
Labels: P1
