### ISSUE TITLE
TC Managers unable to Add/Edit Phases 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#4181] opened 2020-11-06 07:05 UTC
<img width="1680" alt="Screenshot 2020-11-05 at 9 36 46 PM" src="https://user-images.githubusercontent.com/51733042/98336187-78aa2b00-202c-11eb-9b25-da6f6cae452a.png">
<img width="1680" alt="Screenshot 2020-11-05 at 9 44 02 PM" src="https://user-images.githubusercontent.com/51733042/98336216-82cc2980-202c-11eb-997a-029dd7a5db25.png">

**Comment by lakshmiathreya** [comment] 2020-11-06 07:05
cc @RishiRajSahu

**Comment by maxceem** [comment] 2020-11-06 07:38
@lakshmiathreya it works for me. Could you please try with another project or re-login?

**Comment by maxceem** [comment] 2020-11-06 10:35
Can reproduce with this project. This issue happens with all managers who joined any project some time ago with non `manager` role, like `account_manager`. 

Fixed by https://github.com/topcoder-platform/tc-project-service/commit/c316c789fb4e4b253d33b15b070473b05ca35754

**Comment by lakshmiathreya** [comment] 2020-11-06 11:05
'account_manager' is a manager role too right - pls clarify @maxceem

**Comment by maxceem** [comment] 2020-11-06 11:14
Yes, before we have several roles for manages in projects:
- `manager`
- `account_manager`
- `account_executive`
- `project_manager`
- `solution_architect`
- `program_manager`

After this task https://github.com/appirio-tech/connect-app/issues/4101 we don't allow to choose role anymore, so all new managers always join projects with `manager` role.

But in old projects users may already be members with other manager roles. So we still have to support them for backward compatibility. But they all should behave like `manager` role now.

**Comment by lakshmiathreya** [comment] 2020-11-06 12:19
@maxceem we dont have any role called "manager" ... i havent added that to my matrix :- https://docs.google.com/spreadsheets/d/1KTlFFsBaGtEJw6wtpELqpYyqORjWmahE_mK34m8WxWM/edit#gid=0

**Comment by maxceem** [comment] 2020-11-06 12:43
@lakshmiathreya the thing is that we 2 kind of roles:

- **Topcoder Roles** - these are roles which any user have in Topcoder, you can edit them when you use Admin App:  
    - `Connect Admin`
    - `administrator`
    - `Connect Manager`
    - `Connect Account Manager`
    - `Connect Copilot Manager`
    - `Business Development Representative`
    - `Presales`
    - `Account Executive`
    - `Program Manager`
    - `Solution Architect`
    - `Project Manager`
    - `Topcoder User` (if user only has this role, it's either customer or community member)
- **Project Roles** - this is the role which user gets when he joins a Project.
    - `customer`
    - `copilot`
    - `manager`
    - `account_manager`
    - `account_executive`
    - `project_manager`
    - `solution_architect`
    - `program_manager`

This leads to the next facts for example:
- `Connect Copilot Manager` can join a project as `customer` and then he would have the same permissions inside that project as regular customer user. (Plus additional permission which he has as a Copilot Manager).
- Note, that after this task is done https://github.com/appirio-tech/connect-app/issues/4101 we make all manager roles equal: `manager` = `account_manager` = `account_executive` = `project_manager` = `solution_architect` = `program_manager`. So even though in code user may have some these roles, they all should behave now like `manager.

Inside code, each permission is determined by 2 roles **Topcoder Role** and  **Project Role** you can see all the permissions we have in Connect App by this link https://htmlpreview.github.io/?https://github.com/appirio-tech/connect-app/blob/feature/unified-permissions/docs/permissions.html see screenshot:

![image](https://user-images.githubusercontent.com/146016/98366987-87e5a480-203d-11eb-81ec-825400753798.png)

So blue labels are **Project Roles** and green labels are **Topcoder Role**.

It would be great if you could use it instead of the Google Spreadsheet. But if it's not comfortable for your needs or the format is not clear, let me know, and let's try to improve it. Generally we can change the format of this document as you like. The benefit of this document is that it's generated from the code, so it always shows the real situation.

**Comment by lakshmiathreya** [comment] 2020-11-06 15:46
thanks for the clarifications @maxceem. The spreadsheet I shared shows the test results of the latest version of Connect. This format is easier for testers to refer and ensure all combinations have been tested.

**Closed** 2020-11-12 15:28 UTC
Labels: P1, QA Pass in Prod, QA Pass in Test
