### ISSUE TITLE
Discussions: no footer on Discussion tab

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#574] opened 2016-12-09 01:20 UTC
<img width="1273" alt="screen shot 2016-12-08 at 5 17 48 pm" src="https://cloud.githubusercontent.com/assets/12552247/21034179/7c907c16-bd6a-11e6-8394-3a0fdabf70ed.png">

Can use the same footer as on the Specification and Dashboard tabs

**Comment by vikasrohit** [comment] 2016-12-12 12:31
Changes are in dev.

**Comment by fnisen** [comment] 2016-12-12 21:48
@vikasrohit the styling is inconsistent. This is the new footer added to Discussions: 
<img width="363" alt="screen shot 2016-12-12 at 1 46 05 pm" src="https://cloud.githubusercontent.com/assets/12552247/21118142/6fca946c-c071-11e6-9f1d-1ff951f24eb5.png">
This is the footer from the Dashboard and Specification:
<img width="348" alt="screen shot 2016-12-12 at 1 46 16 pm" src="https://cloud.githubusercontent.com/assets/12552247/21118146/715b6298-c071-11e6-8c56-c31b8a8f74c8.png">

**Comment by vic-appirio** [comment] 2016-12-12 22:10
Also - recalculate the height of the containers to accommodate the footer height.
![screen shot 2016-12-12 at 1 59 18 pm](https://cloud.githubusercontent.com/assets/8484061/21118866/b1d05894-c074-11e6-8c16-0b0335aec4f7.png)
Expected:
![screen shot 2016-12-12 at 2 08 23 pm](https://cloud.githubusercontent.com/assets/8484061/21118874/b6cb60f0-c074-11e6-9d12-765df74f8e90.png)

**Comment by vikasrohit** [comment] 2016-12-13 07:14
@fnisen I am not able to see the differences in the footer styles in Chrome, however, I can notice the difference in Safari. I tried to find out that difference in Safari, but not able to find one. @vic-appirio Can you please help me here?

Thanks @vic-appirio for noticing the height issue. Now fixed.

**Comment by vic-appirio** [comment] 2016-12-15 00:32
The reason for different font rendering is the css rule `transform: translate3d(0px, 0px, 0px);` applied to the sticky side column on the dashboard page. This causes improper rendering. The correct rendering is on the Messages page, where the `transform: translate...` is not present. This is caused by the `react-sticky` plugin which I don't like as it causes jumps instead of a simple `position: fixed;` system.

Easiest solution for bringing both footers to be the same rendered is adding the first rule to the footer in the case of the discussions page.

**Comment by fnisen** [comment] 2016-12-15 00:38
Also, I'm not sure if you've fixed this and it's not deployed, but I'm seeing some incorrect spacing in the container in Dev (sample project: http://connect.topcoder-dev.com/projects/438/discussions)

<img width="446" alt="screen shot 2016-12-14 at 4 37 13 pm" src="https://cloud.githubusercontent.com/assets/12552247/21207209/b017b472-c21b-11e6-9c3c-aebb19d97c21.png">

<img width="798" alt="screen shot 2016-12-14 at 4 37 21 pm" src="https://cloud.githubusercontent.com/assets/12552247/21207214/b34b3d58-c21b-11e6-8a89-192ab7eba005.png">

**Comment by vikasrohit** [comment] 2016-12-15 06:19
It is not deployed yet. I fixed it after Vic noticed that.

**Comment by vikasrohit** [comment] 2016-12-15 06:53
Thanks @vic-appirio for the help. Fixed with the easiest solution. 😬 
@fnisen Can you please check the height issue of the left panel again. It seems working for me now.

**Comment by fnisen** [comment] 2016-12-15 17:40
@vikasrohit the problem is not with the height, but with the space between the content and the bottom of the container. Here is a current project in production for example: 

<img width="393" alt="screen shot 2016-12-15 at 9 37 54 am" src="https://cloud.githubusercontent.com/assets/12552247/21235102/39ca85e4-c2aa-11e6-9b52-000e7058ceb2.png">

Do you see how there's plenty of space at the bottom? Now look at this, it's cut off at the bottom: 

![screen shot 2016-12-15 at 9 38 54 am](https://cloud.githubusercontent.com/assets/12552247/21235120/5459be66-c2aa-11e6-94ce-1e1e241d27f2.png)

The same thing happens on the container on the right-hand side. Also, when I create a new post at the bottom of the right container, the composer window that opens is cut-off. This wasn't happening before.

**Comment by vikasrohit** [comment] 2016-12-16 13:24
@fnisen Can you please let me know the project for which you are facing this issue? I am still not able to see the cut off in the left panel. And, sorry, but I didn't get the second issue with the right panel.

**Comment by vikasrohit** [comment] 2016-12-22 07:08
@fnisen Please let me know the project id and browser where you are facing the space issue.

**Comment by fnisen** [comment] 2016-12-23 00:36
@vikasrohit I'm on Mac/Chrome, for this project: http://connect.topcoder-dev.com/projects/438/discussions. 

For the left-hand panel, when I scroll down, the content gets cut-off: 
![image](https://cloud.githubusercontent.com/assets/12552247/21444610/22aa8598-c864-11e6-8e0b-5bdb4dfd086b.png)

For the right-hand panel, when I have several posts and try to create a new one, the post button is not visible: http://www.screencast.com/t/tsq37acsee

**Comment by vikasrohit** [comment] 2016-12-23 05:37
Strange @fnisen I tried it again on Mac/Chrome. Even tried in incognito. But I am getting correct results. It seems somehow it is caching (scroll bars are not visible no your browser) the javascript on your machine. Can you please let me know exact version of chrome? Mine is Version 55.0.2883.95 (64-bit)

**Comment by fnisen** [comment] 2016-12-27 18:35
Hey @vikasrohit. I updated my version of Chrome (I'm now running Version 55.0.2883.95 (64-bit), same as you), and I also tested in Incognito in production. I was seeing the same issue. For example, here the scroll bar would not appear at all: http://www.screencast.com/t/FQeL7vbEl7J and here it would not "bounce" at the bottom, but simply sink through: http://www.screencast.com/t/fDd5p09F. 

I tried in dev in Safari and wasn't seeing the issue, so you may be right about caching; don't know. 

Also, there is this issue with the post composer: http://www.screencast.com/t/tsq37acsee. I'd like the user to be scrolled down, with the composer and post button fully visible (similar to the experience on LinkedIn when you're commenting on someone's post).

**Comment by vikasrohit** [comment] 2016-12-28 09:58
Unfortunately, I am still not able to reproduce it, even in production (project id 39), in incognito and normal windows as well.

**Comment by fnisen** [comment] 2016-12-28 23:37
@vic-appirio can you please have a look at the Discussions page in Dev and tell me if you're seeing the same issues as me with the components being cut off?

**Closed** 2017-09-20 22:50 UTC
Labels: Closing_Old_Issues, P1
