### ISSUE TITLE
[$70] Project which we left or was removed from is still visible in the list

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#3059] opened 2019-05-26 08:24 UTC
### Expected behavior
When we leave a project or we are removed from a project by another member we shouldn't see such a project in the project list as we don't have access anymore.

### Actual behavior
When we leave a project or we are removed from a project by another member. We can still see the project in the list even after reloading of the project list. But we cannot access the project details page, which is correct.

### Steps to reproduce the problem 1 (leave project)
- Use non-manager user for testing like `pshah_customer`
- Invite `pshah_customer` user to some project using `pshah_manger` which can send invites.
- Accept the invitation to the project by `pshah_customer`.
- Leave the project by `pshah_cusomer` user.
- `pshah_customer` user can still see the project he just left in the project list. But if he clicks the project to see details, he get error 404.
#### Screenshot/screencast
https://monosnap.com/file/kqkUaWEtAxwJ1GDRanqT6Gv0dW8Hni

### Steps to reproduce the problem 2 (remove from the project)
- Use non-manager user for testing like `pshah_customer`
- Invite `pshah_customer` user to some project using `pshah_manger` which can send invites.
- Accept the invitation to the project by `pshah_customer`.
- Now remove `pshah_customer` from the project using `pshah_manger` user.
- `pshah_customer` cannot see details page as expected. But he can still see the project he was removed from in the project list. 

#### Screenshot/screencast
https://monosnap.com/file/C64JAT5GP9r28rqXzDQ2qgJpU1GIPk

### Issues
I think there are several issues:
1. When the user leave the project he comes back to the project listing and as project list is not updated he can still see the project he just left.
2. After we realod the project listing page we can still see the project user left or he was removed from. This is a server side issue. Most likely ES index is not updated properly. As project list come from the ES index - and it has wrong information. While project details comes from the DB and when we try to access project details we cannot do it, as DB has an actual data.
3. If user has been removed from the project not sure if we should do something. If such user will try to make some actions on the project he would get erros which is ok. If he tries to go to the project listing he would get an outdated list as we don't reload it. I think what can be done here is if user get notification about he was removed from the project, we can check if he still has access to the project and if no - we can show some alert that he don't have access anymore and on clicking `OK` user would be forwarded to the project list, which should be reloaded.
--

#### Environment
- OS: all
- Browser (w/version): all
- User role (client, copilot or manager): client
- Account used: `pshah_customer`

**Comment by vikasrohit** [comment] 2019-05-27 05:52
@maxceem Can we close #3056 now as this issue takes care of that as well?

Now coming to you queries:

I think 1 and 2 both has to be fixed. I vaguely remember that when I saw such project in my project listing page, and when I clicked on that project, it showed me the Join project modal. I am sure about it, but worth testing it before fixing it.

for 3, I don't think we need to do anything further as we always send notifications when a user is removed from a project. Let me know if I missed something from your concern,

**Comment by maxceem** [comment] 2019-05-27 06:07
> @maxceem Can we close #3056 now as this issue takes care of that as well?

I would say in that issues listed another case: when user is invited. While here we are checking cases wher user has been already a member. Also, I could see in that issue project stays after reloading, will check more

**Comment by maxceem** [comment] 2019-05-27 06:08
>  I vaguely remember that when I saw such project in my project listing page, and when I clicked on that project, it showed me the Join project modal. I am sure about it, but worth testing it before fixing it.

Hmm, I guess that's some other issue. Also, as I understand you use an `admin` user, where behaviout could be different, as the issues above are only for `non-poverful` users.

**Comment by vikasrohit** [comment] 2019-05-27 07:01
Nopes, I didn't use my admin powers. I was testing with a customer account `vikasrohit5` in dev.

**Comment by maxceem** [comment] 2019-05-28 06:54
Server-side part, option 2, has been selected in Project Service and PR created https://github.com/topcoder-platform/tc-project-service/pull/307

**Comment by vikasrohit** [comment] 2019-05-31 11:24
@maxceem Do we have separate ticket for handling the front end changes for this?

**Comment by maxceem** [comment] 2019-05-31 11:56
@vikasrohit no, this ticket for both types of changes.

**Comment by maxceem** [comment] 2019-06-29 05:52
The server-side part of this issue has been fixed. Now we have to fix two client-side issues when we `leave project` and when we `reject invitation`.
One issue which we described above, and one issue was logged here https://github.com/appirio-tech/connect-app/issues/3056

### Steps to reproduce the problem 1 (leave project)
- Use non-manager user for testing like `pshah_customer`
- Invite `pshah_customer` user to some project using `pshah_manger` which can send invites.
- Accept the invitation to the project by `pshah_customer`.
- Leave the project by `pshah_cusomer` user.
- `pshah_customer` user can still see the project he just left in the project list. But if he clicks the project to see details, he get error 404.

#### Screenshot/screencast
https://monosnap.com/file/kqkUaWEtAxwJ1GDRanqT6Gv0dW8Hni

### Steps to reproduce the problem 2 (reject invitation)
- Use non-manager user for testing like `pshah_customer`
- Invite `pshah_customer` user to some project using `pshah_manger` which can send invites.
- Cancel the invitation to the project by `pshah_customer`.
- `pshah_customer` user can still see the project he rejected to join in the project list with the `Join button`. But if he clicks the project to see details, he get error 404.

#### Screenshot/screencast
https://monosnap.com/file/Iz4kNvr6myfODZei3ZiTHZ5GmnKFJE

**Comment by sumitdaga** [comment] 2019-07-04 04:54
@maxceem

Please assign this to me !

**Comment by maxceem** [comment] 2019-07-04 05:14
Assigned @sumitdaga

**Comment by sumitdaga** [comment] 2019-07-04 09:46
@maxceem  
i think the screencast https://monosnap.com/file/kqkUaWEtAxwJ1GDRanqT6Gv0dW8Hni  is showing video before server side issue was fixed right?  
i mean when we reload the browser , the project left is now showing up  
so what we need to do for this issue is when user leaves project and goes back to project list we need to reload project list right ?

**Comment by maxceem** [comment] 2019-07-04 09:49
@sumitdaga yep, you are right.

The same thing when a user rejects invitation - fixed server-side and now we should reload client side.

**Comment by sumitdaga** [comment] 2019-07-04 09:55
@maxceem thanks for confirmation!  
is there any other such situation when we are reloading project list when navigating to it ?  
we are doing `this.props.history.push('/projects/')` after leaving project is confirmed by user !

**Comment by maxceem** [comment] 2019-07-04 10:03
> is there any other such situation when we are reloading project list when navigating to it ?

I don't know any such place where we do such a thing.

**Comment by sumitdaga** [comment] 2019-07-04 12:00
@maxceem  
PR at #3141  
although i am curious why we do not load projects each time we go to `/projects`, since there could be situations when we are seeing old data and such there seems no harm in reloading projects ?

**Comment by maxceem** [comment] 2019-07-04 13:20
Thank you @sumitdaga 

IMHO the main reasons not to reload the project listing are:
- to make navigating between project listing and projects fast
- project listing is updated rarely, users join and leave projects not often
- before we had a feature when we navigate from the project listing to the project and after navigating back, we see the same place in the project listing (not sure if still works)

**Comment by vikasrohit** [comment] 2019-07-22 07:38
Verified.

**Closed by vikasrohit** 2019-07-22 07:38 UTC
Labels: ACCEPTED, CF-18, PAID, Released
