### ISSUE TITLE
Interim blank page with logo displayed before displaying login screen

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#1047] opened 2017-07-26 03:32 UTC
Steps to Reproduce
-----------------------------------------------------------------

- Open the URL https://connect.topcoder-dev.com

- Click 'Login' 

- Observe

Actual Result(s)
-----------------------------------------------------------------
- Interim blank page with logo displayed before displaying login screen

Expected Result(s)
-----------------------------------------------------------------
- Must redirect the page directly to the login page when user click on 'Login' button

URL where the Bug Appears
-----------------------------------------------------------------
https://connect.topcoder-dev.com/

Image/Video/JS Log/Console Log (If not attached here, Please check the comments section) 
-----------------------------------------------------------------
https://www.screencast.com/t/CSMIFeqIjdK

![29](https://user-images.githubusercontent.com/4592712/28604181-79b912f6-71e6-11e7-97da-7f3394d73b80.jpg)

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Operating System:** Windows 7 Pro (64bit) 
- **Browser:** Google Chrome 59.0.3071.115 (Official Build) (64-bit) / IE11
- **User role (client, copilot or manager):** not logged in
- **Account used:** NA

**Comment by gondzo** [comment] 2017-07-31 23:26
@chq-matteo the fix hides the banner when the app is loaded, but it was the same before this change. 
@fnisen The tc logo here is just a placeholder until the actual app is rendered. Do we need to remove it at all? Maybe it's better to show something than just empty screen ?

**Comment by vikasrohit** [comment] 2017-08-01 06:53
This was intentional change done long time back. It is not a bug.

**Comment by chq-matteo** [comment] 2017-08-01 08:27
@gondzo it's quite funny, I've checked now with throttling via chrome.  
You are right, what happens is that ng-hide expression gets evaluated only *after* the app.js file loads.  
*But* when app.js finished loading the page we requested has finished loading as well!  
So basically either we rewrite another index.jade for connect or revert my supposed fixes as they were not that useful since @vikasrohit says it is intentional

**Comment by fnisen** [comment] 2017-08-01 23:04
Agree, let's revert. It was intentional to show the logo while we redirect, as Vikas said.

**Comment by chq-matteo** [comment] 2017-08-02 06:43
@fnisen I've already made the pull request yesterday https://github.com/appirio-tech/accounts-app/issues/145

**Comment by fnisen** [comment] 2017-08-02 16:22
Thanks @chq-matteo. I noticed that--was just confirming.

**Comment by gondzo** [comment] 2017-08-02 18:40
changes are reverted. closing the issue!

**Closed by gondzo** 2017-08-02 18:40 UTC
Labels: bug hunt, P1, won't fix
