### ISSUE TITLE
[Add/Edit Feature] - the same name of projects can be saved

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#428] opened 2016-10-01 17:40 UTC
Expected behavior

- The name of added feature must be unique.

Actual behavior

- The same name of feature must not be able to be saved.
   
Steps to reproduce the problem

    Login into application as manager role.

    Edit any existing project.

    Press Add / Edit Feature.

   Create custom feature.

   Set the name test.

   Set On.

    Press again create custom feature.

   Set the name test.

   Set On.

Environment

    OS: Windows 7
    Browser (w/version): Chrome  49.0.2623.112 m
    User role (client, copilot or manager): copilot
    Account used: cp-superstar

see attach!

![test](https://cloud.githubusercontent.com/assets/5114907/19015975/4f51d7aa-8817-11e6-927f-a4e7c2eea4f2.png)

**Comment by mahestro** [comment] 2016-10-04 19:27
Duplicate of #261

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
