### ISSUE TITLE
message: sometimes not able to post reply as button is showing as posting 

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#227] opened 2016-09-28 19:51 UTC
Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create new project
4. go to message
5. Post a status message
6. post reply

Expected Result: should be able to post reply
Actual Result: not able to post 

Enviroment: windows 7, chrome latest 
![image](https://cloud.githubusercontent.com/assets/16131461/18929586/bb5cedfe-85e2-11e6-932e-196146a882aa.png)

**Comment by vikasrohit** [comment] 2016-10-05 07:35
Seems duplicate of #204

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
