### ISSUE TITLE
Added input data should be removed on creating custom features

### ISSUE THREAD

**Issue by swetaipec** [appirio-tech/connect-app#293] opened 2016-09-28 22:23 UTC
### Expected behavior
previous data should not be present on adding new custom features
### Actual behavior
showing the previous added data
### Steps to reproduce the problem

Steps:
1.) Open the application
2.) Login with username sweta.singh
3. create project
4. go to Specification
5. go to Feature section
8. click on Add/Edit features
9. custom features
10. Add new custom features
11. add new features

### Screenshot/screencast

![image](https://cloud.githubusercontent.com/assets/16131461/18934599/39dc6da2-85f8-11e6-93d8-9f1d3dbd045d.png)

Attach or link a resource.

--

#### Environment
- OS: windows7
- Browser (w/version): chrome latest
- User role (client, copilot or manager):
- Account used: maanger

**Comment by mahestro** [comment] 2016-10-04 11:30
Duplicate of #205.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
