### ISSUE TITLE
[Specification] - when an icon style is selected no info about this

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#253] opened 2016-09-28 20:42 UTC
Expected behavior

- Display the selected icon style as checked / selected.

Actual behavior

 - No visual info when user select an icon style.

Steps to reproduce the problem

- Login into application as manager.

- Edit any existing project eg, test.

- Go to Specification tab section.

- Go to "What icon style do you prefer? (Pick one)" and pick any existing icons,

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: manager
Account used: pat_monahan

![icon](https://cloud.githubusercontent.com/assets/5114907/18931530/457af87c-85d5-11e6-8ab7-08e0fec7f466.png)

**Comment by vic-appirio** [comment] 2016-10-04 21:27
This could be a JS-related. Assigning to @vikasrohit

**Comment by mahestro** [comment] 2016-10-08 20:08
@vikasrohit @fnisen  I'm testing again and I can't reproduce it now. Maybe some PR fixed it ? I tried in win IE, FF and Chrome. Not lucky as the first time.

**Comment by fnisen** [comment] 2016-10-13 23:28
OK, closing.

**Closed by fnisen** 2016-10-13 23:28 UTC
Labels: functionality, P0
