### ISSUE TITLE
Process/add ref code from deep link

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1102] opened 2017-08-08 16:58 UTC
Can you please add functionality for automatically adding the ref code from the deep link? For example, https://connect.topcoder.com/new-project/wireframes?refcode=Wipro would open a Wireframes project with "Wipro" as the ref code already filled in?

**Comment by vikasrohit** [comment] 2017-08-09 10:51
Done. Changes are in dev. Please let me know if any further changes required for the same.

**Comment by fnisen** [comment] 2017-08-09 19:07
@vikasrohit looks good. By the way, if you don't think that URL structure is appropriate, please feel free to change. I just made something up quickly. 

Also, can you limit the ref code to 7 characters? I know we allow more on the back-end, but that's been the front-end limit. If someone enters a longer one, we can just cut it off.

**Comment by fnisen** [comment] 2017-08-09 19:25
One more thing, after you fix this, can you please deploy it to prod (along with any other fixes we'll have). It's urgent for Tony for his Topgear work.

**Comment by vikasrohit** [comment] 2017-08-10 04:01
Done. However, I think @fnisen we should give kind of warn message (just below the project name and ref code components) to the user) to alert them it has been truncated. I could have included that change, however, we don't have style guide for warning messages, I guess. Please correct me if I am wrong.

**Comment by vic-topcoder** [comment] 2017-08-10 15:14
the best approach for limited inputs is to display the limiter:

![screen shot 5](https://user-images.githubusercontent.com/8484061/29177589-ebb0dd8a-7da3-11e7-82ab-28ee2051fe48.png)

**Comment by fnisen** [comment] 2017-08-10 15:36
@vic-topcoder the entry would happen in the URL, so the rate limiter is not that applicable. Let's discuss by phone.

**Comment by fnisen** [comment] 2017-08-10 18:51
@vikasrohit discussed this with Vic.

- The truncation warning shouldn't be an issue b/c the URL would only be created/passed by our team and likely followed from some button or link on a marketing page; regular customers should not be creating/editing the URL
- However, if we do get someone coming to Connect with a prefilled ref code, let's turn off the ref code field on the project creation screen, so that users don't edit it. We want to make sure that the correct value is passed for our tracking purposes.

**Comment by vikasrohit** [comment] 2017-08-11 05:35
Okay. I can put adhoc check for disabling the refcode when it loaded from query string. However, I think it may not be needed because user can not update the refcode to have invalid value. It has to be below 7 characters while entering in the text box. Only case where it makes sense is that if we don't want user to alter the refcode in case it is coming from URL, which I think is the use case you described above. And if we implement this, I can see a use case where it can cause bit usability problem which is when the user (may be our internal sales guys) has a link which contains refcode which is not valid any more or they just want to change that. Only option for them in such cases would be to alter the URL instead.

**Comment by vikasrohit** [comment] 2017-08-11 12:48
Done. Please check in dev now.

**Comment by fnisen** [comment] 2017-08-14 13:50
@vikasrohit something broke. Not seeing the refcode param work at all right now. The correct template loads, but refcode field is there and empty (and can be filled out).

**Comment by vikasrohit** [comment] 2017-08-14 14:04
@fnisen  Just checked http://connect.topcoder-dev.com/new-project/visual_design_prod?refCode=wipro and it seems to be working for me.

**Comment by fnisen** [comment] 2017-08-14 14:15
@vikasrohit my bad. I forgot about the camelCase. OK, it is indeed working. However, can you turn off the ref code field entirely? As you said, otherwise we have a usability issue with it being visible, but not editable. I think in the case of it being passed as a param, the user doesn't need to know about the code, similar to a utm code.

**Comment by vikasrohit** [comment] 2017-08-14 14:20
Yes, I can remove it as well. I guess, it is acceptable to hide, though just from my thinking, how would user know that it is using correct one? I mean if accidentally user modified the ref code in the URL, it would use that wrong code.

**Comment by fnisen** [comment] 2017-08-14 14:25
Well, this is what we're trying to address: keep the user from modifying the code by not exposing it. Of course the user could modify the URL, but that's unlikely. Most users are not paying much attention to the details of the URL and, unless they're pretty technical, wouldn't know that the code was being passed and so wouldn't think to modify it. 

The code is supposed to be controlled by our team. We would tell the user "click this link" or "press this button" and would not expect the user to verify the code. In case we tell them to just go to Connect, we would say, use reference code "foo" and have them enter it.

**Comment by vikasrohit** [comment] 2017-08-14 14:30
So should we remove the ref code from being displayed in project edit?

**Comment by fnisen** [comment] 2017-08-14 14:51
If the user came to us from a deep link with a ref code param, we probably created the link for the user and don't want them editing it. If they didn't come from a deep link, they should be able to enter it and edit it.

Could we make it visible/editable in cases where they entered it and not visible/editable in deep-link param cases? Or does this introduce a new state you have to track?

The other issue is whether managers should be able to edit it in both cases... I think yes.

**Comment by fnisen** [comment] 2017-08-24 00:24
@vikasrohit I'm still seeing the ref code on the spec form when I use a deep link. For example: https://connect.topcoder-dev.com/new-project/wireframes?refCode=Wipro.

![screen shot 2017-08-23 at 5 23 36 pm](https://user-images.githubusercontent.com/12552247/29644012-db7f97d8-8827-11e7-934c-6f6dae120ced.png)

**Comment by vikasrohit** [comment] 2017-08-24 05:12
I guess we discussed that it is okay to have it there in non editable form because user would see it(in non editable mode) anyway when they would go to edit the project.

**Comment by fnisen** [comment] 2017-08-24 20:47
Right, I think that's what I was asking about above: "Could we make it visible/editable in cases where they entered it and not visible/editable in deep-link param cases? Or does this introduce a new state you have to track?" I agree with you about keeping it consistent. I would still rather hide if it's not difficult. Thanks.

**Comment by vikasrohit** [comment] 2017-08-25 05:16
Okay. It should not be difficult. Would do it.

**Comment by fnisen** [comment] 2017-09-07 00:44
@vikasrohit it's working correctly initially, but then is still visible in the spec. I'm using this user account to test: christina_uw/topcoder123!

![screen shot 2017-09-06 at 5 43 03 pm](https://user-images.githubusercontent.com/12552247/30140664-0b7ed7e2-932b-11e7-893e-93e7234eedc0.png)

![screen shot 2017-09-06 at 5 43 58 pm](https://user-images.githubusercontent.com/12552247/30140665-0e7d44ec-932b-11e7-9956-81059b98270c.png)

**Comment by vikasrohit** [comment] 2017-09-07 04:44
@fnisen I didn't change the spec page because managers might need the ref code to view. I can try hiding it for non managers though.

**Comment by fnisen** [comment] 2017-09-14 02:36
@vic-topcoder looping you in so you can check whether the experience for hiding the ref code is like you imagined.

**Comment by mtwomey** [comment] 2017-09-25 19:03
@vikasrohit Chatting w/Victor - he's confirmed we don't want the ref-code to show, even for managers.

**Comment by vic-topcoder** [comment] 2017-09-25 19:06
This is what I see on Dev right now -  ref code still visible; let's hide it:
![screen shot 1](https://user-images.githubusercontent.com/8484061/30826067-f6287f38-a1e9-11e7-995a-53c9b503cb77.png)

**Comment by vikasrohit** [comment] 2017-09-26 05:23
@vic-topcoder Please change `refcode` to `refCode`. The issue raised here is to hide ref code from the Edit project (specification tab) as well.

**Comment by vikasrohit** [comment] 2017-09-26 08:11
@mtwomey It is deployed. Only thing remaining is to hide refCode in Project Edit screen (specification tab). Right now it should be visible there for both managers and non managers. I can hide it for both, however, I don't think we should hide it for managers though. They won't have any way, in project details pages, to see the refCode for a project. They can still see ref code on project listing page, though.

**Comment by vikasrohit** [comment] 2017-10-03 05:31
Closing the issue as it has been open for very long time and the original requirements are fulfilled. @vic-topcoder @mtwomey we can open a new issue for handling hiding/showing ref code in project edit mode.

**Closed by vikasrohit** 2017-10-03 05:31 UTC
Labels: P1
