### ISSUE TITLE
Escape [esc] key stroke is not function in Mac OS. 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3567] opened 2020-01-29 07:29 UTC
### Expected behavior
The esc keyboard should close the window after hitting it.

### Actual behavior
After pressing the Esc button in the keyboard, the window is not getting close.

### Steps to reproduce the problem
- Login as Manager.
- Go to the On-Demand section. 
- Fill the required fields to create a new project. 
- Submit the Create Project button. 
- The congratulation window pops-up. 
- Press the esc key from the keyboard. 

### Screenshot/screencast
Attach or link a resource.
<img width="967" alt="escape" src="https://user-images.githubusercontent.com/57211549/73336052-e7d24200-4298-11ea-8de5-92a6321cd2bb.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

Label:
@bug-hunt-helper help
@bug-hunt-helper add label: Label Name Functional, Label Name P1

**Comment by CreeyaSean** [comment] 2020-01-29 07:42
Label:
@bug-hunt-helper help
@bug-hunt-helper add label: Label Name Functional, Label Name P1

**Comment by CreeyaSean** [comment] 2020-01-29 07:48
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment] 2020-01-30 14:50
@CreeyaSean , Duplicate of #3556 
Closing this, will be tracked in #3556

**Closed by SathyaJayabal** 2020-01-30 14:50 UTC
Labels: BugHunt_JanRelease, Functional, P1
