### ISSUE TITLE
[$150] Fix text area auto-sizing

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1368] opened 2017-11-29 03:56 UTC
We use a react plugin to auto-size text areas on project specification page. Right now the plugin doesn't work all the time.

 

**Goal** : All text areas should be sized to fit all the text without scrolling in all states (normal, active, disabled).

 

Current state:

Screen Shot.png (https://topcoder.aha.io/attachments/6493680258833768883/token/2f573aa94784c7f9e3b0e71e0e7ee39c402994845aec7a8cbc0331cefa1ddf88.download?size=original)

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-111

**Comment by zjuasmn** [comment] 2017-12-05 02:02
PR submitted. https://github.com/appirio-tech/connect-app/pull/1413

**Comment by vic-topcoder** [comment] 2017-12-20 03:52
- [ ] - The text area is still smaller than the text and there's a tiny scroller. The more text lines there are, the bigger the difference - something is not quite right in pixel count.
![screen shot 4](https://user-images.githubusercontent.com/8484061/34190531-2d80c7fc-e4f6-11e7-83bc-d49cb2d9c758.png)


- [ ] - The size is lost after reloading the page - the text area should always keep the size consistent to its contents upon page reload/save/etc. events.
![screen shot 3](https://user-images.githubusercontent.com/8484061/34190523-26d9456e-e4f6-11e7-919d-3c0890c4e278.png)

**Comment by vic-topcoder** [comment] 2017-12-22 23:04
Do we have ETA on this one?

**Comment by gondzo** [comment] 2017-12-22 23:50
@ThomasKranitsas any ideas on the cause here ?

**Comment by ThomasKranitsas** [comment] 2017-12-22 23:54
Sorry, I'm still investigating... I tried few hacks to fix it but none of those worked.

**Comment by vic-topcoder** [comment] 2017-12-22 23:58
Ok, let's move it for CF6

**Comment by ThomasKranitsas** [comment] 2017-12-22 23:59
Ok, I'll focus on the other tickets

**Comment by kevinkid** [comment] 2017-12-29 19:43
I may have a solution for this @ThomasKranitsas @vic-topcoder on [this](https://github.com/appirio-tech/connect-app/pull/1574/commits/7892190cdc83d882abc8459989e50e462abbb09b) commit. Turns out the default React textarea already does the auto-resize.

**Comment by ThomasKranitsas** [comment] 2017-12-29 20:02
This breaks the `Notes` fields in the `New project` page.

**Comment by ThomasKranitsas** [comment] 2017-12-29 20:03
Actually, it breaks the `Notes` field everywhere 🙂 I'll see if I can do any hack to fix it

**Comment by kevinkid** [comment] 2017-12-30 10:48
Okay let me also look into it. Please assign me

**Comment by kevinkid** [comment] 2018-01-01 11:20
The plugin miscalculates the height , a better solution would be to debug it as @zjuasmn said but i  hope [this](https://github.com/appirio-tech/connect-app/pull/1574/commits/78442e9d52c5ee875a588269c93eafa7d0352d2f) commit fixes it.

**Comment by ThomasKranitsas** [comment] 2018-01-01 19:44
@kevinkid this seems to do the trick. I've closed your PR and I will create a new one as your has ~145 commits.

**Comment by vic-topcoder** [comment] 2018-01-03 20:12
Seems to be working. The only problem is how the plugin renders after we get the "value" of the text area. It would be neat to actually calculate the height of the area before we render the page, but I guess that's an optimization.

**Comment by kevinkid** [comment] 2018-01-10 07:10
@vic-topcoder the plugin modifies the height after rendering. Am not sure but also changing the height after the plugin modifies the height would end up in an a loop.

**Comment by vic-topcoder** [comment] 2018-01-10 23:22
@gondzo what is the status of this issue?

@kevinkid - the optimization that I'm talking about is to run the plugin before the page is rendered/populated with content. Right now the page is rendered, content is populated, and then the plugin resizes the text area. This results in a jump after the page is rendered and this is a problem as it creates jarring experience. There is no need to run the plugin twice or in an endless loop.

**Comment by Mukhammadali** [comment] 2018-01-11 05:19
Guys, Could you assign me

**Comment by gondzo** [comment] 2018-01-11 15:46
the plugin uses a hidden textarea (added to document.body) to calculate height for the text area. it sets width property correctly, but it looks like the hidden text area does not respect it. see this screencast (hidden textarea changes the width briefly) https://www.screencast.com/t/vlk9EgkiLU
I'm not that great with css, so I'm not sure what would cause the browser to ignore width value and expand it to 100% body width. Any ideas @vic-topcoder ?
Setting both width and max-width properties on the hidden text area solves the issue, but doing that would require us to fork the react-textarea-autosize library.

**Comment by vic-topcoder** [comment] 2018-01-12 02:04
Maybe we can use another plugin or just port the method for resizing of the text area? I found https://github.com/buildo/react-autosize-textarea as a component, which is based on the jQuery plugin.

Not sure how using a hidden textaarea would help us resolve the page flicker, ideally the text areas are all calculated before rendering, not having to do a second render after load.

**Comment by gondzo** [comment] 2018-01-26 18:14
Prize increased

**Comment by afrisalyp** [comment] 2018-01-30 00:36
Can I work on this?
I have registered on bug bash 07.

**Comment by afrisalyp** [comment] 2018-02-02 15:03
is this issue still open?
I think I can fix it but no one adds me to this git repo.

**Comment by gondzo** [comment] 2018-02-02 17:20
@afrisalyp - I've added you to the repo, you can assign it to yourself

**Comment by afrisalyp** [comment] 2018-02-03 06:58
PR submitted to this repo and appirio-tech/react-components
#1671
https://github.com/appirio-tech/react-components/pull/284

But it seems still not working on Firefox, please review.

**Comment by gondzo** [comment] 2018-02-04 14:29
thanks @afrisalyp 
We still have that short transition while calculating the size, but IMO that's the best we can do without changing the autosize library.
@vic-topcoder

**Comment by vic-topcoder** [comment] 2018-02-06 18:23
It's good enough for the time being. Definitely don't like this interaction, so when we start fixing the page rendering/new form styles, we need to change this behavior.

**Closed** 2018-02-13 19:56 UTC
Labels: ACCEPTED, Aha!:Under consideration
