### ISSUE TITLE
Can't update phase dates when phase is active. 

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2457] opened 2018-08-29 16:14 UTC
### Expected behavior
I tried to update the date of an active phase and the edit view show my updates by the save does not seem to have taken effect.

### Actual behavior
Date on the phase view, the light grey text is not updated.

### Steps to reproduce the problem
Try to update the phase to the actual dates 2nd time.    I want to change the start date from 8/21 to 8/15
![image](https://user-images.githubusercontent.com/1180747/44800533-3d725e80-ab7c-11e8-8ead-c7ca8532cb6b.png)

click pencil and I can see that my last update of 8/15 is there  (this is the second time I tried this.
![image](https://user-images.githubusercontent.com/1180747/44800597-6abf0c80-ab7c-11e8-81c3-18e5d828f851.png)
but it does not reflect the change in the phase list or cascade the dates down.   Note that  Update Phase button is disabled
so I change the title to Exploratory phase challenge.   and the dates in the sub-heading still don't change
![image](https://user-images.githubusercontent.com/1180747/44800654-9215d980-ab7c-11e8-8dd0-d83676212de1.png)

Aha! Link: https://topcoder.aha.io/features/TCCONNECT-412

**Comment by maxceem** [comment] 2018-08-30 04:35
There are a few things which lead to such behavior:
- as we have timeline and milestone, the dates for the phase are controlled by milestones
- when we mark phase `In progress` so it becomes active, the first milestone also becomes active. 
   When milestone becomes active we save the `actualStartDate` of the milestone and show it for the milestone and phase start date. As currently we show the **actual start date** rather then **planned start date** it's not affected by the update after.

As I see there could be few ways to clarify this behaviour:
1. Disable start date in the edit form so it cannot be updated for active phase as it's already started by fact.
2. Keep it editable and when we update an active phase we will update `actualStartDate` for the milestones, but we kind of loose the actual meaning of this property. In this case we may consider removing it. Also, it's clear how we can update `actualStartDate` for the first milestone. But for other milestones, we either have to make it same as `startDate` or calculate the **shift** for the whole timeline and after apply this shift to the `actualStartDate` of every active milestone.
3. We can also combine these two approaches. We can let `actualStartDate` to be changed when there is only **one** milestone is active. But as there more than one milesotnes are active, means some are already compoleted, we disable start date field for the pahse and do not let it to be changed anymore.

**Comment by RishiRajSahu** [comment] 2018-08-30 06:19
@acshields @vic-topcoder  We need to disable editing the startDate of active phase as it could lead to mismatch in date related data of already completed milestones of the phase

**Comment by vic-topcoder** [comment] 2018-08-30 14:28
@kbowerma - why would you need to modify a date once a phase has started? What is your goal here? 

@RishiRajSahu @acshields - Agreed, once a phase is active, we can't change the beginning time as it is a historic record of work started, and we don't want to modify such records. On the other hand, if the phase is switched on by mistake, we have no way to recover from error. It would be nice to think about how we can prevent errors. I am inclined to have a modal warning on for when a phase is switched to active to prevent errors.

**Comment by kbowerma** [comment] 2018-08-30 15:30
@vic-topcoder it is quite common to get the green light to start and then have to wait on some sort of approval.

I thought I might have to move it back to draft to change the dates but I could not get that to work either.

**Comment by RishiRajSahu** [comment] 2018-08-31 05:33
@vic-topcoder 
> I am inclined to have a modal warning on for when a phase is switched to active to prevent errors.

we already have that in place

<img width="770" alt="screen shot 2018-08-31 at 10 55 02 am" src="https://user-images.githubusercontent.com/11248478/44894237-79d4c480-ad0c-11e8-98c0-82afdb6f6ebb.png">

@kbowerma regarding - 
> then have to wait on some sort of approval.

If after reaching any milestone(even if its the first milestone just after activating a phase) one has to wait for some sort of pre-work, one can always request extension for that milestone, each milestone has the ability of requesting an extension. Hope that helps !

**Comment by RishiRajSahu** [comment] 2018-09-11 06:54
@vic-topcoder @kbowerma @acshields ping !

**Comment by acshields** [comment] 2018-09-11 15:58
I would be interested to hear @kbowerma thoughts on @RishiRajSahu point above.  Does leveraging an extension work in this scenario?

**Comment by vic-topcoder** [comment] 2018-09-17 20:10
Had a quick call with Kyle, his feedback is:

> When you start a project 50% of the time the customer is not ready or we need to really change the start date to the actual start date. We (architects) do that all the time to represent actuality of project execution. If you put a restriction on modifying the start date and a project is delayed, we have to delete the whole phase and start over, which is very frustrating.


There are 2 possible solutions to the problem:

A. Allow change of dates on a timeline while in Active state as well, but lock them once phase is delivered (Kyle's ask).
B. Train and explain that a project phase should be set to Active only when the customer is ready to start the work (not desired).

The question is really what is the process we want to implement on the customer portal at this time - restrict the timeline editing, or allow changes. @acshields - the decision is a product-specific now, pushing this issue to you.

**Comment by acshields** [comment] 2018-09-17 20:40
@vikasrohit @vic-topcoder @RishiRajSahu  - How does **Option A** impact the risk to mismatch/discrepancy in date related data that Rishi brought up above?

**Comment by maxceem** [comment] 2018-09-18 00:32
@acshields
As I understood from this comment https://github.com/appirio-tech/connect-app/issues/2457#issuecomment-417362194 of **kbowerma**. The main case when managers want to change start date is if a project was formally started but in reality they wait for customer get ready.
Maybe we can modify the approach **A** and let managers change `startDate` of the phase as long as **NO** milestone is completed. Which is equivalent to the fact that actual work isn't started yet.
This way we shouldn't get mismatch/discrepancy in dates described by **RishiRajSahu** https://github.com/appirio-tech/connect-app/issues/2457#issuecomment-417202861

**Comment by RishiRajSahu** [comment] 2018-09-18 05:58
@acshields the mismatch/discrepancy I was pointing is as below - 
1. Suppose today is 17th Sept and phase startDate was of 15th Sept.
2. Suppose first milestone is completed already which has startDate of 15th Sept and endDate of 16th Sept.
3. Second Milestone is in progress since the completion of first milestone.

Now, as per the requirement of kyle if user updates the startDate of phase to 17th Sept or any other date, 
- we will either see **mismatch** in startDate of phase and startDate of first milestone (which should be same ideally)
**OR** 
- Even if we update the startDate of completed milestone as well to 17th this will be **discrepancy** in actual data of that completed milestone


To solve the above issue(taking inspiration from what vic has mentioned about not allowing change in startDate of **phase** once delivered) , **we should lock the change in startDate of phase once the    
  " _first milestone is marked as completed "_.**

**Comment by acshields** [comment] 2018-09-18 16:58
Thanks @RishiRajSahu.  Explanation above makes sense - Agreed we should lock the change in start date once first milestone is marked as complete.

**Comment by RishiRajSahu** [comment] 2018-09-19 05:28
@maxceem we are all clear with the requirements now.

**Comment by maxceem** [comment] 2018-09-19 05:29
@RishiRajSahu yes, it's clear now.

**Comment by RishiRajSahu** [comment] 2018-09-25 14:38
@acshields I understand we came on consensus earlier but as proceeded to make changes I'm still not feeling fully convinced about allowing changing the startDate once the phase is activated.
we have two different date data associated with milestone/phase `startDate` and `actualStartDate`, In **draft/planned** status phases we update both dates but once the phase is active we set the `actualStartDate` only and ideally as per me we shouldn't update actualStartDate multiple time, the field itself identifies the confirmation from user about the activation and by allowing changing the `actualStartDate` again we are hiding the miss from our side(for example the time taken in approval, gathering specs) and whole definition of actualStartDate is defied.

So right now what happens is, if we are not able to complete the milestone within the expected completionDate it shows the delay warning to us and I think that's the valid way to track the miss by us.

And in the first place we already have solution for this which i mentioned in the beginning of this issue https://github.com/appirio-tech/connect-app/issues/2457#issuecomment-417556475 - 
1. Requesting an extension for the respective milestone.
2. Or would like either letting milestone getting delayed beyond the expected endDate and show the delay warning ( To correctly track the miss from our side)

fyi - @vikasrohit

**Comment by vic-topcoder** [comment] 2018-09-25 22:12
I would like to make things clear going forward with phase and timeline. I have the chance to work with project plans in production, and it makes quite a sense to do the following:

When you plan a phase start, you do not actually indicate that the work is started. Currently we call this date `phase start date`. If we keep it as intended start date, and not actually mapping this to any milestone active state/work, it would be great.

When you start work, or do modify the phase timeline, you want to edit all the milestones (including the first one), and this is where we're missing some logic/usability right now:
- First mimlestone has no start, only duration
- Phase status is not controlled by timeline start, but the opposite - timeline start is controlled by phase start (confusing!)
- Changes to planning are not reflected if your first milestone is changed/delayed, not ready, and the whole timeline becomes confusing.

### Suggestions:
- Use the phase start date/end date for planning purpose only
- Remove "active phase" switch from a phase, and allow the Timeline to update the state. I want to switch the first milestone to active and that would set the phase status.
- Unify all milestones to have a start and end.

**Closed** 2021-05-28 18:00 UTC
