### ISSUE TITLE
Test Environment: v5 - Invitation link has Dev Env link, So this breaks the flow

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3399] opened 2019-12-09 10:18 UTC
1. As a Copilot Manager (topcoderconnect+CopilotManager@gmail.com), create a new project
2. Invite Topcoder Admin user to the project
3. **Open the invitation mail and click Join Project button present in the email (Observe that it goes to Dev environment)**
4. Then open the dashboard of Topcoder Admin User in Test Enviornment
5. Click on the project for which invitation was sent
6. Observe that it shows a popup asking the user to Join or Cancel
7. Click Join and observe

Actual:
Its shows the below error. I think its because of Step:3

Expected:
User should be able to join or cancel the project in Test environment

![image](https://user-images.githubusercontent.com/5114190/70427756-5534d400-1a9b-11ea-96de-c1b96e249b17.png)

**Comment by nithyaasworld** [comment] 2019-12-09 10:20
cc: @lakshmiathreya

**Comment by RishiRajSahu** [comment] 2019-12-11 03:28
@nithyaasworld it should be successful wether its dev/Test env because we have same data store so should behave same.
1. Is it still happening or was a transient issue (could be because of user not returned by member service) ?
2. If still persists could you check the same on Dev env if reproducible ?

**Comment by maxceem** [comment] 2019-12-11 06:12
I haven't managed to reproduce this issue as per steps provided.
@nithyaasworld could you please share the project you've created when you reproduce this issue, and which admin user did you use?

I'd like to try to click Join button as that admin to observe this issue.

**Comment by vikasrohit** [comment] 2019-12-12 09:50
I think we can safely ignore this issue as there are not multiple parallel environments on production. This might happen in dev because the email service is same for both v4 and v5 and it might be sending emails with `connect.topcoder-dev.com` as domain, even though the event was generated on `connect-test01.topcoder-dev.com`.

**Comment by vikasrohit** [comment] 2019-12-24 10:33
Closing.

**Closed by vikasrohit** 2019-12-24 10:33 UTC
Labels: 2.4.16, P1, Test Environment, Won't Fix
