### ISSUE TITLE
Screen loading continuously if Phase start date set as past date

### ISSUE THREAD

**Issue by sandhiyakavi** [appirio-tech/connect-app#4355] opened 2021-04-16 06:02 UTC
Description:

1. If Start Date  set as past date and Drafted. While trying to publish the same. Getting Error "Duration must be a number"

![image (1)](https://user-images.githubusercontent.com/55895538/114978200-ddaf5a00-9ec3-11eb-8f74-2afdc165644b.png)

2. While phase creation If Start Date set as past date and Click Publish. Loading for a long time with error msg in console.
3. After this not able to create phase with normal dates (ie. From current date to Future date). Loading for a long time.

https://user-images.githubusercontent.com/55895538/114978553-4e567680-9ec4-11eb-8669-c297966fd822.mp4

**Comment by SathyaJayabal** [comment] 2021-04-16 06:05
cc @vikasrohit

**Comment by sandhiyakavi** [comment] 2021-04-16 08:28
@vikasrohit The same issue is happening if start date set as future date

**Comment by vikasrohit** [comment] 2021-04-19 13:54
@mirzailhami I reviewed the changes for the fix of this issue. Though it is working after this fix, I am not sure why we need this fix because on production it is working fine without passing `duration` to the payload.

<img width="701" alt="Screen Shot 2021-04-19 at 7 22 25 PM" src="https://user-images.githubusercontent.com/2417632/115247825-c29f4d00-a144-11eb-9561-db349b5011e4.png">

**Comment by mirzailhami** [comment] 2021-04-19 14:08
@vikasrohit you need to check dev endpoint using the same payload, it was showing error without payload.

**Comment by vikasrohit** [comment] 2021-04-19 14:11
that is what confusing me, there is no change between dev and prod in code.

**Comment by mirzailhami** [comment] 2021-04-19 14:18
@vikasrohit I think it might be caused by my latest change. In edit form I use TextBox to show duration as it tied to model variable.

**Comment by vikasrohit** [comment] 2021-04-19 14:28
oh, yes. Nice catch. Lets revert that after an hour or so ( we have demo in next hour)

**Comment by sandhiyakavi** [comment] 2021-04-20 05:25
Verified on Dev Env. Able to create Phases with past or future dates

![image](https://user-images.githubusercontent.com/55895538/115341830-36dcfd80-a1e4-11eb-90e4-0a6e185229de.png)

**Comment by vikasrohit** [comment] 2021-04-20 06:30
Thanks @sandhiyakavi for testing, however, we need to reverify it once we merge the PR https://github.com/appirio-tech/connect-app/pull/4357 because we have improved the way fixed the issue. We would again mark it ready for QA once the PR is merged.

**Comment by sandhiyakavi** [comment] 2021-04-20 10:15
Verified on Dev Env. Working as expected.

![image](https://user-images.githubusercontent.com/55895538/115379715-c0082a80-a20c-11eb-90ff-fdd0d47ac875.png)

**Comment by vikasrohit** [comment] 2021-04-20 10:23
Thanks @sandhiyakavi for double verification.

**Comment by drasticdpk** [comment] 2021-04-22 12:34
Verified.
![image](https://user-images.githubusercontent.com/25297859/115714808-3e90d380-a397-11eb-8d18-1ca48194e753.png)

**Closed by drasticdpk** 2021-04-22 12:34 UTC
Labels: P1, Project: Project Plan Simplification, QA Pass in Dev
