### ISSUE TITLE
Improve red cue notifications for phases

### ISSUE THREAD

**Issue by maxceem** [appirio-tech/connect-app#2966] opened 2019-04-19 07:45 UTC
Follow up for the issue https://github.com/appirio-tech/connect-app/issues/2455

Form @vikasrohit 
I think we have couple of options for that:

1. Hide the red dot after some delay (5 seconds)
2. Show a red dot on the specific milestone and fade that away with some delay (5 seconds) OR flash the background of the appropriate milestone so that user can notice something changed with that milestone
3. We can show a simple notification bar just below the Timeline tab which says something like Timeline has been modified since you last visited the phase. Mark as Read X and let the user explicitly mark the notification as read. Other option within this approach could be to auto hide this after some delay (e.g. 5 seconds)

**Comment by vikasrohit** [comment] 2019-06-04 08:29
@maxceem I think we are good with our last fix for adding some delay in fading out the red cue for Timeline tab. Now for further improvements, I guess we need inputs from product and design team to improve this process across all items in the project.
For now, I have moved it to next release, however, I don't think we are going to handle it in near future.

**Comment by vikasrohit** [comment] 2019-06-04 08:36
Closing this one as well, as this is one is specific to the phases which are going to have major restructuring in very near future. So, we would create new ticket to improve the indication of changes caused by new notifications, in the UI.

**Closed by vikasrohit** 2019-06-04 08:36 UTC
