### ISSUE TITLE
[Pagination] - keep fixed pagination option displaying 5 pages.

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#372] opened 2016-09-29 17:53 UTC
## Expected behavior
- The pagination option must be set as to display 5 pages( <- Prev 1 2 3 4 5 Next ->).
## Actual behavior
- The pagination display all pages.
## Steps to reproduce the problem
- Login into application as connect user role.
- Go to Dashboard.
- See pagination control.
## Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

see attach!

![pagination](https://cloud.githubusercontent.com/assets/5114907/18965742/15512efc-8687-11e6-8877-1bd24e5e18af.png)

**Comment by mahestro** [comment] 2016-10-04 15:54
Not valid. It's intentional.

**Comment by fnisen** [comment] 2016-10-15 00:32
This will break eventually, so we should implement the original design.

**Comment by fnisen** [comment] 2016-12-06 20:31
Here is the required design: 
![99b22756-d1ed-44af-a14a-1d108d55373f](https://cloud.githubusercontent.com/assets/12552247/20942355/e60b29d2-bbaf-11e6-94bb-1b027af905c5.png)

https://drive.google.com/open?id=0B1LbmKnex41fTDhpM3NuWmNGU3M

**Comment by vikasrohit** [comment] 2016-12-22 09:10
@fnisen I have committed and merged changes for this issue into dev. Can you please check the behaviour and let me know if it is serving the purpose or need any modification.

**Comment by vikasrohit** [comment] 2016-12-22 10:20
@fnisen I have committed and merged changes for this issue into dev. Can you please check the behaviour and let me know if it is serving the purpose or need any modification.
One of the known issue/limitation is that as of now user can enter any value in the "Go to page" tooltip i.e. we don't have validations for preventing user from entering a page which does not exist. I am not sure how to prevent this i.e. how to show the error if user enters a value which does not exist. IMO, for day to day usage, user won't be entering out of bound values because they can easily see the min and max possible value of the pages.

**Comment by fnisen** [comment] 2016-12-23 00:22
@vikasrohit it's working well. Yes, agree, no need for validation. However, if I enter a page that doesn't exist and get "no results," when I click back, I also get "no results" again, which is incorrect. 

Also, noticed a few styling issues: 
<img width="284" alt="screen shot 2016-12-22 at 4 14 02 pm" src="https://cloud.githubusercontent.com/assets/12552247/21444484/a85d26d4-c862-11e6-834d-993fe8ce3c5c.png">
Ellipsis ("...") should be at the bottom of the cell, per the design.

<img width="322" alt="screen shot 2016-12-22 at 4 14 07 pm" src="https://cloud.githubusercontent.com/assets/12552247/21444491/bc666460-c862-11e6-9dcb-de848bc030c2.png">
Page selection tool tip is styled incorrectly (wrong colors and fonts).

**Comment by vikasrohit** [comment] 2016-12-27 10:13
@fnisen I have made changes for the issues you pointed out above. From the styling purposes, I need access to parent folder of the specs in drive as I am not able to see the specs page properly with the link given and neither I am able to find these specs in 'Connect' drive folder.

And for the issue with "no results" page when hitting browser back button, I have found that this is an existing issue. To reproduce it on production, just go to any page, other than 1st, after page load and then hit back button. Ideally user should be taken to previous page (which is page number 1 in this case). However, only URL changes in the browser with page param being 1 but content does not. It is still showing the old results.
Anyways, Found root cause and fixed it. :)

**Comment by fnisen** [comment] 2016-12-27 18:46
@vikasrohit yes, here is the link: https://drive.google.com/open?id=0B1LbmKnex41fVVJwVzJvVFFIVE0. Thanks for creating the light theme and agree with you regarding the component approach. Can you please adjust the font on the tool tip, as well? 

The back button is working correctly now. 👍

**Comment by vikasrohit** [comment] 2016-12-28 10:26
Styled tooltip font and box shadow to match it with specs. Please let me know if it still missing some thing.

**Closed by vikasrohit** 2016-12-28 10:26 UTC
Labels: enhancement, P2

**Comment by fnisen** [comment] 2016-12-28 21:58
Beautiful, thank you.
