### ISSUE TITLE
Select product button not visible in Mobile UI

### ISSUE THREAD

**Issue by deepakanbarasan1** [appirio-tech/connect-app#2102] opened 2018-06-28 14:44 UTC
**### Expected behavior**
Describe:

When user adding a phase should ask user to select a product for the phase.
Project Name : Test Mobile project for 2.4.3 & Test Mobile project for 2.4 Select Product testing

**### Actual behavior**
Describe:

When user adding a phase, select product button not visible for the phase. 

**Overall Description :**

I have created new project in Mobile UI, I have tried to add new phase.

When user adding a phase should ask user to select a product for the phase. Select product button not visible in Mobile UI.

Project Name : Test Mobile project for 2.4.3 & Test Mobile project for 2.4 Select Product testing

New Project :
Test Mobile project for 2.4 Select Product testing
![adding a phase should ask user to select a product for the phase_new project](https://user-images.githubusercontent.com/30447858/42041532-bbada0ae-7b0f-11e8-8436-4cfdf15c2433.PNG)

Select Button not visible 

![adding a phase should ask user to select a product for the phase](https://user-images.githubusercontent.com/30447858/42041555-c8f415ea-7b0f-11e8-9a75-7faeb2e8a9a7.PNG)

**Comment by deepakanbarasan1** [comment] 2018-06-28 14:45
@RishiRajSahu  
When user adding a phase should ask user to select a product for the phase.
Project Name : Test Mobile project for 2.4.3 & Test Mobile project for 2.4 Select Product testing. Please check.

**Comment by RishiRajSahu** [comment] 2018-09-11 09:47
duplicate of https://github.com/appirio-tech/connect-app/issues/2190

**Closed by RishiRajSahu** 2018-09-11 09:47 UTC
