### ISSUE TITLE
Same file won't upload when user enters two different names

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#312] opened 2016-09-29 06:33 UTC
### Expected behavior
-----------------------------------------------------------------
Must upload the file 

### Actual behavior
-----------------------------------------------------------------
Same file won't upload when user enters two different names

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Now Click 'Specification' from Menu
- Go to 'Project Files' section
- Upload the file name --> 2016-09-29_11-21-55 --> Can uplaod
- Upload the file name --> ScreenshotScreencastJS Log (2) --> Can't upload

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_12-03-28](https://cloud.githubusercontent.com/assets/4592712/18943364/c3c965b2-863c-11e6-9cd8-a874dbdbb2fe.png)

Check the attached sample file

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by sdgun** [comment] 2016-09-29 06:34
[2016-09-29_11-21-55.txt](https://github.com/appirio-tech/connect-app/files/499916/2016-09-29_11-21-55.txt)
[ScreenshotScreencastJS Log (2).txt](https://github.com/appirio-tech/connect-app/files/499915/ScreenshotScreencastJS.Log.2.txt)

**Comment by mahestro** [comment] 2016-10-04 12:19
Used the attached files and can't reproduce.

http://take.ms/nesIK

**Comment by fnisen** [comment] 2016-10-26 21:14
Can't reproduce either. Closing.

**Closed by fnisen** 2016-10-26 21:14 UTC
Labels: won't fix
