### ISSUE TITLE
The colors feature is not displayed

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#421] opened 2016-10-01 16:48 UTC
Expected behavior

-  The delete button must not be enable after a project is submitted.

Actual behavior

- The delete icon button must not be available.

Steps to reproduce the problem

- Login into application as copilot role.

- New Project.

- Select "Full develop an app".

- Set Pick target device(s) = Android Watch.

- Complete Project name and Description.

- Create Project.

- Select Specification.

- Go to What colors do you like? (Select all that apply).

- Press on "+" sign button.

- Observe as UI feature is not loaded.

Environment

    OS: Windows 7
    Browser (w/version): Chrome 49.0.2623.112 m
    User role (client, copilot or manager): copilot role
    Account used: cp-superstar

![ui](https://cloud.githubusercontent.com/assets/5114907/19015585/f229b40a-880f-11e6-8f51-911f0eb71579.png)

**Comment by mahestro** [comment] 2016-10-04 19:17
Duplicate of #262

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
