### ISSUE TITLE
Discussion on project is sometimes displaying other project discussion seeming from browser cache.

### ISSUE THREAD

**Issue by kbowerma** [appirio-tech/connect-app#2355] opened 2018-08-13 15:25 UTC
### Expected behavior
Every time you open another window with a project discussion view you should always see the proper thread on that discussion.

### Actual behavior
Sometimes,   I dont know when or why yet,   I see a discussion from another project that I either had previously open or have in another window.  I captured this in #2354 .

### Steps to reproduce the problem
I dont know the steps yet,   It is either having two windows open or due to a previous discussion being opened.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/1180747/44040021-0fd3a8ce-9ee0-11e8-8f3f-dc29d4d9f4f5.png)

Now I refresh both windows and they are the same;

![image](https://user-images.githubusercontent.com/1180747/44040169-4705075c-9ee0-11e8-86f6-53f47fcc92ac.png)
--

#### Environment
- OS: mac
- Browser (w/version): chrome
- User role (client, copilot or manager): manager
- Account used:  kbowerma

Aha! Link: https://topcoder.aha.io/requirements/TCCONNECT-351-6

**Comment by mtwomey** [comment] 2018-08-23 17:38
@gondzo Do you think we could perhaps task someone from the community to research possible causes of this (and recommend a solution)? (cc: @vikasrohit)

**Comment by gondzo** [comment] 2018-08-23 19:28
sure @mtwomey. I suspect this is also caused by slow connection or slow api response, but we can just clean the previous data before loading the new project.

**Comment by vikasrohit** [comment] 2018-08-24 05:53
> just clean the previous data before loading the new project.

Yes, that is the solution, however, we need to validate that it clearing the state data does not cause any other issue, hopefully it should not but I think we got some issue in past when clearing the state on listing page.

**Comment by mtwomey** [comment] 2018-08-24 06:44
Ok @gondzo @vikasrohit should we just task this one out to someone to test and validate?

**Comment by vikasrohit** [comment] 2018-08-24 06:47
We can take this internally or I can get it done via ongoing private tasks.

**Comment by mtwomey** [comment] 2018-08-24 16:37
Ok - let's use a private task for it. (@gondzo @vikasrohit

**Comment by maxceem** [comment] 2018-08-28 12:13
I couldn't reproduce it. But I had a relative issue recently when I fixed console warnings in commit af7f7594ad9b6f9c205030a3af187e48642076e6.

We already have `clearLoadedProject` which is being called in a few situations. This action clears the loaded project included relative posts. So I start calling it when container for `/projects/<ID>` route is unmounted. The action by itself already works in other situations without issues. I've also tested some critical cases which could identify some issues and didn't see any.

**Comment by vikasrohit** [comment] 2018-08-30 13:55
@kbowerma Can you please try this now? It should be fixed as we have released a fix for the issue. We applied a potential fix but we would like to get it confirmed from your end. Although, it should load updated scrips, you may need to burst the browser's local cache (by hitting refresh multiple times quickly or through `Disable Cache` in Network tools) to take the latest.

fyi @mtwomey @acshields

**Comment by vikasrohit** [comment] 2018-09-03 05:35
Closing the issue to close the milestone.

@kbowerma please feel free to reopen it if you still see the issue.

**Closed by vikasrohit** 2018-09-03 05:35 UTC
Labels: Hot Fix, Priority, Ready for Review
