### ISSUE TITLE
[$60] Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1795] opened 2018-03-01 23:04 UTC
_From @youdare on February 19, 2018 21:51_

1. Summary:
Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”

### Reported URL ###
 https://connect.topcoder-dev.com/
### Reproduction Steps ###
1. Go to  https://connect.topcoder-dev.com/
2. Log in with pshah_customer/topcoder123
3.Create App project
4.. Go to specification and Fill all the mandatory fields
5.After Filling all the mandatory fields, Try to edit some extra fields
6. Click “Submit For Review” button
7. App will throw message prompt as ““You have unsaved changes. Are you sure you want to leave?”
With “OK” and “Cancel” button
8.Click “Cancel: button

## Expected Result ###
Window-Customer –Project should not be submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”
### Actual  Result ###
Window-Customer –Project is submitted for review while clicking “cancel” button on the message prompt “You have unsaved changes. Are you sure you want to leave?”
### Screenshots ###
See comments
### Issue Information ###
Frequency: Repeated

Device: Window
OS: Windows 10
Browser: Chrome 

_Copied from original issue: topcoderinc/connect-test-cycle-1#369_

**Comment by vic-topcoder** [comment] 2018-03-01 23:04
_From @youdare on February 19, 2018 21:53_

https://youtu.be/YcTpi6qCb28

**Comment by Colinh84** [comment] 2018-03-09 16:49
My fix for this issue also addresses #1791 as these issues are somewhat related. I do not believe that the message prompt described in the issue is an expected behaviour for the "Submit for Review" button. What is happening is that the message prompt is part of the form component and is triggered whenever the user tries to leave the page without saving his changes; so it is triggered also by clicking on links such as to the Dashboard if the user has not yet saved. The "Submit for Review" button is part of a different component for the sidebar. This issue arises because the "Submit for Review" button is only used to advance the project status, and not for saving the project information; that job belongs to the "Save Changes" buttons on the form itself. The actual bug is that the "Submit for Review" button is becoming active when the form required fields are filled, but before that information has been saved by the user. My fix for this issue was to disable the "Submit for Review" button until all required fields are correctly filled AND saved by the user. This prevents the dialog from showing in this instance and the status from changing without the required information being saved.

**Closed** 2018-03-18 22:22 UTC
Labels: ACCEPTED, Functional
