### ISSUE TITLE
Copilot unable to access their Projects 

### ISSUE THREAD

**Issue by lakshmiathreya** [appirio-tech/connect-app#3402] opened 2019-12-10 04:22 UTC
### Expected behavior
Copilot should be able to open Projects that they are Copilots in.

### Actual behavior
Copilot unable to open their own Projects.

### Steps to reproduce the problem
- Login to https://connect-test01.topcoder-dev.com as lakshmiacopilot
- Go to https://connect-test01.topcoder-dev.com/projects/8136 - this user is Copilot for this Project.
- Note that the user is not shown as Copilot within TC team - is shown the 'Join Project as Copilot' link.
- On clicking the above, the Join Project as Copilot dialog is shown. On clicking Join Project, an error is thrown up indicating that the User is already a Copilot in the Project. 

Please see screen recordings shared in the drive.

- 
- 

### Screenshot/screencast
https://drive.google.com/drive/u/0/folders/1ktyICb6vaHDZB2JBHEEeyl0FDn9FUPhi

--

#### Environment
- OS:
- Browser (w/version):
- User role (client, copilot or manager):
- Account used:

**Comment by lakshmiathreya** [comment] 2019-12-10 04:22
Related Issue https://github.com/appirio-tech/connect-app/issues/3401
cc @nithyaasworld

**Comment by lakshmiathreya** [comment] 2019-12-10 05:05
Another related scenario - for certain Projects - the failure in access issue for Copilots follows this flow: Despite being a Copilot, they are prompted Join Project dialog. On clicking Join Project, an error is thrown up indicating that there is no invite available for the User. Please review files attached - both v5 and v4 screenshots attached for the same scenario.
<img width="1481" alt="Screenshot 2019-12-10 at 10 19 31 AM" src="https://user-images.githubusercontent.com/51733042/70497215-71d31980-1b38-11ea-9779-73abc0fadefd.png">
<img width="1246" alt="Screenshot 2019-12-10 at 10 01 09 AM" src="https://user-images.githubusercontent.com/51733042/70497281-a5ae3f00-1b38-11ea-90a9-33b4ee04fdfb.png">

**Comment by vikasrohit** [comment] 2019-12-10 11:22
@maxceem any idea about this?

**Comment by vikasrohit** [comment] 2019-12-10 11:24
@lakshmiathreya project id (8548) in the screenshot is different from the what is there in the in issue description (8136).

**Comment by maxceem** [comment] 2019-12-11 05:07
> @maxceem any idea about this?

@vikasrohit I think that user has been added as a copilot in the DB, so when we try to join - getting an error. But adding copilot as a member in ES failed for some reason, so when we load this project several things happen:
1. This project is not listed on All Projects listing as user is not added as a member in ES.
2. When we open project by the direct link, to check permissions we use data from the DB, thu copilot still can open the project even though in ES copilot is not a member.
3. When we try to join as a copilot Project Service is trying to add copilot to the DB first, but see that copilot is already there - thus fails.

The solution for this is to track errors we are getting during indexing data in ES. As now almost all data come from ES, we any issues in indexing would be visible as a bug. I would suggest adding logging errors in `project-processor-es` into the file, so we can rapidly check it for errors, maybe even every day during testing and we should research and fix all the issues during indexing.

**Comment by maxceem** [comment] 2019-12-11 05:12
> Another related scenario - for certain Projects - the failure in access issue for Copilots follows this flow: Despite being a Copilot, they are prompted Join Project dialog. On clicking Join Project, an error is thrown up indicating that there is no invite available for the User. Please review files attached - both v5 and v4 screenshots attached for the same scenario.

I guess this issue is happened due to a similar issue when data in DB and ES is different. Issues described above might happen if in ES we still have an invite for the user, so we show it. But when we try to accept the invite we get an error as in DB, we might not have it.

Another idea for a handy tool to debugging such issues might be creating some admin endpoint which would compare data in ES and DB and returns mismatches. This might be helpful for debugging, also, potentially, we might run some script with a scheduler, which go through recently changed projects, and check if there are any mismatches between ES and DB, and report about mismatches to us, so we can be notified about such issues.

**Comment by vikasrohit** [comment] 2019-12-12 09:12
Thanks @maxceem for the detailed input. I liked the idea of having a scheduled script which can compare recently updated project's database and ES states and will report if finds any difference.  I can deploy this as regular task or scheduled task in ECS cluster just like we have couple other schedulers (especially in tc-connect2sf).
Please feel to start working on that script asap.

**Comment by vikasrohit** [comment] 2019-12-12 09:42
@lakshmiathreya it is fixed now, actually it didn't need any fix. We had to reindex the project in ES. I know we would have such issues on production even after full regression and fixes because that is inherent in the CQRS pattern, I guess. And I am thinking of solution for it. And as you said @maxceem we can have a scheduled utility which would inform us for such projects daily and then we would reindex such projects using our admin tool. We have to definitely identify the error which originally caused the missing ES update and as we keep on fixing such issues, system would improve automatically and we won't have such incidents in future.

**Closed** 2019-12-19 09:17 UTC
Labels: 2.4.16, P1, Prod Environment, QA Pass in Prod
