### ISSUE TITLE
Other Design page does not have error messages for all the required fields

### ISSUE THREAD

**Issue by macs054** [appirio-tech/connect-app#1036] opened 2017-07-25 20:34 UTC
### Steps to reproduce the problem  
Go to https://connect.topcoder-dev.com 
Click Start a project  
Select Other Design
Type anything on the any of the textboxes then delete all of it, do this step in other project types and notice the result.

### Expected behavior  
There should be error messages when you delete all of your input just like in other pages.

### Actual behavior  
There are no error messages when you delete all of your input.

### Screenshot/screencast
https://youtu.be/XmD_DrVeaPQ

Error messages from other project type pages which is not visible in Other Design page
![error](https://user-images.githubusercontent.com/1199534/28592412-76207114-71bb-11e7-87c1-4009cdb1f07f.png)

#### Environment
- OS: Windows 10 Pro
- Browser: Chrome 59.0.3071.115 (Official Build) (64-bit), Edge 38.14393.0.0, Firefox 54.01, IE 11.576.14393.0  
- User role: None
- Account used: None

**Comment by gondzo** [comment] 2017-07-27 18:30
duplicate of #1033

**Closed by gondzo** 2017-07-27 18:30 UTC
Labels: bug hunt, duplicate
