### ISSUE TITLE
[$30] Empty 'App Screens' saved even though user haven't save them

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#739] opened 2017-03-08 22:27 UTC
Description
-----------------------------------------------------------------
Empty 'App Screens' saved even though user haven't save them

Steps to Reproduce
-----------------------------------------------------------------

- Open the site: https://connect.topcoder-dev.com
- Login as a valid user - Manager (Mentioned in the Environment section)
- In the Dashboard
- Open a Project [Design] (https://connect.topcoder-dev.com/projects/960)
- Click on 'Specification' tab
- Select 4-8 for 'How many screens do you need designed?'
- Scroll down and click on 'Define another screen'
- Again click on 'Define another screen'
- Click on topcoder logo will go to the Projects page
- Don't save changes
- Open the same Project [Design] (https://connect.topcoder-dev.com/projects/960)
- Click on 'Specification' tab
- Check the 'App Screens'

Expected Result(s)
-----------------------------------------------------------------
- Must not save empty 'App Screens'. Because they have required fields

Actual Result
-----------------------------------------------------------------
- Empty 'App Screens' saved even though user haven't save them

Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** IE11, Chrome 56.0.2924.87
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

Image/Video/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------

**Comment by sdgun** [comment] 2017-03-08 22:29
![22](https://cloud.githubusercontent.com/assets/4592712/23727123/d50b0966-047c-11e7-93c5-7ebc77a29fe0.png)

**Comment by gondzo** [comment] 2017-03-11 00:38
Related issue #767

**Comment by Colinh84** [comment] 2017-03-15 16:44
@gondzo This issue seems to be fixed now., can't reproduce.

**Comment by vikasrohit** [comment] 2017-03-16 05:04
Fixed it [here](https://github.com/appirio-tech/connect-app/pull/852/commits/1db43c9625dcad260f51c967aaa085880211b4f0#diff-e00449ea33ce9f6386a95ea29c2b655bR99) Basically the button 'Defined another screen' was not set as type='button' so by default it was assumed to be a submit button which makes patch call to the server immediately without user filling the information.
fyi @fnisen @gondzo

**Closed by vikasrohit** 2017-03-16 05:04 UTC
Labels: bug hunt, in progress, P2, products

**Comment by fnisen** [comment] 2017-03-17 22:27
Thanks @vikasrohit!
@gondzo I've reassigned this issue to Vikas for recordkeeping.
