### ISSUE TITLE
"Project Defaults": Billing Account Display & Management

### ISSUE THREAD

**Issue by acshields** [appirio-tech/connect-app#4269] opened 2021-01-14 18:35 UTC
### Update 1
Display the project's billing account as follows on the "Project Defaults" screen:
- Field Label: "Billing Account"
- Field Data: [Billing Account ID and Name populated in responsive dropdown menu]
- Field Sub-Text Label: [Hyperlinked: "Manage the billing account in Salesforce"]

### Update 2
Only these users should see the Field Sub-Text Label: [Hyperlinked: "Manage the billing account in Salesforce"]:
- Admin
- Connect Manager
- Copilot Manager
- Project Manager
- Program Manager
- Account Manager
- BDR
- Account Executive
- Presales
- Solution Architect

### Update 3
Ensure that the hyperlink can do the following:
- Hyperlink to the project's lead in Salesforce, if it has not been converted to an opportunity
- Hyperlink to the project's opportunity in Salesforce

### Update 4
From the Salesforce API, retrieve:
All billing account ID and names that the user has access to.

**Comment by vikasrohit** [comment] 2021-01-20 12:33
@acshields 

I am not sure why we need Update 3 because we are already showing a link to manage the BA along with the dropdown. Why would we need another link for linking to Lead or Opty now? In case, we need it where to show it? We already have that in left panel right now.

**Comment by vikasrohit** [comment] 2021-01-20 12:34
@acshields we have to decide on how to pull the available BA for showing options because it would increase the scope if we have to alter the BA api or implement some changes in SFDC to get this work done.

**Comment by acshields** [comment] 2021-01-20 16:46
@vikasrohit
**Feedback on Update 3**
What I am saying here is that the "Manage billing account in Salesforce" hyperlink should be smart enough to link to the project's lead, or opportunity, depending on what state it is in in Salesforce.
**Feedback on BA Workflow**
To modify the current BA API so that it can retrieve all active BAs associated with a project in SFDC, you said that changes would be needed in SFDC. To accomplish this retrieval goal to display all project BA options in a dropdown menu, what is the total estimate?

**Comment by vikasrohit** [comment] 2021-01-21 05:28
> What I am saying here is that the "Manage billing account in Salesforce" hyperlink should be smart enough to link to the project's lead, or opportunity, depending on what state it is in in Salesforce.

How would opening a lead or opty would help users to manage biling account though? lead does not have any billing account, and if we somehow know the SFDC billing account id for the platform BA, we can direct show the link to manage the BA in SFDC but that is tricky and depend on the api which we use to populate the available BAs and this what I intended https://github.com/appirio-tech/connect-app/issues/4270#issuecomment-763554481.

> To modify the current BA API so that it can retrieve all active BAs associated with a project in SFDC, you said that changes would be needed in SFDC. To accomplish this retrieval goal to display all project BA options in a dropdown menu, what is the total estimate?

It is very difficult to estimate that because current BA api does not support any linking to project or SFDC object so it has to be revamped ground up and all the existing BAs has to be updated accordingly and it seems to be a huge effort to me. It needs coordination among many departments.
If we directly want to use SFDC APIs, I think we can populate the BA options per project, however, it would cost tight coupling of SFDC and platform which we don't want. If we want to go with this approach, we have to convince mess and mtwomey to relax the norms on SFDC and Platform coupling.

**Comment by acshields** [comment] 2021-01-21 16:01
@vikasrohit - re: our conversation, we can use the Billing API to meet the need. 

Here's how data should be returned from the Billing API: All billing accounts that the user has access to should be returned and displayed in the responsive dropdown menu. When a billing account is defaulted in a project, this will be part of the Project Update event that SDFC can consume. In this case, it can be consumed to add a billing account to a project opportunity.

Also, for "Manage billing account in Salesforce" hyperlink, let's plan to still have this as of now, however depending on Sumiit's feedback on necessary SFDC updates/timeline, we may plan to hide this.

**Comment by maxceem** [comment] 2021-01-22 08:29
@vikasrohit as discussed on Slack, we are going to use endpoint `/v3/me/billing-accounts` to get the list of billing accounts the current user has access to. Though inside response looks like we cannot match which project this account is attached to, I guess we cannot attach any arbitrary account to any arbitrary project, here is an example:
```js
             {
                "id": 1234567890,
                "name": "TaaS App 1.5",
                "status": "Active",
                "startDate": "2021-01-15T00:00Z",
                "endDate": "2021-02-26T23:59Z",
                "budgetAmount": 10000000.0,
                "salesTax": 1.0,
                "poNumber": "N/A",
                "paymentTerms": null,
                "description": "N/A",
                "subscriptionNumber": null,
                "companyId": 1,
                "manualPrizeSetting": 1,
                "clientId": 123,
                "billable": null,
                "updatedAt": "2021-01-15T10:42Z",
                "createdAt": "2021-01-15T10:42Z",
                "createdBy": "22838965",
                "updatedBy": "22838965"
            }
```

**Comment by vikasrohit** [comment] 2021-01-22 09:25
Yes, that is okay and as per updated requirements (we got it confirmed in call yesterday with @acshields)

**Comment by maxceem** [comment] 2021-01-22 10:16
> Yes, that is okay and as per updated requirements

Got it.

@vikasrohit how to format "Manage the billing account in Salesforce" link. I see there are some special requirements but I'm not sure how to follow them.

**Comment by maxceem** [comment] 2021-02-12 13:09
Sum up:
- Add a select dropdown to choose a billing account.
- Options for this select should come from `GET {API_URL}/projects/{:projectId}/billingAccounts`: 
   Example response:
   ```js
   [
        {
            "sfBillingAccountId": "a071123452345RRuSDF",
            "tcBillingAccountId": "10000069",
            "name": "testRDS",
            "startDate": "2017-04-06",
            "endDate": "2017-04-06"
        },
        {
            "sfBillingAccountId": "a07111231238RASDSA4",
            "tcBillingAccountId": "10000068",
            "name": "test12",
            "startDate": "2017-04-12",
            "endDate": "2017-04-12"
        }
    ]
   ```
   - when we choose the value and save, it should set value to `project.billingAccountId`
   - options should be formated like `{name} ({tcBillingAccountId})`, example `test12 (10000068)`
   - if the project has a billing account id, but this list doesn't have this id, then add one more option: `<Assigned Account> (XXXXXXXX)`
- If the project doesn't have the value for billing account id and API endpoint `/billingAccounts` doesn't return any billing account, then disable this select
- for this select we can reuse some existent formsy component with select (we have 2 versions I think) or we can implement a new component for Billing Account select, similar to Groups and NDA. The main, there should not be special logic in the form. All the logic regarding billing accounts should be inside some component.
- Add link which say "Manage the billing account in Salesforce" under the field. The URL for link is `https://c.cs18.visual.force.com/apex/ConnectLead?connectProjectId={projectId}`

**Comment by maxceem** [comment] 2021-02-16 11:04
This is ready for QA. There are some test cases listed in the https://github.com/appirio-tech/connect-app/issues/4269#issuecomment-778185756 above.

**Comment by drasticdpk** [comment] 2021-02-18 06:23
**Verification**
1. When /billingAccounts doesn't return any billing account
> 
![image](https://user-images.githubusercontent.com/25297859/108313805-ff040a80-71e0-11eb-9c8d-786eff609b4d.png)
 2. When user has billing id but doesn't have a billing account id from the list.
  > 
![image](https://user-images.githubusercontent.com/25297859/108314373-e47e6100-71e1-11eb-9848-f2cb80415556.png)

**Comment by drasticdpk** [comment] 2021-02-18 06:27
@maxceem , 
To meet the above test case scenario, I need test user having billing acc. Currently it is not returning any billing acc.  ( with user acc **jcori**). Please suggest. 

Reference : 
![image](https://user-images.githubusercontent.com/25297859/108314587-3cb56300-71e2-11eb-8421-bc36af6f4cb6.png)

**Comment by vikasrohit** [comment] 2021-02-18 07:20
@drasticdpk try now, I have added `jcori` as resource to couple of biliing accounts.

**Comment by drasticdpk** [comment] 2021-02-18 09:33
Ok thank you @vikasrohit. Now we can create more scenario.
Can you please help me to verify blow scenario. 
Project has billing account but user does not have .
> In this case, is is expected ?
![image](https://user-images.githubusercontent.com/25297859/108336569-48ae1e80-71fc-11eb-9d4a-185309466999.png)

2. > if the project has a billing account id, but this list doesn't have this id, then add one more option: <Assigned Account> (XXXXXXXX), details: 

it is not working as expected, please confirm.
**Reference** 
https://connect.topcoder-dev.com/projects/16573/settings 
User : jcori

![image](https://user-images.githubusercontent.com/25297859/108334299-e3f1c480-71f9-11eb-9b85-2e4f69550107.png)

**Comment by vikasrohit** [comment] 2021-02-18 10:55
@drasticdpk I think both cases should show the option `<Assigned Account> (XXXXXXXX)`, right @maxceem ?

**Comment by maxceem** [comment] 2021-02-18 11:00
Yes, it's broken now, I'm checking it...

**Comment by maxceem** [comment] 2021-02-18 13:12
It has been fixed via d3d76eadfa412edb02fd58326b191e35b7f3bbda.

Also, showing "Loading..." during loading of the skills list.

@drasticdpk this ready for QA on DEV now.

**Comment by drasticdpk** [comment] 2021-02-19 06:02
**Verified**.

1. User doesn't have any billing accounts, but the project has a billing account id defined.

![image](https://user-images.githubusercontent.com/25297859/108464202-cf6c0580-72a7-11eb-9926-eb60dcd9a687.png)

2. User has some billing accounts, and the project doesn't have a billing account id from the list.

![image](https://user-images.githubusercontent.com/25297859/108463617-cf1f3a80-72a6-11eb-8ae6-fc26b99cbcb2.png)

**Comment by drasticdpk** [comment] 2021-02-23 09:16
**Prod Verification Reference :**
![image](https://user-images.githubusercontent.com/25297859/108821779-3c540800-75e6-11eb-9819-ab603b90fcb9.png)

![image](https://user-images.githubusercontent.com/25297859/108821905-67d6f280-75e6-11eb-9e74-314ae4fedc58.png)

@vikasrohit @maxceem  
In prod mode  for user drasticdpk, the billing account "**Wipro - Zurich Testing Challenge**" is listing for all project, is it expected ?  Does user drasticdpk has  added in billing mange app ( eg salesforce app), please confirm.

**Comment by vikasrohit** [comment] 2021-02-23 11:44
Yes, @drasticdpk I just verified that your handle is added as resource to this particular BA and it is expected to see all of the BAs that you have access to, in all projects because we haven't implemented the project level filtering of BAs for the first release. We will evaluate the usage of the feature and then based on feedback from users, we might implement project filtering for BAs.

**Comment by drasticdpk** [comment] 2021-02-23 12:27
Ok noted @vikasrohit . Thank you!

**Closed by drasticdpk** 2021-02-23 12:27 UTC
Labels: Feature: Billing Accounts, Feature: Project Defaults, Have A Question, QA - partially reviewed in Prod, Release Due Date: 2/26, SFDC Streamlining
