### ISSUE TITLE
Clearing 'Project Name' from (x) clear button; still display the "Create Project" button activated

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#238] opened 2016-09-28 20:08 UTC
## Description

Clearing 'Project Name' from (x) clear button; still display the "Create Project" button activated
## Steps to Reproduce
- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click '+ New Projects"
- Enter all the required data
- Clear the 'Project Name' from (x) clear button
- Check the "Create Project" button
## Expected Result(s)
- Must disable the "Create Project" button
## Actual Result
- Clearing 'Project Name' from (x) clear button; still display the "Create Project" button activated 
## Environment
- **Device(s):** Laptop
- **Browser(s):** IE11
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan

**Comment by sdgun** [comment] 2016-09-28 23:50
http://screencast.com/t/UNapXbJU

**Comment by fnisen** [comment] 2016-10-26 22:20
Duplicate of https://github.com/appirio-tech/connect-app/issues/241

**Comment by fnisen** [comment] 2016-10-26 22:22
Similar to https://github.com/appirio-tech/connect-app/issues/241, but not exactly the same.

**Comment by vikasrohit** [comment] 2016-11-03 10:37
Its issue with React v15.x, https://github.com/facebook/react/issues/6822 There is a workaround to overcome the issue, however, that would make the form slow because it requires handling onInput event instead of onChange event and onInput event is fired as soon as the value is changed in the text box. If the issue is critical, we can apply the workaround only for IE by detecting the browser.

cc: @fnisen @vic-appirio  @parthshah

**Comment by fnisen** [comment] 2016-11-04 01:17
@vikasrohit how about turning off the "X" in IE, as one of the other commenters suggested?

**Comment by vikasrohit** [comment] 2016-11-07 06:43
Done. Removed the "X" for IE.

**Closed by vikasrohit** 2016-11-07 06:43 UTC
Labels: P2
