### ISSUE TITLE
'Project Name' goes out of the border limits of 'Project Outline' Panel

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#996] opened 2017-07-24 18:23 UTC
### Expected behavior
Any project name entered on left side form, should stay within 'Project Outline' panel border after getting reflected there..

### Actual behavior
Project name leaves the 'Project Panel' border.

### Steps to reproduce the problem
- Go to URL https://connect.topcoder-dev.com ..
- Go to 'Start a Project'..
- Go for 'Wireframes'.
- Scroll down and insert very long text in 'Project Name' field.
- Observe 'Project Outline' panel at right side.

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/20595047/28538243-3ac3b644-70cb-11e7-9014-0b8d78ab7fce.png)
![image](https://user-images.githubusercontent.com/20595047/28538283-58792822-70cb-11e7-969f-0a031167dedc.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not logged in
- Account used: -NA-

**Comment by gondzo** [comment] 2017-07-27 17:54
duplicate of #988

**Closed by gondzo** 2017-07-27 17:54 UTC
Labels: bug hunt, duplicate
