### ISSUE TITLE
Even though the message displayed as "b: User with such handle does not exist", it is added to the invitee list

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3828] opened 2020-04-02 02:32 UTC
### Expected behavior
If there is validation, the user should not be added to the list

### Actual behavior
Even though the message displayed as "b: User with such handle does not exist", it is added to the invitee list

### Steps to reproduce the problem
- Login as Manager
- Click on a project from the project listing page
- Click "Dashboard"
- On "Customer team" > Click 'Manage Invitations'
- Enter 'b' and click on the suggestion 
- Click 'Send Invite'
- There is an error "b: User with such handle does not exist" but check the list

### Screenshot/screencast

https://monosnap.com/file/6YRulac1ZbxbjWBWh2iuOgh8lF3kb1

#### Environment
- OS: Window 10
- Browser (w/version): Chrome 80.0.3987.149 (Official Build) (64-bit)
- User role (client, copilot or manager): Manager
- Account used:  TopConnCustomer

**Comment by maxceem** [comment] 2020-05-15 07:41
@codejamtc I cannot reproduce this issue anymore 

![image](https://user-images.githubusercontent.com/146016/82024405-69a77900-9698-11ea-91c9-28d9f5e60886.png)

Note, that we still have to make a fix there, when we invite user `b` we should successfully invite user `B` as user handle suppose to be case-insensitive. But this is tracked as a separate issue https://github.com/appirio-tech/connect-app/issues/3990.

**Comment by codejamtc** [comment] 2020-05-15 13:33
@maxceem Yes, correct now if we enter `b`, the system will display an error and if we enter `B` system will add the user handle `B` to the list

https://monosnap.com/file/wMtvjfjamVSqVcsO5oXGZKNHpDBqg4

**Comment by maxceem** [comment] 2020-05-15 13:35
Then I'm closing this issue. Feel free to reopen it if there is something that has to be fixed.

**Closed by maxceem** 2020-05-15 13:35 UTC
Labels: Cannot reproduce, Functional, P3
