### ISSUE TITLE
Update Milestone button is Inactive after the valid data has been entered. 

### ISSUE THREAD

**Issue by CreeyaSean** [appirio-tech/connect-app#3580] opened 2020-01-29 08:42 UTC
### Expected behavior
All the values entered should activate the Update Milestone Button.

### Actual behavior
When the value 7 been entered the Update Milestone button gets disabled. However, if we input any other value apart from 7 then the update milestone button gets enables. 

### Steps to reproduce the problem
- Login and Manager.
- GO to the OnDemand detail page.
- Add the required field to create a project.
- GO to Project Dashboard.
- Click on Add New Phase under Dev Iteration.
- Click on Timeline under Dev Iteration. 
- Click on Edit Milestone properties and input the values in the Duration text box. 
- Delete the default  value “7” and increase /decrease value other than 7. 
- Observe the “Update Milestone Button”. 

### Screenshot/screencast
Attach or link a resource.
<img width="1021" alt="update milestone button disable" src="https://user-images.githubusercontent.com/57211549/73340763-6f24b300-42a3-11ea-87d0-12aaacd493eb.png">

--

#### Environment
- OS: Mac OS Mojave
- Browser (w/version):Chrome  : 79.0.3945.130 (Official)
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by CreeyaSean** [comment] 2020-01-29 08:42
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment] 2020-01-30 17:10
@CreeyaSean . Out of scope

**Comment by nithyaasworld** [comment] 2020-02-03 05:00
Cannot reproduce.

![image](https://user-images.githubusercontent.com/5114190/73626775-2dfc1c80-4670-11ea-91f1-8aab740a49d3.png)

**Closed by nithyaasworld** 2020-02-03 05:00 UTC
Labels: BH_OOS, BugHunt_JanRelease, Functional, P1
