### ISSUE TITLE
[Common] UI issue in the popup messages

### ISSUE THREAD

**Issue by codejamtc** [appirio-tech/connect-app#3550] opened 2020-01-29 06:48 UTC
![image](https://user-images.githubusercontent.com/42398485/73333990-08ff4800-4231-11ea-8baa-198b2b917cba.png)

**This is a common issue for most of the popups on all projects**

1. Open the Application and Login as valid user (Manager)
2. Click + New Project > Solutions
3. Click '(User) Design, Development & Deployment' > Select
4. Fill the required data > Next (App Definition)
5. Click 'What work is right for me?'

**Actual:** UI issue in the popup messages

**Expected:** Should display the content properly

**Environment:** Sony Xperia X Compact F5321 | Android_8.0
**Browser:** Google Chrome 79.0.3945.136

**Comment by codejamtc** [comment] 2020-01-29 06:49
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P3

**Comment by SathyaJayabal** [comment] 2020-01-30 12:52
@codejamtc accepted

**Comment by lakshmiathreya** [comment] 2020-02-27 01:34
Duplicate of #3631

**Closed by lakshmiathreya** 2020-02-27 01:34 UTC
Labels: BugHunt_JanRelease, P4, UI
