### ISSUE TITLE
selected icon missing 

### ISSUE THREAD

**Issue by karthikbecse** [appirio-tech/connect-app#754] opened 2017-03-09 11:09 UTC
### Expected behavior
Should show  selected icon 

### Actual behavior
icon missing 

### Steps to reproduce the problem
- Login As manager
- click New Project 
- Enter valid values 
- Click Design
- Click Wireframe
- Goto Project Specfication 
-  How many screens do you need designed?--- Select 10 Screens 
- See icon missing 

### Screenshot/screencast

![screenshot-marvelapp com 2017-03-09 16-36-18](https://cloud.githubusercontent.com/assets/3225433/23747788/ef4ae796-04e6-11e7-9b6f-3f8268d7eb8e.png)
![screenshot-connect topcoder-dev com 2017-03-09 16-37-38](https://cloud.githubusercontent.com/assets/3225433/23747787/ef42e9d8-04e6-11e7-856e-e335c8559d2f.png)

--

#### Environment
- OS:Windows 8.1
- Browser (w/version):FF 52.0
- User role (client, copilot or manager):Manager
- Account used: pat_monahan

**Comment by karthikbecse** [comment] 2017-03-09 11:10
Note: all filed missing icon

**Comment by gondzo** [comment] 2017-03-09 23:36
duplicate of #641

**Closed** 2017-03-09 23:51 UTC
Labels: bug hunt, duplicate
