### ISSUE TITLE
P2: Update 'Modified' Column

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3466] opened 2019-12-24 06:03 UTC
**Objective:** Update the 'Modified' column in the Assets Library.

<p></p>

**Requirements:**

- Relabel the column 'Date'

- The date displayed should be based on two factors:

  - The original date that the file or link was shared

  - ~Once the file or link has been accessed by a user, the date should be replaced with date of most recent access~ Once the file or link has been modified by a user, the date should be updated with the 'modified date'

**Comment by ajefts** [comment] 2019-12-24 06:03
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/2753903

**Comment by maxceem** [comment] 2019-12-24 07:44
> Once the file or link has been accessed by a user, the date should be replaced with date of most recent access

Does the word `accessed` mean that any user loaded this attachment just to view it? Or it means someone updated it?

**Comment by vikasrohit** [comment] 2019-12-30 11:48
@maxceem this requirement is confusing to me as well. I have made query to the product managers.

**Comment by vikasrohit** [comment] 2020-01-16 07:07
@maxceem for now, go with the standard interpretation of modified date i.e. when he attachment is updated by the user. So, I think we are safe to show the Modified data in that column as we always set the modified date for a record even when it is created. I guess, this reduces the scope of the issue to rename the column label only.

**Comment by RishiRajSahu** [comment] 2020-01-17 02:03
@vikasrohit @maxceem Got confirmation on this, by default mofified date would be created and otherwise the date when the asset is updated. `accessed by a user` is in the scope of this issue.

**Comment by lakshmiathreya** [comment] 2020-01-28 14:30
Column modified to 'Date' - Timestamp reflects latest edit time of the Asset.

**Comment by lakshmiathreya** [comment] 2020-01-28 14:31
Pls note Requirement stated 'accessed by user' - assuming requirement is modified to 'modified by user'. Pls clarify @RishiRajSahu @maxceem @vikasrohit

**Comment by nithyaasworld** [comment] 2020-01-28 19:18
Also, there are 2 issues and both of these issues **are seen in production as well.**

1. Modified date of **Link** is not correct, whereas the date of **'Files'** are correct
![image](https://user-images.githubusercontent.com/5114190/73297077-e1a87b00-4230-11ea-85c8-e94b22d9d27e.png)
![image](https://user-images.githubusercontent.com/5114190/73297094-ebca7980-4230-11ea-8a4a-1e77e22d8de2.png)




2. After modifying the Link, 'created by' info is gone missing
![image](https://user-images.githubusercontent.com/5114190/73297123-fdac1c80-4230-11ea-94dc-64838a14ced9.png)

**Comment by maxceem** [comment] 2020-01-29 02:07
> Pls note Requirement stated 'accessed by user' - assuming requirement is modified to 'modified by user'. Pls clarify

We modified 'accessed by user' with 'modified by user' because most likely it is what was meant there. We don't know any other meaning of 'accessed by user' in the current context.

2 issues listed in this comment https://github.com/appirio-tech/connect-app/issues/3466#issuecomment-579410086 are valid. Even though there were not a direct task of this issue I guess it's better to fix it now for consistency.

@nithyaasworld So they are fixed now and ready for testing on DEV.

**Comment by vikasrohit** [comment] 2020-01-29 06:50
> @maxceem for now, go with the standard interpretation of modified date i.e. when he attachment is updated by the user. So, I think we are safe to show the Modified data in that column as we always set the modified date for a record even when it is created. I **guess, this reduces the scope of the issue to rename the column label only.**

@lakshmiathreya It was discussed in our standup call and it turned out that PM meant the standard meaning of modified date. The word `accessed` caused the confusion. Reiterating, the scope of the issue reduced to the column rename and just make sure that we are showing the Modified Date in that column.

**Comment by nithyaasworld** [comment] 2020-01-31 06:24
Verified in Dev.

**Comment by lakshmiathreya** [comment] 2020-02-28 01:42
@drasticdpk pls verify in Prod.

**Comment by drasticdpk** [comment] 2020-02-28 11:54
QA verified in Production. Issue Passed. 
![image](https://user-images.githubusercontent.com/25297859/75546601-fc008f00-5a50-11ea-90d3-a13f43db6ebc.png)

**Comment by vikasrohit** [comment] 2020-03-02 09:28
Closing. Please feel free to create new issues for any regression.

**Closed by vikasrohit** 2020-03-02 09:28 UTC
Labels: 2.5.1, P2, QA Fail in Prod

**Comment by vikasrohit** [comment] 2020-03-02 10:24
@drasticdpk please create separate issue for your findings.
