### ISSUE TITLE
URL does not change when selecting project from "New Project" page

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#1035] opened 2017-07-25 20:33 UTC
Start here: http://connect.topcoder-dev.com/new-project
Click on Wireframes; URL does not change. Same happens with other project types.

**Comment by vikasrohit** [comment] 2017-07-26 03:48
@fnisen that is part of the same wizard and right now our wizard component does not alter URLs because we are just hiding/showing different wizard steps based on the state of the wizard. What exactly is the use case where changing the URL would help user? And if it is really critical, I can look into it because I may have to rewrite the wizard component to support URL updates as well.

**Comment by fnisen** [comment] 2017-07-31 22:37
@vikasrohit to me this would really help with tracking b/c we would know which paths the user has followed and where they are dropping off. I know tracking can be supported without the URL changes, but having the URL change seems easier than firing events/instrumenting (URLs can be tracked more basically with built in tracking in Google Analytics or Mixpanel). Please let me know if you disagree.

**Comment by vikasrohit** [comment] 2017-08-01 05:14
Agree. We might have to analyze the efforts required to handle URL for wizard steps vs adding analytics events on every wizard step change. We can keep it for first few things to do after release.

**Comment by vikasrohit** [comment] 2017-08-10 03:46
@fnisen Tried to resolve this. Please check the solution in dev and if it works for you. Currently I have added adhoc, due to technical restrictions, solution for updating the URLs on wizard step changes, however, ideally I would like it to be done at component (Wizard or ProjectWizard) level.

**Comment by fnisen** [comment] 2017-08-10 13:57
@vikasrohit nope, not working for me in dev.

**Comment by vikasrohit** [comment] 2017-08-10 17:28
I guess it was the build cache issue. Please check now.

**Comment by fnisen** [comment] 2017-08-10 18:46
Yes, it's working now. One issue I'm seeing: the URLs don't change when you're logged into Connect. Would you want to implement that, as well, so the experience is consistent?

**Comment by vikasrohit** [comment] 2017-08-11 03:07
Yes, it is not implement for logged in use case. However, it does not work when one clicks on 'New Project' button which is rendering it as modal, if someone somehow is using /new-project link to create project in logged in mode, it would work. But I don't think that any logged in user would create project using /new-project link.

**Comment by fnisen** [comment] 2017-08-11 04:08
Yeah, don't think they would do that. Can you implement it to work in the logged-in use case, also?

**Comment by vikasrohit** [comment] 2017-08-11 05:29
I think I can do that, however, the point is that it is a modal and changing URL in modal does not make much sense. Further, when user closes the modal, using the close button or ESC button, it would keep the URL in the last wizard state. Though, I can workaround that as well by handling the close event callback, does it really make sense to update URLs in a modal?

The above text is just for a healthy discussion. 😬  I am going to work on making the modal URL aware as well.

**Comment by fnisen** [comment] 2017-08-14 13:54
OK, let me discuss with Vic about how to approach this.

**Comment by vikasrohit** [comment] 2017-09-21 04:46
@vic-topcoder  In that case we have to get rid of modal view for new project in logged in use case. In modal mode, it is very difficult to achieve the changing URL as I mentioned above. Please let me know if you can think of a good way to achieve the same behaviour in modal mode.

**Comment by vic-topcoder** [comment] 2017-09-21 20:48
Maybe what @birdofpreyru is doing in the communyt-app could be used: https://github.com/topcoder-platform/community-app/blob/develop/docs/how-to-deep-link.md

@birdofpreyru please advise on URL manipulation/routing

Also - next.js showed some techniques about clean URLs: https://learnnextjs.com/basics/clean-urls-with-route-masking

Example of better/dynamic/context-aware URL - Dribble. Depending on context, a modal and a full-view page share the same URL. You can load www.dribbble.com and preview any image in the popup, and upon copy-paste the URL in a new window, it'll load a full page instead of modal based on context. Ideally that's the behavior our system should support.

![screen shot 5](https://user-images.githubusercontent.com/8484061/30718039-7ea02d80-9ed3-11e7-9b39-215dfddc93f1.png)
![screen shot 6](https://user-images.githubusercontent.com/8484061/30718038-7e9f3632-9ed3-11e7-8a10-ac560b125c6b.png)

**Comment by birdofpreyru** [comment] 2017-09-21 22:52
@fnisen @vikasrohit @vic-topcoder 

Hello everybody, here I am and I'll be glad to help :)

Just briefly reading through this thread, I am not completely sure what is your exact use case; but in community-app I've played around and come up with a nice way to handle something similar in a consistent way, which Vic has referenced above: https://github.com/topcoder-platform/community-app/blob/develop/docs/how-to-deep-link.md

One difference I see is that here you are trying to manipulate the main part of URL, including the situation when a modal is opened / closed, and it looks a bit akward. In Community App, in such case, we would just add query params to the URL, which does not interfere that much with the app routing, but allows to write into URL any information about the current state of the page, and then restore the state during server-sider rendering, if this URL is directly accessed.

**Comment by vikasrohit** [comment] 2017-09-25 06:14
@vic-topcoder @birdofpreyru Thanks for your inputs here, however, I think these links are not relevant here except the the dribbble behaviour. Yes, we want the dribbble behaviour here, however, to achieve that we have to write a code which handles that neatly and it is not a quick solution and I am anticipating few issues around that once deployed.
So, my suggestion is to analyze the requirement. If it is really critical use case and non modal solution (which we are using for non logged in person) is not going to work, than I can start implementing that behaviour.

**Comment by birdofpreyru** [comment] 2017-09-25 10:28
@vikasrohit I am not sure, what exactly you don't like in my solution referenced above? It works quite good in Community App.

**Comment by vikasrohit** [comment] 2017-09-26 05:12
@birdofpreyru It is not that I didn't like the solution. In fact that solution is really good. It is just that our use case is different. we are more concerned about handling that for modal views.

**Comment by mtwomey** [comment] 2017-10-05 03:25
@vic-topcoder Can I get a recap on what tool or analytic we're using and how it's misbehaving currently (with the URL not-rewriting), so that we can be sure that we make changes that ultimately meet that goal? (or if I'm mis-understanding the business goal, please advise)

**Comment by vikasrohit** [comment] 2017-10-05 05:53
@mtwomey Sorry to jump in when you are asking @vic-topcoder 😬 

However, IMO, if the problem is only the analytics, we can do custom analytics here by explicitly calling segment events on every step change of the wizard. My only concern is that we should not change URL when wizard step changes in modal view of project creation wizard, unless it provides a very useful use case to the customers.

**Comment by mtwomey** [comment] 2017-10-05 16:57
@vic-topcoder This is why I'm asking. I just want to make sure we're all on the same page as to what we're actually pursuing and why. So that we can re-confirm we're actually solving _the_ problem (or solving _a_ problem). @vic-topcoder

**Comment by vic-topcoder** [comment] 2017-10-05 20:03
The wizard is presented as a full page. Navigation between wizard screens are new pages. They should all have unique URL in logged in or logged out state. This should allow the use of browser history, browser back and forward buttons, and sharing the copy-share the URL.

For analytics, I think we use Segment, but I'm not sure. I have to actually do a deeper dive of how we instrumented Connect and what information is needed.

**Comment by mtwomey** [comment] 2017-10-05 22:06
@vikasrohit @vic-topcoder  - please see below and ask any clarifying questions. We'd like to understand your recommended solution for this so we can move forward quickly.

OK - Victor and I on the phone right now and flushing our the desired user behavior. This is the agreed goal we're trying to meet on this request / issue:

**User Story**

As a logged in user I want to be able to copy the links in the URL bar, during the initial steps (opening the project type selection view, each specific project type creation start page and sub-pages) of project creation. I should then be able to send those links to another user. That new user can now go to those links and see those same pages.

Note: copying the URL won't also capture any data filled out in the form (and this is fine).

**Comment by mtwomey** [comment] 2017-10-05 22:29
Note @vikasrohit - we'd like to complete #1234 prior to continuing on this one.

**Comment by vikasrohit** [comment] 2017-10-11 13:48
Should be fixed and changes are in dev.

**Comment by vikasrohit** [comment] 2017-10-13 11:07
Verified on production. Seems to work fine to me.

**Closed** 2017-10-14 05:19 UTC
Labels: P2, Ready for Deploy
