### ISSUE TITLE
[Redesign] Display notification for new messages on threads

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3012] opened 2019-05-08 05:24 UTC
When there is a new message in a thread that a customer is on, or if they have been tagged, a summary of notifications should be shown on each thread.

<p></p>

Let's start with the desktop version of the system and we'll add the mobile view once the design pool completes the interface conversion.

<p></p>

**Acceptance Testing Plan:**

1. Log into the Connect platform

2. Access a project

3. See the count of new messages

<p></p>

Notes: Login to dev environment as different users and post/review messages.

<p></p>

**Comment by ajefts** [comment] 2019-05-08 05:24
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1720736

**Comment by vikasrohit** [comment] 2019-05-08 05:25
@maxceem fyi

**Comment by maxceem** [comment] 2019-05-14 04:14
@vikasrohit 

As I understand we should show the next block on the `Dashboard` tab for each topic user has unread notifications:

![image](https://user-images.githubusercontent.com/146016/57670361-7f2b3280-7641-11e9-9f7e-240c66b58f49.png)

There is one note at the moment: as soon as user open `Dashboard` tab all the notifications related to the posts and topics on this tab would be marked as `read` as currently, we show the whole opened threads on the `Dashboard`.

What do you think about this?

**Comment by vikasrohit** [comment] 2019-05-14 05:43
@maxceem we have to stop marking all notifications as read for topics on dashboard load from now on. We can still render the topics on the dashboard until we do changes for #3013 to move them to their dedicated route. However, the purpose here is to pick the view from the new designs and implement it in existing place because new designs have all topics collapses by default and clicking on the collapsed topic card opens a drawer from the right with full details of the topic (almost similar to our full screen view). So, essentially by adopting this new design, we would be able to keep the notifications unread until user opens the drawer for the particular topic.

I am okay with just keeping the collapsed cards and their drawer in the scope of this task i.e. we don't need to create separate section for Unread topics for now. We can take care of that later, if that increases the scope of this task.

**Comment by maxceem** [comment] 2019-05-14 05:52
> I am okay with just keeping the collapsed cards and their drawer in the scope of this task i.e. we don't need to create separate section for Unread topics for now. We can take care of that later, if that increases the scope of this task.

This task title looks like about the Unread topics section. While as I understand what you would like to implement is a new way of displaying topics: collapsed cards + drawer with messages.

![image](https://user-images.githubusercontent.com/146016/57673672-66297e00-764f-11e9-8243-9d209d17298c.png)

and

![image](https://user-images.githubusercontent.com/146016/57673679-6f1a4f80-764f-11e9-932e-dddd62fdbd05.png)

Maybe we should create another issue then for the new topics and post design?

**Comment by vikasrohit** [comment] 2019-05-14 07:13
The primary purpose of this issue is to have some kind of notification for unread messages on our current dashboard threads. Because we can not achieve this without updating the design (by design I just mean the layout or behavior only), we have to use the collapsed topic/thread card designs from the proposed designs and because we chose that, we have to also choose drawers for showing the details of the collapsed card.
On the other hand, just showing the unread section separately can also serve the purpose which I think is in your mind @maxceem. But still, if just render the topics in current expanded form as is in the Unread section, that won't help much I guess. So, we have to opt for the collapsed topic card. 
Also, as now we have support for private topics and attachments to the posts, we can show some of the metadata shown in the topic card in new designs. We don't have notion for archiving the topics for now, so leave that out from the card.

**Comment by vikasrohit** [comment] 2019-05-22 08:30
@maxceem do you still have any query on this or are we clear to get it in motion?

**Comment by maxceem** [comment] 2019-05-22 08:34
It looks clear. As this would require to reimplement posts in the Drawer on the right, I'm waiting for the common components to be implemented in `react-components` based on material ui. I think we will get submission soon for the challenge https://www.topcoder.com/challenges/30091275

**Comment by vikasrohit** [comment] 2019-05-31 12:05
@maxceem Could you please create a phase for this work in our new Connect project?

**Comment by maxceem** [comment] 2019-05-31 12:44
@vikasrohit sure. Do we already have a new Connect project? Or should I use Connect V3?

**Comment by maxceem** [comment] 2019-06-24 10:38
@vikasrohit 

1. I guess for the content of the Drawer with posts we can use the existent view of list of posts, right?

    ![image](https://user-images.githubusercontent.com/146016/60012704-38544200-96af-11e9-975c-520647780e1d.png)

2. Not sure how to implement the editing Topic title in the new design. In old design it looks like this:

    ![image](https://user-images.githubusercontent.com/146016/60012588-e7dce480-96ae-11e9-8d6e-44cffc343ae4.png)

    Though in the new design there looks like no space in the title bar for the buttons.

**Comment by vikasrohit** [comment] 2019-06-24 11:34
1. Yes, existing view of the posts (along with the option to post the new post) should be reused as is.

2. I think we have to convert the buttons to icons and render them inline after the edit text box.

**Comment by maxceem** [comment] 2019-06-26 06:41
`@vikasrohit 

1. We have an old  `Discussions` tab with route `/projects/:projectId/discussions`. I guess we don't need that tab anymore as we are showing old messages with tag `MESSAGES` as private messages at the moment. So we can remove all code related to the old `Discussions` tab. And use route `/projects/:projectId/discussions` for new `Discussions` page.

2. The only thing, the old tab also supported URLs like `/projects/:projectId/discussions/:discussionId?` which refer to a particular topic. I guess we would have to redirect such URLs to `/projects/:projectId/discussions#feed-${discussionId}` which should show particular topic Drawer.

2. Also, we currently have URLs in the notifications or emails which refer to the topics on the dashboard like this: `/projects/{{projectId}}/#feed-{{topicId}}` and to the posts on the dashboard like this `/projects/{{projectId}}/#comment-{{postId}}`. As the new URL for topics/posts tab would be `/projects/:projectId/discussions`. I guess we also should redirect old topic/post URLs to the new URLs to keep backward compatibility with links inside emails.

   Also, as we are changing URLs anyway. I guess it's a good moment to sliggtly adjust them to:
   - `/projects/{{projectId}}/discussions#topic-{{topicId}}`
   - `/projects/{{projectId}}/discussions#topic-{{topicId}}-post-{{postId}}` - this would make the code easier as URL for posts would containt `topicId`.
   To be in line with phase posts URL:
   - `/projects/{{projectId}}/plan#phase-{{phaseId}}-posts-{{postId}}`

**Comment by maxceem** [comment] 2019-06-26 09:50
4. As I understand when we navigate to `/projects/{{projectId}}/discussions#topic-{{topicId}}` from the email or notification the drawer with topic should be opened.

5. When we navigate to `/projects/{{projectId}}/discussions#topic-{{topicId}}-post-{{postId}}` from email of notification, the drawer with topic should be opened and scrolled to the particular post.

**Comment by vikasrohit** [comment] 2019-06-26 11:02
1. Lets leave it as is for now i.e. don't remove the old Discussions tab for old projects. However, if we are determining the flag for showing the old Discussions tab based only on the presence of 'MESSAGES' tag , I guess we are forced to get rid of this tab.

2. Can we keep this `/projects/:projectId/discussions/:discussionId` URL instead of `/projects/:projectId/discussions#feed-${discussionId}`? I mean the former one is more REST compliant?

3. Yep, I guess for backward compatibility we have to redirect old URLs to new one.

> Also, as we are changing URLs anyway. I guess it's a good moment to sliggtly adjust them to:

My later comments would suggest the URLs for first two cases and for the phase posts, I think the URL you suggested is good for now except that we won't have `phase` keyword after new work management features are in place. So, I am thinking of having a generic keywords in its place.

4. Agreed except I would like the URL pattern to be `/projects/:projectId/discussions/:discussionId` which opens the drawer

5. Agreed except that I would like the URL pattern to be `/projects/:projectId/discussions/:discussionId#comment-{{commentId}}` to open the topic in drawer and scroll to the post.

**Comment by vikasrohit** [comment] 2019-06-26 11:04
1. Lets leave it as is for now i.e. don't remove the old Discussions tab for old projects. However, if we are determining the flag for showing the old Discussions tab based only on the presence of 'MESSAGES' tag , I guess we are forced to get rid of this tab.

2. Can we keep this `/projects/:projectId/discussions/:discussionId` URL instead of `/projects/:projectId/discussions#feed-${discussionId}`? I mean the former one is more REST compliant?

3. Yep, I guess for backward compatibility we have to redirect old URLs to new one.

> Also, as we are changing URLs anyway. I guess it's a good moment to sliggtly adjust them to:

My later comments would suggest the URLs for first two cases and for the phase posts, I think the URL you suggested is good for now except that we won't have `phase` keyword after new work management features are in place. So, I am thinking of having a generic keywords in its place.

4. Agreed except I would like the URL pattern to be `/projects/:projectId/discussions/:discussionId` which opens the drawer

5. Agreed except that I would like the URL pattern to be `/projects/:projectId/discussions/:discussionId#comment-{{commentId}}` to open the topic in drawer and scroll to the post.

**Comment by maxceem** [comment] 2019-06-26 11:08
Thank for replies @vikasrohit 

> Lets leave it as is for now i.e. don't remove the old Discussions tab for old projects. However, if we are determining the flag for showing the old Discussions tab based only on the presence of 'MESSAGES' tag , I guess we are forced to get rid of this tab.

Old `Discussions` tab is only shown for old project which were created without flag which we set to all the new projects, see [code](https://github.com/appirio-tech/connect-app/blob/feature/redesign/src/api/projects.js#L148) so it doesn't depend on the `MESSAGES` tag and we can keep it. Though this page uses URL `/projects/:projectId/discussions/:discussionId`, which I was thinking to use for a new page. Should we use another URL for our new page instead?

**Comment by vikasrohit** [comment] 2019-06-26 11:13
Got it. I guess we can use `messages` instead of `discussions` for the new page URL as the latest design https://marvelapp.com/4acgiai/screen/58136216 is using that naming convention and you can this latest design for final design guidance as well.

**Comment by maxceem** [comment] 2019-06-26 11:13
Regarding URL my thought was like this:
theoretically, we can open any drawer from any page: `Dashboard`, `Files & Links`, `Discussions` and so on. As drawer by its nature can be opened at any page, theoretically, we could end up having links like:
- `/projects/{{projectId}}#topic-{{topicId}}`
- `/projects/{{projectId}}/library#topic-{{topicId}}`
- `/projects/{{projectId}}/report#topic-{{topicId}}`

So I was thinking to distinguish in some way links to pages and links to drawer just in case. But we can go with link format you've suggested above if you think the situations I've described above would never be a case for any drawer.

**Comment by vikasrohit** [comment] 2019-06-26 11:29
I think if we have to show a drawer for a topic on some other page, that would have different URL and might have different way to represent the topic e.g. we have to show topic and posts for a phase so may be we can use `/projects/{{projectId}}/plan/(phase|work)/{{phaseId}}#topic-{{topicId}}` and `/projects/{{projectId}}/plan/(phase|work)/{{phaseId}}` (we have to have something similar URL anyway to support deep linking a work card details page/drawer) would show the drawer for the work card and `#topic-{{topicId}}` would scroll(optionally open the appropriate tab, where we are showing the messages for the work card, as well) user to the start of the discussions (as per new design https://marvelapp.com/3h6bdfd/screen/56039328) for that work card.

**Comment by maxceem** [comment] 2019-06-26 12:08
@vikasrohit regarding `New discussion` button. There are two ways I see:
1. Open drawer with empty title and post fields like this: https://monosnap.com/file/0VtJGawUKwKYNff3FoziUpfiJVKl0k

2. Open a new topic editor like it was before on the page, on in the drawer
    ![image](https://user-images.githubusercontent.com/146016/60178412-18a75000-984e-11e9-9191-2b8d3623a02e.png)

I guess the second approach would be much much easier to implement than do via the drawer. Which way do you prefer?

**Comment by vikasrohit** [comment] 2019-06-26 12:23
I am kind of liking the first way as it is more in sync with our rest of the UI, however, as implementing second one is easier and faster, I would like to go with second one to reduce the time to implement the changes.
Also, we might need to think about a better placement of `New Discussion` button as right now it is shown at the bottom of all threads which would make it very difficult for user to find it. I think we should keep the current way to create new topic as is i.e. on the top of the Message tab, we can show single text box and focusing on that would expand it to full component to create a new topic i.e. exactly like we are doing it right now.

**Comment by maxceem** [comment] 2019-06-26 12:28
That would make this task easier. So no `New Discussion` button and keep the UI for a new message on top of all messages as we have right now:

![image](https://user-images.githubusercontent.com/146016/60179722-dd5a5080-9850-11e9-8b98-765e85bfee0a.png)

**Comment by vikasrohit** [comment] 2019-07-22 07:21
Verified and working as per requirements on production.

**Closed by vikasrohit** 2019-07-22 07:21 UTC
Labels: Aha!:Ready for QA
