### ISSUE TITLE
Delete Confirmation popup overlay is opened center aligned to the list

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#355] opened 2016-09-29 16:37 UTC
### Expected behavior
-----------------------------------------------------------------
Delete Confirmation popup overlay must open near the item that user wants to delete

### Actual behavior
-----------------------------------------------------------------
Delete Confirmation popup overlay is opened center aligned to the list

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Dashboard
- Click Remove team member icon; in the first item
- If the list is big; it is opened in the middle
- User needs to scroll down and then confirm the deletion

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-09-29_22-07-24](https://cloud.githubusercontent.com/assets/4592712/18963100/21bbf8e8-8691-11e6-879c-31258d61e80b.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** pat_monahan
- **User Role:** Manager

**Comment by mahestro** [comment] 2016-10-04 13:12
True - https://connectv2.topcoder-dev.com/projects/363

Valid.

**Comment by parthshah** [comment] 2016-10-07 22:22
I am not able to reproduce this in any other project.  I removed the rows that were impacted but after re-adding those users i am not able to reproduce. 
Closing.

**Comment by mahestro** [comment] 2016-10-07 22:25
Strange. All issues that I wrote valid is because I was able to reproduce them - http://take.ms/UnzXt5

**Comment by fnisen** [comment] 2016-10-07 23:25
@parthshah I can reproduce it, too. There is some inconsistency with how new team members are added. At first they're added one after another in the list and removing works correctly. Then at some point they start being added to the top and after that removing doesn't work anymore. You need about 10 members on the project before this starts happening.

**Comment by vikasrohit** [comment] 2016-10-12 10:01
It was really interesting to solve this one. This problem was because of sorting algorithm used to sort the team members list. Before the fix we were using Array's sort function which produces unstable sort results and it also modifies the existing array after sorting. I have used lodash's sortBy method which produces stable sorting results without modifying the original array.

@parthshah I have created PR for this, please take a look and let me know if you see any improvement.

**Comment by fnisen** [comment] 2016-10-14 16:39
Fixed with https://github.com/appirio-tech/connect-app/pull/459

**Closed by fnisen** 2016-10-14 16:39 UTC
Labels: P2, s_dashboard
