### ISSUE TITLE
[Search / Status] - allow to be selected multiple options

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#434] opened 2016-10-01 18:08 UTC
Expected behavior

   Multiple statuses must be able to be selected because users want usually to search different multiple statuses.

Actual behavior

```
Only one status can be selected.
```

Steps to reproduce the problem

```
Login into application as manager / copilot.

Press Filters option.

Try to select multiple options as example: Active and Completed.
```

Environment

```
OS: Windows 7
Browser (w/version): Chrome 49.0.2623.112 m
User role (client, copilot or manager): manager
Account used: pat_monahan
```

![statuses](https://cloud.githubusercontent.com/assets/5114907/19016151/2af52c3c-881b-11e6-9d7f-44864137d634.png)

**Comment by mahestro** [comment] 2016-10-04 19:50
Not a bug.

**Comment by fnisen** [comment] 2016-10-15 00:09
Will wait to see if there are requests for this kind of functionality

**Comment by fnisen** [comment] 2016-12-06 20:20
No feedback to support this. Closing for now.

**Closed by fnisen** 2016-12-06 20:20 UTC
Labels: enhancement
