### ISSUE TITLE
When editing timing on phases, the logic doesn't work in certain cases

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2148] opened 2018-07-06 02:27 UTC
### Expected:
- When I select a specific time with an offset after the previous phase, the system would acknowledge the time offset.

- Each phase should begin on its own day. We use days as the smallest granular units of time to communicate with the customer. It is rare to deliver at the end of the day and start work on the next phase.

Design specification (https://marvelapp.com/8a94680/screen/41372263)
![screen shot 2018-07-05 at 7 24 22 pm](https://user-images.githubusercontent.com/8484061/42356747-122e69b2-8089-11e8-9f1a-def80be739bb.png)

### Current implementation:
Entering a date that is a day early or day later from the end of the previous phase resets the time to the exact end of the previous phase. This is wrong. 
Look at this project plan (https://connect.topcoder-dev.com/projects/6545/plan) and try changing the date of a phase to be behind or ahead of the end of the previous phase:
![screen shot 2018-07-05 at 7 26 22 pm](https://user-images.githubusercontent.com/8484061/42356809-5dbf09fe-8089-11e8-9635-da9425ed1ae1.png)

**Comment by vic-topcoder** [comment] 2018-07-06 02:29
### Minor:
When you have a date range in the same month, can we omit the second month repetition?

Instead of `Jul 9–Jul 18` I would expect `Jul 9–18`

@rmjmccormick do you think this is ok in terms of language / formatting?

**Comment by rmjmccormick** [comment] 2018-07-06 09:02
@vic-topcoder Yes, this is OK.

**Comment by vikasrohit** [comment] 2018-07-09 05:33
@rmjmccormick I didn't understand the need here. I think we all agreed upon not putting/forcing any validation around dates for the phases because that would incur more complexity than feature. We have to be very clear in terms of what exact behaviour we need for the phases, it is very difficult to tweak the model every other week.

**Comment by rmjmccormick** [comment] 2018-07-09 08:58
@vikasrohit Each phase is listed back-to-back with the precedent and subsequent phase, on a timeline. At the moment, the moment one phase ends, the next phase begins on the same day. Where E is the end date of one phase and S is the start date of the next phase immediately following it in time -->
S = E+1 /= S=E 
Make sense?

**Comment by vikasrohit** [comment] 2018-07-09 09:42
> At the moment, the moment one phase ends, the next phase begins on the same day.

I don't think we ever implemented this logic. As I said, we never forced any validations on phases, so user should be able change to each phase timeline independently.

**Comment by vic-topcoder** [comment] 2018-07-09 17:46
It is not working like this at the moment. There is no way to set different time and save it, as upon saving the time is reset to the end of the previous phase or earlier.

**Comment by vic-topcoder** [comment] 2018-07-09 18:22
[date shifting in connect.mov.zip](https://github.com/appirio-tech/connect-app/files/2177526/date.shifting.in.connect.mov.zip)
Please review the screen recording to see how the phase date shifts when editing other details to fall on the last day of the previous milestone.

**Comment by vikasrohit** [comment] 2018-07-10 05:41
Okay, I think that is happening because of timezone on the machine. It seems to work fine our timezone but seems like it fails when machine is in PST or any timezone which is behind UTC.
We are on it.

**Comment by vikasrohit** [comment] 2018-07-10 07:39
@vic-topcoder @rmjmccormick We have tried to fix the situation here after reproducing the issue on local by changing the timezone to PST. Let us know if you are still facing the same behaviour.
Also, implemented the behaviour for omitting the repetition of the month part.

**Comment by vikasrohit** [comment] 2018-07-11 10:17
Closing the issue @rmjmccormick. We can take care of timezone issue separately for better tracking.

**Closed by vikasrohit** 2018-07-11 10:17 UTC
