### ISSUE TITLE
Provide card view switch for Managers

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1372] opened 2017-11-29 03:56 UTC
As a Manager I want to be able to switch between grid and card view for projects so I can see what my customers see.

Created from Aha! https://topcoder.aha.io/features/TCCONNECT-83

**Comment by vikasrohit** [comment] 2017-12-05 06:31
Duplicate of #1336

**Closed by vikasrohit** 2017-12-05 06:31 UTC
Labels: Aha!:Under consideration
