### ISSUE TITLE
[Redesign] Sidebar alignment w/ Community

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#3013] opened 2019-05-08 05:53 UTC
**Overview**

Streamline experience for TC users we will adopt a standard sidebar navigation experience that is consistent between Connect and the Community.

<p></p>

**Requirements**

- We will remove the top-level tabs of Dashboard, Scope, and Project Plans

- We will still display the project status in the left sidebar, but controls over modifying project status will be updated (re: Feature in Project Plan - Integrate/Automate Project Status)

- Beneath the project status we will be creating the following tabs:

  - Dashboard: This will be the default page/tab that is opened when a user accesses a project. It will show both the full project plan and the scope card.

  - Discussions: This tab will reflect all project discussions in a single repository, including the discussions occurring on individual project plan work cards as well as stand-alone discussion threads.

  - Library: This tab will reflect a single repository of all files and links shared in the project, including those shared in project plan discussions as well as stand-alone discussion threads.

  - Reports: This tab will eventually reflect reports created on the project, including financial burndown, progress burndown, and delivery-specific reports, such as QA results.

  - Team Management: This tab will support the current team management capabilities, including inviting and removing users from a project.

- Underneath the primary navigation tabs in the left sidebar, the current project Topcoder and customer members will be displayed. Architects should be called out separately from Topcoder project members, as this is a professional service that customers are paying for and it would be good to highlight who is their Architect.

**Comment by ajefts** [comment] 2019-05-08 05:53
Link to feature: https://tcprod.productboard.com/feature-board/planning/features/1671859

**Comment by maxceem** [comment] 2019-05-14 04:30
@vikasrohit 

As per the new design, the sidebar should look like this:

![image](https://user-images.githubusercontent.com/146016/57670796-70de1600-7643-11e9-98b0-97582134a1e8.png)

Do I understand it correctly, that this task about implementing the sidebar includes:
1. Changing the Dashboard tab so only shows the project plan and scope card.
2. Creating a Discussion tab which would show only topics and topic notifications.
3. We don't have yet a design for Files and Links tab. We have a design for the drawer with files though. Just want to note, that for the sidebar we have to show a whole page, not a drawer.
4. Team management we have and only have to update with a new design.
4. Add challenge architects. I'm not sure if have a way to detect which members are architects.

**Comment by vikasrohit** [comment] 2019-05-14 05:50
1.  Yes
2. Yes
3. You are right. Need to discuss with product team for that. For now can we put the drawer's content in the whole page instead? I guess we would two list views on the page one for links and another for files. 
Also, please note that we are calling this as `Library` as per description of the ticket.
4. I guess we even don't much design changes here
5. Leave this part out of scope for now. We have to handle it separately later.

**Comment by vikasrohit** [comment] 2019-05-14 05:51
We also need to keep our Project status dropdown as is for now, although it is not shown in the new designs.

**Comment by vikasrohit** [comment] 2019-05-30 06:03
@maxceem https://marvelapp.com/3h6bdfd/screen/57484265 can be reference for project status and other missing items in the new side bar.

**Comment by maxceem** [comment] 2019-06-24 05:21
@vikasrohit a few questions regarding the sidebar:

1. In the new design we don't show a short project description on the sidebar anymore, right?

2. In the new design, we show links to Direct ID and Lead ID. Just would like to point out that they would look like:
   `Direct ID: 18123`
   `Lead ID: 7803`
    Where **Lead ID** would be same to the project ID in Connect.

3. Is there design for the status when it's non-editable?

     ![image](https://user-images.githubusercontent.com/146016/59993330-81da6800-9682-11e9-95cf-02321bad5f45.png)

4. In the new design, there is only one `Team` section, while in the old design we show Topcoder and Project team separately. Should we keep two types of teams?

    ![image](https://user-images.githubusercontent.com/146016/59993412-c7973080-9682-11e9-9b7e-c8d7b2952415.png)

**Comment by vikasrohit** [comment] 2019-06-24 11:28
1. I think we should keep the description field for now as we don't have any other place where we are showing description in new designs. It is not difficult to get rid of it if it is actually required. 

2. Lead id is not the connect project id. Its the salesforce lead id and we are showing a link for that right now just below the Direct project link. However, the problem is that we don't have lead id itself in Connect, rather we have a link with Connect project id in query param and we search the for lead in Salesforce using that id. So, I think we can not show the lead id here. So, we should keep the designs of the Direct and Salesforce lead links as it is.

3. Unfortunately no. Please keep non editable project status as is as well.

4. We don't need to change the team management component as of now for this navigation restructuring feature. We would take care of the team management changes later on when we have more stable requirements around it.

**Comment by maxceem** [comment] 2019-06-24 11:31
> 3. Unfortunately no. Please keep non editable project status as is as well.

Should we keep then the existent UI for the status select also to keep it consistent with the non-editable state?

![image](https://user-images.githubusercontent.com/146016/60015689-a51f0a80-96b6-11e9-9e4b-ba10531cc6fb.png)

**Comment by vikasrohit** [comment] 2019-06-25 07:36
Yes, we should keep it as is as well. However, just to double check the difference in the current and new designs of editable project status are only:
1. Color scheme
2. Grouping of project status options 
3. Position of the dropdown rendered on click of dropdown header.

Right @maxceem ?

**Comment by maxceem** [comment] 2019-06-25 07:41
@vikasrohit right, in general CSS styles are different, in particular, they also different for the select list base:

![image](https://user-images.githubusercontent.com/146016/60078892-6e50ff00-975f-11e9-9a45-4df881db171d.png)

So, for now, we keep the existent UI:

![image](https://user-images.githubusercontent.com/146016/60078950-8cb6fa80-975f-11e9-810f-2f0e2c563410.png)

**Comment by maxceem** [comment] 2019-06-28 04:29
@vikasrohit here is how I see the sidebar as a mix of current elements and new design as per the discussion above:

![image](https://user-images.githubusercontent.com/146016/60316816-bf9b0180-999e-11e9-8f68-bdf1922dc9eb.png)

1. keep description with the link `read more`.

2. separate description with menu with a line unlike in marvel file where we don't have a desciption

3. keep the old design for direct and salesforce links

4. keep old design for status selector but without horizontal lines, as otherwise it would separate it from the `Administation` section it belong too.

5. keep old design/functionality for project and topcoder teams, while updating design for titles and `Manage` link.

6. We keep the sidebar `stickable` as it is now.

7. Is it possible to get the source files for new icons for menu items? I cannot find them in a new marvel file https://marvelapp.com/4acgiai/screen/58136217. Also, we would need an icon for `Scope`/`Specification` page.

8. We have an old `Discussions` tab, which is shown for old projects with posts which have tag MESSAGES`. As our new `Messages` page shows the message with tag `MESSAGES` as private topics I guess we shouldn't show the old `Discussions` page anymore. (We can still keep the code just in case).

**Comment by vikasrohit** [comment] 2019-06-28 06:24
Correct for all points @maxceem 

7. https://marvelapp.com/3h6bdfd/screen/56595828/handoff has some assets, however, I am not able to find the Path details for the left panel icons here.

8. Yep, we can skip that for the release. However, we need to be prepared for re-enabling it quickly (may be as a new tab named `Private Discussions` along with the `Messages` tab) because I can see few active projects using that tab and they might raise concerns.

**Comment by maxceem** [comment] 2019-06-28 06:29
> 7. https://marvelapp.com/3h6bdfd/screen/56595828/handoff has some assets, however, I am not able to find the Path details for the left panel icons here.

I'd like to note, that https://marvelapp.com/3h6bdfd/screen/56595828/handoff has a different design for the sidebar in comparison with the new marvel file provided later https://marvelapp.com/4acgiai/screen/58136217. And the new file uses new icons.

8. Got it. We can keep `Private Discussions` tab from now on the side menu.

**Comment by vikasrohit** [comment] 2019-06-28 06:32
7. Yep, however, as the designs are not yet finalized, we can used any of those icons for now. We would use the final icons when we do the color palette updates.

8. Yep, having that tab would have a separate view for only admin discussions.

**Comment by maxceem** [comment] 2019-06-28 06:38
> 8. Yep, having that tab would have a separate view for only admin discussions.

As we are updating the UI of messages. Should we also update this page as per new design but show it without filters `All`/`Admin only`? Or keep the current design? - I'm not sure how it looks right now as I don't have an example of any project with such tab. It would be great if you could share any project with old `Discussions` tab on DEV.

**Comment by vikasrohit** [comment] 2019-06-28 06:51
We don't need to update the UI of this page. Just fyi, this page has completely different UI for messaging, it has left panel where it lists all topics and clicking on one of them opens the topic with posts in the right panel, just like we have in Outlook email client. e.g. project https://connect.topcoder-dev.com/projects/292/discussions

**Comment by maxceem** [comment] 2019-07-02 05:31
@vikasrohit have a couple of questions:

1. Currently, Scope/Specification page has another sidebar: https://monosnap.com/file/etGFDhG8AC12YkmaNkNhag2KhPMR2x. As for some time we are going to show this page with a new sidebar I guess we should replace this sidebar with a new sidebar, as otherwise there is no way to navigate to other pages, as we are removing the second toolbar at the top which we currently use for navigation.

2. What should we do with an old page `Discussion` which has a quite different design https://monosnap.com/file/e6a3jGbigtKloCCNCYynj3u13R3t7g. See that without the secondary toolbar there is also no way to navigate to other page but we cannot remove the existent sidebar. Should add the second sidebar?

**Comment by vikasrohit** [comment] 2019-07-02 12:33
1. For new projects (created with new smart scope forms), I think we can safely remove this sidebar of the scope tab completely as it does not make sense to have questions breadcrumb for them. I am not sure how we can handle it for old projects. Would it be okay to get rid of this side bar for old projects as well? May be we can add a new component in the new side bar for showing the questions breadcrumb for old projects? Would that work?

2. Good catch. May be just leave the page as is with its secondary side bar. I think it should not require no change as the side panel in this page is technically not a side bar which sticks in the left of the view port.

**Comment by maxceem** [comment] 2019-07-05 08:38
@vikasrohit I guess there is no way at the moment to get this statistic for a user from the Project Service:

![image](https://user-images.githubusercontent.com/146016/60709568-5a698200-9f43-11e9-9319-94a51a724350.png)

Should we hide it for now?

**Comment by vikasrohit** [comment] 2019-07-05 10:16
Actually, we can get these statistics from the `GET /v4/projects` endpoint with `memberOnly=true` as filter and then manually calculating the count for different status (active, draft/in-review/reviewed, completed) projects.
If you think we can calculate them without much performance load on initial page load of connect and if we can implement this without much extra time, we can target it for the upcoming release. Otherwise, we can log a separate issue for this.

**Comment by maxceem** [comment] 2019-07-05 10:36
This endpoint gets paginated results. I'm not sure how many projects may have users in real life, but our test `pshah_manager` user has `3901` projects.
So, I guess we would have to paginate the results or set the limit to the maximum `10000`, though if there are many projects I guess the response size could be quite heavy.

So it feels it would be better to introduce a separate statistics endpoint for this, what do you think?

**Comment by vikasrohit** [comment] 2019-07-05 13:08
Yep, Agreed. I missed that. Lets skip these stats for now. Lets log a separate issue. We would visit that issue after this release.

**Comment by maxceem** [comment] 2019-07-06 03:28
Create a separate issue for showing statistic https://github.com/appirio-tech/connect-app/issues/3151

**Comment by maxceem** [comment] 2019-07-06 07:50
@vikasrohit we have one more page with the full list of notifications https://connect.topcoder-dev.com/notifications

Should we show a new standard sidebar there? 

![image](https://user-images.githubusercontent.com/146016/60753485-bb598e80-a005-11e9-8afc-75ba04ef29d9.png)

**Comment by vikasrohit** [comment] 2019-07-08 06:08
Yes, without any change to the page layout.

**Comment by maxceem** [comment] 2019-07-10 09:39
@vikasrohit for customers we may show the delete button which currently looks like this:

![image](https://user-images.githubusercontent.com/146016/60957884-fd514000-a337-11e9-9455-93434cbebadb.png)

In the new design, we don't have such a good place to show this button, so I have a couple of suggestions:
1. Show delete button next to "All Projects" link

    ![image](https://user-images.githubusercontent.com/146016/60958735-70a78180-a339-11e9-8252-8101af15d7c9.png)

     - looks good, but feels like not a right place for such button

2. As an alternative way we can show a regular `red` button in the "Administration" section, like this:

    ![image](https://user-images.githubusercontent.com/146016/60958367-d21b2080-a338-11e9-89e0-4007df07b47b.png)

    - Looks not that cool, but feels that button more on its right place

**Comment by vikasrohit** [comment] 2019-07-10 10:04
Let me get that confirmed by product managers today. For now, keep it any of these places which requires less efforts from us.

Btw, I have one more idea, we can show the delete button (red one) just next to the `Submit for Review` button as these two buttons are shown only for customers only. However, the `Submit for Review` button is most likely to go away very soon.

**Closed** 2019-07-23 07:32 UTC
Labels: Connect app, Released
