### ISSUE TITLE
Manager: Search is not giving the proper result after applying the filter

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#1803] opened 2018-03-01 23:11 UTC
_From @bikakk on February 18, 2018 1:12_

### Reported URL ###
https://connect.topcoder-dev.com/projects?sort=updatedAt%20desc

### Reproduction Steps ###
1. Open https://connect.topcoder-dev.com/
2. Login as pshah_manager
3. Provide a project name in the search bare ex: BIK and search it
4. Observe the project type of displayed result and now apply the filter for any project type
5. ex: Chatbot
6. observe the result

### Expected Result ###
The filter should apply on the searched result.

### Actual  Result ###
Filter is not applied on the searched results, instead of this it is applying on hole page.
Ex: Here i have searched for BIK , then it is displayed 4 results and none of them are chatbot project.
Now i applied the filter and expected the result as zero. But it is showing lot of results.

### Screenshots ###
Result before applying the filter:
![image](https://user-images.githubusercontent.com/31851673/36347171-53c5aea6-1448-11e8-9e4b-5263cf1971c2.png)

Result after applying the filter:
![image](https://user-images.githubusercontent.com/31851673/36347175-63cf7174-1448-11e8-9f27-51a1f0629f9a.png)

https://youtu.be/tfxRQ-oHnnM

### Issue Information ###

Frequency: Always

Device: Laptop

OS: Windows 64-bit

Browser: Chrome 64.0.3

_Copied from original issue: topcoderinc/connect-test-cycle-1#125_

**Comment by gondzo** [comment] 2018-03-05 00:14
this is duplicate of other search results quality issues

**Closed by gondzo** 2018-03-05 00:14 UTC
Labels: Functional, Open for Pickup, Valid Bug
