### ISSUE TITLE
Project Details page loading scrolled down if the project listing page was scrolled down

### ISSUE THREAD

**Issue by mahestro** [appirio-tech/connect-app#148] opened 2016-09-22 22:18 UTC
Title is hard to get, just see this: http://take.ms/MmQuA

**Comment by vic-appirio** [comment] 2016-09-23 23:57
There's something with react-sticky probably. The position of the left panel depends on it - discussed at #131

**Comment by fnisen** [comment] 2016-11-03 23:06
@vikasrohit yes, I can't reproduce either, although it was happening to me earlier. This must have been fixed as part of some other work. Closing. Thanks.

**Closed by fnisen** 2016-11-03 23:06 UTC
Labels: P2
