### ISSUE TITLE
Text field overlaps processing status wheel.

### ISSUE THREAD

**Issue by Kvm87** [appirio-tech/connect-app#999] opened 2017-07-24 18:40 UTC
### Expected behavior
Clear cut complete, processing status wheel should be seen while registration is processed.

### Actual behavior
Input text field for 'Nickname' overlaps the processing status wheel, while registration is processed..

### Steps to reproduce the problem
- Go to url https://accounts.topcoder-dev.com.
- click on 'Start a Project'.
- Go for Wireframes'.
- Complete the form and press 'Continue'.
- Complete create new account details.
- Press Register button.
- Observe that 'Register' button changes to 'Registering' while processing status wheel at center is overlapped by 'Nickname' field.

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/20595047/28538912-7df67724-70cd-11e7-9d73-c6454b545393.png)
![image](https://user-images.githubusercontent.com/20595047/28538962-a417fb3a-70cd-11e7-9f77-3cf56187d7d8.png)

--

#### Environment
- OS: Windows 8.1
- Browser (w/version): Chrome Version 59.0.3071.115, Firefox 54.0.1
- User role (client, copilot or manager): Not logged in
- Account used: -NA-

**Comment by vikasrohit** [comment] 2017-07-25 08:35
@gondzo Its duplicate of #977. I am not closing right now, you can do that when consolidating.

**Closed** 2017-07-27 17:26 UTC
Labels: bug hunt, duplicate
