### ISSUE TITLE
Skill you team to have drop-down hide

### ISSUE THREAD

**Issue by Krishna1507** [appirio-tech/connect-app#3633] opened 2020-01-29 18:50 UTC
### Expected behavior
Skill drop-down should not hide should be aligned properly.

### Actual behavior
Skill drop-down hide over the page

### Steps to reproduce the problem
- Open the Application and Login as valid user (Manager)..
- Click + New Project > On Demand > Engage Talent > select.
- Fill and Traverse till "What skills are important for your team to have?".
- Observe the drop-down

### Screenshot/screencast
![image](https://user-images.githubusercontent.com/23450398/73387030-e5520580-42f5-11ea-9a63-8a226d9a39db.png)

#### Environment
- OS: Windows 10 pro
- Browser (w/version): IE11/11.592.18362.0
- User role (client, copilot or manager): Manager
- Account used: topcoderconnect+Manager@gmail.com

**Comment by Krishna1507** [comment] 2020-01-29 18:51
@bug-hunt-helper add label: BugHunt_JanRelease, UI, P2

**Comment by SathyaJayabal** [comment] 2020-01-31 06:40
duplicate of #3571

**Closed by SathyaJayabal** 2020-01-31 06:40 UTC
Labels: BugHunt_JanRelease, P2, UI
