### ISSUE TITLE
While saving the Profile settings, it throws error [Invalid Country Code]

### ISSUE THREAD

**Issue by nithyaasworld** [appirio-tech/connect-app#3397] opened 2019-12-09 07:52 UTC
1. Go to https://connect-test01.topcoder-dev.com/
2. Login as topcoderconnect+Customer@gmail.com pw: appirio123
3. Go to My Profile
4. Change any field and save

Actual:
Not able to save the changes. It throws an error as in the screenshot below:

![image](https://user-images.githubusercontent.com/5114190/70417278-e6e61680-1a86-11ea-9c65-2d426c40829d.png)

**Comment by lakshmiathreya** [comment] 2019-12-10 05:26
@nithyaasworld this seems fixed now - pls review.

**Comment by nithyaasworld** [comment] 2019-12-10 05:45
@lakshmiathreya Can you please check for the account stated in the ticket description? It seems to be still there for that account.

**Comment by RishiRajSahu** [comment] 2019-12-11 03:52
@lakshmiathreya seems to be working fine for me, could you recheck and close the issue if working fine ?

**Comment by maxceem** [comment] 2019-12-11 05:25
I can reproduce this issue for this particular user. The reason for this that this user already has some non-valid data in its `basic_traits`:

It has value for `homeCountryCode : "356"`. I'd like to note, that our form doesn't edit this field, so we cannot change it from our profile form. Our form change the fields which it can change and send the whole trait with updated values. So it also sends back the values which we got from the server but didn't update.

![image](https://user-images.githubusercontent.com/146016/70593785-470cc200-1c19-11ea-949d-c195b47a70e9.png)

I guess some time ago this field has been added with some form somewhere after that Member Service changed allowed values for this field.

We can fix it for this particular user by creating a manual request to update the value for `homeCountryCode`. But I'm not sure how we can solve such a class of issues in general if some other user has some data in their traits which is not valid for Member Service anymore.

**Comment by maxceem** [comment] 2019-12-17 07:20
This issue is caused by the Member Service issue. But we will implement a workaround in Connect App, so we don't depend here on the Memeber Service.

**Comment by maxceem** [comment] 2019-12-17 07:31
When we register a new user using https://accounts.topcoder-dev.com/connect/registration. We send a request to the **User Service** to create a new user.

During processing that request, **User Service** internally creates a `basic_info` trait, and set `homeCountryCode` as a 3-digits:

![image](https://user-images.githubusercontent.com/146016/70973816-64da9b00-20e1-11ea-92ac-6185909d6f40.png)

After that, when we try to edit such user on the User Profile Page http://local.topcoder-dev.com:3000/settings/profile we get data from the Member Service, and inside `basic_info` trait we get `homeCountryCode` as a 3-digits. But if we try to send it back to the Member Serivce, we get an error `["Country code 356 is not valid"]`.

So what we can do as a workaround here is:
- if we get from the server `homeCountryCode` as 3 digits, we should convert to it 3-letters country code usign the next list: https://github.com/appirio-tech/connect-app/blob/dev/src/helpers/ISOCountries.js. So we send it back we send it back to the Member Service we send it as 3 letters code which should be accepted.

**Comment by lakshmiathreya** [comment] 2019-12-17 08:29
This issue is occurring in Prod for some users in version 2.4.16.

**Comment by RishiRajSahu** [comment] 2019-12-17 08:44
@lakshmiathreya its in progress we are working on it.

**Comment by maxceem** [comment] 2019-12-18 05:39
This is fixed and can be tested on DEV https://connect.topcoder-dev.com/ and PROD.

**Comment by maxceem** [comment] 2019-12-18 05:57
Oh, this is a new issue. So some users may not have traits. So to fix this I guess, we have to check if users already has trait, then `PUT` it, if doesn't have, then `POST` it.

**Comment by maxceem** [comment] 2019-12-18 06:09
@nithyaasworld I used the account you shared in this issue for testing, and when I click save this time it worked for me. So this account is fixed now. I guess it got fixed by saving 2 times. But the issue is still valid, we just have to find out how to get more accounts like this for testing this issue.

**Comment by RishiRajSahu** [comment] 2019-12-18 08:18
@nithyaasworld @maxceem could we create new ticket for the new issue, otherwise it would be hard to track later which bug got fixed via which commit ?

**Comment by nithyaasworld** [comment] 2019-12-18 08:39
This issue will be verified on Production once the related issue https://github.com/appirio-tech/connect-app/issues/3451 is fixed

**Comment by lakshmiathreya** [comment] 2019-12-19 10:36
This is verified on Prod @nithyaasworld - as well as #3451. Can we close this?

**Closed** 2019-12-19 10:45 UTC
Labels: 2.4.16, P1, Prod Environment, QA Pass in Prod
