### ISSUE TITLE
Able to input negative numeric values for number of resources required in project

### ISSUE THREAD

**Issue by FarazKhan** [appirio-tech/connect-app#3557] opened 2020-01-29 07:08 UTC
### Expected behavior
User should not be allowed to input negative values for number of resources required

### Actual behavior
User is allowed to input and save negative values for number of resources required

### Steps to reproduce the problem
- Login to the app and select new project button
- Select 'On demand' -> 'Engage Talent'
- Fill up form with dummy data till you reach question about how many full time/part time resources do you need
- Input negetive numeric values say -10 for number of full time/part time resources
- Click next

### Screenshot/screencast
Attach or link a resource.
![image](https://user-images.githubusercontent.com/2743246/73334978-20bbe800-4294-11ea-9ca8-8f0bb3e3a073.png)

--

#### Environment
- OS: windows 10
- Browser (w/version): Chrome Version 79.0.3945.130 (Official Build) (64-bit)
- User role (client, copilot or manager): copilot
- Account used: topcoderconnect+Copilot@gmail.com

**Comment by FarazKhan** [comment] 2020-01-29 07:08
@bug-hunt-helper add label: BugHunt_JanRelease, Functional, P1

**Comment by SathyaJayabal** [comment] 2020-01-30 13:26
@FarazKhan accepted

**Comment by lakshmiathreya** [comment] 2020-02-27 01:57
Range checks should be added to numeric fields ...

**Comment by vikasrohit** [comment] 2020-03-03 10:47
@maxceem CF candidate, we can add new validations (e.g. positiveNumber, nonNegativeNumber etc) to react-components and then use them in templates.

**Comment by maxceem** [comment] 2020-03-09 04:41
Sum up:
- This issue has to be implemented in repo https://github.com/appirio-tech/react-components, branch `feature/connectv2-dev`
- Add 2 new validation rules to the Formsy here https://github.com/appirio-tech/react-components/blob/feature/connectv2-dev/components/Formsy/index.js, see [documentation](https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrulename-rulefunc)
   - `isPositiveNumber`
   - `isNonNegativeNumber`
- Make sure that it's enough and the next template works correctly http://local.topcoder-dev.com:3000/new-project/talent-as-a-service. Or make neccessary changes: 

   ![image](https://user-images.githubusercontent.com/146016/76183258-c43cd880-6202-11ea-83c6-373f6ab54367.png)

**Comment by PrakashDurlabhji** [comment] 2020-03-10 06:43
@bug-bash-helper assign

**Comment by PrakashDurlabhji** [comment] 2020-03-11 02:11
@bug-bash-helper I went through code and just need few hours , but do you addvalidation rule on formsy.form will do? because we use TextInput which is another field and not inside formsy.form so adding a validationrule on formsy.form will help?
@maxceem

**Comment by maxceem** [comment] 2020-03-11 03:46
> I went through code and just need few hours , but do you addvalidation rule on formsy.form will do?

I think it should do because in this place we add other validation rules which we use.

> because we use TextInput which is another field and not inside formsy.form so adding a validationrule on formsy.form will help?

This TextInput should be already inside formsy.form because we use Formsy form functionality during project creation.

**Comment by PrakashDurlabhji** [comment] 2020-03-11 22:16
@bug-bash-helper https://github.com/appirio-tech/react-components/pull/350 is ready for review

**Comment by maxceem** [comment] 2020-03-12 05:24
@PrakashDurlabhji the provided fix doesn't work for me. I can still enter negative values during project creating using http://local.topcoder-dev.com:3000/new-project/talent-as-a-service

![image](https://user-images.githubusercontent.com/146016/76489948-c605d680-6464-11ea-90e2-47482c5ad99a.png)

**Comment by maxceem** [comment] 2020-03-13 02:37
@PrakashDurlabhji let me know if you would like to complete this issue. But we have limited time. If you cannot complete it during the next 24 hours, I would have to unassign you.

**Comment by PrakashDurlabhji** [comment] 2020-03-13 18:03
@maxceem will it be ok to show a error below that only positive numbers are allowed? because not allowing negative value seems to be tough

**Comment by maxceem** [comment] 2020-03-14 01:38
@PrakashDurlabhji no, we need both kinds of validations.

**Comment by tcchhabra** [comment] 2020-03-15 04:51
@maxceem I can give this a try once if @PrakashDurlabhji cannot do it.

**Comment by maxceem** [comment] 2020-03-15 12:36
@PrakashDurlabhji as there is no update this issue is now unassigned.

@tcchhabra no, this issue is now excluded from this Bug Bash.

**Comment by maxceem** [comment] 2020-03-19 03:53
@vikasrohit  there is one tricky moment regarding validating positive/negative values. We use `input type="number"` for this field and it, surprise :tada:, returns an empty string when we enter a non-numeric value. So we cannot validate the value in this field when it’s a wrong number.

![image](https://user-images.githubusercontent.com/146016/77029675-500aed80-69d7-11ea-8112-62961bd59c2c.png)

See this example to reproduce it https://jsbin.com/digorojaxe/edit?html,console,output:

![image](https://user-images.githubusercontent.com/146016/77029520-e4c11b80-69d6-11ea-91cd-16a629358c51.png)

There is a big article regarding numerous downsides of `type="number"` with no good solution https://www.filamentgroup.com/lab/type-number.html.

### Solutions

#### 1. Use type="text" for number

I think the only thing why `type="number"` can be useful for us is to show numeric keyboard on mobile devices. Do you think we can sacrifice numeric keyboard on mobile devices and use `type="text"` for entering numbers, while all the validation would be done by JS?

![image](https://user-images.githubusercontent.com/146016/77029580-13d78d00-69d7-11ea-9125-7d67e0885579.png)

In this case, we also wouldn’t have arrows to increase/decrease values, though I guess they might bring more harm than benefits, as it’s very easy accidentally scroll inside the field and change the value (I do it regularly).

![image](https://user-images.githubusercontent.com/146016/77029777-a0824b00-69d7-11ea-9e5b-abbdb7e40952.png)

#### 2. Make all type="number" fields "required"

If we make all the numeric fields required. Then when a user enters the wrong number we would get empty value and would show a validation error to enter a value. Though we would never know if the user enters a wrong number, or didn't enter anything. So the error message should be general to cover both cases: no value and wrong value.

**Comment by vikasrohit** [comment] 2020-03-19 07:49
@maxceem I found `checkValidity()` method  or `validity` field on the number input which gives correct result for validation of the value inside it. Can we use that? May be we can use `valueAsNumber` field (it returns NaN when we enter `-123-123-23` in the field) in combination with regular value field to determine the validation state?

**Comment by maxceem** [comment] 2020-03-19 12:11
That's an interesting finding @vikasrohit. There is also a [validity](https://developer.mozilla.org/en-US/docs/Web/API/HTMLObjectElement/validity) property which can give us more details on what exactly is invalid:
```js
{
  badInput: false, // not a number
  customError: false,
  patternMismatch: false,
  rangeOverflow: false, // value more than "max"
  rangeUnderflow: true, // value less than "min"
  stepMismatch: false,
  tooLong: false,
  tooShort: false,
  typeMismatch: false,
  valid: false,
  valueMissing: false
}
```

Though, it looks like we cannot use this via Formsy.

In the standard Formzy API we can only add validator which relies on the value and other form values https://github.com/christianalfoni/formsy-react/blob/master/API.md#formsyaddvalidationrulename-rulefunc:

![image](https://user-images.githubusercontent.com/146016/77065221-d812e680-6a1b-11ea-8fe5-178757410a6f.png)

`this` also refers to the validations rules list, which cannot help access the filed value:

![image](https://user-images.githubusercontent.com/146016/77065416-39d35080-6a1c-11ea-97a4-1ab84cbf2fa4.png)

I was thinking that we can include this logic directly to `TextInput` component https://github.com/appirio-tech/react-components/blob/22ebf4b5e74ab9e8de7308ec08e285e6a3852e20/components/Formsy/TextInput.jsx though I remember from working on `PhoneInput` component, that we cannot mark that input is invalid for Formzy, so even if we show the error message, which we can, we cannot tell Formzy that the input is invalid. In case of `PhoneInput` to overcome this, we had to add additional logic to the whole form, just to handle the additional validation logic we have for `PhoneInput`. It would be not good for our general forms for project specification.


So at the moment looks like there is no good solution for keeping `type="number"`. Would you like to give this more efforts to find a way to keep `type="number"`? Or if it's not critical, we can switch to `type="text"` for numbers.

**Comment by vikasrohit** [comment] 2020-03-19 14:20
Lets go with `type=text`.

**Comment by maxceem** [comment] 2020-03-20 12:51
@vikasrohit The next fix has been done for this issue:
- I've updated https://connect.topcoder-dev.com/new-project/talent-as-a-service Project Template so now it uses `type="textinput"` instead of `type="number"`, because validations don't work for numbers
- in `react-components` implemented validators `isPositiveNumber` and `isNonNegativeNumber`
- so now we can apply them to any field
- but it appears, that in Connect App we don't actually use `validations` field from Project Template, we only override it with a single validation rule `isRequired`, see https://github.com/appirio-tech/connect-app/pull/3806/files#diff-bcfd7970e8edc78f9946daa468a139a5L134. So the validations added in `react-component` are actually not applied
- to fix this I've created a fix for Connect App in this PR https://github.com/appirio-tech/connect-app/pull/3806.
- the important moment in this fix, that `validations` field is fixed for all fields. So if we have `validations` property for any other fields in any other Project Template, now they would start work, while before they were ignored.
- as an alternative, we can enable `validations` property only for `textinput` question type. But I prefer to fix it in general, so now we would know that we can use `validations` for any field.

Let me know what you think abou this.

**Comment by lakshmiathreya** [comment] 2020-03-25 15:22
@codejamtc have you reviewed this Issue?

**Comment by codejamtc** [comment] 2020-03-25 15:24
@lakshmiathreya No, Only checked `Invites Regfactoring` labeled issues with status `Aha!:Ready for QA`. I will check it now

**Comment by maxceem** [comment] 2020-03-25 15:30
@lakshmiathreya @codejamtc Please, don't test it yet. I'm waiting for confirmation from @vikasrohit that the current implementation method is good to go before applying this fix.

**Comment by codejamtc** [comment] 2020-03-25 15:31
@maxceem Sure

**Comment by lakshmiathreya** [comment] 2020-03-25 15:31
thanks for update @codejamtc - yes i did notice @maxceem hasnt moved it to Ready for QA yet. But this is related to a Prod Issue hotfix so i was curious.
<img width="1469" alt="Screenshot 2020-03-25 at 8 58 14 PM" src="https://user-images.githubusercontent.com/51733042/77554222-cfb72180-6edb-11ea-8177-6ccf152d93fe.png">

**Comment by vikasrohit** [comment] 2020-03-30 07:09
@lakshmiathreya production issue was fixed without code change. I updated the form to accept 0 as input for the hours fields and the issue we used to track that was https://github.com/appirio-tech/connect-app/issues/3802

**Comment by vikasrohit** [comment] 2020-03-30 12:01
> @vikasrohit The next fix has been done for this issue:
> 
> * I've updated https://connect.topcoder-dev.com/new-project/talent-as-a-service Project Template so now it uses `type="textinput"` instead of `type="number"`, because validations don't work for numbers
> * in `react-components` implemented validators `isPositiveNumber` and `isNonNegativeNumber`
> * so now we can apply them to any field
> * but it appears, that in Connect App we don't actually use `validations` field from Project Template, we only override it with a single validation rule `isRequired`, see https://github.com/appirio-tech/connect-app/pull/3806/files#diff-bcfd7970e8edc78f9946daa468a139a5L134. So the validations added in `react-component` are actually not applied
> * to fix this I've created a fix for Connect App in this PR #3806.
> * the important moment in this fix, that `validations` field is fixed for all fields. So if we have `validations` property for any other fields in any other Project Template, now they would start work, while before they were ignored.
> * as an alternative, we can enable `validations` property only for `textinput` question type. But I prefer to fix it in general, so now we would know that we can use `validations` for any field.
> 
> Let me know what you think about this.

@maxceem I am not sure how it was working before but I do remember we have the validation of 160 characters on description fields via setting `"validations": "isRequired,minLength:160",` on the description question and it used to work.

**Comment by maxceem** [comment] 2020-03-30 12:04
@vikasrohit it was enabled, only for one type of fields https://github.com/appirio-tech/connect-app/pull/3806/files#diff-bcfd7970e8edc78f9946daa468a139a5L241-L243. Though now, the proposed fix enables it to all the fields types to avoid confusion in the future.

**Comment by vikasrohit** [comment] 2020-03-30 12:08
Ohk. I think we are good with it then, I don't remember using the `validations` field on any question where it can have side effect now. Only case was for description field which itself is not used anymore now. I guess, it is safe to merge it.

**Comment by maxceem** [comment] 2020-03-30 12:36
@codejamtc This is ready for testing on DEV.

- Use the next link for creating project https://connect.topcoder-dev.com/new-project/talent-as-a-service
- There are 2 fields where we added validation:

   ![image](https://user-images.githubusercontent.com/146016/77912691-a90e3780-729b-11ea-8633-63a739ecd33e.png)

   - Field **Full-Time** should be a positive number (not required, so can be also skipped)
   - Field **How many part-time (20hrs/wk) resources do you need?** should be non-negative number (not required, so can be also skipped)

**Comment by maxceem** [comment] 2020-03-30 12:37
@vikasrohit to apply these rules in any template:
- user field type `textinput` NOT `numberinput`
- add validation rule: 
  - `"validations": "isPositiveNumber"`
  - `"validations": "isNonNegativeNumber"`
- add the error text:
  ```
  "validationErrors": {
      "isPositiveNumber": "Please, enter a positive number."
   },
  ```
   or
   ```
   "validationErrors": {
      "isNonNegativeNumber": "Please, enter a positive number or zero."
   },
   ```

![image](https://user-images.githubusercontent.com/146016/77913131-6862ee00-729c-11ea-911d-d66517508673.png)

**Comment by codejamtc** [comment] 2020-03-30 13:04
@maxceem https://www.screencast.com/t/lO4KerCF

**Comment by coderhacker** [comment] 2020-04-01 13:44
Verified on dev working as expected.

**Comment by codejamtc** [comment] 2020-04-02 13:20
https://www.screencast.com/t/sKLI3pRcZ

**Comment by vikasrohit** [comment] 2020-04-03 06:22
Thanks for catching it @codejamtc. I need to update the template on the production to reflect the changes.  I updated it now, please check it again.

**Comment by vikasrohit** [comment] 2020-04-03 10:10
@codejamtc @lakshmiathreya I have verified this on production and marking it as closed. Please feel free to add final QA comments.

**Closed by vikasrohit** 2020-04-03 10:10 UTC
Labels: Aha!: Issue Logged, BugHunt_JanRelease, Functional, Have A Question, P2, QA Fail in Prod, QA Pass in Dev

**Comment by codejamtc** [comment] 2020-04-03 13:41
@maxceem @vikasrohit Working in `Prod`
