### ISSUE TITLE
No max word limit for 'FEATURE NAME'

### ISSUE THREAD

**Issue by sdgun** [appirio-tech/connect-app#412] opened 2016-10-01 15:25 UTC
### Expected behavior
-----------------------------------------------------------------
Need to have a max word limit for 'FEATURE NAME'

### Actual behavior
-----------------------------------------------------------------
No max word limit for 'FEATURE NAME'

### Steps to reproduce the problem
-----------------------------------------------------------------

- Open the sites 
- Login as a valid user (pat_monahan)
- In the Projects
- Click on a Project name
- Click Specification
- Click 'Add/Edit Features'
- Scroll down and click 'Add a custom feature' button
- Enter a Long feature name 
- (eg: Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features Must reduce the line spacing of the same word in Custom Features)
- Click Save Changes
- Check the Left side panel

### Screenshot/Screencast/JS Log (If not attached here, Please check the comment section) 
-----------------------------------------------------------------
![2016-10-01_20-54-45](https://cloud.githubusercontent.com/assets/4592712/19015016/4ef2da50-8819-11e6-83f3-650ece1ac418.png)

### Environment
-----------------------------------------------------------------
- **Device(s):** Laptop
- **Browser(s):** Chrome 53.0.2785.116 m, FF 49.0.1
- **Operating System:** Windows 7 Pro 64bit
- **User Accounts:** cp-superstar
- **User Role:** Copilot

**Comment by mahestro** [comment] 2016-10-04 19:03
Duplicate of #296

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
