### ISSUE TITLE
Unable to add Connect user

### ISSUE THREAD

**Issue by ajefts** [appirio-tech/connect-app#2890] opened 2019-03-08 21:59 UTC
We're unable to add a user to a customer project.  Let's get the user added ASAP so we unblock them and then figure out the root cause.

Project: https://connect.topcoder.com/projects/9526/
User:  vjain1026

To reproduce, simply try adding the user to the customer team.  It finds the user when searching, but then the handle (or email) disappears as soon as you select it so you can't finish the invite.

**Comment by ajefts** [comment] 2019-03-08 22:01
@vikasrohit @RishiRajSahu Can you help add this user ASAP please for Zurich?  Please let me know if you need any more details.

fyi @acshields

**Comment by maxceem** [comment] 2019-03-09 02:54
@ajefts I've tried to reproduce this issue on production but couldn't. I've tried to invite user `vjain1026 ` to the test project https://connect.topcoder.com/projects/720 and I can select it and it appears in the field, so I only have to press button `Send invite`, though I didn't press it to avoid confusion the member.

![image](https://user-images.githubusercontent.com/146016/54065249-fcf54b00-4258-11e9-83da-d0dc646e7e37.png)

Before @vikasrohit @RishiRajSahu are here, maybe you could try making `hard reload` of the page by pressing `Ctrl + Shift + R` (Windows) ot `Cmd + Shift + R` (Mac).

Just in case if it's some caching issue.

If you still have this issue, could you please check if there are any errros in browser console which could help us to track it down.

**Comment by vikasrohit** [comment] 2019-03-09 04:17
@maxceem it seems there is a different issue. I am also facing the same issue and error in the console is:
`Uncaught TypeError: Cannot read property 'handle' of undefined
    at t.value (main.df62dd887521eb28e165.js:formatted:160589)
    at main.df62dd887521eb28e165.js:formatted:160580`

which in turn turns out to be at this following code:

```
key: "resolveUserHandle",
            value: function(e) {
                var t = this.props.allMembers;
                return b()(t, {
                    userId: e
                }).handle
            }
```
I am applying a quick fix for that, hopefully that should work. @maxceem Let me know if you think the [fix](https://github.com/appirio-tech/connect-app/pull/2892) is not appropriate.

**Comment by maxceem** [comment] 2019-03-09 04:20
@vikasrohit the fix looks legit for me if it fixes the issue. I'm not sure how it could happen that `allMembers` doesn't have the user on production 🤔.

**Comment by vikasrohit** [comment] 2019-03-09 04:32
@maxceem while I am not sure how the user is part of `allMembers` in the test project you tried. 😬 Because `allMembers` should have only team members and invites but the user is completely new when inviting, so it should not be in the state, right?

**Comment by vikasrohit** [comment] 2019-03-09 04:33
Also, it might be the condition https://github.com/appirio-tech/connect-app/pull/2893/files#diff-ef542918bc9a45150e32cf69926cb8fdR56 which might be preventing `resolveUserHandle` to be called for the test project?

**Comment by maxceem** [comment] 2019-03-09 04:37
> Because allMembers should have only team members and invites but the user is completely new when inviting, so it should not be in the state, right?

Yeah, `allMembers` contains team members and invited members. But this line https://github.com/appirio-tech/connect-app/pull/2893/files#diff-ef542918bc9a45150e32cf69926cb8fdR70 is called only for invited users, see https://github.com/appirio-tech/connect-app/pull/2893/files#diff-ef542918bc9a45150e32cf69926cb8fdR57. It's not called for the user we are currently adding.

**Comment by vikasrohit** [comment] 2019-03-09 05:14
@ajefts patched production to fix the bug and I have invited the said user to the customer team as well. Let me know if any thing is still there.

**Comment by vikasrohit** [comment] 2019-03-11 08:49
@maxceem I think I got the root cause, it seems 2 users data is not being returned by member api which was causing the null pointer. I think we are safe now, only implication would be that some users (whose data is not returned by member api) could be invited more than once.

**Comment by vikasrohit** [comment] 2019-03-11 12:14
@ajefts closing the issue, let me know if we need to do anything else to conclude the fix.

**Closed by vikasrohit** 2019-03-11 12:14 UTC
Labels: Priority, zurich

**Comment by ajefts** [comment] 2019-03-11 13:02
Thanks.  I can see the user was invited now.
