### ISSUE TITLE
The Project Name must be required and not access blank spaces

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#292] opened 2016-09-28 22:20 UTC
Expected behavior
------------------------------------------------------------

- The Project Name field must be required and not accept blank spaces in field.

Actual behavior
------------------------------------------------------------

- The blank spaces added in fields are allowed.

Steps to reproduce the problem

------------------------------------------------------------

- Login into application as connect user role.

- New Project.

- Other Work.

- Set some spaces in Project Name field.

- Complete Description.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![pro](https://cloud.githubusercontent.com/assets/5114907/18934537/f3f3ca66-85e2-11e6-8dbf-b37e93dde27b.png)

**Comment by mahestro** [comment] 2016-10-04 11:29
Duplicate of #184.

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
