### ISSUE TITLE
No validation for invalid link set in field

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#398] opened 2016-09-30 18:20 UTC
Expected behavior

 - The validation must be displayed on invalid link set in Address field.

Actual behavior

  - No validation on invalid data set in field.

Steps to reproduce the problem

 - Login into application as copilot user role.

- Edit any project.

- Press on "+" button to add a link.

- Complete title and set an invalid text in Address field (eg. test).
   
- Add Link.

Environment

Operating System(s): Windows 7
Device(s): Laptop HT 635
Display resolution: 1366x768
Browser(s): Chrome 49.0.2623.112 m
User role: connect user role
Account used: christina_uw 

![a_001](https://cloud.githubusercontent.com/assets/5114907/19002225/ab41663a-8753-11e6-9276-a2aed5d26774.png)

**Comment by mahestro** [comment] 2016-10-04 18:08
Duplicate of #219

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
