### ISSUE TITLE
Secondary navigation isn't updating for current active tab

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2035] opened 2018-06-13 16:46 UTC
### Expected behavior
The tabs should change status when navigating between pages.

### Actual behavior
The navigation gets stuck in Project plan and navigating to other tabs doesn't update the active state of the current tab
![screen shot 2018-06-13 at 9 46 31 am](https://user-images.githubusercontent.com/8484061/41365602-ab000d82-6eee-11e8-8a9b-b50e6ecbd2bd.png)

**Comment by sumitdaga** [comment] 2018-06-18 13:12
@vic-topcoder @RishiRajSahu @gondzo  
i can't seem to re-produce this issue

**Comment by rmjmccormick** [comment] 2018-06-19 11:07
@sumitdaga 
on project landing page, click on "Project Plan", you'll notice the underline under "Dashboard" remains activated and is not toggled in turn under "Project Plan". 

![dashboard bug](https://user-images.githubusercontent.com/39598852/41593841-af61205a-73c1-11e8-82c9-6abf8bd7917b.PNG)
![project plan view](https://user-images.githubusercontent.com/39598852/41593842-af7b5254-73c1-11e8-8722-bd34400304b9.png)

**Comment by sumitdaga** [comment] 2018-06-20 13:32
@rmjmccormick  @RishiRajSahu  @gondzo  
i think these issues are mostly happening due to console errors ...which show up on old projects
if you create a new project these errors don't show up and the navigation works perfectly fine i think ...

**Comment by rmjmccormick** [comment] 2018-06-20 13:57
@sumitdaga @RishiRajSahu @gondzo 
Not so. New projects - I created two this morning - have this problem. I can jump on call/screenshare with you if you'd like to demonstrate the problem?

**Comment by sumitdaga** [comment] 2018-06-20 14:00
@rmjmccormick  
can you see console.errors when the page loads (any of these tabs)?

**Comment by deepakanbarasan1** [comment] 2018-06-20 14:04
@RishiRajSahu
- I have created new project (Test Project for 2.4.3)
  On project landing page, Click on "Project Plan", you'll notice the underline under "Dashboard" remains activated and is not toggled in turn under "Project Plan".
  When i refresh the page, you'll notice the underline will change from "Dashboard" to "Project Plan"
![before refresh - project plan](https://user-images.githubusercontent.com/30447858/41663362-e2b2de6c-74c0-11e8-927b-209556b9f870.PNG)
![after refresh - project plan](https://user-images.githubusercontent.com/30447858/41663369-e8cad868-74c0-11e8-8f76-eefd1af64984.PNG)

**Comment by sumitdaga** [comment] 2018-06-20 14:14
@rmjmccormick  @DeepakAnbarasa  
can you confirm if face the issue on this project http://local.topcoder-dev.com:3000/projects/6415 ?

**Comment by rmjmccormick** [comment] 2018-06-20 14:28
@sumitdaga @DeepakAnbarasa 

Yes, confirmed.

![untitled1](https://user-images.githubusercontent.com/39598852/41664901-071e084a-74a7-11e8-8b78-e2c43ab0ca38.png)
![untitled](https://user-images.githubusercontent.com/39598852/41664902-074581c2-74a7-11e8-8a10-a157beca6148.png)

**Comment by RishiRajSahu** [comment] 2018-06-25 10:46
@sumitdaga are you on it ?

**Comment by gondzo** [comment] 2018-06-25 12:32
this is due to userId being null for phase topics. They are created in the backend by the project service, so IMO we should handle this in the frontend and just ignore the topic userId and focus on post user ids

the other option is to set a userId when creating a phase topic. what do you think @vikasrohit @RishiRajSahu

**Comment by gondzo** [comment] 2018-06-25 12:55
@sumitdaga can you update the frontend code so that it doesn't blow up for null on topic.userId for phase topics?

**Comment by gondzo** [comment] 2018-06-25 17:20
@sumitdaga this is already fixed in dev, no need to do anything further

**Comment by vic-topcoder** [comment] 2018-06-26 03:11
I still see this in Dev right now

**Comment by vic-topcoder** [comment] 2018-06-26 03:11
![screen shot 2018-06-25 at 8 11 30 pm](https://user-images.githubusercontent.com/8484061/41887060-f902d34c-78b3-11e8-8b48-2aa9a6626383.png)

**Comment by maxceem** [comment] 2018-06-26 03:30
I can reproduce the issue here at deployed dev https://connect.topcoder-dev.com/projects/6415/plan

But when I deploy locally the `dev` branch it works fine here http://local.topcoder-dev.com:3000/projects/6415

Is it possible that `dev` branch wasn't deployed?

**Comment by RishiRajSahu** [comment] 2018-06-26 05:19
@maxceem correct its working on local fine with latest dev branch. let me check code deployed on dev.
@gondzo could you tell the commit which fixed the issue ?

**Comment by maxceem** [comment] 2018-06-26 08:46
So far I've found out that it works in dev mode (`npm start`), but doesn’t work when run in prod mode (`npm run build`).

I’m currently investigating the issue, but with no luck so far. I guess in some cases components are not re-rendered, but so far behavior looks random.

**Comment by maxceem** [comment] 2018-06-26 08:59
Just an update if somebod has some guesses. 

To speak the same language:
- dev mode means when we run project using `npm start`
- prod mode means when we build project using `npm run build` and after just serve static files form `dist` folder

Different webpack/babel configs are being used to build dev and prod builds.
Difference is quite small, just some dev tools are added and the format of js is different.
I guess the behaviour is different because dev build could work slightly slower due to debug tools and that leads to difference in behaviour between dev/prod…

**Comment by maxceem** [comment] 2018-06-26 10:18
As I'm stuck with this. I'll switch to another task and come back with the fresh sight to this one later.

**Comment by vikasrohit** [comment] 2018-06-26 11:36
@gondzo is it fixed?

**Closed** 2018-06-26 11:35 UTC
Labels: Project-Plan

**Comment by gondzo** [comment] 2018-06-26 11:37
it should be, deploying to dev now. I guess adding the commit message closed the issue

**Comment by vikasrohit** [comment] 2018-06-26 11:38
I have made one fix for the same as well, which also seems to fix the issue. 😬

**Comment by gondzo** [comment] 2018-06-26 11:40
:) it's almost the same fix. We can revert mine.

**Comment by vikasrohit** [comment] 2018-06-26 11:59
I think adding `pure: false` might cause more re-renders.
