### ISSUE TITLE
The Create button is enable even blank spaces are in field

### ISSUE THREAD

**Issue by onetliviunicolae** [appirio-tech/connect-app#291] opened 2016-09-28 22:17 UTC
Expected behavior
------------------------------------------------------------

- The Create button must not be enable when blank spaces are set in field.

Actual behavior
------------------------------------------------------------

- The Create button is enable when blank spaces are added in field.

Steps to reproduce the problem
------------------------------------------------------------

- Login into application as connect user role.

- Press New Project.

- Select Other Work.

- In Project Name field add some blank spaces.

- Complete description.

Environment
------------------------------------------------------------
Operating System(s): Windows 7
Device(s): Laptop HT 635
Browser(s): Chrome 49.0.2623.112 m
            Mozilla Firefox 48.0.2  
            IE 11.0
User role: connect user role
Account used: christina_uw

![create](https://cloud.githubusercontent.com/assets/5114907/18934453/70396cee-85e2-11e6-9acd-061fb6a7bfd5.png)

**Comment by mahestro** [comment] 2016-10-04 11:28
Duplicate of #184.

"project name accepts spaces though it is mandantory field"

**Closed** 2016-10-07 15:36 UTC
Labels: duplicate
