### ISSUE TITLE
Project creation: set up Salesforce web-to-lead

### ISSUE THREAD

**Issue by fnisen** [appirio-tech/connect-app#562] opened 2016-11-23 19:50 UTC
@vikasrohit have an enhancement request, please. Related to this issue https://github.com/appirio-tech/connect-app/issues/112, Mauricio was working to set up a Salesforce lead to be created every time we had a new project come in (so that we could run drip campaigns). However, this worked required some changes to our instance of Salesforce, which Appirio IT is not allowing us to make. Joey has suggested we use "web-to-lead" to do this instead, which would not require any Salesforce code changes. More info here: https://help.salesforce.com/articleViewid=setting_up_web_to_lead.htm&language=en_US&type=0&release=204.14. 

Would you be able to implement this or run a community challenge to do it? Thank you. 

cc @ajefts

**Comment by vikasrohit** [comment] 2016-11-29 07:59
@fnisen The link shared is not working. However, I have checked on web about the web to lead, and understood the basics of it. It does not seem complicated, however, it would require access to a dev org in salesforce so that I can test it out on my local.

Further, I may need some ramp up time for starting working on this because I don't have much acquaintance with Salesforce and our messaging service. I would try to setup the message service on my local today and let you know the progress.

**Comment by fnisen** [comment] 2016-11-29 22:46
Thanks for researching this @vikasrohit. Can you please hold off from starting this work for now? Let me check with Tony about how best to handle it. If you don't have any particular experience with Salesforce or our messaging service, it may be better for us to run a challenge. Will get back to you.

**Comment by vikasrohit** [comment] 2016-11-30 05:20
Okay. Even in case we get it fixed via community, I need to get understanding of the system to run the challenge and answer the queries.

**Comment by fnisen** [comment] 2016-12-02 23:59
@vikasrohit I checked with Tony. Please work on this when you're available (if you're helping with Discourse, that one is higher priority) and run challenges as you see fit. 

The scenario we want to support is fairly basic: 
When a user creates a new project in Connect, we create an SFDC lead with the following info: First Name, Last Name, Email (based on registration), and Project Name, Project Description, and Connect project link (based on Connect project)

You mentioned needing to use the messaging service. I think only the project service would be required, but let me know if I'm mistaken. You can get access to the SFDC dev sandbox via Okta. Your login will be [username]@topcoder.com.dev. Please email Appirio IT Support if that's not working.

**Comment by vikasrohit** [comment] 2016-12-05 07:43
Yes, @fnisen, you are correct. I don't remember why I mentioned message service, may be I got confused with discourse issue. I am setting up project service on my local machine. It would be helpful for me in https://github.com/appirio-tech/connect-app/issues/551 as well. I think most of my day today, will be consumed in setting up the environment, analyzing the problem and thinking the solution. Meanwhile, can you please let me know the priority between #551 and this one?

**Comment by fnisen** [comment] 2016-12-05 19:30
Hey @vikasrohit, this one is a higher priority than #551. Also, you're right, Mauricio worked on the connector. However, it requires code changes to SFDC, which we're not able to make. Web-to-lead is supposed to be implementable with no code changes. Is that true?

**Comment by parthshah** [comment] 2016-12-05 19:35
`@fnisen is this different from the connector mauricio worked on? We already
have all the code to create a lead in sales force`. This was from me, posted it via email.  Let me know if you run into problems setting up tc-project-service

**Comment by fnisen** [comment] 2016-12-05 20:28
@parthshah ah, I see.

**Comment by vikasrohit** [comment] 2016-12-06 11:44
@fnisen @parthshah  I am able to create lead in salesforce with web to lead feature. However, we can't get the id of the lead created this way, hence can't store that for the project in db. So, I am not sure how would we create the link to the lead on the project details page. With my limited knowledge about Salesforce, I think only thing we can do is to give link to leads page with some query params e.g. email id of the project owner and/or have a custom field, which contains project id e.g. CONNECT_27, in lead and then take user to the search page with CONNECT_27 as search string. This would show user the list view of leads and user has to click to go to the actual lead.

**Comment by parthshah** [comment] 2016-12-06 21:43
Use connect project id as the custom field in Salesforce. That's how the current link is setup anyway.

**Comment by vikasrohit** [comment] 2016-12-07 05:27
How would we map that custom field? Or it does not matter what name we give to that custom field or whatever is the id of that field?

**Comment by vikasrohit** [comment] 2016-12-07 06:54
@parthshah I have pushed my changes. Please review the changes here https://github.com/appirio-tech/tc-project-service/pull/28

**Comment by ajefts** [comment] 2016-12-14 22:34
@vikasrohit Can you ping me when you're on slack to explain the custom field issue?  I'll try to help out.

**Comment by vikasrohit** [comment] 2016-12-15 06:32
Sure @ajefts However, it seems like we are going to discard these changes, I saw comment from mess in slack about that.

**Comment by fnisen** [comment] 2016-12-15 17:13
@vikasrohit sorry for the confusion. We are still going ahead with this. The current plan is:
1. Finish and release web-to-lead ASAP (it will help support the Marketing team and allow us to drive more traffic directly to Connect)
2. After we move to our own Salesforce org, do the full integration, which is what Mauricio had planned originally. No date for this yet--may be 1-3 months.
Can you please check in with @ajefts when you're back online tomorrow?

**Comment by vikasrohit** [comment] 2016-12-16 14:23
Okay. I would start working on it again from coming Monday. It was not possible to include this in today's release.

**Comment by vikasrohit** [comment] 2016-12-22 10:44
@fnisen @ajefts @parthshah I am able to create and access the newly created lead in my org. I have committed my changes into https://github.com/appirio-tech/tc-project-service/tree/feature/salesforce-lead branch. I tried the same changes against appirio's dev org, and it didn't throw any error as well but it didn't create the lead. Further, I don't have sufficient privileges in dev sandbox to view the ConnectLead VF page or modify its settings.

**Comment by fnisen** [comment] 2016-12-28 23:39
@vikasrohit I mentioned this issue to Greg, and he recommended checking with Nikita, who may have pretty good general Salesforce knowledge. You could also try talesforce. Otherwise, Tony is back to normal schedule next week. Thanks.

**Comment by vikasrohit** [comment] 2016-12-29 05:26
Thanks @fnisen, however, I have already discussed this with Ritesh who is expert on salesforce. 😬 However, right now the problem is that I don't have enough privileges on Appirio dev sandbox to validate things. My fix is working fine with my own trial production org. So, action items are:

1. Someone to check what is wrong with Appirio dev sandbox or what changes I need to make it work with Appirio dev sandbox.
2. Give me some more privileges on Appirio Dev Sandbox so that I can do more debugging when integrating changes with it.

**Comment by fnisen** [comment] 2016-12-30 00:29
@vikasrohit ah, I see. OK, well done, then. If it's an issue with the Appirio dev sandbox, can you please open a ticket with Appirio IT (Chris Bruzzi)? They should be able to get you set up. Thanks.

**Comment by vikasrohit** [comment] 2017-01-02 09:40
@fnisen I am not sure if they would give me admin access by my request. Can you or Tony raise the request for the same? or Should I created ticket for that and you guys can authorize the request there?

**Comment by fnisen** [comment] 2017-01-04 00:33
Perfect. Yes, please involve us if needed, but I think IT should be able to give you access directly.

**Comment by vikasrohit** [comment] 2017-01-04 06:46
@fnisen I think IT guys saw some issues with providing admin privileges to my account. So, I might not get admin privileges for long enough. However, I was able to test, with the help of Ritesh, the things before they revoke my privileges. It is working fine in dev sandbox as well. It was URL of web to lead posting in sandbox. I tried with sandbox url and it worked fine for me. I think we are ready to go for production.

@parthshah Please let me know how to deploy project service to dev/production.

**Comment by parthshah** [comment] 2017-01-10 22:12
Hey vikas, tc-project-service deploys are handled through circle-ci. Just merge your changes in dev (for Dev env) and master (for Production env) and that should trigger the build and deploy. Feel free to send me a PR.

**Comment by vikasrohit** [comment] 2017-01-11 05:48
Okay. I have merged my changes with latest changes in the dev. It had a few conflicts. Resolved them and tested it  again on my local. I would try again in dev after merging the [PR](https://github.com/appirio-tech/tc-project-service/pull/28).

**Comment by fnisen** [comment] 2017-01-18 21:56
@vikasrohit bumping this. Can you please finish in dev and then push to prod if it's working?

**Comment by vikasrohit** [comment] 2017-01-19 07:10
Sorry @fnisen Missed to update the issue (updated the PR instead), however, I have tested things in dev and it is working fine. For production, I don't have access to create custom fields, so I won't be able to test it there. Basically, to deploy on production following steps are needed:
1. Create custom field for Connect Project Id (api name of the field should be TC_Connect_Project_Id__c)
2. Create custom fields for Project Name, Project Description, Project Link. This step is not necessary if we can map these fields to existing fields e.g. in dev sandbox, I have mapped them to standard fields title, description and URL respectively. If that works for prod as well, we can avoid creating custom fields for them.
3. Extract custom field ids of all the custom fields created from step 1 and 2.
4. Deploy ConnectLead visual force page to production. Mauricio deployed this page in dev and I am not sure how to deploy it to production and do we have permission to do that in production org.
5. Deploy the project service and update the environment variables extracted in step 3.

I can do the step 3 and 5 but I don't have permissions for other steps and I doubt that Appirio IT would give me the permissions for that.

**Comment by fnisen** [comment] 2017-01-19 22:25
@dmessing FYI

**Comment by fnisen** [comment] 2017-01-20 03:22
@vikasrohit as a first step, can you try writing to Appirio IT and asking for the permissions you need?

**Comment by vikasrohit** [comment] 2017-01-20 05:41
@fnisen I have asked them for sandbox and they did provided me the access. However, later on it was revoked.

**Comment by fnisen** [comment] 2017-01-21 01:37
Is it possible for you to get it back? Can you please try? If not, we can go with plan B, but I'd like to make sure this won't work first.

**Comment by vikasrohit** [comment] 2017-01-27 05:16
@fnisen I don't think so. I can definitely start the process again to get the credentials, however, I think it would take time and nods from people above in hierarchy to get it resolved. And as we have already started working on our separate salesforce org, I think we can integrate it directly there.

**Comment by fnisen** [comment] 2017-02-08 01:08
@vikasrohit wanted to check in with you on this one. Sumit and the team were apparently working on the new SFDC org for us and the sandbox should already be available. Can you please check with Sumit, Ritesh or someone on the Jaipur team to find out the status of this? Thank you.

**Comment by vikasrohit** [comment] 2017-02-08 06:17
@fnisen I just talked to Ritesh about this. We are expecting the new org to be live by end of this Q5 so we can not move the changes to production until then. Though I have already validated changes against Appirio sandbox, I can again validate the changes against the sandbox of the new Topcoder org to be sure that it won't fail on production.

**Comment by vikasrohit** [comment] 2017-09-19 07:41
We can close this as we have already handled the salesforce integration via https://github.com/appirio-tech/tc-connect2sf.
@vic-topcoder Fixing lead link issue via #1181

**Closed by vikasrohit** 2017-09-19 07:41 UTC
Labels: enhancement, P1
