### ISSUE TITLE
Opening project creation briefly displays the login window

### ISSUE THREAD

**Issue by vic-topcoder** [appirio-tech/connect-app#2152] opened 2018-07-06 02:37 UTC
I can't reproduce it at the moment, but this morning before I created https://connect.topcoder-dev.com/projects/6545 I briefly was flashed the login window while loading the new project wizard. I saw the same on Rory's screen. @vikasrohit what would cause such a flash to your best knowledge?

**Comment by vikasrohit** [comment] 2018-07-06 05:21
I think it is because of the same reason as of #2126

**Comment by RishiRajSahu** [comment] 2018-09-11 08:42
Not reproducible anymore. Seems to be fixed with #2126 . Closing.

**Closed by RishiRajSahu** 2018-09-11 08:42 UTC
